### ISSUE TITLE
Image lost between txt2img and img2img

### ISSUE THREAD

**Issue by patrickjonesdotca** [TheLastBen/fast-stable-diffusion#10]
(Colab issue): Tried sending a generated image from that tab over to the img2img tab for interrogation and it never appears.

**Comment by TheLastBen** [comment]
if the image is large, it takes some time to upload then redownload, if it is too large, it doesn't appear at all, this is Gradio limitation for now, hopefully they will fix it in the future.

**Comment by fractaltr33** [comment]
It's not about the size. Everything works in other collabs, but not in fast_stable_diffusion_AUTOMATIC1111. "Send to img2img" just doesn't work.

**Comment by TheLastBen** [comment]
because this colab stores everything in Gdrive for faster execution, it doesn't update until you remove the folder "sd" from your Gdrive, try doing that to get the latest update, also use the latest colab from this repo, and let me know how it goes

**Comment by TheLastBen** [comment]
problem fixed, please confirm to close this issue
