### ISSUE TITLE
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

### ISSUE THREAD

**Issue by donttellmeimcute** [TheLastBen/fast-stable-diffusion#1013]
when i run the last cell this error appears:
AttributeError: type object 'BasicTransformerBlock' has no attribute 'ATTENTION_MODES'

im on a stable diffusion 2.1 trained chkpt

**Comment by TheLastBen** [comment]
Remove the folder SD and do a clean run with the latest colab
