### ISSUE TITLE
Colab won't generate from saved checkpoint - AttributeError: 'Options' object has no attribute 'filter_nsfw'

### ISSUE THREAD

**Issue by jaaaamIron** [TheLastBen/fast-stable-diffusion#1020]
Hi.

I've already trained a model and have successfully generated images with it using the Dreambooth colab notebook.
However, I'm now trying to - a few weeks later - reload the trained checkpoint, and when I go to generate an image through the SD interface, I get the error in colab:
AttributeError: 'Options' object has no attribute 'filter_nsfw'

It's probably worth point out that I'm not using Dreambooth to generate nsfw images, and I'm guessing this is some sort of safeguarding setting.

Does anyone know what to do, and is this a common issue?

The full error is this:

Error completing request
Arguments: ('Chris2022 in a hospital, as a very old man.', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 0, 0, 0, False, False, False, '', 1, '', 0, '', True, False, False) {}
Traceback (most recent call last):
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
res = list(func(*args, **kwargs))
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
res = func(*args, **kwargs)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/txt2img.py", line 49, in txt2img
processed = process_images(p)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 430, in process_images
res = process_images_inner(p)
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 544, in process_images_inner
if opts.filter_nsfw:
File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 459, in getattr
return super(Options, self).getattribute(item)
AttributeError: 'Options' object has no attribute 'filter_nsfw'

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/issues/1006

**Comment by Danesed** [comment]
Simple solution is to remove lines 544,545,546 from processing.py file
`  544    #if opts.filter_nsfw:
    545         #   import modules.safety as safety
    546         #   x_samples_ddim = modules.safety.censor_batch(x_samples_ddim)
`

**Comment by TheLastBen** [comment]
if you modify any of the A1111 files, it won't pull updates anymore and that will cause you more errors later, I recommend just doing a clean run with a new sd folder

**Comment by jaaaamIron** [comment]
Thanks all - I deleted SD folder and it re pulled and worked.
Best
Jamie

**Comment by TheLastBen** [comment]
great!
