### ISSUE TITLE
Is the auto tag complete extension not supported with the colab?

### ISSUE THREAD

**Issue by luci9t** [TheLastBen/fast-stable-diffusion#1035]
[This ](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete) extension has never worked anytime I've tried to make it work. I've tried installing it from the UI and installing it manually, doesn't work either way. It throws this error: 

`Traceback (most recent call last):`
  `File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)`
 ` File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)`
 `File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 89, in <module>
    write_tag_base_path()`
  `File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 64, in write_tag_base_path
    f.write(TAGS_PATH.relative_to(FILE_DIR).as_posix())`
  `File "/usr/lib/python3.8/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"`
`ValueError: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/tags' does not start with '/content/gdrive/MyDrive/sd/stablediffusion'
`

**Comment by lolxdmainkaisemaanlu** [comment]
same, actually none of the extensions seem to work for me!

**Comment by luci9t** [comment]
@TheLastBen Could you look into this please? From the last line, It looks like the path is not updated somewhere.

**Comment by TheLastBen** [comment]
I'll look into it

**Comment by TheLastBen** [comment]
Change 
```
with capture.capture_output() as cap:
  %cd /content/gdrive/MyDrive/sd/stablediffusion/
```
to
```
with capture.capture_output() as cap:
  %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/
```

I can't change it in the colab until I'm sure it won't break anything else
