### ISSUE TITLE
Training on my self - what params should I use in colab?

### ISSUE THREAD

**Issue by royherma** [TheLastBen/fast-stable-diffusion#105]
I'm using the colab at the bottom of the repo home page (https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb)

My use case is I would like to test and train on photos of my self. 

I provided:
```
With prior reservation: no
Instance name`: unique name of instance (let's say johnnydoe)
```
I then uploaded 52 photos
And chose:
```
Training steps: 1000
Seed: some random int
```

Is that the recommended approach or has anyone found an better way of doing this?

Thx!!!!

**Comment by TheLastBen** [comment]
You'll get average results with those settings, the best settings would be :
With prior reservation: "Yes", then manually choose more than 200 high quality class images of males your age, and set steps to 2500.
but it's better to test with lower settings and go up from there.

**Comment by royherma** [comment]
Awesome, thanks Ben – will try

Sent via Superhuman iOS ( ***@***.*** )

**Comment by 1blackbar** [comment]
i succesfully trained on class - male or female, class is very important, i trained a cartoon boy character, not used any class and got crap results, then i trained him as boy - great resuts beyond my expectations and could stylise him into real photo.

**Comment by royherma** [comment]
> You'll get average results with those settings, the best settings would be : With prior reservation: "Yes", then manually choose more than 200 high quality CLASS images of males your age + the 52 INSTANCE images of yourself (uploaded as instance not class), and set steps to 2500 but it's better to test with lower settings and go up from there.

Would you recommend square photos for all or doesn't matter?

Also about the images themselves, i saw some places that said the more different the pictures the better (diff backgrounds and such), whereas some other people have said it is preferred with similar noiseless background, just in different positions.

Any insights on these? Will save time preparing the data...

**Comment by TheLastBen** [comment]
square images are best to avoid cropping, and for the content it's better to use different environments and lightings.

**Comment by royherma** [comment]
@TheLastBen as a follow up - let's say I want to train it on an item of clothing, like a custom sweatshirt I made.

Would you also suggest taken 5-15 photos of the sweatshirt, then making class name "sweatshirt" or "clothes", as well as do we need to add the CLASS images?

Thanks for tips!

**Comment by TheLastBen** [comment]
For objects, you will have to experiment with and without prior preservation.
