### ISSUE TITLE
"RESUME TRAINING" WONT WORK - same errors as before.

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#1057]
Session found, loading the trained model ...
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1107, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1076, in convert
    key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
  File "/content/convertodiff.py", line 1013, in save_stable_diffusion_checkpoint
    torch.save(new_ckpt, output_file)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in __init__
    super(_open_zipfile_writer_file, self).__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.
Conversion error, if the error persists, remove the CKPT file from the current session folder
![Screenshot 2022-12-16 212205](https://user-images.githubusercontent.com/112510084/208216245-86548093-1702-416b-9ba4-77953eb1ef57.jpg)
![Screenshot 2022-12-16 212205](https://user-images.githubusercontent.com/112510084/208216249-9c03086e-8037-4d32-8e20-0fbc2cd2d48a.jpg)

**Comment by TheLastBen** [comment]
there is a problem with the CKPT, either it's corrupt, or it was converted with a previous script that was broken

**Comment by LIQUIDMIND111** [comment]
> there is a problem with the CKPT, either it's corrupt, or it was converted with a previous script that was broken

this was done 2 days ago, i trained 6000 steps, tested it and decided to RESUME training the next day, i did all as requested in the instructions for resuming training and boom, error. nor sure how can it be corrupted if it worked well, just needed more training, it was not broken, it loads well in automatic 1111 with its proper YAML file... the problem is every time i try to resume LATER ON, not on the same session.

**Comment by TheLastBen** [comment]
I do it all the time, never had an issue, make sure you choose the right version in the Load/Create session cell

**Comment by LIQUIDMIND111** [comment]
> I do it all the time, never had an issue, make sure you choose the right version in the Load/Create session cell

ok then. thanks
