### ISSUE TITLE
About hypernetwork

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#106]
I change the finetune hypernetwork in colab (AUTOMATIC111 version) but nothing happen! Who can help me?

**Comment by 9NTNT9** [comment]
same problem, no idea how to solve.
AttributeError: module 'modules' has no attribute 'hypernetwork'

**Comment by acjbizar** [comment]
Getting this same error right now. Was working fine before today.

**Comment by TheLastBen** [comment]
Update the repo

**Comment by acjbizar** [comment]
Ah! Silly me, Thank you.
