### ISSUE TITLE
CLASS_DIR: How does it work?

### ISSUE THREAD

**Issue by Crimsonfart** [TheLastBen/fast-stable-diffusion#107]
Where in gdrive do I have to create a folder with the images and what exactly do I have to enter in CLASS_DIR:?

**Comment by TheLastBen** [comment]
For example if you want to train a model on your dog, you can add 200 random images of a dog, or you can let the scripts generate them if you don't want to upload them yourself.

**Comment by Crimsonfart** [comment]
I already understood that, but until now I have always uploaded/generated them and it takes a very long time, so I wanted to ask how the file path works so that I don't always have to upload/generate the 400 images.

**Comment by TheLastBen** [comment]
if you have the images in your Gdrive, just copy the path of the folder containing them using the colab file explorer and paste it in the CLASS_DIR box

**Comment by Crimsonfart** [comment]
OMG now I got it. Thanks for the quick help!
