### ISSUE TITLE
Can we get KLMS sampler?

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#11]
I've only used KLMS since I got access to colabs. With these older samplers, I don't get nearly the same quality of output from my prompts.

**Comment by TheLastBen** [comment]
All the samplers are available in all 3 colabs

**Comment by GuruVirus** [comment]
I'm only aware of: https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

I only see these samplers. How do I get KLMS?
![image](https://user-images.githubusercontent.com/4285187/192606866-4600df81-ccf5-4a02-b976-08c78fef886a.png)

**Comment by TheLastBen** [comment]
LMS is part of the k-diffusion sampling or "KLMS"

**Comment by GuruVirus** [comment]
Thanks. I see now that it is called LMS, KLMS, or K_LMS. For some reason fast-stable-diffusion (FSD)'s LMS does not generate the same as pharmapsychotic's klms here: https://colab.research.google.com/github/pharmapsychotic/ai-notebooks/blob/main/pharmapsychotic_Stable_Diffusion.ipynb

I can't figure out what is going on. I get the closest results to pp's klms using FSD's EulerA.

**Comment by TheLastBen** [comment]
Make sure the other settings like cfg scale and the steps are set, also Euler_a gives best results even at low steps
