### ISSUE TITLE
Traceback (most recent call last):   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>     from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call ModuleNotFoundError: No module named 'modules.call_queue'

### ISSUE THREAD

**Issue by Psytorpz** [TheLastBen/fast-stable-diffusion#1100]
It doesn't work anymore. I get this message when I try to start the stable diffusion module.

**Comment by TheLastBen** [comment]
is you colab up to date ?
A1111
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Dreambooth
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

remove the folder sd from your gdrive and do a clean run

**Comment by a-toms** [comment]
I had the same problem. Removing the folder sd from your gdrive and doing a clean run solved it. Suggest closing issue.
