### ISSUE TITLE
Persistent error while running the training cell

### ISSUE THREAD

**Issue by Mastersh7bu** [TheLastBen/fast-stable-diffusion#1106]
When running the training cell on the colab i keep getting this error(below): 
![Screenshot 2022-12-21 at 21 44 11](https://user-images.githubusercontent.com/110874689/209008024-19f79490-9b4b-4237-ad82-2fceb9f122a9.png)
I have ran everything as default but i keep running into the same problem!
Is anyone else facing this? Is there a fix ?

**Comment by TheLastBen** [comment]
if it's a custom model, edit the scheduler_config.json and remove the trailing comma and make sure you're using the latest colab, I think I fixed that error recently

**Comment by Mastersh7bu** [comment]
no this is not a custom model it's the dreambooth colab on https://github.com/TheLastBen/fast-stable-diffusion main page, that is the latest one right?

**Comment by TheLastBen** [comment]
paste the content of  scheduler_config.json here

**Comment by Mastersh7bu** [comment]
Im sorry I'm unsure of where that's located, is it in the  "'/content/stable-diffusion-custom/scheduler/scheduler_config.json',"  because when I run the colab it does not install an sd folder like it did when it was working. I just have a fast dreambooth folder that has "Sessions" and then "instnace_images"?

**Comment by TheLastBen** [comment]
that file is inside colab storage, you can find it using the colab file explorer in the left side

**Comment by Mastersh7bu** [comment]
Ok here 
{
  "_class_name": "PNDMScheduler",
  "_diffusers_version": "0.6.0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "num_train_timesteps": 1000,
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null,
  "clip_sample": false
}

**Comment by nawnie** [comment]
{
  "_class_name": "PNDMScheduler",
  "_diffusers_version": "0.9.0.dev0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "num_train_timesteps": 1000,
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null
}


looks like your diffusers version is behind

**Comment by nmeln** [comment]
It started training encoder & unet after updating diffusers version:
`sed -i 's/0.6.0/0.9.0.dev0/g' /content/stable-diffusion-custom/scheduler/scheduler_config.json`

Not sure if there will be any unintended effects on the training quality (probably not)

**Comment by nawnie** [comment]
sounds like somehow you pulled an old commit of his DB, your welcome, no issue with quality but it takes too much ram to do unet and Text encoder for v2 i believe.

remember easiest way to pull up your his most recent version is the image on the github page, but heres a link

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
