### ISSUE TITLE
it's canceling itself with ctrl+c

### ISSUE THREAD

**Issue by rewixx** [TheLastBen/fast-stable-diffusion#1110]
Checkpoint mti.ckpt [ff134a12] not found; loading fallback v2-1_768-ema-pruned.ckpt [4bdfc29c]
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [4bdfc29c] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/v2-1_768-ema-pruned.ckpt
**^C**

why?

**Comment by Daviljoe193** [comment]
Google Drive? That causes there to be just enough RAM to be unavailible that the model can't load.

**Comment by TheLastBen** [comment]
check the box "large model"

**Comment by rewixx** [comment]
ok

**Comment by rewixx** [comment]
it works now
