### ISSUE TITLE
Wrong Output image dimensions

### ISSUE THREAD

**Issue by pixexid** [TheLastBen/fast-stable-diffusion#112]
Using Automatic1111
I'm generating my images in 768x512 but on the output folder, the images are saved with 512x512px. Any way to fix this?
![Uploading Screen Shot 2022-10-09 at 2.29.46 PM.png…]()

**Comment by TheLastBen** [comment]
check in settings tab in the AUTOMATIC1111 webui

**Comment by pixexid** [comment]
> check in settings tab in the AUTOMATIC1111 webui

i can't find any option for this in settings. It should save with the input dimensions, but it's keeping saving on 512x512

<img width="1439" alt="Screen Shot 2022-10-09 at 7 43 07 PM" src="https://user-images.githubusercontent.com/54691335/194792716-640b9350-6448-46b3-a1ff-1c3b1be175be.png">

**Comment by pixexid** [comment]
It was the preview image in the Gdrive folder, it's working fine.
