### ISSUE TITLE
Can't run it in Google Colab

### ISSUE THREAD

**Issue by FerikkusuOC** [TheLastBen/fast-stable-diffusion#1125]
I use free plan of Google Colab and just a few days ago I used to run SD without any problem, but now I can't run SD 2.0 or 2.1 apparently because so much RAM is being consumed in "Start stable-diffusion" part.

It starts like this, as always:

"LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [2c02b20a] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
^C"

And then it stops when RAM consuming is too high for free Google Colab. Google Colab didn't change RAM amount for free plan since the last time I ran stable diffusion (just few days ago), so that's not the problem. I used to run SD 2.1 in there, but now I can't.

**Comment by nawnie** [comment]
add --medram, if that doesnt work add --lowram, at least until ben can help ya more

**Comment by nawnie** [comment]
last three lines of launch cell after this

......
!python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --no-half-vae  --ckpt "$path_to_trained_model" $configf $xformers (add it here)
.....

**Comment by FerikkusuOC** [comment]
> last three lines of launch cell after this
> 
> ...... !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --no-half-vae --ckpt "$path_to_trained_model" $configf $xformers (add it here) .....

Thanks, but even with --lowram, it doesn't work. From the beginning, in "LatentDiffusion: Running in v-prediction mode", it already takes 10.31GB/12.68GB and continues to increase in the next steps. When it starts to load the weights, it's already taking all 12GB available. As I said, this hasn't happened for a few days, so I don't know what to do to get it back to normal.

**Comment by FerikkusuOC** [comment]
> last three lines of launch cell after this
> 
> ...... !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --no-half-vae --ckpt "$path_to_trained_model" $configf $xformers (add it here) .....

Thanks, but even with --lowram, it doesn't work. From the beginning, in "LatentDiffusion: Running in v-prediction mode", it already takes 10.31GB/12.68GB and continues to increase in the next steps. When it starts to load the weights, it's already taking all 12GB available. As I said, this hasn't happened for a few days, so I don't know what to do to get it back to normal.

**Comment by FerikkusuOC** [comment]
> > last three lines of launch cell after this
> > ...... !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --no-half-vae --ckpt "$path_to_trained_model" $configf $xformers (add it here) .....
> 
> Thanks, but even with --lowram, it doesn't work. From the beginning, in "LatentDiffusion: Running in v-prediction mode", it already takes 10.31GB/12.68GB and continues to increase in the next steps. When it starts to load the weights, it's already taking all 12GB available. As I said, this hasn't happened for a few days, so I don't know what to do to get it back to normal.

Ok, i did it. If someone is being as dumb as i was and having the same problem, that's the solution: simply check "Large_Model"  in "Start stable-diffusion". I should have tried this before, but I was stupid.
