### ISSUE TITLE
Training failing halfway 

### ISSUE THREAD

**Issue by poudi7** [TheLastBen/fast-stable-diffusion#113]
Hi, after having trained a model of myself at 4000step I decided to try at 8000step, this time I increase the subject images from 32 to 44 and the class pictures from 4644 to 6689.
Except it failed at 47%
Any idea what went wrong? 

> The following values were not passed to `accelerate launch` and had defaults used instead:
> 
> 	`--num_processes` was set to a value of `1`
> 	`--num_machines` was set to a value of `1`
> 	`--mixed_precision` was set to a value of `'no'`
> 	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
> To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link

> ================================================================================

> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:99: UserWarning: /usr/lib64-nvidia did not contain libcudart.so as expected! Searching further paths...
>   f'{candidate_env_vars["LD_LIBRARY_PATH"]} did not contain '
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('true}'), PosixPath('"/usr/local/bin/dap_multiplexer","enableLsp"'), PosixPath('6000,"kernelManagerProxyHost"'), PosixPath('["--ip=172.28.0.2"],"debugAdapterMultiplexerPath"'), PosixPath('{"kernelManagerProxyPort"'), PosixPath('"172.28.0.3","jupyterArgs"')}
>   "WARNING: The following directories listed in your path were found to "
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//ipykernel.pylab.backend_inline'), PosixPath('module')}
>   "WARNING: The following directories listed in your path were found to "
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
>   "WARNING: The following directories listed in your path were found to "
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 7.5
> CUDA SETUP: Detected CUDA version 112
> CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda112.so...
> Steps:  47% 3767/8000 [1:34:41<1:46:25,  1.51s/it, loss=0.0778, lr=5e-6]Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFile.py", line 233, in load
>     s = read(self.decodermaxblock)
>   File "/usr/local/lib/python3.7/dist-packages/PIL/PngImagePlugin.py", line 838, in load_read
>     cid, pos, length = self.png.read()
>   File "/usr/local/lib/python3.7/dist-packages/PIL/PngImagePlugin.py", line 129, in read
>     length = i32(s)
>   File "/usr/local/lib/python3.7/dist-packages/PIL/_binary.py", line 71, in i32be
>     return unpack_from(">I", c, o)[0]
> struct.error: unpack_from requires a buffer of at least 4 bytes
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 585, in <module>
>     main()
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 509, in main
>     for step, batch in enumerate(train_dataloader):
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in __iter__
>     next_batch = next(dataloader_iter)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
>     data = self._next_data()
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 274, in __getitem__
>     example["class_images"] = self.image_transforms(class_image)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 94, in __call__
>     img = t(img)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 678, in forward
>     return F.crop(img, i, j, h, w)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 504, in crop
>     return F_pil.crop(img, top, left, height, width)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_pil.py", line 237, in crop
>     return img.crop((left, top, left + width, top + height))
>   File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1133, in crop
>     self.load()
>   File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFile.py", line 239, in load
>     raise OSError("image file is truncated")
> OSError: image file is truncated
> Steps:  47% 3767/8000 [1:34:42<1:46:24,  1.51s/it, loss=0.0778, lr=5e-6]
> Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
>     args.func(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
>     simple_launcher(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-4', '--instance_data_dir=/content/data/brianpme', '--class_data_dir=/content/gdrive/MyDrive/person_joepenna_jackwh_combine', '--output_dir=/content/models/brianpme', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of a brianpme person', '--class_prompt=photo of a person', '--seed=11111', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=8000', '--num_class_images=6689']' returned non-zero exit status 1.
> Something went wrong

**Comment by TheLastBen** [comment]
try doing a clean run with the latest colab

**Comment by poudi7** [comment]
Just launched it again, will see if it worked in the morning

**Comment by poudi7** [comment]
It failed again at 38%



> The following values were not passed to `accelerate launch` and had defaults used instead:
> 	`--num_processes` was set to a value of `1`
> 	`--num_machines` was set to a value of `1`
> 	`--mixed_precision` was set to a value of `'no'`
> 	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
> To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
> 
> ===================================BUG REPORT===================================
> Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
> For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
> ================================================================================
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:106: UserWarning: /usr/lib64-nvidia did not contain libcudart.so as expected! Searching further paths...
>   f'{candidate_env_vars["LD_LIBRARY_PATH"]} did not contain '
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:28: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('"/usr/local/bin/dap_multiplexer","enableLsp"'), PosixPath('6000,"kernelManagerProxyHost"'), PosixPath('"172.28.0.3","jupyterArgs"'), PosixPath('true}'), PosixPath('{"kernelManagerProxyPort"'), PosixPath('["--ip=172.28.0.2"],"debugAdapterMultiplexerPath"')}
>   "WARNING: The following directories listed in your path were found to "
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:28: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//ipykernel.pylab.backend_inline'), PosixPath('module')}
>   "WARNING: The following directories listed in your path were found to "
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:28: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
>   "WARNING: The following directories listed in your path were found to "
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 7.5
> CUDA SETUP: Detected CUDA version 112
> CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda112.so...
> Steps:  38% 3018/8000 [1:16:32<2:06:18,  1.52s/it, loss=0.0442, lr=5e-6]Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFile.py", line 233, in load
>     s = read(self.decodermaxblock)
>   File "/usr/local/lib/python3.7/dist-packages/PIL/PngImagePlugin.py", line 838, in load_read
>     cid, pos, length = self.png.read()
>   File "/usr/local/lib/python3.7/dist-packages/PIL/PngImagePlugin.py", line 129, in read
>     length = i32(s)
>   File "/usr/local/lib/python3.7/dist-packages/PIL/_binary.py", line 71, in i32be
>     return unpack_from(">I", c, o)[0]
> struct.error: unpack_from requires a buffer of at least 4 bytes
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 585, in <module>
>     main()
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 509, in main
>     for step, batch in enumerate(train_dataloader):
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 357, in __iter__
>     next_batch = next(dataloader_iter)
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
>     data = self._next_data()
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 274, in __getitem__
>     example["class_images"] = self.image_transforms(class_image)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 94, in __call__
>     img = t(img)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py", line 678, in forward
>     return F.crop(img, i, j, h, w)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional.py", line 504, in crop
>     return F_pil.crop(img, top, left, height, width)
>   File "/usr/local/lib/python3.7/dist-packages/torchvision/transforms/functional_pil.py", line 237, in crop
>     return img.crop((left, top, left + width, top + height))
>   File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 1133, in crop
>     self.load()
>   File "/usr/local/lib/python3.7/dist-packages/PIL/ImageFile.py", line 239, in load
>     raise OSError("image file is truncated")
> OSError: image file is truncated
> Steps:  38% 3018/8000 [1:16:32<2:06:21,  1.52s/it, loss=0.0442, lr=5e-6]
> Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
>     args.func(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
>     simple_launcher(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-4', '--instance_data_dir=/content/data/brianpme', '--class_data_dir=/content/data/person_joepenna_jackwh_combine', '--output_dir=/content/models/brianpme', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of a brianpme person', '--class_prompt=photo of a person', '--seed=1125', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=8000', '--num_class_images=6689']' returned non-zero exit status 1.
> Something went wrong

**Comment by TheLastBen** [comment]
Try a different set of instance and class images, it looks like some of the images you used are corrupt or not recognized

**Comment by poudi7** [comment]
So I tried again with the folder of 4644 CLASS image, that I used for the 4000step training, and it worked. Thanks

**Comment by TheLastBen** [comment]
Great !
