### ISSUE TITLE
How to use this without updating? Every time Auto1111 updates something breaks.

### ISSUE THREAD

**Issue by tamal777** [TheLastBen/fast-stable-diffusion#1131]
I want to use without updating. anybody know how to do it?

**Comment by arxivi** [comment]
```
Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer/inference_codeformer.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 30, in <module>
    from blendmodes.blend import blendLayers, BlendType
ModuleNotFoundError: No module named 'blendmodes'
```

me error

**Comment by TheLastBen** [comment]
fixed

**Comment by arxivi** [comment]
> fixed

thanks! I uninstalled everything from gdrive and reinstalled. same problem. model version 1.5

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 30, in <module>
    from blendmodes.blend import blendLayers, BlendType
ModuleNotFoundError: No module named 'blendmodes'`

**Comment by Cemvegas** [comment]
same here

File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 30, in <module>
    from blendmodes.blend import blendLayers, BlendType
ModuleNotFoundError: No module named 'blendmodes'

**Comment by TheLastBen** [comment]
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by tamal777** [comment]
> https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Ben Thanks I will test it now. Is there anyway to use without updating? I do not want to update and redo all of my settings every time.

**Comment by fixing-it** [comment]
now I get this error:
`/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/.shortcut-targets-by-id/1s72GKp1yYc5oo43L_IfY9bA5zjP3mUIu/sd/stable-diffusion-webui/modules/sd_models.py", line 284, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "/content/gdrive/.shortcut-targets-by-id/1s72GKp1yYc5oo43L_IfY9bA5zjP3mUIu/sd/stable-diffusion-webui/modules/sd_models.py", line 115, in select_checkpoint
    if len(model_checkpoint) == 0:
TypeError: object of type 'NoneType' has no len()`

**Comment by ClashSAN** [comment]
@tamal777 create a copy of one from history

you may need to mod the files to revert to specific version with

    git revert <oldercommitversionofwebui>

**Comment by tamal777** [comment]
> https://github.com/TheLastBen/fast-stable-diffusion/commits/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> 
> @tamal777 create a copy of one from history
> 
> you may need to mod the files to revert to specific version with
> 
> ```
> git revert <oldercommitversionofwebui>
> ```

thanks

**Comment by Cemvegas** [comment]
/usr/local/lib/python3.8/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 284, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 115, in select_checkpoint
    if len(model_checkpoint) == 0:
TypeError: object of type 'NoneType' has no len()

> now I get this error, deleted all previous folders before, so it can start fresh:

same here

**Comment by obisims** [comment]
> /usr/local/lib/python3.8/dist-packages/scipy/**init**.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.0 warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}" Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in webui() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui initialize() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize modules.sd_models.load_model() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 284, in load_model checkpoint_info = checkpoint_info or select_checkpoint() File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 115, in select_checkpoint if len(model_checkpoint) == 0: TypeError: object of type 'NoneType' has no len()
> 
> > now I get this error, deleted all previous folders before, so it can start fresh:
> 
> same here

I also get this error after a SD delete and rerun

**Comment by mflux** [comment]
Same.

**Comment by rewixx** [comment]
Same

**Comment by Protegee1505** [comment]
same

**Comment by obisims** [comment]
My python is very bad and pardon me but my git is too because i only do sall hobbyist projects.

It looks like v2 checkpoint specific issue? I was able to get around this by going into stable-diffusion-webui/sd_models.py
at line 112 "def select_checkpoint()"...
replacing with:
`model_checkpoint = {}  # initialize model_checkpoint as an empty dictionary

def select_checkpoint():
    global model_checkpoint
    model_checkpoint = model_checkpoint or {}  # assign default value if model_checkpoint is None
    if len(model_checkpoint) == 0:
        # code to handle empty model_checkpoint
        model_checkpoint = shared.default_sd_model_file`

**Comment by TheLastBen** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5974

**Comment by obisims** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#5974](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5974)

pardon

**Comment by TheLastBen** [comment]
this is actually the issue in A1111 : https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5971

**Comment by amratef** [comment]
sorry for asking, where do i insert this ? 
git revert <oldercommitversionofwebui>

**Comment by TheLastBen** [comment]
you don't have to, just do a clean run with the latest colab

**Comment by tamal777** [comment]
> you don't have to, just do a clean run with the latest colab

I don't want to reinstall SD for each update. how to stay on the working version?

**Comment by TheLastBen** [comment]
A1111 merged a dozen pull requests today, it doesn't happen everyday

**Comment by brunakrc** [comment]
> 

Could you teach me how to use an old version?

**Comment by brunakrc** [comment]
> https://github.com/TheLastBen/fast-stable-diffusion/commits/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> 
> @tamal777criar uma cópia de um da história
> 
> você pode precisar modificar os arquivos para reverter para uma versão específica com
> 
> ```
> git revert <oldercommitversionofwebui>
> ```

could you teach me how to use this command to use an old version?
