### ISSUE TITLE
Training gives error when starts

### ISSUE THREAD

**Issue by RayZ3R0** [TheLastBen/fast-stable-diffusion#1145]
I'm getting this error when I start the training, I'm using Anything-v3 model by Linaqruf 
![image](https://user-images.githubusercontent.com/69317757/209464104-7fa78864-35cf-4b9b-bdb2-77e0f7db1435.png)
![image](https://user-images.githubusercontent.com/69317757/209464111-ed7c3fc5-e2b4-4fb2-a334-b6298370fce7.png)

**Comment by TheLastBen** [comment]
which custom model are you using ?

**Comment by wongedyan** [comment]
Same problem here. I'm using model from dreamlike-art/dreamlike-diffusion-1.0

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
can you paste the content of /content/stable-diffusion-custom/scheduler/scheduler_config.json here ?

**Comment by StanPHC** [comment]
The scheduler_config.json is generated with a syntax error. If you download it and open it in a text editor, you can change it. 

You will see:
`{
  "_class_name": "PNDMScheduler",
  "_diffusers_version": "0.6.0",
  "beta_end": 0.012,
  "beta_schedule": "scaled_linear",
  "beta_start": 0.00085,
  "num_train_timesteps": 1000,
  ,
  "set_alpha_to_one": false,
  "skip_prk_steps": true,
  "steps_offset": 1,
  "trained_betas": null
}`

Simply remove the stray comma, save it, delete the previous config file from the colab file viewer and upload the changed file. 

Alternatively you can resolve this by adding some code into the colab notebook, that reads the json-file and removes the stray comma. In any case, I expect this to be resolved soon.

**Comment by wongedyan** [comment]
It's working now :) Thank you so much.

**Comment by RayZ3R0** [comment]
Same for me, thank you :)
