### ISSUE TITLE
2.1-768 model does not load, defaults to inpaint 1.5 and crashed

### ISSUE THREAD

**Issue by MushroomFleet** [TheLastBen/fast-stable-diffusion#1159]
~ When using the Auto1111 webUI colab
error:

> Checkpoint model.ckpt [a2a802b2] not found; loading fallback sd-v1-5-inpainting.ckpt [19cd8e84]
LatentInpaintDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.93 M params.
Loading weights [19cd8e84] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/sd-v1-5-inpainting.ckpt
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 195, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 133, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 313, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 197, in load_model_weights
    model.load_state_dict(sd, strict=False)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LatentInpaintDiffusion:
**long error about size mismatch, because its in 2.1 mode using a 1.5 inpainting checkpoint**

Steps to reproduce
choose 2.1-768 and check the redownload the model box
choose 2.1-768 mode 
above error happened, no GUI launch.

**Comment by TheLastBen** [comment]
You can't use the v2.1 mode and use inpainting 1.5

**Comment by MushroomFleet** [comment]
> You can't use the v2.1 mode and use inpainting 1.5

Yes. 
i did not select it. 
the log I copied to you above says:

**Checkpoint model.ckpt [a2a802b2] not found; loading fallback sd-v1-5-inpainting.ckpt [19cd8e84]**

not sure why you think i chose the inpainting model?

**Comment by MushroomFleet** [comment]
![image](https://user-images.githubusercontent.com/7318371/209613177-315f555d-2a8a-4360-ad91-b29a1c19c6d7.png)
&
![image](https://user-images.githubusercontent.com/7318371/209613237-1de67919-b533-423f-b431-3d3d17e413d2.png)

this still won't start on 2.1, just letting you know

**Comment by TheLastBen** [comment]
Remove the in painting model and redownload the V2
