### ISSUE TITLE
Fix: to get plugins working (including the new and improved outpaint)

### ISSUE THREAD

**Issue by createperhaps** [TheLastBen/fast-stable-diffusion#1165]
Hey @TheLastBen,

https://github.com/zero01101/openOutpaint-webUI-extension/issues/11

there was a discussion here and the devs on this plugin had found a fix for your colab. It just requires a cd change, and debug to be true.

Could you get this in the rep?

**Comment by seijihariki** [comment]
Hey, don't know about debug as true, did nothing to that! But the working directory should be the webui when it is loaded by running webui.py

**Comment by createperhaps** [comment]
Thanks for the correction.

**Comment by TheLastBen** [comment]
fixed https://github.com/TheLastBen/fast-stable-diffusion/commit/164eae2175a0be41f50d9e1e4eab753f5ad0855f
