### ISSUE TITLE
Automatic111 colab won't start SD

### ISSUE THREAD

**Issue by jorymo** [TheLastBen/fast-stable-diffusion#117]
Worked fine yesterday, but when I tried running it today, I got this:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 10, in <module>
    from modules.paths import script_path
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    import modules.safe
ModuleNotFoundError: No module named 'modules.safe'
```

**Comment by TheLastBen** [comment]
AUTOMATIC1111 added some files, you'll have to either update the repo or remove the folder "sd" and do a clean run, make sure you use the latest colab

**Comment by jorymo** [comment]
> AUTOMATIC1111 added some files, you'll have to either update the repo or remove the folder "sd" and do a clean run, make sure you use the latest colab

Thanks!
