### ISSUE TITLE
[Dreambooth] Does training text encoder have a character limit?

### ISSUE THREAD

**Issue by younyokel** [TheLastBen/fast-stable-diffusion#1175]
Hello. I haven't used dreambooth in about a month, and now here are some updates that I don't quite understand. I just did what I did in the past, but I noticed that the current caption is cropped instead of showing the full filename. Is this just a print limit, or is it really cropped?

**Comment by TheLastBen** [comment]
the display is limited to 45 characters but it's just the display, under the hood, it's using the full caption

**Comment by younyokel** [comment]
> the display is limited to 45 characters but it's just the display, under the hood, it's using the full caption

Pheww, thanks Ben
