### ISSUE TITLE
Difference between "text encoder training" and "Manual/External Captions"

### ISSUE THREAD

**Issue by iqddd** [TheLastBen/fast-stable-diffusion#1184]
Please explain to beginner what is the difference between "text encoder training" and "Manual/External Captions"?
Do I understand correctly that these are two approaches to the same thing? based on this piece of code:
```
if Text_Encoder_Training_Steps==0 or External_Captions:
   Enable_text_encoder_training= False
```

**Comment by iqddd** [comment]
@TheLastBen, сould you explain? At least a few sentences.

**Comment by TheLastBen** [comment]
Finetuning the text_encoder helps the model converge faster towards the trained subject, but you will be also make the model overfit faster, when you use the captions, you will be training only the unet to converge towards the trained subject when it receives those specific embeddings (captions) from the text_encoder through the prompt, you will get less overfitting but less smart model when it comes to the trained subject unless you're enhancing an existing instance.
