### ISSUE TITLE
Class paramter in training promprt

### ISSUE THREAD

**Issue by dmitrii-brand** [TheLastBen/fast-stable-diffusion#1185]
It seems there is no class parameter in training prompt, eg "sks dog" (where dog is a class and sks is an instance name).

I see that there is $PT variable, but can't find definition for it to check. 

https://github.com/TheLastBen/fast-stable-diffusion/blame/main/fast-DreamBooth.ipynb#L1032

**Comment by TheLastBen** [comment]
This colab uses the image filename as an instance name, you can also use manual captioning

**Comment by dmitrii-brand** [comment]
Thanks for answering! I already read that it's by design. Closing.
