### ISSUE TITLE
Progress no longer display full text desc after checkpoint saved in middle

### ISSUE THREAD

**Issue by longlivebigcat** [TheLastBen/fast-stable-diffusion#1191]
While I upload 95 images and then upload 95 text files with the same name, I can start training with captions. The progess will display the text of the trained image like "a young file is wearing a yttleajack jacket". This is what we are expecting.

However, if I chose to save the checkpoint for N steps. After the first checkpoint save, the training resumed. The progress will no longer display the text content. Instead, it will display "yttleajack" (originally it displays "a young file is wearing a yttleajack jacket"). Does it mean the caption was not working after first checkpoint saving?

**Comment by TheLastBen** [comment]
did you set the text encoder to any value ?

**Comment by longlivebigcat** [comment]
I have set the text encoder to 700, The checkpoint saved at 3000, 5000.

**Comment by TheLastBen** [comment]
When using external captions, the text_encoder isn't finetuned, the unet will stop receiving the captions at the number of steps set  for the text encoder

**Comment by longlivebigcat** [comment]
Do you mean:
1. I need to set the text_encoder to be the same steps as image training
2. Or it doesn't matter, I just set the text_encoder to a few hundred

**Comment by TheLastBen** [comment]
If you set the text_enc to 0 or 100% unet steps, it will use the captions the whole time, but that might lead to excessive overfitting, so chose a reasonable amount of steps for which to use the captions
