### ISSUE TITLE
ModuleNotFoundError: No module named 'midas'

### ISSUE THREAD

**Issue by maelfonrei** [TheLastBen/fast-stable-diffusion#1194]
I installed this add-on (https://github.com/thygate/stable-diffusion-webui-depthmap-script) and got this error:

```
Error loading script: depthmap.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 195, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/stable-diffusion-webui-depthmap-script/scripts/depthmap.py", line 36, in <module>
    from midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'midas'
```

Installed via Extensions -> Install from URL.

In sd/stablediffusion in the model "midas" appeared, but in sd/stablediffusion-webui it was not there. I also moved the second folder 'midas' to sd/stablediffusion-webui/models, but it didn't make a difference. There is also a possibility that this happened after yesterday's depthmap-script update. 

This problem is only in Google Colab, it is not on the local server.

I don't know if this is the right place to write this, but it's my first time on the Git.

**Comment by TheLastBen** [comment]
It must be the update, I'll check it out.

**Comment by outhipped** [comment]
same for me!

**Comment by TheLastBen** [comment]
fixed

**Comment by maelfonrei** [comment]
Thanks
