### ISSUE TITLE
Checkpoint overwritten when resuming training and saving each n steps

### ISSUE THREAD

**Issue by nikoferro** [TheLastBen/fast-stable-diffusion#1198]
Hey, reporting a bug i found while using the current colab. Did some search around and couldn't find an open/closed issue for this, but if i missed it, feel free to close this one.

Basically if you resume a training, and check `Save_Checkpoint_Every_n_Steps`. Since the count starts from 0, the ckpt files are overwritten with the new ones. 

**Example:**

Train a model for 2000 steps. Save a ckpt each 200
Resume training for 1000 extra steps (trying to get the model to 3000)

Since count starts from 0, on the second training ckpt at 200 steps is saved as `model_step_200.ckpt`, when it should be `model_step_2200.ckpt`. Resulting in the model at 200 beinig lost, and also model at 2200 being mislabelled.

Thanks for the great work!

**Comment by TheLastBen** [comment]
I figured that if the user is able to load a previous checkpoint he won't be needing all other previous checkpoints and it's way easier to maintain at this simpler state.

**Comment by nikoferro** [comment]
@TheLastBen sorry for the stale issue, closing this one since i cannot commit to send an actual PR or proposal for a better implementation. For anyone that has time and feels like this is confusing, my idea would be continue with the count using the starting point from the filename.
