### ISSUE TITLE
Output text file

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#12]
Can we get it to generate a textfile with each batch to record the full properties? E.g.
    "steps": 40,
    "guidance_scale": 7.5,
    "init_image": "",
    "init_strength": 0,
    "num_batch_images": 1,
    "prompt": "cat by cartoonist",
    "sampler": "klms",
    "samples_per_batch": 1,
    "seed": 912943576,
    "width": 640,
    "height": 640

**Comment by TheLastBen** [comment]
which fork ? AUTOMATIC1111 or hlky ?

**Comment by GuruVirus** [comment]
I'm using Automatic's at the moment. Now that I see you have all 3 I am going to try hlky's tomorrow. Which do you prefer?
Also, I think for me, an easier solution would be to append the guidance scale and steps into the filename like "40s-20c" (s for steps and c for scale).

**Comment by TheLastBen** [comment]
I'm using the relaxed mode just for fun, but if you want specific output system you're gonna gave to edit the fork's main py files to adjust the settings to your likings.

**Comment by GuruVirus** [comment]
Thanks!

**Comment by TheLastBen** [comment]
hlky fork : https://i.postimg.cc/g0BZxBxP/Captureh.jpg
