### ISSUE TITLE
The last checkpoint  with step that equals to total shouldn't be saved

### ISSUE THREAD

**Issue by longlivebigcat** [TheLastBen/fast-stable-diffusion#1211]
When I set the Unet training step to be 5000, and save checkpoint every 1000 steps, at the end of the training, I would get two CKPT files named XXXX.ckpt and XXXX_step_5000.ckpt. 

These two CKPT files are saved within two minutes and are exactly the same files. The XXXX_step_5000,ckpt is redundant and should not be saved

**Comment by TheLastBen** [comment]
Set the save_every_n_steps to 1050 instead of exact 1000

**Comment by longlivebigcat** [comment]
OK, that is a walkaround. Thanks
