### ISSUE TITLE
FATAL: this function is for sm80, but was built for sm750

### ISSUE THREAD

**Issue by Noctree** [TheLastBen/fast-stable-diffusion#1216]
Get this error spammed into console when attempting to train an embedding with SD WebUI on A100.

I tried fixing it by building XFormers from scratch by using [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Xformers), but couldn't figure out how to safely install it, as my session keeps crashing after restarting and running all cells again.

If it's of any use I'll attach the xformers I built inside the Colab, [here](https://drive.google.com/file/d/14F8OTF5pp9tetVQmVZ6xIv0RJsVynaqk/view?usp=share_link)

**Comment by TheLastBen** [comment]
use the latest colab, it's fixed now

**Comment by xXwatermelon** [comment]
This error is still happening. 

> use the latest colab, it's fixed now
