### ISSUE TITLE
Problem with trained model

### ISSUE THREAD

**Issue by noedvil10** [TheLastBen/fast-stable-diffusion#1222]
Hello, does anyone know why when training and testing the SD V1.5 model with the new collab updates, the generated images have that poor quality, something like haze and sometimes the images are distorted as if their face melted?
It does not happen to me with models that I train with previous versions of the colab

![00003-436496300-photo of skare___](https://user-images.githubusercontent.com/119390846/210195830-07b72c9d-d6f0-4d94-85bb-7b5a1d62f5a0.png)
![00002-416682736-photo of skare___](https://user-images.githubusercontent.com/119390846/210195840-cce00c7a-e540-44a2-922c-af7a0a3c88a3.png)
![00004-1439927439-photo of skar___](https://user-images.githubusercontent.com/119390846/210196084-777608a7-f49e-4480-a5be-2c1ef9ebd6fd.png)

**Comment by longlivebigcat** [comment]
Could you clarify what happened. E.g. you opened a previously generated CKPT files, using the same prompts, found the images are blurred. Or you train the model using the same raw pictures  and setting as before, and could not generate as good picture as before?

**Comment by noedvil10** [comment]
> Could you clarify what happened. E.g. you opened a previously generated CKPT files, using the same prompts, found the images are blurred. Or you train the model using the same raw pictures and setting as before, and could not generate as good picture as before?

Training a new model using the same images that you used in a generated model before UNet_Learning_Rate was added to the colab, the images that this new model generates do not output correctly. In the previous one, if everything goes well, I don't know what I can be doing wrong or why they come out like this.

**Comment by longlivebigcat** [comment]
> 

Have you tried to modify the UNet Learning Rate to 2-e6 and try again? When the colab UI was modified, the default UNet Learning Rate was set to 3-e5. This is quite a high value and could influence the result.
