### ISSUE TITLE
stable diffusion checkpoint dropdown not appearing

### ISSUE THREAD

**Issue by edwardk1234** [TheLastBen/fast-stable-diffusion#1225]
I have saved my models into the correct folder. However, when I load the web UI, I do not see place to select the models. I am missing the part with the red box. How to solve this? thanks

![image](https://user-images.githubusercontent.com/56983402/210271765-18d3ef2b-5ab9-49ba-afa8-17e8cf67bbe1.png)

**Comment by TheLastBen** [comment]
What folder did you put the models into ?

**Comment by edwardk1234** [comment]
> What folder did you put the models into ?

I put it over here. 

![image](https://user-images.githubusercontent.com/56983402/210272090-334d474d-bb65-4a1f-b712-b2bb20755b7c.png)

**Comment by TheLastBen** [comment]
Is it A1111 colab or dreambooth ?

**Comment by edwardk1234** [comment]
Uninstalled and reinstalled. Works already. No idea what happened.
