### ISSUE TITLE
I get a Error: "EOFError: Ran out of input"

### ISSUE THREAD

**Issue by TheSirTigerr** [TheLastBen/fast-stable-diffusion#1238]
I get this error and i dont know what i can do can somone pls help me?
![image](https://user-images.githubusercontent.com/96537622/210355298-4b55685b-7fcd-4e7b-bd26-337e4976f148.png)

**Comment by TheSirTigerr** [comment]
is there a way i can add multiple model inside the skript? because i used like 5 other models and it didnt worked. now i didn't used them and it worked. is it because one of the files are corrupt or because i used multiple models?

**Comment by TheLastBen** [comment]
probably one of them is corrupt

**Comment by TheSirTigerr** [comment]
it was a corruption i redownloaded the files and it works now.
