### ISSUE TITLE
I tried to send a image to Extras and it doesnt load the image

### ISSUE THREAD

**Issue by TheSirTigerr** [TheLastBen/fast-stable-diffusion#1241]
I tried to send a image to Extras and it doesnt load the image i get this error:
![image](https://user-images.githubusercontent.com/96537622/210373764-e033fa4b-bee7-4f51-8410-617bb94d1f4c.png)

**Comment by apaicu123** [comment]
Same here.

**Comment by TheLastBen** [comment]
try with the latest colab and see if the error persists

**Comment by TheSirTigerr** [comment]
thanks now it is working with the new colab and after i deleted the old files.
