### ISSUE TITLE
automatic1111 not accessible on github now?

### ISSUE THREAD

**Issue by longlivebigcat** [TheLastBen/fast-stable-diffusion#1262]
Just tried to run the Colab, found that it could not do:
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui

It seems that the AUTOMATIC1111/stable-diffusion-webui is not accessible on github. Is it going through an update?

**Comment by bananasss00** [comment]
https://github.com/AUTOMATIC1111
404 error 
he renamed the profile or deleted it

**Comment by imacopypaster** [comment]
https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui.git

**Comment by longlivebigcat** [comment]
Thank you for the info. Now I know what was going on.

**Comment by xITmasterx** [comment]
I finally got Fast-Stable-Diffusion working with the new links, do I push a new update?

**Comment by cerarslan** [comment]
How can I solve on colab guys? I triend ' git remote set-url origin https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui ' on a cell but didn't work for me. Just wait for legend Ben's solution?

**Comment by Larry2600** [comment]
> How can I solve on colab guys? I triend ' git remote set-url origin https://gitgud.io/AUTOMATIC1111/stable-diffusion-webui ' on a cell but didn't work for me. Just wait for legend Ben's solution?

Shouldn't take too long, Ben made a few new commits already, he's porting the gits to Gitgud as we speak.

**Comment by cerarslan** [comment]
I just saw before your comment. He is a really hero :)

**Comment by DearDhruv** [comment]
Account has been restored on Github: https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by xITmasterx** [comment]
Should we transition this back to github?

**Comment by jcplus** [comment]
gitgud sucks. it's down again.

**Comment by TheLastBen** [comment]
The colab was transitioned back to github the same day
