### ISSUE TITLE
No link output in the last cell

### ISSUE THREAD

**Issue by Geeky-Mechanic** [TheLastBen/fast-stable-diffusion#1266]
Hi! Yesterday everything worked fine, then I had the lag of not being able to generate more than one image, so I restarted the runtime. After that, the last cell did not output the link, so I restarted and deleted the runtime. Still did not do the trick, so I deleted my copy of the colab and pulled a fresh one and still have the same error... Is there a setting that I could have checked accidentally?

**Comment by mcalabuig** [comment]
Same here. I've tried everything and still doesn't work. Yesterday everything was fine.

**Comment by TastyMackerel** [comment]
Something must've happened with the code again, having the same issues here - it just "completes" in maybe 5 seconds without actually doing anything.

**Comment by TheLastBen** [comment]
fixed now, use the latest colabs
