### ISSUE TITLE
Error while testing the trained model

### ISSUE THREAD

**Issue by krutikbackup** [TheLastBen/fast-stable-diffusion#1268]
fatal: could not read Username for 'https://github.com/': No such device or address

**Comment by longlivebigcat** [comment]
The AUTOMATIC1111 web GUI‘s github repository have been remove by github. You need to:
1. remove the SD folder on your google drive
2. use the latest [TheLastBen](https://github.com/TheLastBen) Colab.

It will work

**Comment by krutikbackup** [comment]
Thank you 
I will try

**Comment by krutikbackup** [comment]
Issue solved 
Thank you again :)
