### ISSUE TITLE
AttributeError: module 'modules.ui_tempdir' has no attribute 'on_tmpdir_changed'

### ISSUE THREAD

**Issue by Shirogenesis** [TheLastBen/fast-stable-diffusion#1272]
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [6bccbcc6] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 203, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 142, in webui
    initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 78, in initialize
    shared.opts.onchange("temp_dir", ui_tempdir.on_tmpdir_changed)
AttributeError: module 'modules.ui_tempdir' has no attribute 'on_tmpdir_changed'

**Comment by afrosadr2** [comment]
same with me

**Comment by Shirogenesis** [comment]
I resolved it by reinstalling my google colab try to clear your existing colab i guess and reinstall everything it worked for me ! hope will work for you 👍
