### ISSUE TITLE
Hypernetworks issues

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#128]
Hypernetworks isn't working correctly.
But it works good on local deployment of Auto1111 original version
I suspect this problem may cause by xformers.
![xy_grid-0019-1665286262](https://user-images.githubusercontent.com/112967097/195000476-b0dc01b3-2169-456a-86d6-7ced24f4e0f6.png)

**Comment by TheLastBen** [comment]
we'll wait for more users feedback to see where is the issue

**Comment by zwitshr** [comment]
Running the last cell gives me this message:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 32, in <module>
    import modules.hypernetworks.hypernetwork
ModuleNotFoundError: No module named 'modules.hypernetworks'

**Comment by TheLastBen** [comment]
@zwitshr you are using an outdated colab notebook, use the one from here https://github.com/TheLastBen/fast-stable-diffusion

**Comment by zwitshr** [comment]
> @zwitshr you are using an outdated colab notebook, use the one from here https://github.com/TheLastBen/fast-stable-diffusion

Thx, 
got it working after deleting and reinstalling

**Comment by TheLastBen** [comment]
Great !

**Comment by jcplus** [comment]
> Running the last cell gives me this message:
> 
> Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 32, in import modules.hypernetworks.hypernetwork ModuleNotFoundError: No module named 'modules.hypernetworks'

I have the same issue. By deleting the `sd` folder fixed it.
*Suggestion*:
Can the output folder be defined outside of the `sd` folder?
Mostly starting the colab I receive an error of something not found. I had to copy the `outputs` folder out and delete the `sd` folder than restart the colab and things work again.

**Comment by tsound97** [comment]
> 

Could see if it's working correctly?
I can't see big difference when using different Hypernetworks

**Comment by tsound97** [comment]
Could see if it's working correctly? @zwitshr 
I can't see big difference when using different Hypernetworks

**Comment by jcplus** [comment]
My bad, I should've noticed it. Thanks @TheLastBen
