### ISSUE TITLE
All models, embeddings, VAEs deleted from Google Drive after updating repo in Notebook

### ISSUE THREAD

**Issue by grexzen** [TheLastBen/fast-stable-diffusion#1289]
Just updated the repo, while starting the notebook, and all my models (including custom) are gone, can't find them in the trash either.

Do they get moved to another folder or are they really all gone now? :(

**Comment by TheLastBen** [comment]
nothing in the code that wipes out storage, check the gdrive trash, everything should be there if you didn't manually empty the trash

**Comment by SorenTruelsen** [comment]
> Just updated the repo, while starting the notebook, and all my models (including custom) are gone, can't find them in the trash either.
> 
> Do they get moved to another folder or are they really all gone now? :(

Google can recover them if you are wiling to beg a chatBot.

**Comment by grexzen** [comment]
Thanks, I really don't know what happened, I have used this notebook for months no issue. 

But here you can see that I updated the notebook yesterday at 11AM, and it put a fresh copy of all files and folders in the SD folder, and there were only 4 files in the trash from the old folder. 

![image](https://user-images.githubusercontent.com/30579087/211170710-1244df85-d432-4915-8cf5-033c4ba79ae0.png)
![image](https://user-images.githubusercontent.com/30579087/211170735-89cda138-2154-4267-9af4-3bc7b8c75a2a.png)

Currently downloading like 30 models from CivitAI. Will have to redo the merge ones. 

Although things like my log, styles xls, scripts are gone now.

**Comment by TheLastBen** [comment]
The files cannot disappear if you didn't manually remove them from the trash, if you didn't you should check with google support.

**Comment by grexzen** [comment]
Will do.
