### ISSUE TITLE
colab error file not found error gradio

### ISSUE THREAD

**Issue by re231** [TheLastBen/fast-stable-diffusion#1290]
FileNotFoundError                         Traceback (most recent call last)

[<ipython-input-3-1fdeffdd84f6>](https://localhost:8080/#) in <module>
     62 if Use_Gradio_Server:
     63   share='--share'
---> 64   for line in fileinput.input('/usr/local/lib/python3.8/dist-packages/gradio/blocks.py', inplace=True):
     65     if line.strip().startswith('self.server_name ='):
     66         line = '            self.server_name = server_name\n'

1 frames

[/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
    340                     pass
    341                 # The next few lines may raise OSError
--> 342                 os.rename(self._filename, self._backupfilename)
    343                 self._file = open(self._backupfilename, self._mode)
    344                 try:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.8/dist-packages/gradio/blocks.py.bak'

**Comment by ataa** [comment]
I am facing the same issue with/without "Use gradio ..." check mark.

**Comment by TheLastBen** [comment]
Great!
