### ISSUE TITLE
No training steps in colab?

### ISSUE THREAD

**Issue by R-Olivaw** [TheLastBen/fast-stable-diffusion#1291]
I'm not seeing any training steps in the dreambooth training section of the colab - it just trains the UNet and text encoder, then stops. It doesn't actually train. There used to be an option to input the number of training steps, but I'm not seeing that now.

**Comment by TheLastBen** [comment]
the training steps are separated into unet steps and text encoder steps, this allows better training, the actual training steps are UNet steps, keep the text encoder total steps below 400 and keep the unet steps below 1000

**Comment by R-Olivaw** [comment]
Ah, I see - thank you for clarifying!
