### ISSUE TITLE
Xformers does not work in Colab for Automatic1111

### ISSUE THREAD

**Issue by tusharbhutt** [TheLastBen/fast-stable-diffusion#13]
Hi,

the xformers cell does not wok in the Google Colab for Automatic1111.  This is the error:
> NameError                                 Traceback (most recent call last)
> 
> [<ipython-input-9-b1c1e5f3072b>](https://localhost:8080/#) in <module>
>      17   gpu = 'P100'
>      18 
> ---> 19 if (gpu=='T4'):
>      20   get_ipython().run_line_magic('cd', '/content/')
>      21   get_ipython().system('git clone https://github.com/TheLastBen/fast-stable-diffusion')
> 
> NameError: name 'gpu' is not defined

Seems like 'gpu' is not fonud and also, what happens if the GPU is a V100 or better?

**Comment by TheLastBen** [comment]
The supported GPUs are T4 and P100, if you care to add yours (V100), you can run 
`pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers`

after around 40min, and the installation is done, navigate to `/usr/local/lib/python3.7/dist-packages/xformers`
save the two files : "**_C_flashattention.so**" and "_C.so", upload the to any host and send me the link and I will integrate them in the Colab for V100 users

**Comment by gquarles** [comment]
@TheLastBen 

Hey! I installed the repo on colab with a V100, I tossed the files in google drive

_C.so
https://drive.google.com/file/d/1Gl_9nxbom02ntBRVpEt8bYYDsBz6Wzvt/view?usp=sharing

_C_flashattention.so
https://drive.google.com/file/d/1EegDE6zEMKsqFBvTdDOFATttqdR6HUPO/view?usp=sharing

**Comment by TheLastBen** [comment]
Thank you very much, I'll integrate them immediately

**Comment by tusharbhutt** [comment]
> Hello, The supported GPUs are T4 and P100, but if you care to add yours (V100), you can run `pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers`
> 
> after around 40min, and the installation is done, navigate to `/usr/local/lib/python3.7/dist-packages/xformers` save the two files : "**_C_flashattention.so**" and "**_C.so**", upload them to any host and send me the link and I will integrate them in the Colab for V100 users.
> 
> Note: for V100 or equivalent, the speed increase is almost 100%

Excellent, will give that I try, thank you!

**Comment by TheLastBen** [comment]
@tusharbhutt  wait a few minutes before trying

**Comment by TheLastBen** [comment]
let me know if it works

**Comment by tusharbhutt** [comment]
Just snagged an A100, so will probably not work :)

I'll let you know if I can save those two files you mentioned

**Comment by taylorharrison** [comment]
@tusharbhutt @TheLastBen Just got an A100 too, ha. I'll send a link to the files, Ben.

**Comment by tusharbhutt** [comment]
Three times?!?!  Wow, I dropped from an A100 to a P100 in one go... can't wait to see what the limits are when they're imposed tomorrow by Google.

No appearance of the xformers folder under  the dist-packages yet.

**Comment by taylorharrison** [comment]
My install finished but I don't see anything with those file names. https://imgur.com/a/OIQvUN5

**Comment by TheLastBen** [comment]
@taylorharrison  try the commande : `!ls -a [path to xformers folder]` to see ifthe files exist

**Comment by tusharbhutt** [comment]
Same results, no folder.  Not sure how to run a Unix command on a Google Web Colab

**Comment by TheLastBen** [comment]
@tusharbhutt make a new cell and run this code : `!ls -al /usr/local/lib/python3.7/dist-packages/xformers/`

**Comment by TheLastBen** [comment]
files beginning with "." or "_" don't show in the colab file explorer

**Comment by gquarles** [comment]
@tusharbhutt Colab file manager hides files with certain file extensions, I had to rename those files to .py to be able to see them.

I already uploaded the compiled libraries for the V100 card on colab in a message above if you want to use those, I think @TheLastBen has already included them in the repo

**Comment by TheLastBen** [comment]
@gquarles the V100 are included, but he got an A100

**Comment by gquarles** [comment]
Oh I see, I had to rename my files to get them to show up

```
!cp /usr/local/lib/python3.7/dist-packages/xformers/_C.so /usr/local/lib/python3.7/dist-packages/xformers/C.py
!cp /usr/local/lib/python3.7/dist-packages/xformers/_C_flashattention.so /usr/local/lib/python3.7/dist-packages/xformers/C_flashattention.py 
```

**Comment by tusharbhutt** [comment]
> !ls -al /usr/local/lib/python3.7/dist-packages/xformers/

No go...

ls: cannot access '/usr/local/lib/python3.7/dist-packages/xformers/': No such file or directory

**Comment by TheLastBen** [comment]
@tusharbhutt  it needs to be reinstalled in case you disconnected from the colab

**Comment by taylorharrison** [comment]
I just got another A100. I'll run the install again and try and retrieve the files when I have a moment

**Comment by RaphaelMaschinsen** [comment]
Just came here because I got lucky and got an A100 myself. Thx @taylorharrison!

**Comment by taylorharrison** [comment]
@RaphaelMaschinsen don't thank me yet. Still building wheels over here. Will be nice to play with the A100 eventually though, ha...
