### ISSUE TITLE
Training on custom model

### ISSUE THREAD

**Issue by inck86** [TheLastBen/fast-stable-diffusion#1312]
**Error when training on a custom model with huggingface. If you train on the standard 1.5 without choosing a custom model, then the training goes well.**

Training the UNet...

  0% 0/2100 [00:00<?, ?it/s] elinckus  elinckus Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 726, in main
    accelerator.clip_grad_norm_(params_to_clip, args.max_grad_norm)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 920, in clip_grad_norm_
    self.unscale_gradients()
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 904, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/amp/grad_scaler.py", line 282, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/amp/grad_scaler.py", line 210, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.
  0% 0/2100 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--stop_text_encoder_training=350', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Elinckus-dreamlike-2100', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Elinckus-dreamlike-2100/instance_images', '--output_dir=/content/models/Elinckus-dreamlike-2100', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/Elinckus-dreamlike-2100/captions', '--instance_prompt=', '--seed=186068', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=5e-06', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=2100']' returned non-zero exit status 1.

Something went wrong

![Screenshot_1](https://user-images.githubusercontent.com/119116007/211195559-cf46a397-3990-4baf-872b-09673e7f4955.png)
![Screenshot_2](https://user-images.githubusercontent.com/119116007/211195566-5951bf6c-5482-46f6-aa94-718f636eed91.png)

**Comment by TheLastBen** [comment]
The dreamlike diffusers model is in FP16, for that specific model, use the CKPT link instead of the huggingface link
https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0/blob/main/dreamlike-photoreal-2.0.ckpt

**Comment by inck86** [comment]
> The dreamlike diffusers model is in FP16, for that specific model, use the CKPT link instead of the huggingface link https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0/blob/main/dreamlike-photoreal-2.0.ckpt


I tried this way, I get an error
![Screenshot_3](https://user-images.githubusercontent.com/119116007/211196999-dd892f23-47c1-420c-a49d-eea59bb51ea9.png)
![Screenshot_4](https://user-images.githubusercontent.com/119116007/211197001-bdaeb570-d580-4ef5-a0f5-55158f6e64bc.png)
![Screenshot_5](https://user-images.githubusercontent.com/119116007/211197003-eb68c8c0-51db-487c-87d5-7e7981181036.png)

**Comment by TheLastBen** [comment]
this is the link : https://huggingface.co/dreamlike-art/dreamlike-photoreal-2.0/resolve/main/dreamlike-photoreal-2.0.ckpt

**Comment by inck86** [comment]
thx, it works!
Ur the Best)
