### ISSUE TITLE
Img2Img Outpainting-mk2 produces "TypeError: match_histograms() got an unexpected keyword argument 'channel_axis'"

### ISSUE THREAD

**Issue by bananasss00** [TheLastBen/fast-stable-diffusion#132]
Used colab: fast_stable_diffusion_AUTOMATIC1111.ipynb

`!pip install scikit-image --upgrade`
solve this problem

**Comment by TheLastBen** [comment]
I'll add that to the dependencies

**Comment by TheLastBen** [comment]
done https://github.com/TheLastBen/fast-stable-diffusion/commit/50e957ef048100774231782ddefc4e00cfd0413f
