### ISSUE TITLE
Trained model ignores the trained subject with moderately complex prompts

### ISSUE THREAD

**Issue by RoboPhred** [TheLastBen/fast-stable-diffusion#1339]
I am training a model on 20 photos of a single face, which contains a 50/50 mix of torso and up selfies and full body shots.
I am not using any context images, and sticking to the default settings for the trainer (650 unet, 250 text enc).

In both SD 1.5 and 2-512, the models have no trouble producing new images that are highly similar to the old ones with a prompt such as "A photo of sks".  However, the moment I try to add any additional context, say, "A photo of sks on a white sand beach", it completely forgets the faces I trained it on and starts generating either random people, or scenes without any people in it at all

Additional training of unet doesn't seem to solve this issue...

I am entering this space mostly blind, so I have no idea what the issue might be here.  Any guidance as to how to train a model to produce people in situations beyond the original training data would be greatly appreciated.

**Comment by TheLastBen** [comment]
two solutions,1- use ( ) around the identifier (don't use sks) to put more weight on it
2- resume the training for an addition 250 steps for the text encoder (only).

**Comment by RoboPhred** [comment]
Thanks.  Using parenthesis around the identifier didn't have any effect, but further text encoder training has seemed to given it the right idea.  However, that also has seemed to cause the quality of the resulting images to degrade from the base "a photo of identifier" prompt.

Knowing that it's the text encoder that was failing on me might be enough to help me push this further.  I will re-try training some of my other image sets with additional text encoder training and see if I can start to get the quality up.

**Comment by RoboPhred** [comment]
I'm sure I will have more questions in the future, but this particular issue is more or less solved.  Closing.
