### ISSUE TITLE
Need large model option back

### ISSUE THREAD

**Issue by kitty7779** [TheLastBen/fast-stable-diffusion#1341]
We need it to load the [Waifu Diffusion v1.4](https://huggingface.co/hakurei/waifu-diffusion-v1-4) model from Google Drive on Colab without crashing.
I tried this [pruned version](https://huggingface.co/subaqua/_unofficial-WD1.4-fp16-safetensors/blob/main/wd-1-4-anime_e1-fp16.safetensors) too and it didn't work either.

**Comment by TheLastBen** [comment]
it crashed because somehow you A1111 repo didn't update, make sure you're running the latest A1111 repo
run
```
%cd /content/gdrive/MyDrive/sd/stable-diffusion-webui
!git pull
```

**Comment by kitty7779** [comment]
It worked. Thank you. I had to do a git reset --hard however because it was complaining about local changes to modules/ui.py.

**Comment by mrice888** [comment]
Im having the same issue with a custom model which is around the 7gb mark.  It will no longer load, crashing after loading weights on the colab.  using the code you provided did not seem to fix the issue.  It worked fine with the previous setup to allow for larger ckpt files

**Comment by TheLastBen** [comment]
fixed now

**Comment by TheLastBen** [comment]
WD1.4 uses a custom yaml file unlike other models
