### ISSUE TITLE
Large model compatibility

### ISSUE THREAD

**Issue by mrice888** [TheLastBen/fast-stable-diffusion#1342]
Since the update, using large models has become an issue on the colab.   In a previous ticket you had said to use the !git pull command to update the repo however even with an update, colab still struggles to load my whopping 7gb custom model.  The old system perfomed this task using a radial button and worked with no issues.

**Comment by TheLastBen** [comment]
I'll fix it shortly

**Comment by mrice888** [comment]
working now.  nice job thanks
