### ISSUE TITLE
FATAL: this function is for sm80, but was built for sm750

### ISSUE THREAD

**Issue by Rahza** [TheLastBen/fast-stable-diffusion#1352]
I'm receiving the above error when starting the training with the newest version, it worked for me before

**Comment by Rahza** [comment]
I'm using a EC2 instance for training - turns out it does work with T4 GPUs but doesn't with A10G GPUs (anymore - it used to work with those). Any tips on how I could resolve this issue so that it works with A10G again as well?

**Comment by TheLastBen** [comment]
two solutions :
1- `!pip uninstall -y xformers` this will remove xformers
2- run
```
!pip install ninja
!pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers
```
this will install and compile xformers but will take more than 60 minutes to finish.

**Comment by Rahza** [comment]
Perfect, that worked! Thank you
