### ISSUE TITLE
The training images don't show up in the gradio ui while training

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1356]
I noticed something changed: the textual_inversion folder used to be in the stablediffusion folfder, but now it writes them to the stable_diffusion_webui folder.

Could that be the reason? Due to the new location?

Also: gradio throws a connection error after step 397 and won't show any progression anymore. The training is still on though. There was no problem with my internetconnection btw.

**Comment by TheLastBen** [comment]
changed it to stable-diffusion-webui folder to fix all the extensions issues

**Comment by Topzie** [comment]
I'm sorry to bother you, you're doing a great job here, but could you make the image generation during training visible again?

**Comment by Topzie** [comment]
Ok, I'll let you know

**Comment by Topzie** [comment]
Now I get the CUDA out of memory warning:

 File "/usr/local/lib/python3.8/dist-packages/torch/functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.16 GiB (GPU 0; 14.76 GiB total capacity; 12.57 GiB already allocated; 989.75 MiB free; 12.73 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Applying xformers cross attention optimization.

**Comment by Topzie** [comment]
I tried to make it work by adding   !pip install transformers==4.19.2  like you suggested before, but this doesn't work anymore.

**Comment by Topzie** [comment]
The images are just black squares

**Comment by Topzie** [comment]
Output when starting stable diffusion:

LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading weights [6bccbcc6] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying xformers cross attention optimization.
No Image data blocks found.

**Comment by Topzie** [comment]
(Deleted the last comment, since that was about an embedding)

**Comment by Topzie** [comment]
I'm sorry, my bad, I forgot to check Move VAE and CLIP to RAM when training if possible. Saves VRAM. and Use cross attention optimizations while training

It's running, but still without the images showing up in the interface.

**Comment by Topzie** [comment]
The issue is still there. No problem with 'normal' image generation, just the images during training.

**Comment by Topzie** [comment]
No luck fixing it or no time (yet)?

**Comment by Topzie** [comment]
Thank you so much for making it work again, you are a gem. 😘
