### ISSUE TITLE
modify the colab notebook.

### ISSUE THREAD

**Issue by tamal777** [TheLastBen/fast-stable-diffusion#1359]
hey ben how do I modify the notebook if I fork or copy auto1111 repo so I don't have to worry about auto1111 updates? thanks

**Comment by TheLastBen** [comment]
the colab always download few python files from the A1111 repo even without the update to make sure it's 100% compatible with colab, so I'm afraid it's impossible to have a stable version of the colab.

**Comment by tamal777** [comment]
> the colab always download few python files from the A1111 repo

So it will not work if I copy and upload the whole repo to my account?

**Comment by TheLastBen** [comment]
it will always download the newest files from A1111
