### ISSUE TITLE
ModuleNotFoundError: No module named 'modules.hypernetworks'

### ISSUE THREAD

**Issue by graphicgolem** [TheLastBen/fast-stable-diffusion#136]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 32, in <module>
    import modules.hypernetworks.hypernetwork
ModuleNotFoundError: No module named 'modules.hypernetworks'

**Comment by graphicgolem** [comment]
Needed to update

**Comment by TheLastBen** [comment]
there is a checkbox (update repo), use it periodically.
