### ISSUE TITLE
Dreambooth colab script bug--can't use External_Captions for Text_Encoder_Training

### ISSUE THREAD

**Issue by alinasama** [TheLastBen/fast-stable-diffusion#1364]
When I only training Text_Encoder_Training, if select External_Captions, the training will not start with error: "something goes wrong"

**Comment by TheLastBen** [comment]
Copy the error log here if possible

**Comment by alinasama** [comment]
I know the reason. I select using external captions but I only select train text encoder, so it will have the error, looks I can't only train text encoder using external captions.
