### ISSUE TITLE
Dreambooth colab script bug--the Save_Checkpoint_Every_n_Steps doesn't working

### ISSUE THREAD

**Issue by alinasama** [TheLastBen/fast-stable-diffusion#1365]
When training the model, even I set save checkpoint every 500 steps, but it will never save any of them into my google drive. until you finished max step you set and it stopped training, it just save this "finnal" checkpoint to my google drive.

**Comment by TheLastBen** [comment]
Did you tick the box "save_checkpoints" ?

**Comment by alinasama** [comment]
I found that the "save_checkpoints" only works for unet not the text encoder

**Comment by TheLastBen** [comment]
Yes
