### ISSUE TITLE
Can't load up a previously trained model into the tester

### ISSUE THREAD

**Issue by Brandyfan** [TheLastBen/fast-stable-diffusion#1374]
I'm trying to reload a trained model I made yesterday into the tester on the bottom of the google colab since I didn't have time to test it yesterday. When I put in the ckpt file, it says- The model doesn't exist on you Gdrive, use the file explorer to get the path : 
I then tried copying the file path from my google drive, but got the same response.
I tried looking through the guide but there's nothing listed about uploading a previously made model to test or train some more.
Any ideas?

**Comment by Brandyfan** [comment]
Cancel that, I was able to figure it out. I had to load it up in the previous steps then to bypass the training since it was already trained, I told it just to train 1 step. Now I'm able to test the model and it works perfectly. :)

**Comment by TheLastBen** [comment]
or you can simply type the pervious session name in the box "previous_session" and run the cell

**Comment by Brandyfan** [comment]
> or you can simply type the pervious session name in the box "previous_session" and run the cell

I tried that but all I get is "The model doesn't exist on you Gdrive, use the file explorer to get the path :"
I tried the name of the session and then the link to that session from my google drive.
