### ISSUE TITLE
FileNotFoundError - blocks.py

### ISSUE THREAD

**Issue by Ai-Artsca** [TheLastBen/fast-stable-diffusion#1382]
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-5-c1bc5a97bd8c>](https://localhost:8080/#) in <module>
     61 if Use_Gradio_Server:
     62   share='--share'
---> 63   for line in fileinput.input('/usr/local/lib/python3.8/dist-packages/gradio/blocks.py', inplace=True):
     64     if line.strip().startswith('self.server_name ='):
     65         line = '            self.server_name = server_name\n'

1 frames
[/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
    340                     pass
    341                 # The next few lines may raise OSError
--> 342                 os.rename(self._filename, self._backupfilename)
    343                 self._file = open(self._backupfilename, self._mode)
    344                 try:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.8/dist-packages/gradio/blocks.py.bak'

**Comment by TheLastBen** [comment]
either you missed the requirements cell or you are using aa very old version of the notebook
