### ISSUE TITLE
UNDERSTANDING Learning Rate, Steps, and Loss

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#139]
Hello Ben, I have read about the learning rate some weeks ago, and I am getting curious on how on many webpages they mention that the best rate is 2e-4 or even 1e-4.

Still on MANY collabs about model training, I see you guys use 5e-6. 

What PRO's mention is that the LR depends on how many images are used to train...? Is that accurate? Anyway, how can we learn more about, or what's the BEST LR for, let's say, 15 images for training a 2000 steps model? I also have read that YOU CAN COOK a model (burn it), and I have done it before, so I believe LR is important. 

So how can we balance steps with image's input amount, and LR...... ?

**Comment by TheLastBen** [comment]
All those settings need to be experimented with, dreambooth is still in early stage
