### ISSUE TITLE
Error loading stable diffusion on the latest colab.

### ISSUE THREAD

**Issue by luci9t** [TheLastBen/fast-stable-diffusion#1390]
I am using the latest colab, do I need to delete the folder and rerun it? It loads the ckpt, and before loading vae it just shows this. Also, [this](https://github.com/TheLastBen/fast-stable-diffusion/blob/00943c3fd2503155ecd3666a10b3a112a8fb4293/fast-DreamBooth.ipynb) commit works fine though. 
```
loading stable diffusion model: ValueError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 74, in initialize
    modules.sd_models.load_model()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 385, in load_model
    load_model_weights(sd_model, checkpoint_info)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 280, in load_model_weights
    vae_file, vae_source = sd_vae.resolve_vae(checkpoint_info.filename)
ValueError: too many values to unpack (expected 2)

Stable diffusion model failed to load, exiting
```

**Comment by TheLastBen** [comment]
I think that's an A1111 issue not the colab's

**Comment by Brandyfan** [comment]
I had the same issue earlier too. I had to re-run the cell three times before it worked.

**Comment by luci9t** [comment]
> I think that's an A1111 issue not the colab's, no need to remove the folder sd anymore

ohk, that's a relief, it was a pain to set up everything again and again.
