### ISSUE TITLE
Crash after Dreambooth extension install  

### ISSUE THREAD

**Issue by freeload101** [TheLastBen/fast-stable-diffusion#1392]
* colab pro paid
* one drive paid
* tried without/with mounting gdrive
* A111 works fine untill I install the dream booth extension ..
* tried colab version ( https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb )  and direct from github both same issue

```
raceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
  File "/usr/local/lib/python3.8/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.8/dist-packages/gradio/components.py", line 36, in <module>
    from gradio.blocks import Block
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 44, in <module>
    from gradio.documentation import (
ImportError: cannot import name 'document_component_api' from 'gradio.documentation' (/usr/local/lib/python3.8/dist-packages/gradio/documentation.py)
```

**Comment by oxie** [comment]
same problem, just tryed, and seems problems getting more and more :/

**Comment by TheLastBen** [comment]
crash because the dreambooth extension dev decided to force gradio 3.15 dependency, it's not the colab's fault

**Comment by oxie** [comment]
it would great if you could have an easy process to sync dependencies, so we would have at least 1 working version of SD with DB

**Comment by freeload101** [comment]
Thank god ill try Linaqruf/kohya-trainer/ ( complicated ... ) or see if I can get to put on the plugin URL to get the newest pre 1.35 repo ... Thanks I was beating my head against the wall trying to get it to work.

**Comment by Excalibro1** [comment]
> it would great if you could have an easy process to sync dependencies, so we would have at least 1 working version of SD with DB

Sorry in advanced if this is out of the scope of what you're saying.

Your best bet would be to fork Ben's repo and keep that as your stable version and update the fork only if Ben's is stable enough for what you need to do.

So instead of `https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb` you would use `https://colab.research.google.com/github/YourUser/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb`

 If you're using the db extension through Automatic1111 probably best to try the extension through Ben's main branch and if it has issues go back to your fork of the notebook  and don't install updates to the db extension unless you know it's working.

**Comment by TheLastBen** [comment]
@oxie  I already packed most of the dependencies to make sure most of the extensions work, but the dreambooth extension is too demanding dependencies wise as it forces specific versions of each package which messes with the stability of the vm's environment, these are the requirements for the extension : https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/requirements.txt

**Comment by nawnie** [comment]
to use D8's webui DB its best to use the Fast stable diffusion notebook so you can avoid dependency issues with Ben's "fast-Dreambooth"
