### ISSUE TITLE
Automatic and hkly colab dont work

### ISSUE THREAD

**Issue by Spiri2022** [TheLastBen/fast-stable-diffusion#14]
No such operator xformers::efficient_attention_forward_cutlass - did you forget to build xformers with `python setup.py develop`?
![image](https://user-images.githubusercontent.com/111901502/193060012-569f46db-39cd-4f0f-bd95-f5c2e41e3f71.png)

**Comment by TheLastBen** [comment]
xformers updated their repo, I will fix it in 5 minutes

**Comment by Spiri2022** [comment]
Nice!!

**Comment by Spiri2022** [comment]
Is it possible that files are missing for the P-100?
![image](https://user-images.githubusercontent.com/111901502/193085245-eabf874f-e047-42b1-b2e4-f7a34f073803.png)

**Comment by Spiri2022** [comment]
![image](https://user-images.githubusercontent.com/111901502/193086832-81c71273-5e80-4091-9640-55ab6494c5bc.png)

**Comment by TheLastBen** [comment]
I think the problem is with "git", try to run the cell again, just rename the folder fast-stable-diffusion into something else before that.

**Comment by TheLastBen** [comment]
it works in most cases
![image](https://user-images.githubusercontent.com/110583491/193089468-14939ddb-632a-4582-a1c1-01d0ec6e88b2.png)

**Comment by Spiri2022** [comment]
Now works fine!!, thanks
