### ISSUE TITLE
if i load a model it will exit 

### ISSUE THREAD

**Issue by rewixx** [TheLastBen/fast-stable-diffusion#1404]
✔ Connected
LatentInpaintDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.93 M params.
Loading weights [2a208a7ded] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/512-inpainting.ckpt
^C

**Comment by mediocreatmybest** [comment]
It is running out of RAM, I've found you need to select High RAM in the runtime, as soon as you are loading larger models or using V2 items like that.

**Comment by TheLastBen** [comment]
You shouldn't get this error if your A1111 repo is up to date

**Comment by rewixx** [comment]
still its not working

**Comment by TheLastBen** [comment]
is it this model ? https://huggingface.co/stabilityai/stable-diffusion-2-inpainting/tree/main

**Comment by rewixx** [comment]
yes

**Comment by TheLastBen** [comment]
use the latest colab and check there is no extension that causes high RAM usage

**Comment by rewixx** [comment]
its still causes high RAM usage

**Comment by TheLastBen** [comment]
Since google colab updated their internal packages, stable diffusion has issues with high RAM, I left them a message but I doubt they will answer, I suspect they've done it on purpose to push people to buy premium.

**Comment by rewixx** [comment]
i hope
