### ISSUE TITLE
After converting to ckpt: The config attributes {'upcast_attention': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1411]
SD didn't start, I got a lot of errors so I did a fresh install.
This is what happened (I'm using the regular 2.1 7-68 model)

After running Model load/download, I see this error/warning:

The config attributes {'upcast_attention': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.

Next when trying to start SD I get this and it stops.

Warning: Taming Transformers not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/taming-transformers/taming
Warning: CodeFormer not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/codeformer/inference_codeformer.py
Warning: BLIP not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/blip/models/blip.py
Warning: k_diffusion not found at path /content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/sampling.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 21, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 8, in <module>
    import k_diffusion.sampling
ModuleNotFoundError: No module named 'k_diffusion'

I have tried it with safetensors on as well as off.

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by Topzie** [comment]
Good to know. the first one is nothong to worry about.
Btw, it worked yesterday, so I guess it has to do with the latest update.

**Comment by TheLastBen** [comment]
will fix in a few minutes

**Comment by Topzie** [comment]
Wow, thanks! A lot!

**Comment by TheLastBen** [comment]
refresh the colab from the main link, it should work now

**Comment by Topzie** [comment]
Not yet there..

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 13, in <module>
    import modules.interrogate
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/interrogate.py", line 13, in <module>
    from modules import devices, paths, lowvram, modelloader
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 18, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['/content/gdrive/MyDrive/sd/stablediffusion', '.', '/content/gdrive/MyDrive/sd']

**Comment by Topzie** [comment]
Oops, the stablediffusionfolder is missing.

**Comment by Topzie** [comment]
I've rerun the requirements and now it's working. 
Thanks again 😘
