### ISSUE TITLE
Save Checkpoint every n steps fails to save file

### ISSUE THREAD

**Issue by jonathangoorin** [TheLastBen/fast-stable-diffusion#1413]
When Training the UNet I specify to save every 1000 steps, but it fails everytime and outputs 

Progress:|████████                 | 33% 999/3000 [14:03<27:51,  1.20it/s, loss=0.00737, lr=3.37e-6] SAVING CHECKPOINT...
Converting to CKPT ...
Killed
Done, resuming training ...

It does save the final checkpoint 
Started happening from today, any ideas?

**Comment by TheLastBen** [comment]
the v2 is too big for the colab free RAM to handle, if you're using colab pro, set the runtime-shape to HIGH-RAM and keep the GPU to standard

**Comment by flesler** [comment]
And if not using colab pro bro? You just broke it for everyone using free colab without warning?

**Comment by 2blackbar** [comment]
thats true , it wont save checkpoints

**Comment by strangePause** [comment]
Why now? It was fine yesterday. I trust it will be fixed soon, however.

**Comment by TheLastBen** [comment]
Could be xformers 16 or pytorch 1.13.1, i'm testing it

**Comment by TheLastBen** [comment]
Google colab bumped pytorch to 1.13.1, that's what's causing RAM issues, I'll implement a temporary fix that will convert the checkpoints to CKPT only after training.

**Comment by flesler** [comment]
Is it working right now?
If so, do the intermediate versions get saved or only the last?

**Comment by flesler** [comment]
Gave it a quick try, couldn't even get there. Reported #1436

**Comment by TheLastBen** [comment]
not fixed yet, I'm working on i

**Comment by TheLastBen** [comment]
It should work now https://github.com/TheLastBen/diffusers/commit/df1d14f0117eaa74d91a2fa8c4c0fcf1862060e5

**Comment by jonathangoorin** [comment]
@TheLastBen Thanks!!!
