### ISSUE TITLE
Model merge problem: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by KuzeyVural** [TheLastBen/fast-stable-diffusion#1417]
Error loading/saving model file:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1713, in modelmerger
    results = modules.extras.run_modelmerger(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 292, in run_modelmerger
    tertiary_model_info = sd_models.checkpoints_list.get(tertiary_model_name, None)
TypeError: unhashable type: 'list'

When I try to merge, I get this.

**Comment by TheLastBen** [comment]
You didn't set the tertiary model

**Comment by KuzeyVural** [comment]
But I used to do it that way, never happened before.

**Comment by TheLastBen** [comment]
what type of merging did you use ?

**Comment by TheLastBen** [comment]
it's an issue with A1111 https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6878 they will fix it soon

**Comment by KuzeyVural** [comment]
Oh, sorry.. Thank you <3
