### ISSUE TITLE
Arguments?

### ISSUE THREAD

**Issue by rustyorb** [TheLastBen/fast-stable-diffusion#1419]
Having trouble finding arguments in the code. I was hoping to flag, toggle, a few.

Thanks for everything though, seriously gotta be a pain in the arse dealing with users. Using it for free, and expecting so much. lol.

**Comment by TheLastBen** [comment]
in the last cell, the last 3 lines you can find the arguments there.

**Comment by rustyorb** [comment]
I was about to say disregard, as I found them. Thanks though.
