### ISSUE TITLE
Fast Dereambooth colab huggingface login issue

### ISSUE THREAD

**Issue by mrice888** [TheLastBen/fast-stable-diffusion#1422]
The cell for downloading the model from huggingface, no longer has a spot for  a token and will not download custom models from huggingface.  It seems it will only allow for sd 1.5 model

**Comment by TheLastBen** [comment]
do the custom models require the hf token ?

**Comment by mrice888** [comment]
I think so  Its access is private for my team only I set it to publican d works fine but it used to work while it was listed as private

**Comment by TheLastBen** [comment]
I'll add an option for private models

**Comment by mrice888** [comment]
thank you

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/f9cf6f348ae8d42b1419115f3e57b881fa973d73

**Comment by mrice888** [comment]
I like the way you set that up but for some reason when I put the token.txt file in that directory it still fails to load the repository from huggingface

**Comment by TheLastBen** [comment]
I'll fix it
