### ISSUE TITLE
Save to PC/Local Drive on Google Colab

### ISSUE THREAD

**Issue by SorenTruelsen** [TheLastBen/fast-stable-diffusion#1429]
It would be really cool if it was possible to setup Fast-Stable-diffusion (WebUI on Gradio) to save directly to local PC/Laptop. It works saving on Google Drive (Output folder), but I then have to transfer them all to my PC later to sort my pictures. Security settings on my network prevents me from installing and running the application local and I cannot get "local tunnel" to work on Colab.

**Comment by TheLastBen** [comment]
the notebook can only have access to colab storage or gdrive.

**Comment by SorenTruelsen** [comment]
> the notebook can only have access to colab storage or gdrive.

It it possible to run the WebUI local, from my PC, but using Colab's GPU/Servere for running SD?

**Comment by TheLastBen** [comment]
Not possible

**Comment by SorenTruelsen** [comment]
Oh well :)
