### ISSUE TITLE
fast Dreambooth is  producing lot of errors in google colab, (since few days)

### ISSUE THREAD

**Issue by tronizx** [TheLastBen/fast-stable-diffusion#1431]
since few days , i think you have updated somthing that is why fast dreambooth colab notebook is producing errors, it doesnt even start with creating new model of loading previous both, at first it asked to install 'wget' and then 'deffusers' which  is before installed by default by you inbuild scripts. But now it is not working not training model either, here is sample errors:

In training cell - 
Training the UNet...
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 542, in main
    import bitsandbytes as bnb
ModuleNotFoundError: No module named 'bitsandbytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 544, in main
    raise ImportError(
ImportError: To use 8-bit Adam, please install the bitsandbytes library: `pip install bitsandbytes`.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--stop_text_encoder_training=250', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shinkai-v2', '--pretrained_model_name_or_path=/content/stable-diffusion-custom', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shinkai-v2/instance_images', '--output_dir=/content/models/shinkai-v2', '--captions_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/shinkai-v2/captions', '--instance_prompt=', '--seed=822512', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=1e-05', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=50']' returned non-zero exit status 1.
Something went wrong

and some dependencies error too, i don't know what cause this happen but checked it with completely new file in colab but still got same errors, plz take a look and try to figure it out in repository.

**Comment by TheLastBen** [comment]
You're probably running an old version of the notebook, use the official links
