### ISSUE TITLE
Update Model at Huggingface

### ISSUE THREAD

**Issue by tronizx** [TheLastBen/fast-stable-diffusion#1433]
can  you fix code in dreambooth notebook to to update model files in huggingface

**Comment by TheLastBen** [comment]
you're getting an error ?

**Comment by tronizx** [comment]
Yes i'm getting error like " This repository already exist"...

**Comment by TheLastBen** [comment]
I see, as a temporary fix, remove the line "create_repo(repo_id,private=True, token=hf_token)" in the hf uploading cell

**Comment by tronizx** [comment]
Thanx for  you quick responses , i m gonna try it!!!
