### ISSUE TITLE
Cannot merge models

### ISSUE THREAD

**Issue by manzomium** [TheLastBen/fast-stable-diffusion#1440]
I get this error
Error merging checkpoints: run_modelmerger() missing 2 required positional arguments: 'config_source' and 'bake_in_vae'
 these are my settings:
![image](https://user-images.githubusercontent.com/119815787/213579770-f65f018a-fd4d-4acc-814f-d394c1347e29.png)

**Comment by TheLastBen** [comment]
I'm sure you'll find the right answer here : https://github.com/AUTOMATIC1111/stable-diffusion-webui
