### ISSUE TITLE
Cannot interrupt execution

### ISSUE THREAD

**Issue by manzomium** [TheLastBen/fast-stable-diffusion#1441]
When I click on the Interrupt button, nothing happens and batch generation goes on. No error messages are shown. I need to stop the process in the console and reload to stop it.
I'm using tunnel.

**Comment by TheLastBen** [comment]
Try clicking many times until it stops

**Comment by KuzeyVural** [comment]
same issue here, I even clicked several times it didn't stop or skip

**Comment by TheLastBen** [comment]
that's the side effect of using the "queue" to avoid images not showing in the UI

**Comment by KuzeyVural** [comment]
how can I fix it

**Comment by TheLastBen** [comment]
if you fix it you won't be able to generate batches

**Comment by KuzeyVural** [comment]
I don't need generate batches I'm generating 1 for example, I'm testing a prompt but I didn't like so I want to interrupt or skip, but I can't. How can I?

**Comment by TheLastBen** [comment]
in the A1111 colab, remove this line:
```
!sed -i 's@ui.create_ui().*@ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)@' /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py
```

**Comment by KuzeyVural** [comment]
> When I click on the Interrupt button, nothing happens and batch generation goes on. No error messages are shown. I need to stop the process in the console and reload to stop it. I'm using tunnel.

Hey, I fixed it by removing all my files and reinstalling sd. Now I can interrupt 👍 thanks for help for all

**Comment by manzomium** [comment]
> > When I click on the Interrupt button, nothing happens and batch generation goes on. No error messages are shown. I need to stop the process in the console and reload to stop it. I'm using tunnel.
> 
> Hey, I fixed it by removing all my files and reinstalling sd. Now I can interrupt 👍 thanks for help for all

**Comment by manzomium** [comment]
yeah, fresh install solved the problem
