### ISSUE TITLE
Checkpoint model.ckpt [43c90409bd] not found; loading fallback model.ckpt [43c90409bd]

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1453]
Why is this?
I redownloaded the original model from HF. Twice, to be sure. Didn't make any difference.

automatic1111 notebook (not dreambooth)

**Comment by TheLastBen** [comment]
It's just a message, it's the same model anyway

**Comment by Topzie** [comment]
Ok, thanks.
Never had it before, so I wondered.
