### ISSUE TITLE
hypernetworks don't working

### ISSUE THREAD

**Issue by Inkorak** [TheLastBen/fast-stable-diffusion#146]
I try to apply the hypernetworks from the novelai in the AUTOMATIC1111 settings, but they don't change anything.
In this colab hypernetworks work fine.
https://github.com/daswer123/stable-diffusion-colab

**Comment by Inkorak** [comment]
No, everything works as if they were not turned on.

**Comment by Inkorak** [comment]
I did this, still doesn't work. And as I said above, the colab from daswer123 link works great. But it is worse than yours in that it takes a long time to set up.

**Comment by Inkorak** [comment]
And perhaps a clarification. I throw the weights from the novelai on the google drive where the SD is installed. So for novelai, you need main weights, vae weights, yaml config and the weights of the hypernetworks themselves. 
I do not use Model Download / Load, since it only allows one file to be loaded.

**Comment by TheLastBen** [comment]
You will get better answers about hypernetwork opening a discussion in the AUT1111 repo https://github.com/AUTOMATIC1111/stable-diffusion-webui/

**Comment by tsound97** [comment]
Same problem.  Hypernetworks don't work. No error messages.

**Comment by tsound97** [comment]
Thanks so much for fixing that problem! You are my hero. @TheLastBen

**Comment by TheLastBen** [comment]
happy to help
