### ISSUE TITLE
Colab notebook is broken for Automatic1111 (missing a file).

### ISSUE THREAD

**Issue by DarkAlchy** [TheLastBen/fast-stable-diffusion#1470]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 23, in <module>
    import modules.extras
  File "/content/gdrive/.shortcut-targets-by-id/1jDr0_KMRaPiALQdKq3oR3pPuSFMDR9kY/sd/stable-diffusion-webui/modules/extras.py", line 10, in <module>
    from modules.ui_common import plaintext_to_html
ModuleNotFoundError: No module named 'modules.ui_common'

I tried updating twice then I regrabbed the notebook and ran through all choices and the same error so no training tonight it seems.

**Comment by dogjamboree** [comment]
you have to delete or rename the sd folder and try again and it should work...worked for me

**Comment by DarkAlchy** [comment]
> you have to delete or rename the sd folder and try again and it should work...worked for me

Ouch :(  I wonder why?

**Comment by dogjamboree** [comment]
Not sure what happened but it just started happening today for me. Not sure if a change was made that triggered this or what.

**Comment by DarkAlchy** [comment]
> Not sure what happened but it just started happening today for me. Not sure if a change was made that triggered this or what.

A lot of changes happening lately with Automatic1111 and I will have to let it build it then bring in my changes to SD.
