### ISSUE TITLE
LFS: Authorization error: https://cdn-lfs.huggingface.co...

### ISSUE THREAD

**Issue by JammersUK** [TheLastBen/fast-stable-diffusion#1473]
How do I create the token.txt file?  There used to be a box to enter the Huggingface Key.
I'm trying to train with v1.5.

**Comment by HustLion** [comment]
> Error downloading object: text_encoder/pytorch_model.bin (770a47a): Smudge error: Error downloading text_encoder/pytorch_model.bin... Check that you have proper access to the repository

I solved it. Just changing the token.txt content to a newly generated Huggingface token solves the error.

**Comment by HustLion** [comment]
> How do I create the token.txt file? There used to be a box to enter the Huggingface Key. I'm trying to train with v1.5.

Use the colab file browser and navigate to gdrive/My Drive. Then create folder `Fast-Dreambooth`, and inside it create a new file called `token.txt`. Double click this file and fill your token there and save it.
