### ISSUE TITLE
AttributeError: module 'modules.paths' has no attribute 'data_path'

### ISSUE THREAD

**Issue by Tyde** [TheLastBen/fast-stable-diffusion#1505]
It seems like in the Automatic1111 repo the [`modules/paths.py`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/paths.py) was changed. Now the sideloaded [`paths.py`](https://github.com/TheLastBen/fast-stable-diffusion/blob/9ee7c0e94beb2dca7bc58774ed76def9e425eecf/AUTOMATIC1111_files/paths.py) from here does not include a data_path variable

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 16, in <module>
    from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_networks_textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks_hypernet.py", line 2, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 10, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 13, in <module>
    from modules import devices, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
    from modules import localization, extensions, script_loading, errors, ui_components, shared_items
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 10, in <module>
    extensions_dir = os.path.join(paths.data_path, "extensions")
AttributeError: module 'modules.paths' has no attribute 'data_path'
```

**Comment by abvgdeabvgde2** [comment]
Ah, here we go again. A clean setup doesn't help.

**Comment by longlivebigcat** [comment]
Had the same problem here. Tried two versions of AUTOMATIC1111 ipnb file, also tried removing SD folder, none worked.

However, the fast dreambooth ipnb seems still working (its AUTOMATIC1111 is at an older version)

**Comment by Rymi2003** [comment]
had the same problem, i hope it will be fix soon

**Comment by ToniOnlyTax** [comment]
Waiting for divine help 🫠🫠

**Comment by EleVicted** [comment]
Anyone know off hand if there are archived versions of the colab?

**Comment by EleVicted** [comment]
Also, thanks be to the (likely sleepy) divines

**Comment by VeryEvilHumna** [comment]
I often wonder why no one made a stable and beta branches

**Comment by Rymi2003** [comment]
lesson learned,take out git pull

**Comment by longlivebigcat** [comment]
> I often wonder why no one made a stable and beta branches

Some code directly pull result from other's git. That's why when something updated, it easily runs into compatibility issue. It is recommended to do git clone using compatible hash.

**Comment by VeryEvilHumna** [comment]
I made a temp fix. (Temp, don't do hardlinking in real code)

in `sd/stable-diffusion-webui/modules/paths.py`
Paste:
```data_path = "/content/gdrive/MyDrive/sd/stable-diffusion-webui/" # or some your custom path to stable-diffusion-webui folder```

**Comment by jtran-developer** [comment]
Doesn't work for me.  Can we really not disable updates?  This thing breaks 2-3 times a week.

**Comment by Rymi2003** [comment]
> lesson learned,take out git pull

@jtran-developer

**Comment by Ai-Artsca** [comment]
every update it breaks for me also just wish we had one version that just works without updating so often:

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 16, in <module>
    from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_networks_textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks_hypernet.py", line 2, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 10, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 13, in <module>
    from modules import devices, shared
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in <module>
    from modules import localization, extensions, script_loading, errors, ui_components, shared_items
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 10, in <module>
    extensions_dir = os.path.join(paths.data_path, "extensions")
AttributeError: module 'modules.paths' has no attribute 'data_path'

**Comment by Njbx** [comment]
temporary fix
change this line: ` !wget -O paths.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/AUTOMATIC1111_files/paths.py`
to
` !wget -O paths.py https://github.com/Njbx/stable-diffusion/blob/main/paths.py`

**Comment by Njbx** [comment]
temporary fix
change this line:  `!wget -O paths.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/AUTOMATIC1111_files/paths.py`
to
`!wget -O paths.py https://raw.githubusercontent.com/Njbx/stable-diffusion/main/paths.py` in Start Stable-Diffusion code chunk

**Comment by CodingMaid** [comment]
> temporary fix change this line: `!wget -O paths.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/AUTOMATIC1111_files/paths.py` to `!wget -O paths.py https://raw.githubusercontent.com/Njbx/stable-diffusion/main/paths.py` in Start Stable-Diffusion code chunk

Works for me, thank you.

**Comment by Rymi2003** [comment]
> every update it breaks for me also just wish we had one version that just works without updating so often:
> 
> Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 16, in from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_networks_textual_inversion File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks_hypernet.py", line 2, in from modules.hypernetworks import hypernetwork File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 10, in import modules.textual_inversion.dataset File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 13, in from modules import devices, shared File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 16, in from modules import localization, extensions, script_loading, errors, ui_components, shared_items File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 10, in extensions_dir = os.path.join(paths.data_path, "extensions") AttributeError: module 'modules.paths' has no attribute 'data_path'

bruh

**Comment by Tyde** [comment]
Was closed by the latest commits
