### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by M1L0J05** [TheLastBen/fast-stable-diffusion#1512]
After generating the model with v2.1-768px I can't use it in the NMKD Stable Diffusion GUI app. When loading the model I get the error:

Failed to load model
The model appears to be incompatible.

Someone knows to that can it be?

Thanks!

**Comment by Excalibro1** [comment]
Just looked through NMKDs github and it doesn't support 2.x models yet with no ETA atm.

**Comment by M1L0J05** [comment]
Thank you!! I must be blind, I read the NMKD repo and didn't see it, I'll have to be aware in case they update!

Thank you very much again!

**Comment by Excalibro1** [comment]
All good! I think it isn't actually stated in the README I had to go into closed issues and type 2.1 haha
