### ISSUE TITLE
Any problem with Gradio?

### ISSUE THREAD

**Issue by fariajurado** [TheLastBen/fast-stable-diffusion#1525]
The colab generates the URL but is not working.  bad gateway after wait 5min, tryed to create new sd folder and change the computer but not working.
Thanks for your helping

**Comment by fariajurado** [comment]
Loading weights [1c04e893ab] from /*
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 49.4s (load weights from disk: 38.0s, find config: 3.0s, load config: 1.6s, create model: 0.2s, apply weights to model: 1.6s, apply half(): 0.6s, load VAE: 3.6s, move model to device: 0.7s).
Running on public URL: https://xxd132321332131.gradio.live/
✔ Connected

Look like everything is correct, but 504 Gateway Time-out

**Comment by ariraz513** [comment]
having this problem too

**Comment by Glup30** [comment]
same here, something to do with the server or anything else?

**Comment by TheLastBen** [comment]
use localtunnel instead, gradio server is having issues at the moment

**Comment by Glup30** [comment]
> use localtunnel instead, gradio server is having issues at the moment

i will try that,thank you.

**Comment by Glup30** [comment]
> use localtunnel instead, gradio server is having issues at the moment

it works great, can you tell me the difference between local tunnel and the other one pleass?

**Comment by TheLastBen** [comment]
localtunnel is a proxy that doesn't need to use gradio server, it's an alternative in case the gradio server doesn't work

**Comment by Glup30** [comment]
> localtunnel is a proxy that doesn't need to use gradio server, it's an alternative in case the gradio server doesn't work

i see, thank you again.

**Comment by fariajurado** [comment]
I tried with **local tunnel**. Its working perfectly. Thanks a lot!
Your are the best 👌

**Comment by fariajurado** [comment]
I tried with local tunnel. Its working perfectly. Thanks a lot!
Your are the best 👌
