### ISSUE TITLE
new error- python3: can't open file '/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Brandyfan** [TheLastBen/fast-stable-diffusion#1533]
Everything loads as it's supposed to, but when I try to open stable diffusion-webui, I get the above error. Not sure what happened and if it's a problem on my end or if something's wrong with the server as it worked just fine yesterday. I've tried the local tunnel as well but keep getting the same error. Should I completely remove everything and start over or do you have another idea?
Thanks for the help!

**Comment by TheLastBen** [comment]
make sure your gdrive is correctly connected

**Comment by Brandyfan** [comment]
I think it is. How would I check that? Everytime I open the notebook, I run the first three cells assuming that's all I need to do.

**Comment by TheLastBen** [comment]
does the error persist even after disconnecting and reconnecting? make sure the folder "/content/gdrive/MyDrive/sd" exists

**Comment by Brandyfan** [comment]
Yes it does and the folder does exist.

**Comment by ViacheslavMM** [comment]
Hi everybody.
I see that the topic is closed, but has anyone encountered such a problem? You go through all the stages from "Connect Google Drive" to "Start Stable-Diffusion", after starting it takes about 2 minutes and the connection breaks. Do not re-launch.
