### ISSUE TITLE
AUTOMATIC1111 notebook: allow to point to dir of models

### ISSUE THREAD

**Issue by doegox** [TheLastBen/fast-stable-diffusion#154]
Hello,

rather than `Path_to_trained_model` pointing to a single model, we can allow it to point to the parent directory and let webui getting access to all of them with this single change:

```python
if os.path.isfile(model):
  !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --ckpt "$model"
else:
  !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --ckpt-dir "$model"
```

**Comment by TheLastBen** [comment]
was "--ckpt-dir" added recently, I didn't notice it

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/bdaa90466227b502b9b03e7334a99a6de6c64d35
thanks for the tip
