### ISSUE TITLE
Getting "AttributeError: module 'modules.hypernetworks.hypernetwork' has no attribute 'apply_strength'"

### ISSUE THREAD

**Issue by jonathangoorin** [TheLastBen/fast-stable-diffusion#1544]
I'm trying to use the infinity axis generator script from 
https://github.com/mcmonkeyprojects/sd-infinity-grid-generator-script

and getting the following error:
getting AttributeError: module 'modules.hypernetworks.hypernetwork' has no attribute 'apply_strength'

any ideas?

**Comment by TheLastBen** [comment]
check witht that repo for updates, it seems outdated
