### ISSUE TITLE
img2img generation API

### ISSUE THREAD

**Issue by krutikbackup** [TheLastBen/fast-stable-diffusion#1573]
Hello, I want to use img2img generation API in python inside my Python file

I checked the "[stable-diffusion-webui](https://github.com/TheLastBen/stable-diffusion-webui)" but got confused about the API to use

Can anyone help me with this?

Thanks in advance

**Comment by TheLastBen** [comment]
check the A1111 repo wiki https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by krutikbackup** [comment]
Thank you for response.
This uses the webui API, but can we use local API in which we can provide the model and yaml and generate  image 
or is it compulsory to use webui link to generate image?

Sorry I am confused right now
Can you please help?

**Comment by krutikbackup** [comment]
and also where to get the url like below?
url = "http://127.0.0.1:7860"

where this type of url can be generated and we can see and access the same?
please help

**Comment by TheLastBen** [comment]
For this type of issue you will find the best help in the A1111 repo [https://github.com/AUTOMATIC1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API)

**Comment by krutikbackup** [comment]
Okay
Thank you very much :)
