### ISSUE TITLE
Convert .ckpt -> diffuser conversion

### ISSUE THREAD

**Issue by kimtaehyeong** [TheLastBen/fast-stable-diffusion#1589]
Hello.
Thank you for your wonderful work.
I currently learned my data from ```https://github.com/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb``` for fine-tuning.
Also, I checked that it actually works well in Webui.

The next thing I want is to use the Stable Diffusion Pipeline Five-line to bring in the model and create it.
ex)
```
https://github.com/huggingface/diffusers

pipe = StableDiffusionPipeline.from_pretrained("./mymodel", torch_dtype=torch.float16)
```

So what I looked for is to convert the .ckpt file to diffuser format.
```https://github.com/TheLastBen/fast-stable-diffusion/blob/main/Dreambooth/convertodiffv1.py``` I could find the code here. However, the following error occurred during execution:

![image](https://user-images.githubusercontent.com/11425786/218673062-a5208f55-5a82-40c2-bb0d-4632da5dbdde.png)

The questions are as follows:
What should I do to convert my .ckpt file into diffuser format? I trained v1.5.

**Comment by TheLastBen** [comment]
right before the conversion command, run this : 

```
!wget -q -O refmdlz https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/refmdlz
!unzip -o -q refmdlz
!rm -f refmdlz
```

**Comment by kimtaehyeong** [comment]
Thank you This issue has been resolved.
