### ISSUE TITLE
Start DreamBooth Error - google colab

### ISSUE THREAD

**Issue by sholms** [TheLastBen/fast-stable-diffusion#16]
![Screenshot 2022-09-29 124809](https://user-images.githubusercontent.com/22715993/193091108-6cb73179-41b0-4a77-beda-012ec9f2a66b.png)
![Screenshot 2022-09-29 124913](https://user-images.githubusercontent.com/22715993/193091124-9941df99-c144-45b8-b101-afa8f0a37f75.png)

**Comment by TheLastBen** [comment]
in your Gdrive, remove the folder stable-diffusion-v1-4 (also from the trash to save space), and then put your huggingface token in the colab to redownload the model

**Comment by TheLastBen** [comment]
not yet, for now it's in diffusers only.
Update the colab, I reduced the time of training to 13 minutes

**Comment by yuipopo98** [comment]
Thanks a lot for the colab! I also have an error while trying to start DreamBooth. I Tried deleting the stable diffusion v1.4 folder and downloading it again, tried to clone it myself and nothing worked. I get this error message. Is there something I am missing? Thank you for your time.


![image](https://user-images.githubusercontent.com/114702901/193149791-fc90809e-b0e8-49f7-9881-c54ea5ab5ad7.png)

**Comment by TheLastBen** [comment]
hi,
did you accept the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4 ?
if so, remove the folder from gdrive, disconnect the runtime and rerun the colab manually step by step to make sure everything is in order

**Comment by yuipopo98** [comment]
Thank you for your quick answer! I'll try to fix it that way. Should I accept the terms and conditions before running the colab? Or does the colab take you to the website? If so, I may have missed it. And should I only delete the v1,4 folder? Thank you for your time.

**Comment by TheLastBen** [comment]
you should go to https://huggingface.co/CompVis/stable-diffusion-v1-4 and accept the terms (i'll add a link in the colab later), and in google drive, delete the v1.4 folder.

**Comment by yuipopo98** [comment]
I tried implementing the fix and it did work, but I now get another error. I even reran the colab step by step. Thank you for your time!

![image](https://user-images.githubusercontent.com/114702901/193154490-5736e78b-d8db-4bfe-8e7a-aba30ae7193b.png)

**Comment by TheLastBen** [comment]
go inside the folder stable-diffusion-v1-4 and make a screenshot

**Comment by TheLastBen** [comment]
I think your GDrive is full, make sure you empty the trash

**Comment by yuipopo98** [comment]
![image](https://user-images.githubusercontent.com/114702901/193155893-f626f6ca-05cf-44fe-8613-2e01e4edc476.png)

**Comment by yuipopo98** [comment]
That might be the case. How much disk space is needed?

**Comment by TheLastBen** [comment]
seems fine, at least 5Gb a start, then another 5Gb for the trained model, so 12GB should be free before downloading the model

**Comment by TheLastBen** [comment]
it's best to work with an empty GDrive, if you have personal files in your current account, it's best to create an account for stable diffusion

**Comment by yuipopo98** [comment]
It was a clear drive. I'll try again. Thank you very much for your time and patience. I can't wait to try your code!

**Comment by yuipopo98** [comment]
The training started, but I got another error. I'll try again tomorrow, doing everything from scratch. I appreciate your help. It's really nice of you to try to help me run your program. Thanks a lot!
![image](https://user-images.githubusercontent.com/114702901/193157180-436ed335-2d59-4ff0-9b23-c06088c543f7.png)

**Comment by TheLastBen** [comment]
You probably missed a cell in xformers installation

**Comment by liangwei191** [comment]
same error,i cant run it either ,not creating any file in the gdisk.And keeping stuck after the uploading cell.
I already delete all file in my gdisk.But I dont know why the space show in notebook and google driver site isnt the same.(notebook colab always start by half occupied even there is completely no file)

**Comment by TheLastBen** [comment]
create a new cell and run `!nvidia-smi` and see what gpu you have

**Comment by liangwei191** [comment]
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+



The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 606, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 393, in main
    args.pretrained_model_name_or_path, subfolder="tokenizer", use_auth_token=args.use_auth_token
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1748, in from_pretrained
    _commit_hash=commit_hash,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 419, in cached_file
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1022, in hf_hub_download
    cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 137, in validate_repo_id
    "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/content/gdrive/MyDrive/stable-diffusion-v1-4'. Use `repo_type` argument if needed.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/gdrive/MyDrive/stable-diffusion-v1-4', '--instance_data_dir=/content/data/pudog', '--output_dir=/content/models/



no idea what happened.I don't know why no file created in my gdisk. I run the colab on this site directly

**Comment by TheLastBen** [comment]
you have a T4, good, make you accept the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4
then go to your GDrive and delete the folder stable-diffusion-v1-4 and disconnect the runtime and restart the whole colab

**Comment by liangwei191** [comment]
seems start to run,it looks because of I didnt click some agreement on huggingface.
Thank you very much

**Comment by TheLastBen** [comment]
pleasure to help
