### ISSUE TITLE
Sharing a model or folder with models to other people

### ISSUE THREAD

**Issue by younyokel** [TheLastBen/fast-stable-diffusion#161]
![image](https://user-images.githubusercontent.com/53343081/196052226-17348b4b-7f5c-4c2f-b291-cfb36394bc80.png)

Hello, I'm trying to share the models of mine to other people via public Google Drive link but I get this error. I tried sharing both folders which has these models and the models itself in seperate links.

![image](https://user-images.githubusercontent.com/53343081/196052293-260af8be-816e-4a77-a5aa-f244c10a13a0.png)

I get the "Wrong link, check that the link is valid" error. Am I doing something wrong?

**Comment by TheLastBen** [comment]
did you share the file with "everyone with a link" in the sharing dialogue in gdrive ?

**Comment by younyokel** [comment]
> did you share the file with "everyone with a link" in the sharing dialogue in gdrive ?

Yes. Also gave editing access just in case but there's still an error.

![image](https://user-images.githubusercontent.com/53343081/196052586-9e08010c-b5ca-42f2-9437-619cfc046957.png)

**Comment by TheLastBen** [comment]
try the link in a regular browser (incognito) and see if you can download it

**Comment by younyokel** [comment]
> try the link in a regular browser (incognito) and see if you can download it and make sure the link directs to a ckpt file not a folder

Looks like the link must necessarily have "/view" at the end, otherwise it doesn't work. So the link should look like https://drive.google.com/file/d/blahblahblah/view

Folder sharing doesn't work. Too bad, because I also left VAE weights in the file specifically for this model.

**Comment by TheLastBen** [comment]
you can create a cell and use this code : 

```
%cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion
!gdown --fuzzy --folder linktoyourfolder
```

once the folder is downloaded, manually move the files wherever needed
