### ISSUE TITLE
cpu only?

### ISSUE THREAD

**Issue by bonecountysheriff** [TheLastBen/fast-stable-diffusion#1625]
Is there a way to run this cpu only? Thank you!

**Comment by TheLastBen** [comment]
I think A1111 has an argument to use CPU only, check with their repo

**Comment by bonecountysheriff** [comment]
So run `python launch.py --skip-torch-cuda-test --use-cpu all --precision full --no-half` to completely eliminate gpu dependence from what I have read. Add `--share` for a public url (unless you're running it on huggingface).
