### ISSUE TITLE
Feature request:Model download/load refactor.

### ISSUE THREAD

**Issue by nikitastaf1996** [TheLastBen/fast-stable-diffusion#1629]
I save my version of colab notebook to my drive to save defaults.
So I propose to divide it into three different parts.
1)Download default models.1.5,2.0.2.1, inpainting.
2)Load models from certain folder.When you already have downloaded models and don't want to download anything.Just want to run.
3)Download model.Also this part can be enhanced by an ability to select into which folder to download the file.Lora,hypernetwork,model,e.t.c.Default ones.And maybe select file name.Civitai often gives Lora without extension.In my experience.
Current behavior doesn't allow to download model when path to model is defined.

**Comment by TheLastBen** [comment]
if you specify a local path, the cell will use that option as a priority one, so you have to keep unneeded input boxes empty.
As for the Loras, I'll see what I can do.
