### ISSUE TITLE
install.py from an installed extension doesn't run properly on colab?

### ISSUE THREAD

**Issue by hithereai** [TheLastBen/fast-stable-diffusion#1631]
Hi Ben,

I'm trying the following code snippet in install.py of the official [deforum](https://github.com/deforum-art/deforum-for-automatic1111-webui) extension (file is located at the root folder of the extension, as it's supposed to be):

```
import os, sys, launch
req_file = os.path.join(os.path.dirname(os.path.realpath(__file__)), "requirements.txt")
with open(req_file) as file:
    for lib in file:
        lib = lib.strip()
        print(lib)
```

And I get **no** printing in the CLI whatsoever upon launching the webui. I tested this snippet because we have a bug in deforum where pip pack named 'rich', which was added about 1-2 weeks ago, is never being auto-installed for users of your auto1111 colab. 

I added quite a few of pip packs to our requirements.txt and it always worked, but my testing-code snippet suggest that something broke recently, as I should have seen the printing of the packs in the cli, at the least. :)

If I miss something, please kindly let me know, and thanks for the awesome work!

**Comment by kabachuha** [comment]
Yeah, it's a serious issue as some extensions appear to be broken now

**Comment by TheLastBen** [comment]
I regularly add the dependencies required by extensions, especially decorum, I'll add the missing deps very soon.

**Comment by hithereai** [comment]
Working for me now, I guess you fixed it and forgot to update this issue. I will re-open if it arises again.

Thanks!
