### ISSUE TITLE
'Upload Mask' Missing in the Img2img tab

### ISSUE THREAD

**Issue by Bez22** [TheLastBen/fast-stable-diffusion#1636]
Hello, I noticed that the upload mask option is gone in the img2img tab but there is an option to upload mask in the inpaint tab. Does this represent the same function if not is there any way I can roll back the interface one where this option is available?

**Comment by TheLastBen** [comment]
Hi, You will find the answer in the A1111 repo

**Comment by Bez22** [comment]
Thanks but I think I'll just use what's already there, it works more or less the same.
