### ISSUE TITLE
conversion error .... can't train with any custom models..please help me out ...

### ISSUE THREAD

**Issue by cxyzdroid90** [TheLastBen/fast-stable-diffusion#1657]
can't convert models like... protogen,deliberate,dreamshaper etc...

**Comment by TheLastBen** [comment]
Send me the links to the models

**Comment by cxyzdroid90** [comment]
https://huggingface.co/darkstorm2150/Protogen_x3.4_Official_Release/resolve/main/ProtoGen_X3.4-pruned-fp16.ckpt,
https://civitai.com/api/download/models/11925
https://civitai.com/api/download/models/5636
THESE DOWNLOADS FINE BUT
THEN
conversion error 
conversion error
....

**Comment by TheLastBen** [comment]
for Protogen, use this link in "path_to_huggingface" instead : `darkstorm2150/Protogen_x3.4_Official_Release`

for the civitai models, try finding them in huggingface

**Comment by cxyzdroid90** [comment]
thank you very much for the help,it worked without any errors
thanks for the BLAZING FAST REPLIES  👍
