### ISSUE TITLE
Offset Noise Support

### ISSUE THREAD

**Issue by adunato** [TheLastBen/fast-stable-diffusion#1665]
I just saw a commit which adds offset noise option in fast dream booth, is this the implementation of the Nicholas Guttenberg's approach that has become si popular lately? Great if so.

Dumb and lazy bonus question, I can see the offset noise option in the interface, but where is the actual implementation of offset noise training? I thought it required a change of the Stable Diffusion noise function.

**Comment by TheLastBen** [comment]
Yes it is the Nicholas Guttenberg's approach, this is the line : https://github.com/TheLastBen/diffusers/blob/updt/examples/dreambooth/train_dreambooth.py#L670

**Comment by adunato** [comment]
That's really great. I have a style based on Midjourney images that is of good quality but lacks contrast and depth compared to the originals, I look forward to testing this out.

Thanks for your committment to this project @TheLastBen, it's a great tool for the community.
