### ISSUE TITLE
Inpaint function creates mask in the wrong place

### ISSUE THREAD

**Issue by trolly056** [TheLastBen/fast-stable-diffusion#167]
**Problem**
Images with different width/height when loaded in inpaint create the mask in the wrong spot.
Example >> https://i.imgur.com/HvTsJqx.png
**Reproduce**
This only happens on "inpaint", seems to be a mask issue, Sending/Uploading/Dropping, all create the same issue
**Relevant info?**
I'm using Chrome/Win10
This was fixed on automatic's
Same issue >> https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/2750
Fixed here >> https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a1d3cbf92cfde6b3e02a9c795412d01cdc268934

My update repo box is checked. maybe this is related? https://github.com/TheLastBen/fast-stable-diffusion/issues/153

**Comment by trolly056** [comment]
If anyone is having any problems, my solution was deleting the SD folder and running the notebook again, i encountered some issues with some "local modified files" blocking the cell from running, i fixed this by going on **File > Revision history >** clicking on the **three dots of the topmost/recent version** of the notebook and clicking **Open in Colab**, that gave me a clean notebook.

I'm gonna consider this issue closed because it doesn't seem the author intends to change how the repo update behaves, when you encounter any issues i suggest you do what i said above. Especially since downloading the repo does not download any models, so you can keep your models separate in a different folder. I actually saved a lot of space by deleting the SD folder and resetting, don't know why but i'm happy i gained 2~3 extra gb space.

**Go to colab > File > Revision history > Open in colab the most recent version for a clean notebook**

**Comment by TheLastBen** [comment]
There is an a checkbox "update_repo" in the second cell, it will update all the files without removing anything.

as for the "Open in colab the most recent version for a clean notebook" that means you have modified the colab code, and the best way to fix it is to use the latest colab from this repo instead of using an old one
