### ISSUE TITLE
Runpod error when trying to save

### ISSUE THREAD

**Issue by cfragkos** [TheLastBen/fast-stable-diffusion#1672]
I get this error when trying to save the trained model. And also a similar error after it finished the text encoder training
Using lykon/dreamshaper

`Progress::  50%|████▉     | 599/1200 [02:12<02:11,  4.56it/s, loss=0.45, lr=1e-6]Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 616, in _get_config_dict
    resolved_config_file = cached_path(
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py", line 299, in cached_path
    raise EnvironmentError(f"file {url_or_filename} not found")
OSError: file /workspace/stable-diffusion-custom/config.json not found`

**Comment by TheLastBen** [comment]
does it work with the default model ?

**Comment by cfragkos** [comment]
I dont know, but it did work on some others. And it works on dreamshaper on colab

**Comment by TheLastBen** [comment]
Ok fixed

**Comment by cfragkos** [comment]
How will i get the updated version of the notebooks though? The runpod docker is not updated when you make a change

**Comment by TheLastBen** [comment]
you only have to run the first cell and it will pull the latest code, no need to update the notebook
