### ISSUE TITLE
Runpod instance images get renamed

### ISSUE THREAD

**Issue by cfragkos** [TheLastBen/fast-stable-diffusion#1674]
When uploading instance images in the runpod notebook they get renamed from x x (n) to x-x-(n) which messes up the tokens

**Comment by TheLastBen** [comment]
That's how the notebook operates since the beginning, if you want spaces in the tokens, use _ to separate the words, but I recommend using only one word as the instance name

**Comment by cfragkos** [comment]
Why not make it more intuitive though

**Comment by cfragkos** [comment]
So if an image gets renamed to x-(n) it will not have a problem?

**Comment by TheLastBen** [comment]
at the training it will remove the -(n) all what will be left is x
