### ISSUE TITLE
How to disable xformers?

### ISSUE THREAD

**Issue by A-Dream-Of-Illusionary-Senses** [TheLastBen/fast-stable-diffusion#1688]
Greetings. I have no need for xformers because I hate how it butchers image output. How do I disable it? Is there a .bat file somewhere in the folder I can edit?

**Comment by TheLastBen** [comment]
run `!pip uninstall xformers -y`
xformers doesn't affect quality as far as I know

**Comment by A-Dream-Of-Illusionary-Senses** [comment]
Thanks a lot!
