### ISSUE TITLE
No module named 'ldm.models.diffusion.sampling_util'

### ISSUE THREAD

**Issue by thekevinscott** [TheLastBen/fast-stable-diffusion#1690]
Running the colab notebook `fast-DreamBooth.ipynb`. Training seems to complete fine, but running the UI produces:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 14, in <module>
    from ldm.models.diffusion.sampling_util import norm_thresholding
ModuleNotFoundError: No module named 'ldm.models.diffusion.sampling_util'
```

**Comment by TheLastBen** [comment]
try test running the notebook without the first cell

**Comment by danielgwilson** [comment]
Had the same issue

Fix:
1. Rename `/content/gdrive/MyDrive/sd/stable-diffusion-webui` to `/content/gdrive/MyDrive/sd/stable-diffusion-webui-old`.
2. Reinstall dependencies.
3. New `...webui` folder will be fixed and working.

**Comment by loboere** [comment]
This is annoying, I have to reinstall all the extensions

**Comment by cerarslan** [comment]
> This is annoying, I have to reinstall all the extensions

Yes. How we deal with it @TheLastBen?  I guess all extension not work properly when we have to reinstall again?

**Comment by TheLastBen** [comment]
Rename the current SD folder, then copy the extension back to the new SD folder

**Comment by thekevinscott** [comment]
[Following the comment](https://github.com/TheLastBen/fast-stable-diffusion/issues/1690#issuecomment-1454965474) by @danielgwilson fixed my issue. Thanks all!
