### ISSUE TITLE
Is there any solution for local pc only?

### ISSUE THREAD

**Issue by yoshihirosakamoto** [TheLastBen/fast-stable-diffusion#1696]
I see a lot of people try to run fast-stable-diffusion at google colab... so I think google may add some limit soon...

so I want to try it at my windows 10 pc.
is there any solution let tme download this version and run in my windows 10?
(I know this is a modify version of automatic1111 + dreambooth) , but origianl dreambooth is not easy to use, but this version of fast dreambooth is very good and easy to use. Will they release extensions for automatic1111 ?
I try it to run via jupyter, but lot of error and I can't run it successfully)

Thank you so much.

**Comment by TheLastBen** [comment]
No plans for local at the moment, but I'll do my best in the future
