### ISSUE TITLE
stable diffusion model failed to load,exiting

### ISSUE THREAD

**Issue by Yanagine** [TheLastBen/fast-stable-diffusion#1698]
I've been attempting to find solution for a day now. I'm not a person who writes code or understands it very well. I was just hoping to use Stable-Diffusion. I installed and reinstalled git and python a few times and end up here. 

One Note: The webui-user batch file does not have .bat at the end. Does that make a difference?

D:\Stable-Diffusion\stable-diffusion-webui>git pull
Already up to date.
Creating venv in directory D:\Stable-Diffusion\stable-diffusion-webui\venv using python "C:\Users\jchen\AppData\Local\Programs\Python\Python310\python.exe"
venv "D:\Stable-Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Collecting torch==1.13.1+cu117
  Using cached https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-win_amd64.whl (2255.4 MB)
Collecting torchvision==0.14.1+cu117
  Using cached https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bcu117-cp310-cp310-win_amd64.whl (4.8 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
     ---------------------------------------- 97.1/97.1 kB 1.4 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Installing collected packages: urllib3, typing-extensions, pillow, numpy, idna, charset-normalizer, certifi, torch, requests, torchvision
Successfully installed certifi-2022.12.7 charset-normalizer-3.1.0 idna-3.4 numpy-1.24.2 pillow-9.4.0 requests-2.28.2 torch-1.13.1+cu117 torchvision-0.14.1+cu117 typing-extensions-4.5.0 urllib3-1.26.14

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: D:\Stable-Diffusion\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into repositories\stable-diffusion-stability-ai...
Cloning Taming Transformers into repositories\taming-transformers...
Cloning K-diffusion into repositories\k-diffusion...
Cloning CodeFormer into repositories\CodeFormer...
Cloning BLIP into repositories\BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Calculating sha256 for D:\Stable-Diffusion\stable-diffusion-webui\models\Stable-diffusion\Model.ckpt: cc6cb27103417325ff94f52b7a5d2dde45a7515b25c255d8e396c90014281516
Loading weights [cc6cb27103] from D:\Stable-Diffusion\stable-diffusion-webui\models\Stable-diffusion\Model.ckpt
Creating model from config: D:\Stable-Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
loading stable diffusion model: OutOfMemoryError
Traceback (most recent call last):
  File "D:\Stable-Diffusion\stable-diffusion-webui\webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "D:\Stable-Diffusion\stable-diffusion-webui\modules\sd_models.py", line 417, in load_model
    sd_model.to(shared.device)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 113, in to
    return super().to(*args, **kwargs)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 2.00 GiB total capacity; 1.71 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Stable diffusion model failed to load, exiting

**Comment by TheLastBen** [comment]
You're out of RAM, you're not using the notebooks, this repo is only for the notebooks

**Comment by Yanagine** [comment]
> 
You're out of RAM, you're not using the notebooks, this repo is only for the notebooks

Thank you for the response :)
As a person who doesn't do this type of thing on his computer, I followed a guide to install stable diffusion from youtube.
Could you explain a bit more about what you mean by using the note books for this repo? Thanks again.

**Comment by TheLastBen** [comment]
you can run A1111 online using a notebook : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by Yanagine** [comment]
It works! thanks so much man. Really appreciate the help. :)
