### ISSUE TITLE
not downloading Huggingface

### ISSUE THREAD

**Issue by moral3jo** [TheLastBen/fast-stable-diffusion#17]
the code hidde the problem
not accept the terms and dont detect until delete %%capture from code in "Downloading the model"
the log explain really good but hidden, maybe show it if fails

**Comment by TheLastBen** [comment]
did you input your huggingface token after accepting the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4 ?

**Comment by moral3jo** [comment]
yes i repair accepting the terms, in the console shows the url to open and accept.
just telling if you can change it for future fools like me or a note in the text

**Comment by TheLastBen** [comment]
I will add a note for the future, thank you.
