### ISSUE TITLE
Default Libraries problem

### ISSUE THREAD

**Issue by DobrySkazochnik** [TheLastBen/fast-stable-diffusion#1716]
tarting last night, whenever I try to run your Colab version of Automatic1111, I get the following error:

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'`

If use `!pip install -U fastapi`
get `ModuleNotFoundError: No module named 'gradio'`

if u setup every model - it take more and more errors

my clumsy and temp solution is:
create two code blocks after "Requirements"
1st:
`%%writefile requirements.txt blendmodes accelerate basicsr fonts font-roboto gfpgan gradio==3.16.2 invisible-watermark numpy omegaconf opencv-contrib-python requests piexif Pillow pytorch_lightning==1.7.7 realesrgan scikit-image>=0.19 timm==0.4.12 transformers==4.25.1 torch einops jsonmerge clean-fid resize-right torchdiffeq kornia lark inflection GitPython torchsde safetensors psutil albumentations==0.4.3 opencv-python pudb==2019.2 imageio==2.9.0 omegaconf==2.1.1 test-tube>=0.7.5 webdataset==0.2.5 open-clip-torch==2.7.0 kornia==0.6 invisible-watermark>=0.1.5 streamlit-drawable-canvas==0.8.0 xformers fastapi`
2nd:
`!pip install -r requirements.txt !pip install git+https://github.com/openai/CLIP.git !pip install --upgrade fastapi==0.90.1`

![2023-03-09_06-10-51](https://user-images.githubusercontent.com/32751843/224006134-e5b5d451-15a6-4321-a6e2-c69719407390.png)

but, if i use open pose - i get new error
![2023-03-09_13-59-01](https://user-images.githubusercontent.com/32751843/224006077-59041b28-4960-4330-b79f-28d771fe494b.png)

**Comment by DobrySkazochnik** [comment]
Oh, ok, problem with openpose was in SD 2.1 model.
But default libraries problem still exist

**Comment by ayoubachak** [comment]
I have the same issue with the imports, your clumsy solution did the job, thanks!

**Comment by doyouhike** [comment]
> Oh, ok, problem with openpose was in SD 2.1 model. But default libraries problem still exist

thanks a lot for saving me

**Comment by generatorman** [comment]
Can confirm this is broken. [DobrySkazochnik]'s solution fixes but I had to change the space-separated list of packages into a newline-separated list.

**Comment by shirooo39** [comment]
```python
wheels = [
    'blendmodes', 'accelerate', 'basicsr', 'fonts', 'font-roboto',
    'gfpgan', 'gradio==3.16.2', 'invisible-watermark', 'numpy', 'omegaconf',
    'opencv-contrib-python', 'requests', 'piexif', 'Pillow', 'pytorch_lightning==1.7.7',
    'realesrgan', 'scikit-image>=0.19', 'timm==0.4.12', 'transformers==4.25.1', 'torch',
    'einops', 'jsonmerge', 'clean-fid', 'resize-right', 'torchdiffeq',
    'kornia', 'lark', 'inflection', 'GitPython', 'torchsde',
    'safetensors', 'psutil', 'albumentations==0.4.3', 'opencv-python', 'pudb==2019.2',
    'imageio==2.9.0', 'omegaconf==2.1.1', 'test-tube>=0.7.5', 'webdataset==0.2.5', 'open-clip-torch==2.7.0',
    'kornia==0.6', 'invisible-watermark>=0.1.5', 'streamlit-drawable-canvas==0.8.0', 'xformers', 'fastapi'
]

with open('requirements.txt', 'w') as f:
    for item in wheels:
        f.write(f'{item}\n')
```

**Comment by generatorman** [comment]
This solution does break localTunnel functionality - the output no longer generates the URL (only the inaccessible IP address). Possibly due to a different version of streamlit, but in my tests downgrading streamlit to 1.13.0 did not fix.

**Comment by generatorman** [comment]
> This solution does break localTunnel functionality - the output no longer generates the URL (only the inaccessible IP address). Possibly due to a different version of streamlit, but in my tests downgrading streamlit to 1.13.0 did not fix.

Was able to hack around this by commenting out the line !rm /content/srv.txt /content/srvr.txt and then opening up srvr.txt from the colab file explorer to read the URL.

**Comment by TheLastBen** [comment]
fixed
