### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Icaab** [TheLastBen/fast-stable-diffusion#1755]
Hello
Recently AUTOMATIC1111 was fully operational. Today began to appear such a bug when you enable "Start Stable-Diffusion" (always use "Use_localtunnel"). 
![Screenshot_1513](https://user-images.githubusercontent.com/79973635/224545891-61150d3f-134b-47e7-9933-c9d25812ab46.png)
Waiting for repairs?

**Comment by TheLastBen** [comment]
use the latest notebooks, you can get them using the thumbnails in the main page of this repo

**Comment by Icaab** [comment]
> use the latest notebooks, you can get them using the thumbnails in the main page of this repo

Yes, the question has been resolved
Thank you

**Comment by TheLastBen** [comment]
great!
