### ISSUE TITLE
Last cell not loading?

### ISSUE THREAD

**Issue by Finderz1** [TheLastBen/fast-stable-diffusion#1772]
i tried everything, I used the latest version,  reinstalled again, checked if i had vram, what am i doing wrong?
![not](https://user-images.githubusercontent.com/90747417/225162100-e634e4aa-c986-485f-8506-8e82bb32a872.PNG)

**Comment by Finderz1** [comment]
apologies, i should've checked first
https://github.com/TheLastBen/fast-stable-diffusion/issues/889\

i also got it load with no errors but now its not even showing the gradio link or anything, its been loading for almost 30 minutes 
![g](https://user-images.githubusercontent.com/90747417/225173070-9aa58bdc-1a7e-443d-8da3-38356c762fe1.PNG)

**Comment by TheLastBen** [comment]
try removing the extensions and try again

**Comment by Finderz1** [comment]
it's still not showing anything :/

**Comment by Finderz1** [comment]
ran for 20 minutes and still nothing
![20](https://user-images.githubusercontent.com/90747417/225180476-16185317-abfe-45dd-a948-ede584dcb40a.PNG)

**Comment by TheLastBen** [comment]
run the notebook without the first cell and see if it works

**Comment by Finderz1** [comment]
well now i can open the web ui, but it wont load any of the models,  or any other file ifrom my googdrive folders :/

**Comment by Finderz1** [comment]
yeah, just double checked, its not loading my files because it didn't run the first cell
![gdrive](https://user-images.githubusercontent.com/90747417/225202561-8fd0d8f1-9287-4613-8568-de85eb36392a.PNG)

**Comment by Finderz1** [comment]
>let the collab rebuild it and move the files i want from the old model folders into the new install

 this is not working for me because it is not connected to gdrive, and the folders are not appearing in gdrive

**Comment by Finderz1** [comment]
Alright i just tested it, pcrii, your method worked when i ran it with the first cell, it works now with the drive mounted(i still had to move my files into the reinstalled folders, but that's fine)
thanks @pcrii @TheLastBen 
have a great day/night!
