### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by Super-zapper** [TheLastBen/fast-stable-diffusion#1789]
After couple of steps get Cuda out of memory for both unet and text encoder training. Tried with 2.1 and 1.5 non-custom models, with 768 and 512 resolution, with and without offset noise, with 900 and 50 pics, doesn't matter

![image](https://user-images.githubusercontent.com/112967133/226156161-9bf8a323-d8fc-41cb-a6cc-e42e1cd9205c.png)

**Comment by TheLastBen** [comment]
Are you using the latest notebook ?

**Comment by Super-zapper** [comment]
not sure
can I ask where to find the link?

**Comment by Super-zapper** [comment]
I think i use the last. Just go to this link, but there is no difference
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

I tried to use less size of image and looks that it helps. So pictures with 1024x1024 resolution doesn't work. But just a week ago I trained model on 1024 resolution and image size up to 5600x5600 and there never was problems

**Comment by Super-zapper** [comment]
I tried to resume training model that I finished training 16th of march with same instance images and same training settings but now getting out of memory

**Comment by InternalMegaT** [comment]
Same issue, what is the latest notebook that doesn't have this issue?

**Comment by InternalMegaT** [comment]
> what training resolution ?

Any does the same thing. I switched to early versions and worked on the same settings.

**Comment by TheLastBen** [comment]
what early versions ? early versions won't work with the recent colab update, use this notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by InternalMegaT** [comment]
> what early versions ? early versions won't work with the recent colab update, use this notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

Whenever I use the latest colab it's broken. That's why I have to load an earlier version to work.

**Comment by TheLastBen** [comment]
It works fine, I'm training at this very moment

**Comment by Super-zapper** [comment]
I confirm still not working. Try image for training with 1024 resolution or more and use 2.1-768 as base. You must get out of memory. Before I used images with size up to even 5600x5600 with 1024 res for training and there never was troubles

**Comment by TheLastBen** [comment]
512 with the default model ?

**Comment by TheLastBen** [comment]
T4 can't handle 1024, I'll see what I can do

**Comment by InternalMegaT** [comment]
> T4 can't handle 1024, I'll see what I can do

I've been trying with this type of resolution for months with no issues, has the gpus downgraded?

**Comment by TheLastBen** [comment]
add the flag `--gradient_checkpointing` to both unet and textenc

**Comment by Super-zapper** [comment]
Can I ask where exactly insert this?

**Comment by TheLastBen** [comment]
in the start training cell, you'll find many flags that start with --, add it there

**Comment by InternalMegaT** [comment]
This fix doesn't work for me. It works for around 5 seconds longer then it did.

**Comment by InternalMegaT** [comment]
Is a 10 thousand image database the issue?

**Comment by InternalMegaT** [comment]
Progress:|█                        |  4% 13/300 [01:21<28:53,  6.04s/it, loss=0.18, lr=9.57e-7] dramine  Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 803, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 668, in main
    latents = vae.encode(batch["pixel_values"].to(dtype=weight_dtype)).latent_dist.sample()
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/autoencoder_kl.py", line 158, in encode
    h = self.encoder(x)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/vae.py", line 105, in forward
    sample = down_block(sample)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/unet_2d_blocks.py", line 984, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/diffusers/models/resnet.py", line 542, in forward
    hidden_states = self.nonlinearity(hidden_states)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/modules/activation.py", line 395, in forward
    return F.silu(input, inplace=self.inplace)
  File "/usr/local/lib/python3.9/dist-packages/torch/nn/functional.py", line 2059, in silu
    return torch._C._nn.silu(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.13 GiB (GPU 0; 14.75 GiB total capacity; 11.36 GiB already allocated; 1.30 GiB free; 12.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Progress:|█                        |  4% 13/300 [01:22<30:24,  6.36s/it, loss=0.18, lr=9.57e-7]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_text_encoder', '--dump_only_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-768', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/anime-diffusion/instance_images', '--output_dir=/content/models/anime-diffusion', '--instance_prompt=', '--seed=486120', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=1e-06', '--lr_scheduler=linear', '--lr_warmup_steps=0', '--max_train_steps=300', '--gradient_checkpointing']' returned non-zero exit status 1.

**Comment by TheLastBen** [comment]
I don't understand, you're using the v2-768 but you're training on a resolution of 512

**Comment by InternalMegaT** [comment]
> I don't understand, you're using the v2-768 but you're training on a resolution of 512

Thats odd I selected 1024

**Comment by TheLastBen** [comment]
the T4 can't handle 1024

**Comment by InternalMegaT** [comment]
> the T4 can't handle 1024

wasn't the --gradient_checkpointing thing above supposed to fix that?

**Comment by TheLastBen** [comment]
there is a limit to what it can fix, but you should update your colab

**Comment by TheLastBen** [comment]
I just tried training on 1024 images, it works fine

**Comment by InternalMegaT** [comment]
> I just tried training on 1024 images, it works fine

It may just be my database size. And I also realized you updated the notebook quite a few times. From when I last changed it.
