### ISSUE TITLE
Safetensor

### ISSUE THREAD

**Issue by JustAnOkapi** [TheLastBen/fast-stable-diffusion#1790]
![image](https://user-images.githubusercontent.com/39418801/226164543-28a16846-8b37-402a-9528-ae85adb45cb2.png)

**Comment by JustAnOkapi** [comment]
![image](https://user-images.githubusercontent.com/39418801/226164552-c5a2e28d-a2a1-4c45-8764-de0c7e11974a.png)

**Comment by JustAnOkapi** [comment]
from `        while os.path.getsize('/content/model.ckpt') < 1810671599:`
to `        while os.path.getsize('/content/'+modelnm) < 1810671599:`

**Comment by JustAnOkapi** [comment]
![image](https://user-images.githubusercontent.com/39418801/226164596-9d86acab-6143-43b8-a80c-f5dfef55619f.png)
fixed

**Comment by TheLastBen** [comment]
thanks, I'll fix it

**Comment by JustAnOkapi** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/9630acdd154501f14f061beed7072ddb45d16527
