### ISSUE TITLE
I have a question about this version of stable-diffusion and vae

### ISSUE THREAD

**Issue by garyakimoto** [TheLastBen/fast-stable-diffusion#1804]
First of all, I want to thanks the author of this version of dreambooth, he let us easy to train our model

I would like to ask: I tried to use the CKPT model made in this version of dreambooth via [colar](https://colab.research.google.com/)  , but I found some of model have a problem: the eyes, noise...  of the model were obviously weird. I don’t know if I should add vae to correct it? A version would recommend?

thanks

**Comment by TheLastBen** [comment]
The latest vae is already included in the base model, what you have to do is make sure your input images are high quality in the format png

**Comment by garyakimoto** [comment]
> The latest vae is already included in the base model, what you have to do is make sure your input images are high quality in the format png

Thanks for resolving my concerns for me
