### ISSUE TITLE
The model degrades when resuming a training session.

### ISSUE THREAD

**Issue by iqddd** [TheLastBen/fast-stable-diffusion#1816]
The model degrades when resuming a training session. Most likely, the conversion from .ckpt to a training-suitable format is done incorrectly and the model breaks. (Based on SD2.1-512px)
![00001-123](https://user-images.githubusercontent.com/37406615/227170842-7378a296-4661-47bf-bc59-a825847a5464.png)
This image is generated after 1000 text_encoder training steps and 9500 UNet training steps.

![00014-123](https://user-images.githubusercontent.com/37406615/227171186-0f7c90b6-4e7f-4569-94f1-f510aae2640b.png)
And this is after resuming training with another 500 steps of UNet training. (Same prompt, same seed, etc.)

**Comment by TheLastBen** [comment]
will fix shortly

**Comment by iqddd** [comment]
Let us know when you fix it.
