### ISSUE TITLE
cant start SD on colab

### ISSUE THREAD

**Issue by piler87** [TheLastBen/fast-stable-diffusion#183]
hi i have already tried to delete sd folder and empty trash but i keep getting this error

![image](https://user-images.githubusercontent.com/55285153/196749815-da055f16-483e-4d22-9f0f-a0e77c184aaf.png)

**Comment by TheLastBen** [comment]
it's a syntax error by AUTOMATIC1111, they fixed it 10 minutes ago, check the box "update_repo" in the second cell and rerun it

**Comment by piler87** [comment]
thank you @TheLastBen
