### ISSUE TITLE
NameError: name '_C' is not defined in ControlNET section

### ISSUE THREAD

**Issue by TommyHolmberg** [TheLastBen/fast-stable-diffusion#1837]
In the lates notebook when I press run all, I get an error in the first line of the  ControlNET section:

from torch.hub import download_url_to_file

[<ipython-input-14-57cb507c7a6f>](https://localhost:8080/#) in <module>
      1 #@markdown # ControlNet
----> 2 from torch.hub import download_url_to_file
      3 from urllib.parse import urlparse
      4 import re
      5 

[/usr/local/lib/python3.9/dist-packages/torch/__init__.py](https://localhost:8080/#) in <module>
    247     raise  # If __file__ is not None the cause is unknown, so just re-raise.
    248 
--> 249 for name in dir(_C):
    250     if name[0] != '_' and not name.endswith('Base'):
    251         __all__.append(name)

NameError: name '_C' is not defined

**Comment by TheLastBen** [comment]
couldn't reproduce the error

**Comment by TommyHolmberg** [comment]
I'm not sure what happened but after restarting the notebook the error was gone.
