### ISSUE TITLE
 How to skip the gpu start in colab, I just want to test a extension

### ISSUE THREAD

**Issue by wth153** [TheLastBen/fast-stable-diffusion#1842]
How to skip the gpu start in colab, I just want to test a extension

**Comment by TheLastBen** [comment]
use the argument `--ui-debug-mode`

**Comment by wth153** [comment]
> use the argument `--ui-debug-mode`

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--ui-debug-mode

call webui.bat
like this ?

**Comment by wth153** [comment]
@TheLastBen 


in webui-user.bat
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--ui-debug-mode

call webui.bat
like this ?

**Comment by wth153** [comment]
> use the argument `--ui-debug-mode`

in webui-user.bat
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--ui-debug-mode

call webui.bat
like this ?

**Comment by TheLastBen** [comment]
in the last cell of the colab

**Comment by wth153** [comment]
> in the last cell of the colab

Its working,thanks
