### ISSUE TITLE
How to use stable diffusion gui

### ISSUE THREAD

**Issue by Maxhem2** [TheLastBen/fast-stable-diffusion#1843]
I dont want to use Dreambooth where is the option to start the normal ui to select my just downloaded module form civitai? In the Step-by-step guide the notebook linked is Dreambooth only

**Comment by TheLastBen** [comment]
in the main page of the repo, you can click on the A1111 thumbnail, here's the notebooks link

**Comment by Maxhem2** [comment]
Thanks a lot
