### ISSUE TITLE
Error when starting the gui

### ISSUE THREAD

**Issue by Maxhem2** [TheLastBen/fast-stable-diffusion#1845]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 18, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['/content/gdrive/MyDrive/sd/stablediffusion', '.', '/content/gdrive/MyDrive/sd']

**Comment by TheLastBen** [comment]
try renaming/removing the sd folder

**Comment by Maxhem2** [comment]
I did then I get:
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
python3: can't open file '/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py': [Errno 2] No such file or directory

**Comment by Maxhem2** [comment]
Was a google drive space issue
