### ISSUE TITLE
"Error loading script: lora_script.py" while starting SD

### ISSUE THREAD

**Issue by beanzie** [TheLastBen/fast-stable-diffusion#1857]
Using latest notebook

```
Error loading script: lora_script.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/scripts/lora_script.py", line 4, in <module>
    import lora
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 238, in <module>
    def lora_apply_weights(self: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
Startup then completes but LoRA is not listed under extra networks and cannot be used in generations. Entering a LoRA prompt returns

`Skipping unknown extra network: lora`

**Comment by legendan** [comment]
I have the same error

**Comment by Hyperzenno** [comment]
same here

**Comment by jimlin1668478052** [comment]
Same here

**Comment by Omenizer** [comment]
No Lora for me either :(

**Comment by stradanie** [comment]
same

**Comment by SadSAYA** [comment]
same issue

**Comment by JarvisSan22** [comment]
I comminted out the lines after the function self call in lora.py. and it got it working again for me. 
238
`def lora_apply_weights(self): #: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention):`
and 
298 
`def lora_reset_cached_weight(self): # : torch.nn.Conv2d | torch.nn.Linear):`

**Comment by JarvisSan22** [comment]
This error has been repored on AUTOMATIC1111 
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8968

**Comment by f4cyw** [comment]
> I comminted out the lines after the function self call in lora.py. and it got it working again for me.
> 238
> `def lora_apply_weights(self): #: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention):`
> and
> 298
> `def lora_reset_cached_weight(self): # : torch.nn.Conv2d | torch.nn.Linear):`

I tried this and forced the file not to be updated. 
And there is no error when SD starts.
But when I tried to generate image it shows error again.

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7fb6e40f6bb0>]: RuntimeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 213, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 175, in load_lora
    module.weight.copy_(weight)
RuntimeError: output with shape [32, 32, 1, 1] doesn't match the broadcast shape [32, 32, 3, 3]

**Comment by vaclav-kyle** [comment]
> I comminted out the lines after the function self call in lora.py. and it got it working again for me. 238 `def lora_apply_weights(self): #: torch.nn.Conv2d | torch.nn.Linear | torch.nn.MultiheadAttention):` and 298 `def lora_reset_cached_weight(self): # : torch.nn.Conv2d | torch.nn.Linear):`


Thanks so much for finding the solution! It was really hard!!

**Comment by JarvisSan22** [comment]
Still not working. I am getting the same issuse as @f4cyw

**Comment by vaclav-kyle** [comment]
> Still not working. I am getting the same issuse as @f4cyw


I just checked the master file and it seems I'm missing some code in the master file itself. The master file Lora.py file is missing code on lines 238 and 298.

**Comment by JarvisSan22** [comment]
This seem to be a issue caused by the Stable diffusion v2 comptabilty change.  Not anything to do with colab so its just a version revertion and it fixed the problem.
`!git checkout 64da5c4`
Add this line to your notebook and it will turn back to a usable version

**Comment by beanzie** [comment]
@netrunner-exe 's [workaround](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8968#issuecomment-1484068849) has it temporarily fixed for me

In the colab interface go to /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora and open up lora.py

enter the following on a new line at the top of the file:

`from __future__ import annotations`

Then restart SD and you should be able to used LoRA again. Note that if you reinstall SD lora.py will reset and you'll need to add the line again.

**Comment by kopyl** [comment]
@JarvisSan22 it gave me this error: `ImportError: cannot import name 'ModuleAvailableCache' from 'lightning_utilities.core.imports' (/usr/local/lib/python3.9/dist-packages/lightning_utilities/core/imports.py)`

WebUI doesn't launch at all now.

**Comment by joung-chang-wei** [comment]
Me too! Besides, I don't know any programs or anything like that! There's no way to fix it even if you suggest a solution! I just hope this issue is anything big and general, and it will be fixed soon!

**Comment by umishima** [comment]
> !git checkout 64da5c4

where exactly to add it, before git clone line?

**Comment by rohithbv1991** [comment]
> This seem to be a issue caused by the Stable diffusion v2 comptabilty change. Not anything to do with colab so its just a version revertion and it fixed the problem. `!git checkout 64da5c4` Add this line to your notebook and it will turn back to a usable version

Where do I add this? I tried using git command line but it is stuck on the same commit and I can't even change commits. git log shows only one commit and no history.

**Comment by TheLastBen** [comment]
fixed no need to git checkout, just update the notebook

**Comment by tafari127** [comment]
Still getting "Error loading script: lora_script.py".

**Comment by TheLastBen** [comment]
do a screenshot to the error

**Comment by f4cyw** [comment]
> do a screenshot to the error
Thanks always. 
But I think I have same issue. 
pls find below error in colab. 


activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x7fca262b8190>]: RuntimeError
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extra_networks.py", line 75, in activate
    extra_network.activate(p, extra_network_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/extra_networks_lora.py", line 23, in activate
    lora.load_loras(names, multipliers)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 214, in load_loras
    lora = load_lora(name, lora_on_disk.filename)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions-builtin/Lora/lora.py", line 176, in load_lora
    module.weight.copy_(weight)
RuntimeError: output with shape [32, 32, 1, 1] doesn't match the broadcast shape [32, 32, 3, 3]

**Comment by beanzie** [comment]
> fixed no need to git checkout, just update the notebook

thanks, resolved

**Comment by zilvergrafix** [comment]
this updates are just for broken things not improve nothing
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/126435153/07250599-2dcf-4e65-a24d-69666d4d39ad)
