### ISSUE TITLE
Add support for --gradio-auth

### ISSUE THREAD

**Issue by GrantHoffman** [TheLastBen/fast-stable-diffusion#186]
https://www.reddit.com/r/StableDiffusion/comments/y56qb9/security_warning_do_not_use_share_in/
when adding --gradio-auth example123:password123
I've tried adding --gradio-auth to the params however collab fails

  File "/usr/local/lib/python3.7/dist-packages/gradio/blocks.py", line 1055, in launch
    "Cannot queue with encryption or authentication enabled."
ValueError: Cannot queue with encryption or authentication enabled.

**Comment by TheLastBen** [comment]
If you're not using "gradio server", your webui is safe, you don't need a password

**Comment by TheLastBen** [comment]
> @TheLastBen the default, non-gradio server, option opens the UI to the public via `loca.lt`

Yes, but it should be safe
