### ISSUE TITLE
Cant generate more image

### ISSUE THREAD

**Issue by Indras91** [TheLastBen/fast-stable-diffusion#1869]
I dont know why, no errors found, but, but i cant generate more image, after make some image, even if i refresh the webui or even restart the runtime, the generate button like not responding, force me to do fresh install again,

**Comment by beanzie** [comment]
I experienced this recently and think it was a gradio issue

Have you tried using localtunnel? No issues for me with it selected

**Comment by TheLastBen** [comment]
use ngrok

**Comment by AIT300** [comment]
what is Ngrok_token?how to get it ?

**Comment by TheLastBen** [comment]
signup and go here https://dashboard.ngrok.com/get-started/your-authtoken
