### ISSUE TITLE
[feature request] customer install dir 

### ISSUE THREAD

**Issue by Yang-z** [TheLastBen/fast-stable-diffusion#1882]
Hi,
I love this scrip "fast_stable_diffusion_AUTOMATIC1111.ipynb" since my first run, really fantastic job.

I'm here to ask for a feature that allows users to spesify their install direction, sine some people don't have enough space in 'mydrive' but they get shared drives from their companies. So they need to install sd and s-d-webui on one of the shared drives.

Yes, I can I modify the dir settings manually, and there's three aspects I need to care about:
1. Replace '/MyDrive/' in the ".ipynb" script , by '/shareddrives/my-shared-drive/'.
2. After the 'Requirements' cell run, move 'stablediffusion' fold under '/mydrive/sd/' to '/shareddrives/my-shared-drive/sd/'. I can not avoid this by replace dir in the script, and I gusee the file path is determined in the compressed files.
3. In the cell 'Start Stable-Diffusion', it seems to exist a "hotfix' for the file "paths.py". I have to replace the url of "paths.py" by a version of myself, with the fellowing changes: `possible_sd_paths = [os.path.dirname(script_path) + '/stablediffusion', '.', os.path.dirname(script_path)]`. This will work for both situations as I menthed ('/mydrive/sd/' or '/shareddrives/my-shared-drive/sd/').

If this script could support customer install dir, it would more fantastic.
Thanks a lot.

**Comment by TheLastBen** [comment]
Noted, I'll try to replace `/content/gdrive/MyDrive` with an editable variable. soon

**Comment by vienduong88** [comment]
> Added, update your notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Hello, I tried the shared drive function but when I Install automatic 1111 it keeps saying shared drive not detected and install to default location instead.

**Comment by Yang-z** [comment]
Hi,
I just did a test and encountered the same problem as [vienduong88](https://github.com/vienduong88).
I find that the dir of shared drives is actually "Shareddrives/" rather than "shareddrives/", it‘s case sensitive.
Sorry I didn't notice this in my first post.

**Comment by TheLastBen** [comment]
I'll fix it

**Comment by Yang-z** [comment]
Hi, I just test the last version, "stable-diffusion-webui" folder is now in the right place of my shared drive, but  the "stablediffusion" folder still goes to "/content/gdrive/MyDrive/sd"

**Comment by TheLastBen** [comment]
I'll fix it in the next few hours
