### ISSUE TITLE
try another colab Back to v2.0 fix all bugs (maybe) 

### ISSUE THREAD

**Issue by wth153** [TheLastBen/fast-stable-diffusion#1891]
Sorry, I made a mistake, automatic1111 only has a master branch, we can try the colab of camenduru, when I was trying various weird methods yesterday, I started the colab of camenduru, and found that it can be used. I am so happy,  Forgot to check the following link, now my account is also restricted, I can't try it, you can try it, v2.0 fix bug or just network _issue_

https://github.com/camenduru/stable-diffusion-webui-colab

I tried this yesterday
https://colab.research.google.com/github/camenduru/stable-diffusion-webui-colab/blob/main/stable/papercut_diffusion_webui_colab.ipynb

**Comment by Gushousekai195** [comment]
Has anybody tried this yet?

**Comment by SDPDVADER** [comment]
I did and it didn't work

**Comment by Hsoraa** [comment]
Although the version number does not seem to have changed, it seems miraculously that img2img works correctly, or it may be due to the network.🤗

**Comment by TheLastBen** [comment]
use ngrok for better connectivity

**Comment by TheLastBen** [comment]
get the token from this link https://dashboard.ngrok.com/get-started/your-authtoken

**Comment by kieranxsomer** [comment]
Ngrok is meant to work better but earlier ngrok wouldn't connect but local tunnel would, so it's odd.

**Comment by SDPDVADER** [comment]
I am seeing some antivirus blocking ngrok due to botnets.
