### ISSUE TITLE
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

### ISSUE THREAD

**Issue by Topzie** [TheLastBen/fast-stable-diffusion#1911]
So I just tried the latest update:
shared drive: unchecked
use latest working commit: checked
v2 model, no controlnet,no extensions, loras, embeddings, fresh install (renamed sd)

This is the complete output:

/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")
Loading weights [8f093ec6ad] from /content/gdrive/MyDrive/rmadamerge/rmadaMergeSD21768_v50.safetensors
Creating model from config: /content/gdrive/MyDrive/rmadamerge/rmadaMergeSD21768_v50.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 16.1s (load weights from disk: 9.0s, create model: 0.7s, apply weights to model: 3.9s, apply half(): 1.6s, move model to device: 0.8s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by Light-Danube** [comment]
Getting same error with "Latest_Working_Commit" checked and local tunnel checked.

**Comment by Light-Danube** [comment]
> try running, Use_Latest_Working_Commit: unchecked Use_localtunnel: checked

Unchecked Use Latest_Working_Commit and it's worked! Using localtunnel however.

**Comment by TheLastBen** [comment]
does the error persist or not ?

**Comment by Topzie** [comment]
It does wwhen you check use latest working commit

**Comment by Topzie** [comment]
I just tried to run it with my saved sd folder, but it errored again.
use latest working commit unchecked


Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 340, in <module>
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 246, in webui
    gradio_auth_creds = []
AttributeError: 'Namespace' object has no attribute 'no_gradio_queue'

I'll run it again, checked and unchecked and let you know

**Comment by Topzie** [comment]
Too bad, the webui is becoming unresponsive again. It's still buggy, I guess it's the auto repo.
