### ISSUE TITLE
Shared drive link doesn't work? Alternative solution: Shortcut to shared drive

### ISSUE THREAD

**Issue by anonderpling** [TheLastBen/fast-stable-diffusion#1919]
~~I'm not sure of the proper way to use shared drive; the path SharedDrives does not exist. However, I have no problem if I make a shortcut to the shared folder in my account named *sd*. Hmm. I'm getting a different issue, but I'm not sure if it's actually related.~~ This is because what I'm using is a shared folder, not a shared drive. However, I was still able to get around the limitations with this with the following process:

I had to hack around a different path issue 

Cell 2 (Install/Update Automatic1111 repo) says `Shared drive not detected, using default MyDrive`

[![](https://i.imgur.com/NCPj1hNs.png)](https://i.imgur.com/NCPj1hN.png) [![](https://i.imgur.com/Q4QDC1rs.png)](https://i.imgur.com/Q4QDC1r.png) [![](https://i.imgur.com/yqwrusds.png)](https://i.imgur.com/yqwrusd.png) [![](https://i.imgur.com/ghTXFXXs.png)](https://i.imgur.com/ghTXFXX.png)

modify cell 1, changing the mount point:
```
print("[0;33mConnecting...")
drive.mount('/content/gdrive2')
%cd /content
!mkdir -p /content/gdrive/MyDrive/sd
!mount --bind /content/gdrive2/.shortcut-targets-by-id/*/sd /content/gdrive/MyDrive/sd
```

If you have multiple shared folders, you'll probably need to adjust this by identifying the correct shared folder in that directory and replacing the asterisk.

**Comment by TheLastBen** [comment]
the first cell option is for shared drive only

**Comment by anonderpling** [comment]
Huh. Further research for me. I didn't even know there was such a thing as a separate shared drive, I thought all this was referring to shared folders. Now this all makes sense.

Since I see you're changing the tunneling options a bit, I'll just leave this here in case cloudflare decides to give SD the boot.: https://github.com/anderspitman/awesome-tunneling
