### ISSUE TITLE
Dreambooth step with custom ckpt: expected {'safety_checker', 'tokenizer', 'unet', 'vae', 'feature_extractor', 'scheduler', 'text_encoder'}, but only {'tokenizer', 'unet', 'vae', 'scheduler', 'text_encoder'} were passed.

### ISSUE THREAD

**Issue by lgrkvst** [TheLastBen/fast-stable-diffusion#192]
Hi,

I just tried my hands at Dreamboothing on a custom ckpt and got the following error:

```
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> expected {'safety_checker', 'tokenizer', 'unet', 'vae', 'feature_extractor', 'scheduler', 'text_encoder'}, but only {'tokenizer', 'unet', 'vae', 'scheduler', 'text_encoder'} were passed.
```
I realize I'm in over my head, but apparently there seems to be differences between ckpt files and ckpt files... 😬

**Comment by TheLastBen** [comment]
I'll fix this issue shortly

**Comment by lgrkvst** [comment]
Amazing =D =D

**Comment by TheLastBen** [comment]
fixed, try training a ckpt and see if there are more issues

**Comment by lgrkvst** [comment]
Splendid! But did you commit? It says 'TheLastBen committed 7 hours ago'...

**Comment by TheLastBen** [comment]
@lgrkvst in the diffusers repo

**Comment by lgrkvst** [comment]
Oh! And I'm `Generating class images:   7%`! Amazing work @TheLastBen!

**Comment by TheLastBen** [comment]
Thanks
