### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Finderz1** [TheLastBen/fast-stable-diffusion#1920]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

I tried multiple things:

- not running the first cell
- deleting the sd folder & reinstalling
- deleting the sd folder & reinstalling without the first cell
- i dont even have any extension installed or put any loras in the folder

 im using the latest version too
 i tried using ngrok but that didn't work either

It was working completely fine yesterday(besides the ui loading to long)

**Comment by Finderz1** [comment]
tried reinstalling it again and got an even longer Wackyer error

/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/usr/local/lib/python3.9/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tensorflow13GcsFileSystemE']
  warnings.warn(f"file system plugins are not loaded: {e}")
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4c86efd062ea772972dd068c3870773f1fd9a37ba9a288ee79ec848448ce7785
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:01<00:00, 867kB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 587kB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 94.4kB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 268kB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 711kB/s]
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 80.6s (calculate hash: 51.8s, load weights from disk: 11.8s, create model: 12.4s, apply weights to model: 2.9s, apply half(): 1.0s, move model to device: 0.7s).
Error executing callback after_component_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 191, in after_component_callback
    c.callback(component, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 860, in on_after_component_callback
    component.click(fn=self.save_submit_img2img_tab, inputs=gr.State(component.elem_id), outputs=[])
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

Error executing callback after_component_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 191, in after_component_callback
    c.callback(component, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 860, in on_after_component_callback
    component.click(fn=self.save_submit_img2img_tab, inputs=gr.State(component.elem_id), outputs=[])
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.9/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by DobrySkazochnik** [comment]
Same problem

**Comment by RabbitRoom** [comment]
Same problem.
If check Use_Latest_Working_Commit:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
ImportError: cannot import name 'timer' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
@RabbitRoom Use a fresh sd folder and the latest notebook

**Comment by Finderz1** [comment]
> @RabbitRoom Use a fresh sd folder and the latest notebook

this worked for me too, thanks ben!

**Comment by Finderz1** [comment]
@RabbitRoom Use a fresh sd folder and the latest notebook

this worked for me too, thanks ben!

case closed :D
