### ISSUE TITLE
Slowwww and crash

### ISSUE THREAD

**Issue by Fronscavenger** [TheLastBen/fast-stable-diffusion#1933]
I don't know if it's just me or if it's happening to others too, but it's working very slowly. I can only generate three images before the UI stops responding. It's frustrating.

**Comment by ShunKaiser** [comment]
I got the same problem. Back then I could generate a bunch of images at a time, but now I just can generate one or two pictures and the UI stops responding. It's frustrated and I don't know what is the issue here.

**Comment by TheLastBen** [comment]
use ngrok or cloudflare tunnel

**Comment by ShunKaiser** [comment]
> use ngrok or cloudflare tunnel

Thanks, I will try it.
