### ISSUE TITLE
(Small feature request): More info on the "COLAB screen" when generating images

### ISSUE THREAD

**Issue by SorenTruelsen** [TheLastBen/fast-stable-diffusion#1960]
Hi Ben and team
When running large batches or XYZ-scripts it can be hard guess how fare you are in the script. So it would be cool to get a bit more info on the "COLAB Screen". Say, instead of simply putting out: 

80% 20/30 [00:06<00:02,  4.80it/s]

It could put out something like: 

80% 20/30 [00:06<00:02,  4.80it/s]: XYZ: Image 23 of 40, Parameteres: Steep 30, CFG 5.0

Best of all would of course be if it could be configured like with file names. 

Thanks

Søren

![image](https://user-images.githubusercontent.com/7306254/230713706-706cf805-5637-4c43-b1be-7782ba8974a2.png)

**Comment by TheLastBen** [comment]
Only A1111 has control over the script output, I don't have control over that

**Comment by SorenTruelsen** [comment]
Thanks - Ill send the request over there (I really have a hard time telling which program/part of the program, does what)
