### ISSUE TITLE
(Bug) Progress bar and preview image disappears when queue requests

### ISSUE THREAD

**Issue by SorenTruelsen** [TheLastBen/fast-stable-diffusion#1961]
Hi Ben and Team
On COLAB, if I hit "generate" before ALL the images from the previous back, inclusive the grid, has finished loading, the progress bar disappears as well as the image preview. The request is running fine in the background and will display once the request is complete. 
This is a bit annoying, since the loading of images to the interface sometimes takes a long time.

Thank

Søren

**Comment by christytom007** [comment]
This usually happens to me when I have too many Chrome tabs and Chrome decided to suspend that tab. I managed to fix some of this by going to Chrome tools > More settings > Performance > add the white list to the "Memory Saver" or disabling it. Also "gradio" is janky, use Cloudflare Tunnel. Having Ngrok also makes it better (it's free).

**Comment by SorenTruelsen** [comment]
This seems to be an Automatic1111 issue. I will close it here. @christytom007 I will try playing around with the Chrome settings to see if it works
