### ISSUE TITLE
small issue

### ISSUE THREAD

**Issue by BigDogg99** [TheLastBen/fast-stable-diffusion#1974]
When downloading models from link, they are assigned a default name of "model.ckpt". This can create a problem when attempting to download multiple models during separate sessions, as the new model will overwrite the previous one unless it is manually renamed. It would be helpful if each downloaded model had its own name to reduce confusion and eliminate the need to constantly rename files.

**Comment by TheLastBen** [comment]
I did that because most users use free gdrive and that is limited size-wise, so if you want to keep the model long-term, you can simply rename it
