### ISSUE TITLE
Model or A1111 problem? 

### ISSUE THREAD

**Issue by KenLi041** [TheLastBen/fast-stable-diffusion#1976]
Hi when I run a meinamix v7 model on your a1111 it has a NaN problem, when I use it I can't generate image it says "A tensor with all NaNs was produced in Unet" but when I used other models it's working fine. Could you please kindly inform me if this is a model problem or A1111 problem? I tried all the fixes online like the ticking float32 or add commandline arg no half but that doesn't work. Thank you

**Comment by tianhwu** [comment]
I also have this problem with the last Ben's implementation here. I did not have this problem running camenduru's similar project yesterday.

**Comment by KenLi041** [comment]
Nevermind that problem is fixed on last Ben too thanks

**Comment by robertwt7** [comment]
how'd you end up fixing it? @KenLi041 , i just ran the https://github.com/TheLastBen/fast-stable-diffusion notebook today and it returns the same NaN problem

**Comment by KenLi041** [comment]
It's been many months so I really can't recall how I fixed that... I think some certain Anime style checkpoints like Meina could cause such problem... If you wait like a day to redownload that model or download somewhere else like in huggingface that might fix the problem
