### ISSUE TITLE
Add path link for 1.5 inpainting model

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#198]
I keep a copy of each model on GDrive and would like to point to them instead of having it download them. The trained model path works great, thank you for that. But now with 1.5 inpainting, I would like automatic to load it locally as well, instead of downloading as is the default.

I hear that automatic now loads all models from the same folder? Is the automatic colab set up to allow just the the folder path instead of a specific model .ckpt file?

Regards

**Comment by TheLastBen** [comment]
I added the option to download the inpainting model, once downloaded, you will be able to chose it from the drop down menu in the webui
and in the model path, you can specify either a model or of folder containing models

**Comment by GuruVirus** [comment]
Thank you!
