### ISSUE TITLE
Fast Dreambooth error (name 'check_output' is not defined)

### ISSUE THREAD

**Issue by Valdex** [TheLastBen/fast-stable-diffusion#1983]
Tab: Create/Load a Session

Session found, loading the trained model ...
Detecting model version...
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-4-7e8db7ce4151>](https://localhost:8080/#) in <cell line: 92>()
    101   wget.download('https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/det.py')
    102   print('Detecting model version...')
--> 103   Model_Version=check_output('python det.py --MODEL_PATH '+MDLPTH, shell=True).decode('utf-8').replace('\n', '')
    104   clear_output()
    105   print(''+Model_Version+' Detected')

NameError: name 'check_output' is not defined

**Comment by TheLastBen** [comment]
Your pull request has been merged
