### ISSUE TITLE
starting staable diffusion don't work

### ISSUE THREAD

**Issue by username-094** [TheLastBen/fast-stable-diffusion#1992]
when i try to start stable diffusion it comes up with this:

`ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-0e3a00bb2f4e>](https://localhost:8080/#) in <cell line: 6>()
      4 import sys
      5 import fileinput
----> 6 from pyngrok import ngrok, conf
      7 
      8 Use_Cloudflare_Tunnel = False #@param {type:"boolean"}

ModuleNotFoundError: No module named 'pyngrok'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.`

**Comment by TheLastBen** [comment]
use the latest notebook by clicking on the thumbnail on the main page of this repo
