### ISSUE TITLE
Keep getting error while UI is running

### ISSUE THREAD

**Issue by Brown-Michael** [TheLastBen/fast-stable-diffusion#2005]
https://pastebin.com/7wb5AYfX

I'm just chilling, leaving the UI running in the background, and keep getting this error over and over.

Can't seem to find anything it might be affecting, but the startup is taking forever and I do not want to get surprised in the future.

**Comment by TheLastBen** [comment]
try using ngrok

**Comment by Brown-Michael** [comment]
Still same issue

**Comment by TheLastBen** [comment]
Maybe it is caused by an extension
