### ISSUE TITLE
Dreambooth error when trying to train on sd-v1-5-inpaining.ckpt

### ISSUE THREAD

**Issue by samf1986** [TheLastBen/fast-stable-diffusion#202]
![image](https://user-images.githubusercontent.com/46737294/197347434-229acd00-f470-4c62-b30d-e9f0c4af0cc3.png)

**Comment by TheLastBen** [comment]
sd-v1-5-inpaining.ckpt has a slightly different architecture and is based on sd 1.2.

**Comment by samf1986** [comment]
Thanks! Will it be compatible in the future?

**Comment by TheLastBen** [comment]
that's up to the devs of dreambooth or runwayml
