### ISSUE TITLE
Concept Images loading error

### ISSUE THREAD

**Issue by impallari** [TheLastBen/fast-stable-diffusion#2026]
The subject training images loads ok, but
when loading the Concept images I got this error:

|               | 0/50 Uploaded
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/PIL/JpegImagePlugin.py](https://localhost:8080/#) in _save(im, fp, filename)
    628     try:
--> 629         rawmode = RAWMODE[im.mode]
    630     except KeyError as e:

KeyError: 'RGBA'

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
2 frames
[/usr/local/lib/python3.9/dist-packages/PIL/JpegImagePlugin.py](https://localhost:8080/#) in _save(im, fp, filename)
    629         rawmode = RAWMODE[im.mode]
    630     except KeyError as e:
--> 631         raise OSError(f"cannot write mode {im.mode} as JPEG") from e
    632 
    633     info = im.encoderinfo

OSError: cannot write mode RGBA as JPEG

**Comment by TheLastBen** [comment]
check the images extensions

**Comment by impallari** [comment]
They are all .jpg

**Comment by TheLastBen** [comment]
one of them isn't the correct format, you'll have to find it
