### ISSUE TITLE
Throwing an odd error and stalling out the collab

### ISSUE THREAD

**Issue by wordbrew** [TheLastBen/fast-stable-diffusion#2027]
Just did a brand new re-install on latest colab, with unchecked "latest commit" option.

When I run the cell to start Stable Diffusion, it provides the following read out, then spikes in VRAM, followed by nothing. It just sits and spins. It fails to respond to stop resulting in having to completely restart the runtime.

```
Downloading: "https://download.pytorch.org/models/raft_large_C_T_SKHT_V2-ff5fadd5.pth" to /root/.cache/torch/hub/checkpoints/raft_large_C_T_SKHT_V2-ff5fadd5.pth
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4732:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5220:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
```

Unsure what might be causing this. Obviously there are no soundcards involved here. Any help is appreciated.

**Comment by TheLastBen** [comment]
do you have any extension installed ?

**Comment by wordbrew** [comment]
I have a few installed and have been trying to find the source of the cause. I'm fairly confident it is originating from: https://github.com/CiaraStrawberry/TemporalKit

Though it worked fine on the prior commit and actually worked initially on this one. Then suddenly started hanging everything up.

**Comment by TheLastBen** [comment]
delete it then reinstall it

**Comment by wordbrew** [comment]
I've deleted the extension, but colab just sits there spinning with no output at the Start Stable-Diffusion cell... System-RAM still spiking to max 25.5gb too before falling to 0. Just completely stalled.

I can't tell if it is my install or google colab itself. I'm a Colab Pro subscriber, but (as you definitely know) google has really been cracking down on web-ui usage. :( I get a captcha test regularly when I hit the Start Stable-Diffusion cell. One time it made me do 6 different captcha tests just to pass and by then the runtime had disconnected.

Ugh. Looks like I'm going to have to waste another 2 hours setting up all my SD shit again...

**Comment by wordbrew** [comment]
Completely uninstalling and reinstalling the whole SD install is the only thing that worked, it seems. Pity.
