### ISSUE TITLE
controlnet stops working after one use

### ISSUE THREAD

**Issue by Japtranslator** [TheLastBen/fast-stable-diffusion#2044]
i get this error:

Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 417, in process
    script.process(p, *script_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 1056, in process
    tmp_seed = int(p.all_seeds[0] if p.seed == -1 else max(int(p.seed),0))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

I just generate one picture and everything works fine, but then it fails to load the controlnet. Could anyone please help me?

**Comment by TheLastBen** [comment]
try again with fresh settings

**Comment by Japtranslator** [comment]
> try again with fresh settings
i just realized what the problem was. I had an empty seed. Always needs to be a seed or -1.
