### ISSUE TITLE
Dreambooth - CalledProcessError: Command 'python det.py --from_safetensors --MODEL_PATH /content/gdrive/MyDrive/model.safetensors' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by IMatheusss** [TheLastBen/fast-stable-diffusion#2056]
I'm trying to finetune a model I have but it keeps giving this error when I select the path from my GDrive, it also gives me the same error if I try to link the path from huggingface (I also had to insert !pip install wget before loading it, I was getting the error ModuleNotFoundError: No module named 'wget')
CalledProcessError: Command 'python det.py --from_safetensors --MODEL_PATH /content/gdrive/MyDrive/model.safetensors' returned non-zero exit status 1.

**Comment by TheLastBen** [comment]
give me the link to the model

**Comment by IMatheusss** [comment]
> 

any model I tested gave me the same error, but I haven't tested them as cptk, only safetensors
https://civitai.com/models/4823/deliberate

**Comment by TheLastBen** [comment]
tick the box "safetensors" in the model download cell

**Comment by IMatheusss** [comment]
> tick the box "safetensors" in the model download cell

it's ticket

**Comment by IMatheusss** [comment]
> What is the exact link to the model you're using ?

this one I sent, deliberate. But I tried using 1.5 only, didn't worked anyway

**Comment by TheLastBen** [comment]
make sure you check the box safetensors if the model is a safetensors

**Comment by IMatheusss** [comment]
I'v checked the safetensors box but it doesn't work anyway, and even if I don't try a custom model and decide to go with the usual 1.5 sd, when trying to train the pictures it doesn't work either

**Comment by IMatheusss** [comment]
I've tested in another google account withou any type of custom model, only the sd 1.5 and for some reason it worked, even though I did nothing different, I'm gonna test in a new account to see what will happen

**Comment by IMatheusss** [comment]
It worked either, I don't know why it's not working in my main account though, I'm using the updated link

**Comment by Soliaonline** [comment]
I am also having this issue.

**Comment by Soliaonline** [comment]
I figured it out, google randomly bans you if too many people are using it.

**Comment by AdrianAguilarT** [comment]
I had the same problem recently. I tried with another account as you commented and it worked. After trying again with another account, it failed me. It turns out that this message appeared to me because to read the base model it makes use of GPU, which I did not have configured. Once the GPU was assigned, it worked perfectly.
