### ISSUE TITLE
Feature request: Save checkpoint & preview every n steps

### ISSUE THREAD

**Issue by HexPlox** [TheLastBen/fast-stable-diffusion#206]
Any chance of adding the ability to save a checkpoint and a preview every "n" number of steps while training in the dreambooth colab?
Thank you. ❤️

**Comment by TheLastBen** [comment]
Unlike textual inversion, Dreambooth script doesn't offer this feature, but you can get great results with only 1500 steps with dreambooth (less than 1h)

**Comment by HexPlox** [comment]
This was linked in the dreambooth discord server.
https://github.com/DonStroganotti/diffusers/blob/jocke_test/examples/dreambooth/train_dreambooth.py
I dunno if I can just use this file instead, but it's supposed to provide support for saving checkpoints every n steps and captioned training.

**Comment by TheLastBen** [comment]
Very interesting, thank you, I'll look into it

**Comment by DonStroganotti** [comment]
> Very interesting, thank you, I'll look into it

Just ping me if you have any questions, it should be fairly self explanatory though, just follow the newly added commands.

The default optimizer has been changed because I use deepspeed locally, and class image captions aren't implemented, but should be just a copy paste of the instance code.

**Comment by TheLastBen** [comment]
@DonStroganotti
 Great work, does the script provide the option to save checkpoints every n steps ?

**Comment by DonStroganotti** [comment]
> 

Yes. 

Like this for example saves every 3000 steps up to 12000 and uses the file names as instance_prompt: 
`
--max_train_steps=12000 \

--save_n_steps=3000 \

--image_captions_filename \
`

**Comment by TheLastBen** [comment]
perfect, thanks !

**Comment by TheLastBen** [comment]
Feature added https://github.com/TheLastBen/diffusers/commit/0b77c4e56bf377d424c7ed87d6cb1804469b0217
https://github.com/TheLastBen/fast-stable-diffusion/commit/a8de378e12df1a3b155f6750f02072b7d75290c6

**Comment by DonStroganotti** [comment]
Yarrrrr from Reddit says Hi.

**Comment by TheLastBen** [comment]
> Yarrrrr from Reddit says Hi.

If you want to remove your code from my repo, I'll happily do it, just say the word
