### ISSUE TITLE
ModuleNotFoundError: No module named 'wget'

### ISSUE THREAD

**Issue by benghee** [TheLastBen/fast-stable-diffusion#2061]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-23c40f50b731>](https://localhost:8080/#) in <cell line: 7>()
      5 from os.path import isfile
      6 from subprocess import check_output
----> 7 import wget
      8 import time
      9 

ModuleNotFoundError: No module named 'wget'

---------------------------------------------------------------------------

The problems come back from yesterday, not even set it to Use Fallback Runtime version. What am I missing here?

**Comment by TheLastBen** [comment]
use the latest notebook
