### ISSUE TITLE
Bug in Hypernetworks Training

### ISSUE THREAD

**Issue by jvkap** [TheLastBen/fast-stable-diffusion#207]
I'm trying to use Hypernetworks but this errors occurs:

''AssertionError: no gradient found for the trained weight after backward() for 10 steps in a row; this is a bug; training cannot continue""

**Comment by TheLastBen** [comment]
check the AUTOMATIC1111 repo for similar issue to find out if it is related to the colab

**Comment by jvkap** [comment]
> no gradient found for the trained weight after

I might have searched wrong, but I tried and found nothing.

**Comment by TheLastBen** [comment]
what model are you training, the default one ?

**Comment by jvkap** [comment]
I am trying to train a modified dreambooth. Could this be it?

I made another modified dreambooth model (I thought the old model might be buggy), but the error persisted. I couldn't test it with the traditional model yet.

**Comment by jvkap** [comment]
It is important to emphasize that traditional embedding is working normally.

**Comment by TheLastBen** [comment]
Probably Dreambooth makes the model incompatible with Hypernetworks training

**Comment by jbrsfa** [comment]
I get the same error, but I don't use the model trained in dreambooth. How to fix it?

**Comment by TheLastBen** [comment]
@jbrsfa you're using the default model ?

**Comment by jbrsfa** [comment]
Yes, I'm just using stable diffusion 1.5

**Comment by TheLastBen** [comment]
try the 1.4 and see if you get the same error

**Comment by jbrsfa** [comment]
The training has started, thank you!

**Comment by TheLastBen** [comment]
Great, I guess the current hypernetwork isn't compatible with 1.5

**Comment by jvkap** [comment]
> Reference in ne
I asked a friend to test with 1.5 and the latest version of the Automatic1111 repo running locally, and it went normally, no errors.

**Comment by TheLastBen** [comment]
it must be the new vae then, i'll look into it

**Comment by jvkap** [comment]
Maybe hypernetworks is not compatible with the new vae.

**Comment by TheLastBen** [comment]
I'll add a checkbox for hypernetworks compatibility shortly, once added, try it

**Comment by TheLastBen** [comment]
Option added, try it and see if it works

**Comment by jvkap** [comment]
Dont work.
AssertionError: no gradient found for the trained weight after backward() for 10 steps in a row; this is a bug; training cannot continue

**Comment by jvkap** [comment]
I tried once, it didn't work out. I created another hypernetwork, the second time it worked.

Thanks!

**Comment by jvkap** [comment]
Actually, instead of 10 steps, it stopped at 15, but the error is the same.

**Comment by jvkap** [comment]
Full error:

Applying cross attention optimization (Doggettx).
Error completing request
Arguments: ('CTANCHYPE', '0.00001', 1, '/content/gdrive/MyDrive/AnimalsTrainingEBF', 'textual_inversion', 512, 512, 2000, 100, 100, '/content/gdrive/MyDrive/sd/stable-diffusion-webui/textual_inversion_templates/style_filewords.txt', False, '', '', 20, 0, 7, -1.0, 512, 512) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 223, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 63, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/ui.py", line 47, in train_hypernetwork
    hypernetwork, filename = modules.hypernetworks.hypernetwork.train_hypernetwork(*args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 393, in train_hypernetwork
    assert steps_without_grad < 10, 'no gradient found for the trained weight after backward() for 10 steps in a row; this is a bug; training cannot continue'
AssertionError: no gradient found for the trained weight after backward() for 10 steps in a row; this is a bug; training cannot continue

**Comment by TheLastBen** [comment]
did you also check hypernetwork compatibility in the last cell ?

**Comment by jvkap** [comment]
It was really that mistake. I thought it was more about using it than training it. And then I thought that when I checked the box in the models cell, I didn't need to check it in the "start" cell.

Sorry, Ben!

Thank for your support!

**Comment by TheLastBen** [comment]
Happy to help, 
would you please confirm that both (compatibility) checkboxes have to be checked or just the one in the last cell
