### ISSUE TITLE
got an error TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

### ISSUE THREAD

**Issue by wearks** [TheLastBen/fast-stable-diffusion#2079]
I just ran google colab with Use_Latest_Working_Commit:
Some hours before code was working, but now isnt
ControlNet v1.1.125
ControlNet v1.1.125
Loading weights [1b5f8211ec] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/aurora_v10.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 50.8s (load weights from disk: 40.9s, create model: 4.9s, apply weights to model: 3.3s, apply half(): 0.9s, move model to device: 0.7s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by wearks** [comment]
![image](https://user-images.githubusercontent.com/132305606/235531520-cf9d2180-23e2-45d1-8617-88c10b4d01d5.png)

**Comment by wearks** [comment]
Also I deleted folder sd and nothing changed

**Comment by lhucklen** [comment]
Same

**Comment by ariraz513** [comment]
Me 2

**Comment by Khayoon** [comment]
using latest notebook and this still happens

**Comment by xxxxxDantexxxxx** [comment]
same error

**Comment by NicoHuve** [comment]
Same here

**Comment by okeymmloo** [comment]
Does anyone know how to fix it ;(

**Comment by kieranxsomer** [comment]
Yea i'm on twitch rigfht now, new notebook - same thing, it LITERALLY worked yesterday XD

**Comment by okeymmloo** [comment]
I was able to make it work by installing radio 3.18.0 but the interface now has a lot of stuff xd

**Comment by Lewis-Di39** [comment]
Same error

**Comment by Lewis-Di39** [comment]
![SDerror](https://user-images.githubusercontent.com/122175613/235568346-e9ef65e3-719d-4a6b-92e1-97d7af39d8e9.JPG)

**Comment by HorrySheet** [comment]
seems to be working now for me with regular default settings except inpaint only works for about 5 generations then just stops causing you to reload the page .. worse than ever =/

**Comment by modulator** [comment]
Same

**Comment by materosx** [comment]
Glad it's not just me doing it wrong at least, hope it gets fixed soon.

**Comment by XacDinh** [comment]
For me it happen when I check Use_Latest_Working_Commit, work well on A1111 newest commit. The problem is newest commit is worse than older one, everyone knew it.

**Comment by kende** [comment]
> I was able to make it work by installing gradio 3.18.0 but the interface now has a lot of stuff xd

Only thing that worked for me so far. Thanks!

**Comment by protrading104** [comment]
> I have same error when I check `Use_Latest_Working_Commit`. So I try to use newest commit but find there is a bug in this code
> 
> ```
>   %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
>   !git reset --hard
>   time.sleep(1)
>   !rm webui.sh
>   !git pull
>   if Use_Latest_Working_Commit:
>     !git fetch --unshallow
>     !git checkout a9eab236d7e8afa4d6205127904a385b2c43bb24
>     !pip install gradio==3.16.2 --no-deps -qq
>   else:
>     !pip install gradio==3.28.1 -qq
> ```
> 
> If you have checked `Use_Latest_Working_Commit` before, the branch will keep in detached HEAD even you uncheck the option. Because there is no `git checkout master` in `else`. Workaround is create another cell after `Install/Update AUTOMATIC1111 repo` to run following code to solve it after uncheck `Use_Latest_Working_Commit`.
> 
> ```
> %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
> !git checkout master
> !git reset --hard
> ```

ya, it help me, thanks

![image](https://user-images.githubusercontent.com/71656833/235612997-dc97c485-db50-4591-8708-8f797ad1e261.png)

**Comment by Wyeel** [comment]
> I have same error when I check `Use_Latest_Working_Commit`. So I try to use newest commit but find there is a bug in this code
> 
> ```
>   %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
>   !git reset --hard
>   time.sleep(1)
>   !rm webui.sh
>   !git pull
>   if Use_Latest_Working_Commit:
>     !git fetch --unshallow
>     !git checkout a9eab236d7e8afa4d6205127904a385b2c43bb24
>     !pip install gradio==3.16.2 --no-deps -qq
>   else:
>     !pip install gradio==3.28.1 -qq
> ```
> 
> If you have checked `Use_Latest_Working_Commit` before, the branch will keep in detached HEAD even you uncheck the option. Because there is no `git checkout master` in `else`. Workaround is create another cell after `Install/Update AUTOMATIC1111 repo` to run following code to solve it after uncheck `Use_Latest_Working_Commit`.
> 
> ```
> %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
> !git checkout master
> !git reset --hard
> ```

omygosh, this helped! Thank you!

**Comment by TheLastBen** [comment]
you're getting the error because you manually modified the A1111 files, I'll add git reset to fix that

**Comment by wearks** [comment]
I didn't change the files in any way, so I don't know what exactly caused the error

**Comment by wearks** [comment]
> I have same error when I check `Use_Latest_Working_Commit`. So I try to use newest commit but find there is a bug in this code
> 
> ```
>   %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
>   !git reset --hard
>   time.sleep(1)
>   !rm webui.sh
>   !git pull
>   if Use_Latest_Working_Commit:
>     !git fetch --unshallow
>     !git checkout a9eab236d7e8afa4d6205127904a385b2c43bb24
>     !pip install gradio==3.16.2 --no-deps -qq
>   else:
>     !pip install gradio==3.28.1 -qq
> ```
> 
> If you have checked `Use_Latest_Working_Commit` before, the branch will keep in detached HEAD even you uncheck the option. Because there is no `git checkout master` in `else`. Workaround is create another cell after `Install/Update AUTOMATIC1111 repo` to run following code to solve it after uncheck `Use_Latest_Working_Commit`.
> 
> ```
> %cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
> !git checkout master
> !git reset --hard
> ```

thx

**Comment by wearks** [comment]
With new cell it is working

**Comment by jihocult** [comment]
I still have this problem and can't fix it

**Comment by mdlieber99** [comment]
adding this code from Wyeel totally worked:
%cd /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/
!git checkout master
!git reset --hard

**Comment by ArrowA1** [comment]
I just created a new copy of [theLastBen's notebook](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb?authuser=5) in my drive, made sure `Use_Latest_Working_Commit` is unchecked, and it works
