### ISSUE TITLE
Very slow training since yesterday.

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#2087]
Hello ben, i have noticed that for some reason the iterations and time to train has increase 2X. I have been training some models for the last 3 weeks, SAME settings and almost same amount of images, and when i used to RESUME training for 1000 steps, it always took 20 minutes! Now it takes 40 minutes for the same resuming.... did something happened to xformers or did you had to change something?

**Comment by LIQUIDMIND111** [comment]
Progress:|█████████████            | 51% 507/1000 [16:48<16:12,  1.97s/it, loss=0.0489, lr=9.86e-7] ZRHxome 

it says remaining time AFTER 50% is 16:12!!! This is the time it used to do a FULL resume run last week! Now its half the speed...... 

iterations normally is 1.29 s/it now its 1.97s/it,

**Comment by LIQUIDMIND111** [comment]
> Nothing was changed, check your settings and check that your getting the T4

im doing the same as always, and in settings it says Hardware accelerator
GPU
GPU class
Standard


and STANDARD is in grey... wont let me change to something else.

**Comment by LIQUIDMIND111** [comment]
> run `!nvidia-smi` to see what GPU you're getting

![Screenshot 2023-05-02 092336](https://user-images.githubusercontent.com/112510084/235679211-41310399-c110-4827-9079-7fdb865d37c4.jpg)

**Comment by TheLastBen** [comment]
what resolution are you training on ?

**Comment by LIQUIDMIND111** [comment]
> what resolution are you training on ?

768, as i have been doing all the time since november last year. i dont use 512 anymore, and this is the first time is so slow on 768 

Most of the time i use 30 instance images, and this time im using 60 instance images, but one time i also used 65 and it was normal speed, not slow, now i had to stop it because it was at 2.20 s/it, and it took 3 hours what it was taking 1:30 or 2 hours some days ago, :(
