### ISSUE TITLE
When to set External_Captions=True ?

### ISSUE THREAD

**Issue by Trithilon** [TheLastBen/fast-stable-diffusion#2089]
Will it ignore any manual captions till I manually set External_Captions to true?

Does it generate its own captions using BLIP right before training if manual captions are unavailable?

I bulk upload images and their captions and they get copied to their directories in the session folder.
Sometimes I manually edit them using the manual captioning tool.

**Comment by TheLastBen** [comment]
You need to set External_Captions=True to activate your captions

**Comment by Trithilon** [comment]
@TheLastBen  What happens if you leave it to false and when do you want to leave it as false?

**Comment by TheLastBen** [comment]
if you set it to false, it will only use the images filenames as a token

**Comment by Trithilon** [comment]
Is it important to use the token in the captions,
"a photo of a sksss woman smiling in a red dress"
or will
"a photo of a woman smiling in a red dress" suffice?

**Comment by Trithilon** [comment]
Thank you!
