### ISSUE TITLE
Settings should be saved outside of its working path

### ISSUE THREAD

**Issue by jcplus** [TheLastBen/fast-stable-diffusion#209]
Every time the webui updated, I have to remove the sd folder in case to get it working again that I will loose my settings. Though it takes a short time to redo the settings but it should be possible to have the settings saved in somewhere like the output images that wouldn't be removed even sd folder is removed. Please consider, thanks.

**Comment by TheLastBen** [comment]
I added the option "update_repo" for both AUTOMATIC and Dreambooth, you don't need to remove the sd folder anymore, but I'll change the output folder path to gdrive/outputs

**Comment by jcplus** [comment]
Thanks, it's good to know.
