### ISSUE TITLE
Error when start sd

### ISSUE THREAD

**Issue by yanfma123** [TheLastBen/fast-stable-diffusion#2094]
Error when start sd
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

and when I check Use_Latest_Working_Commit, another problem happen,
Crying

**Comment by TheLastBen** [comment]
use this link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by metzo007** [comment]
I have the same error

**Comment by metzo007** [comment]
I did reload the colab since you canged something just now but sitill the same error. I will try the old delete SD folder trick ;-)

**Comment by TheLastBen** [comment]
just pushed a fix, always use the link

**Comment by metzo007** [comment]
I did :-). I deleted the SD folder. Now it looks like it works. thanks,

**Comment by yanfma123** [comment]
> just pushed a fix, always use the link

it works，thank you so much，i found my happy again

**Comment by TheLastBen** [comment]
great!
