### ISSUE TITLE
Dreambooth colab CKPT conversion error

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#210]
Loading from CKPT_PATH, both sd-v1-4.ckpt and 1.5-pruned giving me the following output. Tried multiple paths. Edit: finally went with huggingface token just so I can move forward, and it said "DONE!" faster than I could revise this intro and type this sentence. That seems awfully fast for 4GB... Maybe the token is required even with CKPT_PATH filled in? If so, please update the comment thx.

Traceback (most recent call last):
  File "/content/convert_original_stable_diffusion_to_diffusers.py", line 644, in <module>
    checkpoint = torch.load(args.checkpoint_path)["state_dict"]
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1049, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.7/dist-packages/torch/serialization.py", line 1042, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'pytorch_lightning'
Conversion error, check your CKPT and try again
Conversion error, check your CKPT and try again
Conversion error, check your CKPT and try again
^this loops

**Comment by TheLastBen** [comment]
try : 
`!pip install pytorch_lightning`

**Comment by GuruVirus** [comment]
See https://github.com/TheLastBen/fast-stable-diffusion/issues/439

**Comment by wilzamguerrero** [comment]
i try this but dont work, is the same stop when create.
