### ISSUE TITLE
Colab started to turn itself off. 

### ISSUE THREAD

**Issue by Archon332** [TheLastBen/fast-stable-diffusion#2103]
After a few minutes colab started to cut you off from connection with GPU.
There is no illegal code message and code can be rebooted, but I suppose Google started to turn UI off by force.

**Comment by marcosotb** [comment]
Same here, well, it had to start happening at some point.

**Comment by Archon332** [comment]
In last 30 minutes it turned off 3 times.

**Comment by Sotonya** [comment]
same here

**Comment by XacDinh** [comment]
So it not only me. One last 22 mins and one 12 mins.

**Comment by X-eyn** [comment]
yeah, been facing a lot of bugs and errors recently

**Comment by Gamemaster2930** [comment]
You are right. Exactly 12 minutes - then disconnect. Damn them

**Comment by TheLastBen** [comment]
If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.

Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified

Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU

**Comment by Ktr4ks** [comment]
Oh, and I thought it was the wifi.

**Comment by Archon332** [comment]
Already uses Paperspace, but free plan works slower and I you can use big models with this plan. Unfortunately, I can't use paid plans because Visa, Mastercard and Paypal don't work in my country.

**Comment by Gamemaster2930** [comment]
I guess that's the end. NOOOO

**Comment by XacDinh** [comment]
> If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.
> 
> Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified
> 
> Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU

Do those 2 have storage like drive (15GB), I usually store a lot of models in my sd folder. Paid 100GB drive quite cheap, other 2 I just didn't know. And what GPU equivalent to Colab Pro one?

**Comment by Gamemaster2930** [comment]
> > If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.
> > Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified
> > Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU
> 
> Do those 2 have storage like drive (15GB), I usually store a lot of models in my sd folder. Paid 100GB drive quite cheap, other 2 I just didn't know. And what GPU equivalent to Colab Pro one?

I used Paperspace for a while and I can say this - Free version has only 5GB of storage space, GPU is at least half as slow as CoLab's GPU. But it isn't something you can't live with. You can download the models in the temporary storage and run them from here.

**Comment by XacDinh** [comment]
> > > If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.
> > > Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified
> > > Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU
> > 
> > 
> > Do those 2 have storage like drive (15GB), I usually store a lot of models in my sd folder. Paid 100GB drive quite cheap, other 2 I just didn't know. And what GPU equivalent to Colab Pro one?
> 
> I used Paperspace for a while and I can say this - Free version has only 5GB of storage space, GPU is at least half as slow as CoLab's GPU. It also has only 8GB of VRAM. But it isn't that bad. You can download the models in the temporary storage and run them from here.

Technically it's 3060 ti, exactly half VRAM and half speed of T4. Did you try ControlNet on there?

**Comment by Gamemaster2930** [comment]
> > > > If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.
> > > > Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified
> > > > Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU
> > > 
> > > 
> > > Do those 2 have storage like drive (15GB), I usually store a lot of models in my sd folder. Paid 100GB drive quite cheap, other 2 I just didn't know. And what GPU equivalent to Colab Pro one?
> > 
> > 
> > I used Paperspace for a while and I can say this - Free version has only 5GB of storage space, GPU is at least half as slow as CoLab's GPU. It also has only 8GB of VRAM. But it isn't that bad. You can download the models in the temporary storage and run them from here.
> 
> Technically it's 3060 ti, exactly half VRAM and half speed of T4. Did you try ControlNet on there?

There was no point because I could use CoLab with better speeds but now when free people are not allowed to use the webui which sucks really badly I'll need to try it. I don't think there will be issues with ControlNet

**Comment by ElThunasFBI** [comment]
So you can't use the Fast Stable Diffusion colab again?

**Comment by Gamemaster2930** [comment]
> So you can't use the Fast Stable Diffusion colab again?

As mentioned above, they will now disconnect you from your session killing all your processes when you attempt to generate an image. Or they will allow it, but will cut the connection right after one image you make.

**Comment by ahmedsiha** [comment]
> So you can't use the Fast Stable Diffusion colab again?

Not for free, paid colab users can still use it as usual.

**Comment by Gamemaster2930** [comment]
> > So you can't use the Fast Stable Diffusion colab again?
> 
> Not for free, paid colab users can still use it as usual.

Yeah, that's true. Some people including me just can't afford paying 12€ per month.

**Comment by HaikenEdge** [comment]
> > > > So you can't use the Fast Stable Diffusion colab again?
> > > 
> > > 
> > > Not for free, paid colab users can still use it as usual.
> > 
> > 
> > Yeah, that's true. Some people including me just can't afford paying 12€ per month.
> 
> Not per month. It's 50 hours of using.

Dude, that's like, less than a week for me.

**Comment by Archon332** [comment]
> > > So you can't use the Fast Stable Diffusion colab again?
> > 
> > 
> > Not for free, paid colab users can still use it as usual.
> 
> Yeah, that's true. Some people including me just can't afford paying 12€ per month.

And some can afford but live in 2nd world country.

**Comment by Akshat-Gupta04** [comment]
whats the whole matter ?
can anybody explain facing the same closing issue

**Comment by XacDinh** [comment]
> whats the whole matter ? can anybody explain facing the same closing issue

Possibly Colab crackdown stable diffusion now, since paid user can still use just fine, and free user got disconnected. Let's hope just a shortage and they prioritize paid user.

**Comment by Gamemaster2930** [comment]
> whats the whole matter ? can anybody explain facing the same closing issue

Google simply doesn't want us - free users use Auto1111's on CoLab without subscription because lots of people were using it and the power bill was huge. TheLastBen managed to trick their system with blasphemy library (?) so the "webui" word wasn't identified. However, Google found that out and now free users without Pro subscription face disconnection after few minutes of running the webui making it completely unusuable. It sucks

**Comment by Akshat-Gupta04** [comment]
> > whats the whole matter ? can anybody explain facing the same closing issue
> 
> Google simply doesn't want us - free users use Auto1111's on CoLab without subscription because lots of people were using it and the power bill was huge. TheLastBen managed to trick their system with blasphemy library (?) so the "webui" word wasn't identified. However, Google found that out and now free users without Pro subscription face disconnection after few minutes of running the webui making it completely unusuable. I also hope it is just a shortage but if it isn't, well it sucks

while this issue be solved?
and its charging 11 dollers for 100 computing units what is this computing unit?

**Comment by XacDinh** [comment]
> > > whats the whole matter ? can anybody explain facing the same closing issue
> > 
> > 
> > Google simply doesn't want us - free users use Auto1111's on CoLab without subscription because lots of people were using it and the power bill was huge. TheLastBen managed to trick their system with blasphemy library (?) so the "webui" word wasn't identified. However, Google found that out and now free users without Pro subscription face disconnection after few minutes of running the webui making it completely unusuable. I also hope it is just a shortage but if it isn't, well it sucks
> 
> while this issue be solved? and its charging 11 dollers for 100 computing units what is this computing unit?

No one know. The one thing we know here is only paid user can use SD. By paid Colab Pro, you got 100 computing unit (CU, every hour of usage take 1.98 CU, so 10 USD (in my country) equal ~50 hours.

**Comment by sajjadalis** [comment]
It was bound to happen, just a matter of time. I was using 3 different accounts for the last one and half months and yesterday, I added 4th and I was wondering how long we have to enjoy this free service. Well, the dream didn't last long. :) I also hope this is some kind of temporary overall shortage for free users and not a crackdown on SD users.

**Comment by ahmedsiha** [comment]
> It was bound to happen, just a matter of time. I was using 3 different accounts for the last one and half months and yesterday, I added 4th and I was wondering how long we have to enjoy this free service. Well, the dream didn't last long. :) I also hope this is some kind of temporary overall shortage for free users and not a crackdown on SD users.

There's no such thing as crackdown on SD users, it's mainly about them cutting down the electricity bill and making profit.

**Comment by banMo88** [comment]
> If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.
> 
> Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified
> 
> Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU

hi,ben.There's a bug in the pps notebook.Could you please take a look?

**Comment by josemerinom** [comment]
Hello, a few minutes ago I finished 4 dreambooth colab workouts (2h each, different colabs) and the colab did not turn off. I don't know if it's just something that affects SD colab, but for training there's no problem.

**Comment by Akshat-Gupta04** [comment]
is the issue still existing?

**Comment by HaikenEdge** [comment]
> is the issue still existing?

Yes, it seems to be. I got disconnected after ~20 minutes about 10 minutes ago.

**Comment by roygear** [comment]
I just wonder is there any information about Google not allowing the free tier to run Auto1111?

**Comment by Gamemaster2930** [comment]
> I just wonder is there any information about Google not allowing the free tier to run Auto1111?

https://twitter.com/thechrisperry/status/1649189902079381505

**Comment by norfuer** [comment]
And here I thought I was getting disconnected because I was trying to load a safetensor as my main model. Not sure if I'm glad it's not because I don't know how to use a safetensor model (works fine as lora), rather than Google just being Google...

**Comment by HaikenEdge** [comment]
I mean, technically, Colab TOS doesn't allow the running of remote web UIs, so technically, I think using Auto1111 is itself a TOS violation and they're just being nice enough to only soft ban users, instead of hard banning them completely.

**Comment by sahildeshpande** [comment]
Same. Got disconnected in 7 min

**Comment by Gamemaster2930** [comment]
> I mean, technically, Colab TOS doesn't allow the running of remote web UIs, so technically, I think using Auto1111 is itself a TOS violation and they're just being nice enough to only soft ban users, instead of hard banning them completely.

That's true. Webuis are now against TOS if you don't have a Pro subscription. But they are doing a mistake. I would let users use webuis but limit their runtime to 2-3 hours instead of 6. It would lower electricity bill and motivate users to buy Pro. But who am I to judge...

**Comment by HaikenEdge** [comment]
> > I mean, technically, Colab TOS doesn't allow the running of remote web UIs, so technically, I think using Auto1111 is itself a TOS violation and they're just being nice enough to only soft ban users, instead of hard banning them completely.
> 
> That's true. Webuis are now against TOS if you don't have a Pro subscription. But they are doing a mistake. I would let users use webuis but limit their runtime to 2-3 hours instead of 6. It would lower electricity bill and motivate users to buy Pro. But who am I to judge...

I mean, I'd like to buy a pro subscription, but the $10 option only offers 100 compute units per month, and even the low end GPUs that are available to free users cost 1.5 CU an hour, with higher end GPUs costing more CUs. That means, using the cheapest possible GPU, in a bit under 67 hours, all the compute units will be gone, and that's not even really a week of use for a dedicated Automatic1111 user.

**Comment by sahildeshpande** [comment]
But this is definitely targeted on Stable Diffusion use. I'm sure you can use colab for other projects. Someone above commented that they could use it for Dreambooth training.

**Comment by HaikenEdge** [comment]
> But this is definitely targeted on Stable Diffusion use. I'm sure you can use colab for other projects. Someone above commented that they could use it for Dreambooth training.

According to a dev on reddit, it specifically targets webui use; the dev said that it wouldn't affect a user running SD via command line.

**Comment by Archon332** [comment]
> 
Not 6, but 3.5-4 hours already. For me and my bro at least.

**Comment by Archon332** [comment]
> > I mean, technically, Colab TOS doesn't allow the running of remote web UIs, so technically, I think using Auto1111 is itself a TOS violation and they're just being nice enough to only soft ban users, instead of hard banning them completely.
> 
> That's true. Webuis are now against TOS if you don't have a Pro subscription. But they are doing a mistake. I would let users use webuis but limit their runtime to 2-3 hours instead of 6. It would lower electricity bill and motivate users to buy Pro. But who am I to judge...

Not 6, but 3.5-4 hours already. For me and my bro at least.

**Comment by sahildeshpande** [comment]
> > But this is definitely targeted on Stable Diffusion use. I'm sure you can use colab for other projects. Someone above commented that they could use it for Dreambooth training.
> 
> According to a dev on reddit, it specifically targets webui use; the dev said that it wouldn't affect a user running SD via command line.

Yea I think we all are quite aware of that. This issue is known for a while but free accounts could still use it all these days. Apparently this is a new issue since a few hours where colab is automatically getting disconnected.

**Comment by HaikenEdge** [comment]
I seem to be alternating between sessions in the 7-8 minute range to the 18-20 minute range. I mean, I still run out of resources after 3-4 hours, but now I've really got to babysit it and restart it as soon as the execution failure message pops up.

**Comment by sahildeshpande** [comment]
> I seem to be alternating between sessions in the 7-8 minute range to the 18-20 minute range. I mean, I still run out of resources after 3-4 hours, but now I've really got to babysit it and restart it as soon as the execution failure message pops up.

Is there a quick way to restart this colab without going through all steps?

**Comment by Gamemaster2930** [comment]
> I seem to be alternating between sessions in the 7-8 minute range to the 18-20 minute range. I mean, I still run out of resources after 3-4 hours, but now I've really got to babysit it and restart it as soon as the execution failure message pops up.

You just need to restart cell? It disconnects me from the whole session and I need to restart everything one by one

**Comment by HaikenEdge** [comment]
> > I seem to be alternating between sessions in the 7-8 minute range to the 18-20 minute range. I mean, I still run out of resources after 3-4 hours, but now I've really got to babysit it and restart it as soon as the execution failure message pops up.
> 
> Is there a quick way to restart this colab without going through all steps?

I wish there was.



> > I seem to be alternating between sessions in the 7-8 minute range to the 18-20 minute range. I mean, I still run out of resources after 3-4 hours, but now I've really got to babysit it and restart it as soon as the execution failure message pops up.
> 
> You just need to restart cell? It disconnects me from the whole session and I need to restart everything one by one

No, I need to restart everything too.

**Comment by XacDinh** [comment]
My webui took 10 minutes to start (100gb of models), so basically a death sentence to me. It would be 15 if count all cells.

**Comment by norfuer** [comment]
7 minutes sounds about right, yeah... Sometimes 18. Basically enough to get in one or two images, or one batch of 12.

**Comment by SadSAYA** [comment]
It automatically disconnects every 14 minutes and I have to restart everything

**Comment by jtran-developer** [comment]
I can keep one instance up, but a second instance gets killed immediately.  I gen way too much to pay that hourly rate and I really don't want to buy those extremely overpriced nvidia gpu.  This is unfortunate.

**Comment by sahildeshpande** [comment]
> I can keep one instance up, but a second instance gets killed immediately. I gen way too much to pay that hourly rate and I really don't want to buy those extremely overpriced nvidia gpu. This is unfortunate.

You can keep one instance up on a free account or a pro?

**Comment by sahildeshpande** [comment]
> > > I can keep one instance up, but a second instance gets killed immediately. I gen way too much to pay that hourly rate and I really don't want to buy those extremely overpriced nvidia gpu. This is unfortunate.
> > 
> > 
> > You can keep one instance up on a free account or a pro?
> 
> free. sounds like i'm luckier than most at the moment.

You are. Now I am getting disconnected even before it starts :P

**Comment by jtran-developer** [comment]
I haven't tested this, but the one I don't have a problem keeping connected is my main account that I have a lot of other activities on.  The ones I'm having problems staying connected are throw away accounts.  What kind of account are you connecting with?

**Comment by Archon332** [comment]
> I haven't tested this, but the one I don't have a problem keeping connected is my main account that I have a lot of other activities on. The ones I'm having problems staying connected are throw away accounts. What kind of account are you connecting with?

My main account.

**Comment by jtran-developer** [comment]
There goes that idea then.  Maybe there's a lottery and I just got lucky.  Who knows.

**Comment by cmatrix7777** [comment]
A Google Drive error has occurred.

**Comment by Gryphan1** [comment]
same

**Comment by Light-Danube** [comment]
Same.

**Comment by gerry1268** [comment]
Anyone know of an alternative paid for solution that will accept PayPal?

**Comment by 1111dontworryaboutit** [comment]
Wellll I guess that's it with the free usage. This created issue is somewhat of a relief, as this is happening constantly since yesterday no matter what account I'm using.

**Comment by jtran-developer** [comment]
So what's the play here?  Do we pay paperspace the 8 dollars and hope one of their free machines is available?  Do we cave and buy one of those ridiculously overpriced nvidia GPUs?  Something else?

**Comment by Kirika-chan** [comment]
i just hope we can still use colab for auto1111, paperspace machice kept being inaccessible for me

**Comment by Saruvuk** [comment]
> why we don't use Kaggle? it's free!!

They flat-out banned NSFW content.

**Comment by sajjadalis** [comment]
Colab is done. webui is [not coming back](https://twitter.com/thechrisperry/status/1649456437905727488) as free. The good days to test and generate images at high speed for free are over.

Paperspace free is too slow > when available. It takes 6 and a half minutes to generate a single 2x highres 1080 x 1350 image with DPM 2M Karras sampler (SDE takes almost double the time). The funny part is that my 5-year+ old laptop with GTX 1060 6GB takes 15 seconds less than Paperspace to create 2x hires image with the same settings, without xformers, optimization settings are set to low and model CUDA running at half otherwise Pytorch throws CUDA out of memory error.

**Comment by DanoGL** [comment]
Paperspace or Runpod? Which is better for a 1 hour long session every day?

> If you're planning to use paid plans, avoid google, go Runpod or Paperspace, I have the same notebooks there, they are way faster than colab's.
> 
> Runpod : https://www.runpod.io/console/gpu-browse?template=runpod-stable-unified
> 
> Paperspace : https://console.paperspace.com/github/TheLastBen/PPS?machine=Free-GPU

**Comment by Ansonii11** [comment]
> Ya usa Paperspace, pero el plan gratuito funciona más lento y puede usar modelos grandes con este plan. Desafortunadamente, no puedo usar planes pagos porque Visa, Mastercard y Paypal no funcionan en mi país.
And how do I use camenduru for example in that?

**Comment by editorpabs** [comment]
I have read everything here. I think have a solution but I need your help. As read we can use SD but not in webui. So it's like it was at the beginning of SD. No user interface. Here comes the question, does anyone have a colab that works without a user interface?

**Comment by TheLastBen** [comment]
> Paperspace or Runpod? Which is better for a 1 hour long session every day?

with Runpod you can have a 1 hour session for 0.20$ with the rtx 3070 which is fairly fast

**Comment by DanoGL** [comment]
> 

Thank you so much Ben 🫂❤️

**Comment by DanoGL** [comment]
> > Paperspace or Runpod? Which is better for a 1 hour long session every day?
> 
> with Runpod you can have a 1 hour session for 0.20$ with the rtx 3070 which is fairly fast

Thank you so much Ben ❤️🫂
