### ISSUE TITLE
Model download/load issue

### ISSUE THREAD

**Issue by Light-Danube** [TheLastBen/fast-stable-diffusion#2108]
Using google colab version, running "Model/download" cell gives next issue:
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-2-2cfad68da792>](https://localhost:8080/#) in <cell line: 148>()
    160 
    161 elif MODEL_LINK != "":
--> 162   gdrv='/content/gdrive/'+mainpth+'/sd/stable-diffusion-'+blasphemy+'/models/Stable-diffusion'
    163   tmp="/content"
    164   pth=tmp if Use_temp_storage else gdrv

NameError: name 'mainpth' is not defined

I'm using using MODEL_LINK option, models is .safetensors, using temp_storage & safetensors on.

**Comment by TheLastBen** [comment]
run the first cell

**Comment by Light-Danube** [comment]
Thanks, now it works. However running last cell with Cloudfare on gives next error:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by TheLastBen** [comment]
remove the sd folder and use the latest notebook
