### ISSUE TITLE
Paperspace Quadro M4000 xformers?

### ISSUE THREAD

**Issue by Gamemaster2930** [TheLastBen/fast-stable-diffusion#2110]
Hello, is there any way to enable xformers for Paperspace's Quadro M4000? If so, how? Or is it already enabled? Thanks for info

**Comment by TheLastBen** [comment]
it is already enabled in Paperspace

**Comment by Gamemaster2930** [comment]
> it is already enabled in Paperspace

Okay, thanks for info
