### ISSUE TITLE
Stable Diffusion UI Session (on Gradient Paperspace) Randomly Times Out

### ISSUE THREAD

**Issue by Bez22** [TheLastBen/fast-stable-diffusion#2118]
I have been using Stable Diffusion on Gradient Paperspace for a while now, primarily for the img2img function and ControlNet. However, I have noticed that the UI randomly times out after a small number of image generations, so that I have to either reload the page or restart the server completely. I'm confident that there is a solution to this issue, and I'm reaching out to the community for help.

If anyone has experienced a similar problem and found a solution, please share it with me. I'm open to any suggestions and advice on how to resolve this issue.
Thank you in advance for your help.

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by lgooders** [comment]
I was using ngrok today and it was still timing out/disconnecting.  All good now?

**Comment by Archon332** [comment]
> I'll check it out
> 
> EDIT : I added ngrok, use the latest notebook and use your ngrok token

Used latest notebook, but there is still error if the first cell. 
![image](https://user-images.githubusercontent.com/119755850/236526398-cfbf00a8-a031-40b7-a42e-86ccc30c920b.png)

**Comment by TheLastBen** [comment]
open the notebook inside the folder "latest_notebooks"

**Comment by Saruvuk** [comment]
@TheLastBen

PaperSpace is actively disabling accounts because of the ngrok implementation --- even if you don't use it.

**Comment by brunojorgemartinho** [comment]
Not working :\

**Comment by TheLastBen** [comment]
Any source for that claim ?

**Comment by Bez22** [comment]
> @TheLastBen
> 
> PaperSpace is actively deactivating accounts because of the ngrok implementation --- even if you don't use it.

Can you confirm this in some way

**Comment by Saruvuk** [comment]
> @Saruvuk Any source for that claim ?

I myself. That's the reason they gave me. I'm still trying to get my account back.

**Comment by TheLastBen** [comment]
@Saruvuk it won't happen if it's used for SD

**Comment by Archon332** [comment]
Mine account was closed too about 1 hour ago after I tried to use ngrok token.

> > @Saruvuk Any source for that claim ?
> 
> I myself. That's the reason they gave me. I'm still trying to get my account back.

**Comment by Bez22** [comment]
The Automatic111 update seems to have permanently fixed this problem for me so I'm closing this issue now.
