### ISSUE TITLE
Downloading VAE to temporary storage on Paperspace makes model disappear in the webui

### ISSUE THREAD

**Issue by Gamemaster2930** [TheLastBen/fast-stable-diffusion#2121]
Hello, I have a problem. If I download a VAE to my model in temporary Paperspace's storage, the model "disappears" and can't be used in the webui (It's not in the dropdown men). What can I do about this issue? Thanks for help

**Comment by TheLastBen** [comment]
the vae should be put in the right folder as far as I know

**Comment by Gamemaster2930** [comment]
> the vae should be put in the right folder as far as I know

I put it right beside the model. It always worked for me, but now it doesn't. Maybe I'll try to put it into VAE folder

**Comment by Gamemaster2930** [comment]
Okay, downloading it to VAE folder works. Seems like my problem has been solved. Thanks anyway
