### ISSUE TITLE
Problem in the Model download cell of Paperspace.

### ISSUE THREAD

**Issue by Archon332** [TheLastBen/fast-stable-diffusion#2134]
4 hours before all worked good. Don't know, why this happened.
![image](https://user-images.githubusercontent.com/119755850/236963773-aa274398-8e62-43ac-b449-4a4cd7e8ba6e.png)

**Comment by Archon332** [comment]
Tried to add "!pip install gdown". Didn't solved.

**Comment by Archon332** [comment]
UI started to work when I switched machine. Don't know why, so, will not close until someone figure it out.

**Comment by TheLastBen** [comment]
did you run the first cell ?

**Comment by Archon332** [comment]
> did you run the first cell ?

Yes. First and second cell were done. But, the had been done much faster than ussual.
