### ISSUE TITLE
WebUI link doesn't show up when running the last cell in paperspace

### ISSUE THREAD

**Issue by hugo-k-m** [TheLastBen/fast-stable-diffusion#2145]
ControlNet v1.1.150
ControlNet v1.1.150
Calculating sha256 for /models/model.safetensors: f6cbc1d7302d08737dd4686c0a6455e2c2918d4c2ea09d7af1cdf877b9a864cc
Loading weights [f6cbc1d730] from /models/model.safetensors
Creating model from config: /notebooks/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0): 
Model loaded in 14.0s (calculate hash: 7.2s, create model: 1.1s, apply weights to model: 1.7s, apply half(): 1.4s, load VAE: 2.2s, move model to device: 0.5s).

This cell shows running and after waiting for a long time I'm not getting the webui link. Yesterday it worked fine for me but today not getting the link and the cell shows its running....Any idea what's the issue here ? Please help

_Originally posted by @HelpANewbie in https://github.com/TheLastBen/fast-stable-diffusion/issues/2132#issuecomment-1541795779_

**Comment by Litva320** [comment]
I have the same problem

**Comment by moooosky** [comment]
the same problem in paperspace

**Comment by yaroslavvaran** [comment]
Same

**Comment by hanzheg** [comment]
same

**Comment by okeymmloo** [comment]
same

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by KeeganEad** [comment]
Suddenty getting same problem but in Google Colab.  Worked fine yesterday.   

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/26011894/f12f0cc2-11d1-40f6-91bd-54dc1054fc66)

Just hangs here.

**Comment by CoqueTornado** [comment]
also it happens the same with google colab, after this:

Model loaded in 29.1s (calculate hash: 7.5s, load weights from disk: 11.4s, create model: 5.5s, apply weights to model: 2.9s, apply half(): 1.0s, move model to device: 0.7s).
*Deforum ControlNet support: enabled*

nothing else appears. No link.

**Comment by hanzheg** [comment]
I chose Cloudflare_Tunnel and it worked

**Comment by KeeganEad** [comment]
It seems to have been resolved!

**Comment by hugo-k-m** [comment]
Yes, the server seems to be operational again. I'll close the issue now.
