### ISSUE TITLE
Paperspace Last Cell Error

### ISSUE THREAD

**Issue by Wyeel** [TheLastBen/fast-stable-diffusion#2152]
Hello, I'm getting this error on Paperspace when trying to run the last cell. I've tried restarting the machine and changing it as well to no avail:

TypeError                                 Traceback (most recent call last)
Cell In [7], line 13
      7 Ngrok_token = ""
      9 # Offers better gradio responsivity, get your token here https://dashboard.ngrok.com/get-started/your-authtoken
     10 
     11 
     12 #-----------------
---> 13 configf=sdui(User, Password, Ngrok_token, model) if 'model' in locals() else sdui(User, Password, Ngrok_token, "")
     14 get_ipython().system('python /notebooks/sd/stable-diffusion-webui/webui.py $configf')

TypeError: sdui() takes 3 positional arguments but 4 were given

**Comment by TheLastBen** [comment]
use the latest notebook by copying it from the folder "latest_notebooks" to the main workspace (overwrite existing)

**Comment by Wyeel** [comment]
I couldn't copy overwrite as it just kept saying error similar name. Did some renaming and just used the new notebook and works fine, thanks!

**Comment by TheLastBen** [comment]
you can simply remove the old notebooks and copy the new ones
