### ISSUE TITLE
Loading ControlNet models in the Paperspace Gradient Note

### ISSUE THREAD

**Issue by TintaViva** [TheLastBen/fast-stable-diffusion#2167]
Hi
Can I load ControlNet models manually in the Paperspace Gradient Note?
If i upload the model to the models folder in the ControlNet webui folder, will it work?
I´m having an error everytime I try to load a model at the ControlNet cell and I don´t want to load all the models for space saving.

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/120289853/81262dc7-dc6d-4011-a020-30e67f1249ba)

**Comment by TheLastBen** [comment]
you don't write the name of the model, just input the number :

1 for canny, 2 for depth, 3 for HED, it's all in the comment in the cell

**Comment by TintaViva** [comment]
> you don't write the name of the model, just input the number :
> 
> 1 for canny, 2 for depth, 3 for HED, it's all in the comment in the cell

Thank you for your help and patience
