### ISSUE TITLE
MODEL NOT LOADING In PaperSpace 

### ISSUE THREAD

**Issue by HelpANewbie** [TheLastBen/fast-stable-diffusion#2168]
I'm getting the below error in the Model Load cell - It was working fine yesterday - I have checked the link and the permissions too - No clue why it isn't getting access :(

Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

**Comment by TheLastBen** [comment]
that's google drive putting limits on the file, the workaround is to duplicate it in your gdrive, remove the old one, get the link from the fresh copied file

**Comment by HelpANewbie** [comment]
@TheLastBen Thanks Ben...That worked :)

**Comment by TheLastBen** [comment]
great!
