### ISSUE TITLE
Notebook throws errors. Multiple fixes tried.

### ISSUE THREAD

**Issue by bluefuzzball** [TheLastBen/fast-stable-diffusion#2176]
Good evening! I'm a Collab Pro user and for the last week and a half or so I haven't been able to use: 

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

I run everything in order and got: "File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module> from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir ModuleNotFoundError: No module named 'modules.paths_internal'"

So I went looking for solutions. I tried renaming sd to sd-old then puttings my loras and such back. Same error. Then I clicked latest working commit and re ran everything and got a new error: "AttributeError: module 'gradio.components' has no attribute 'TempFileManager'"

So looking for solutions I tried renaming sd again and running again. Still one of those two errors based on whether or not I used latest working commit. 

Stumbling around I found that Gradio might be the issue so I installed ngrok and verified it working on my machine. I put the token in "start stable diffusion" and get the same errors. Module error if latest commit is unchecked, and tempfilemanager if it is checked. So ngrok didn't seem to make a difference. I'm at a loss for what to do. 

Help with this would be greatly appreciated.

**Comment by bluefuzzball** [comment]
> try running the notebook without the first cell

I did this. I was able to get a gradio link without ngrok. The only problem being that files are all deleted whenever the session ends rather than getting stored in my google drive. Also all the check points and loras and such I store there I can't access. 

Knowing that it runs without the first cell is good though. What action does that mean I need to take to make it function once more from my google drive?

**Comment by bluefuzzball** [comment]
This time I totally deleted all of SD from my gdrive and redid the install. Ran without ngrok or latest commit and it's working again. Simply renaming wasn't enough. So my issue is resolved. Let us know if that works for you Jowe79.

**Comment by Jowe79** [comment]
Is recommended in the notbook install all models in 2 sections of control net? (20GB) can be this the origin of the problem? Or are problems about ngrok o gradio or the code itself of notebook?
Thanks

**Comment by bluefuzzball** [comment]
> Is recommended in the notbook install all models in 2 sections of control net? (20GB) can be this the origin of the problem? Or are problems about ngrok o gradio or the code itself of notebook? Thanks

You'll download the control net stuff if you want to use a control net. There are plenty of tutorials on youtube but it's much more advanced than just prompting. I don't download them because I don't know how to use them yet. 

The problem seemed to be that, unless you did a total reinstall, the bad files would persist. It was in the automatic1111 and requirements section where the files went wrong it seems.
