### ISSUE TITLE
Won't import all instance images

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2181]
Can someone help me out with this?I have successfully created several models, but suddenly today, dreambooth won't read in all my instance images.  This is the same folder I used to train another model with a difference base model so it has read these images in the past (and they are all cropped to squares).  Sometimes it gets to 57, sometimes only 37 and then I get this error message:

error                                     Traceback (most recent call last)
[<ipython-input-13-f6c3db40a532>](https://jti7armqt9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230516-060150-RC01_532530302#) in <cell line: 54>()
     66       width, height = file.size
     67       if file.size !=(Crop_size, Crop_size):
---> 68         image=crop_image(file, Crop_size)
     69         if extension.upper()=="JPG" or extension.upper()=="jpg":
     70             image[0] = image[0].convert("RGB")

2 frames
[/content/smart_crop.py](https://jti7armqt9-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230516-060150-RC01_532530302#) in image_face_points(im, settings)
     56 
     57       np_im = np.array(im)
---> 58       gray = cv2.cvtColor(np_im, cv2.COLOR_BGR2GRAY)
     59 
     60       tries = [

error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

**Comment by TheLastBen** [comment]
try to find which image is causing this issue

**Comment by mdlieber99** [comment]
Is there a way to do this?  It stops at different places in different attempts.  Do you know what I should be looking for?

**Comment by TheLastBen** [comment]
are your images cropped ?

**Comment by mdlieber99** [comment]
I'm using 180 images and the error always comes in the first 60.  I renumbered them so the original first 60 come at the end now and I still got an error at image 44

**Comment by mdlieber99** [comment]
Am currently running a new model with different images and it seems to work fine.  Can't figure out what is wrong with the one set that isn't working (but that worked with the exact same files last week)

**Comment by mdlieber99** [comment]
I just tried it again and it stopped on image 60 so I took out images 59, 60, and 61 and it still stopped on image 60 the next time (even though these were different images)

**Comment by TheLastBen** [comment]
try disabling "smart_crop"

**Comment by TheLastBen** [comment]
great!
