### ISSUE TITLE
Paperspace - Unable to download a model to temporary storage

### ISSUE THREAD

**Issue by Gamemaster2930** [TheLastBen/fast-stable-diffusion#2182]
Hello, I am having an issue with downloading a custom model from civitai to temporary storage. Everything worked correctly but after Paperspace's outage (I guess they've updated something) it gives me this error: 

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [2], line 27
     21 Temporary_Storage = True
     23 # Download the model to a temporary storage, bigger capacity but will be removed at session shutdown.
     24 
     25 
     26 #--------------------
---> 27 model=mdl(Original_Model_Version, Path_to_MODEL, MODEL_LINK, safetensors, Temporary_Storage)

NameError: name 'Original_Model_Version' is not defined

I guess that the notebook will require an update, not sure where tho. Thanks

**Comment by TheLastBen** [comment]
you'll always find the latest notebooks inside the folder "latest_notebooks"
