### ISSUE TITLE
[BUG] 0 images in this directory

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#219]
Image Browser doesn't work. 
It says "0 images in this directory. Loaded 0 images during 2022/10/24 - 2022/10/24, divided into 1 pages"
("Image Browser" is the “history” function before the update)

And auto1111 release a new extension named "aesthetic-gradients", it doesn't work, too.

**Comment by TheLastBen** [comment]
did you fix it ?

**Comment by tsound97** [comment]
Yes, auto1111 has just update the extension. The "aesthetic-gradients" works perfectly!
However, when using "Image Browser", you need to copy the directory(txt2img,img2img,etc) to the custom fold, other options don't work. I'll respond to the author of this extension later.
![BFBD_FKQ4%Z82CPY_1H(97R](https://user-images.githubusercontent.com/112967097/197506261-15f2dcc6-3cef-446f-8941-36df2bf5b5e4.png)
