### ISSUE TITLE
Problem with Paperspace. No module named "torch."

### ISSUE THREAD

**Issue by Archon332** [TheLastBen/fast-stable-diffusion#2190]
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/119755850/c3a1c3e1-d02d-42dd-8840-7da932bf3550)

Tried to add ''import torch'' in mainpapersapceA1111.py file, but this file changes but whenever you run the first cell.

**Comment by TheLastBen** [comment]
Restart the machine and try again
