### ISSUE TITLE
No idea how to use the new model on local

### ISSUE THREAD

**Issue by liangwei191** [TheLastBen/fast-stable-diffusion#22]
I've successfully run the new model on colab.But have no idea how to grab some ckpt from generated files.
Do you have any tutorial for doing that?Thanks again.

**Comment by TheLastBen** [comment]
I will soon add a colab that will let you use the trained model easily (not in ckpt, in diffusers)

**Comment by Stupack** [comment]
> 

Hi, any directions on how to generate a ckpt file to use with A1111? Thanks.

**Comment by TheLastBen** [comment]
so far, there is no clear way to convert a diffusers model into a ckpt

**Comment by 1blackbar** [comment]
You can kinda do that already by modifying dreambooth notebook , it doesnt have  a selector, i have a buynch of folders with models on shared google drives and id like to be able to select/swap them in webui somehow if youre gonna make new colab just for this.

**Comment by liangwei191** [comment]
I tried to run the last section very first time.But got the error like there is no install any all.
I dont find there is such files in the gdisk.But acutually it can run if start from beginning.

sed: can't read /content/interface.py: No such file or directory
python3: can't open file '/content/interface.py': [Errno 2] No such file or directory

Was it because of files only generated on cache and cant run again after stops

**Comment by TheLastBen** [comment]
You can't run directly the last cell, you need to install the dependencies first from the top cells
