### ISSUE TITLE
"ckpt at every n step" broken

### ISSUE THREAD

**Issue by giteeeeee** [TheLastBen/fast-stable-diffusion#220]
The dreambooth colab is dumping ckpt of diff N step with exactly the same hash:

![New Project (2)](https://user-images.githubusercontent.com/89521447/197453495-598276dd-d135-402d-94db-afb2cfa63ecd.jpg)

This simple test model was trained using 600 steps. One dump at every 200 steps. 

But the result of the last step ckpt (ay_step-600.ckpt) looks different than that of the final output (ay.ckpt):

![New Project (1) (1)](https://user-images.githubusercontent.com/89521447/197456217-0848f34f-1c2e-432a-80de-ca8be81e027a.png)

Another things is that although each "ay_step_N" has the same hash (828b131a), they all generate slightly different images.

Above is a simple test done using the default model just to demonstrate. I was able to  reproduce this problem with other custom models trained at higher steps.

In terms of the result, the final dump i.e. xxx.cpkt always work, resembling the training images. But the interval ckpt (including one dumped at the last step) always give very different looking result.

**Comment by TheLastBen** [comment]
They are supposed to give different results, try saving at higher steps to notice the similarly

**Comment by giteeeeee** [comment]
> ifferent results, try saving

But shouldn't the last step "name_step-N.ckpt" be equivalent to the final "name.ckpt"? I've done training using 2000 steps and the two always look vastly different.

**Comment by TheLastBen** [comment]
Yep, the hash not changing means the script dumps the original model everytime

**Comment by TheLastBen** [comment]
I tried a fixed, try again and let me if it works

**Comment by giteeeeee** [comment]
> I tried a fixed, try again and let me if it works

It now works:

![234](https://user-images.githubusercontent.com/89521447/197502810-5de4ed59-a7dc-469c-adb4-e45f4a46d696.jpg)

Each cktp now produces images similar to the training images. The final cktp produces the same image with that of the last step cktp.

Black magic :D
