### ISSUE TITLE
Invisible watermarks?

### ISSUE THREAD

**Issue by AgavaBlack** [TheLastBen/fast-stable-diffusion#2202]
Does it implement invisible watermarks into the output images? If yes, is there a way to turn it off? I remember there used to be an option months ago. Asking purely for learning purposes.

**Comment by EleVicted** [comment]
There was an option for this, but I'm not seeing it in the most recent version. Either the watermarking is removed entirely or stuck on by default. :/

**Comment by chalab23** [comment]
> There was an option for this, but I'm not seeing it in the most recent version. Either the watermarking is removed entirely or stuck on by default. :/

It was never implemented in the first place https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8847
