### ISSUE TITLE
ModuleNotFoundError: No module named 'tomesd' (Runpod)

### ISSUE THREAD

**Issue by dazaibsd** [TheLastBen/fast-stable-diffusion#2211]
Got this error in the last cell on Runpod

Traceback (most recent call last):
  File "/workspace/sd/stable-diffusion-webui/webui.py", line 49, in <module>
    from modules import shared, sd_samplers, upscaler, extensions, localization, ui_tempdir, ui_extra_networks, config_states
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers.py", line 1, in <module>
    from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_compvis.py", line 9, in <module>
    from modules import sd_samplers_common, prompt_parser, shared
  File "/workspace/sd/stable-diffusion-webui/modules/sd_samplers_common.py", line 5, in <module>
    from modules import devices, processing, images, sd_vae_approx, sd_samplers, sd_vae_taesd
  File "/workspace/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/workspace/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    import modules.textual_inversion.textual_inversion
  File "/workspace/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 17, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers, sd_hijack_checkpoint
  File "/workspace/sd/stable-diffusion-webui/modules/sd_models.py", line 20, in <module>
    import tomesd
ModuleNotFoundError: No module named 'tomesd'

**Comment by hey12344321** [comment]
sameeee!!

**Comment by wknudsen** [comment]
and same

**Comment by RebelCat90** [comment]
The exact same thing happens to me. Last night I was using it without problems, and now in the morning, I wanted to enter and it is with this error. I hope you can help.

Greetings from Mexico.

**Comment by chubbypillow93** [comment]
Same...I wonder what is happening

**Comment by TheMindExpansionNetwork** [comment]
same


jeeeeez we all addicted

**Comment by porcelanovva** [comment]
same on colab

**Comment by TheMindExpansionNetwork** [comment]
ohhhhhhhhhh my friends

**Comment by TheMindExpansionNetwork** [comment]
I found a work around

you  need to do this at least in runpod guessing collab same

go to the plus here 

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/77267159/499e959e-5cb2-4b01-b0b8-b4790be81221)

then 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/77267159/01c11f10-de9e-4343-b528-55378c5529ec)

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/77267159/75ceaab5-827d-4796-91e5-cf202453644e)


Then use this command

pip install tomesd

Should be good

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/77267159/5109708d-731b-4239-8ddc-ca256e6e7e82)

**Comment by Maxadox** [comment]
Newb alert: Can someone tell me where to do this exactly in a google Colab? thanks

**Comment by chubbypillow93** [comment]
> Newb alert: Can someone tell me where to do this exactly in a google Colab? thanks

Hi, I'm not sure if I did this correctly but it worked: I inserted `!pip install tomesd` into the code of requirement, and run it, then when I run the start SD part it went through. Hope this helps!

**Comment by RebelCat90** [comment]
> !pip install tomesd

Hello, my friend. Thank you very much for your help. I did the same thing you mention and it worked for me. You are my new hero.

Greetings from Mexico.

**Comment by Maxadox** [comment]
didn't work for me, I added !pip install tomesd in the code of the requirement and  my error changed to
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'

**Comment by TheLastBen** [comment]
new A1111 update, will fix shortly

**Comment by TheLastBen** [comment]
@Maxadox you need a fresh sd folder

**Comment by RebelCat90** [comment]
> didn't work for me, I added !pip install tomesd in the code of the requirement and my error changed to:
> 
> Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in from modules import paths, timer, import_hook, errors File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir ModuleNotFoundError: No module named 'modules.paths_internal'

I before doing the solution you mentioned, I deleted the SD folder from drive, reinstalled everything with that solution and it worked for me.

**Comment by Maxadox** [comment]
All Right, up and running :) , thank you all

**Comment by Bigchicken166** [comment]
For me is still not working. Im quite new in these. Where do you install `!pip install tomesd`? I added in requirement but it didn't work for me. Can anyone help?

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/128165875/0bc81e0c-4a0c-40ce-9584-437cb6ff77a2)

**Comment by TheLastBen** [comment]
> For me is still not working. Im quite new in these. Where do you install `!pip install tomesd`? I added in requirement but it didn't work for me. Can anyone help?

Just restart the pod and it will work

**Comment by 4bn3r** [comment]
solution for me in google colab and google drive

![asi](https://github.com/TheLastBen/fast-stable-diffusion/assets/133182673/6420e293-d223-4525-a300-fc7084d48f15)

solution
![asi2](https://github.com/TheLastBen/fast-stable-diffusion/assets/133182673/b0944019-1b92-4fa5-9a3f-2ecfcba05e98)

**Comment by Olymmpia** [comment]
Thank you. I added !pip install tomesd in the requirements cell. It worked

**Comment by TheLastBen** [comment]
use the latest notebook, it has been fixed a day ago

**Comment by Olymmpia** [comment]
> use the latest notebook, it has been fixed a day ago

Thank you! Can you, please, answer to dummie, what to do, where do I get the latest notebook? :)))

**Comment by wangming688** [comment]
Thank you!

**Comment by Torcelllo** [comment]
My tomesd is already downloaded, but when line 1 of the C:\stable-diffusion-webui\extensions\sd-webui-tome\scripts\tome.py asks to "import tomesd" says there is "N module named tomesd"

**Comment by Torcelllo** [comment]
Says its already installed!

**Comment by TheLastBen** [comment]
make sure it's installed in the same venv as A1111
