### ISSUE TITLE
deforum controlnet not loading

### ISSUE THREAD

**Issue by rickyars** [TheLastBen/fast-stable-diffusion#2218]
hello - until yesterday i was able to use controlnet in deforum. now when i enable the "preprocessor" dropdown doesn't populate. all i see is counter that continuous increases and the gradio spinning diamonds. halp!

**Comment by memewizards** [comment]
If you are using brave browser try disabling brave shield for the site.

**Comment by rickyars** [comment]
@memewizards i think the issue occurs when i try to use the dropdown before the form has fully loaded.
