### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'ui_debug_mode'

### ISSUE THREAD

**Issue by alexisargyris** [TheLastBen/fast-stable-diffusion#222]
Yesterday it worked with no problems. Today I get the error mentioned above. I get regardless if I update the repo or not. What should I do?

**Comment by TheLastBen** [comment]
remove the folder "sd" from your gdrive and do a clean run with the latest colab

**Comment by alexisargyris** [comment]
Worked! Thanks!
