### ISSUE TITLE
RAM leak

### ISSUE THREAD

**Issue by Toshik-One** [TheLastBen/fast-stable-diffusion#2228]
How to reduce the consumption of RAM? When working, it uses too much RAM and, if it is exceeded, disables the cell in colab. 
In the console output, the console outputs this :  ^C
![Скриншот 02-06-2023 21_25_55](https://github.com/TheLastBen/fast-stable-diffusion/assets/120157367/9db492ab-5d5f-482e-abc6-6562601762bd)

**Comment by TheLastBen** [comment]
Which notebook and what is the size of the model used ?

**Comment by Toshik-One** [comment]
> 

your notebook  
model size 3.4 GB
