### ISSUE TITLE
runpod error when loading model using a google drive link

### ISSUE THREAD

**Issue by bayoumedic** [TheLastBen/fast-stable-diffusion#2234]
NameError                                 Traceback (most recent call last)
Cell In[3], line 18
     12 MODEL_LINK = "https://drive.google.com/xxxxxxxxxxxxx"
     14 # A direct link to a Model or a shared gdrive link.
     15 
     16 
     17 #--------------------
---> 18 model=mdl(Original_Model_Version, Path_to_MODEL, MODEL_LINK)

File /workspace/mainrunpodA1111.py:250, in mdl(Original_Model_Version, Path_to_MODEL, MODEL_LINK)
    248    dwn(MODEL_LINK, model, 'Downloading the custom model')
    249 elif src=='gdrive':
--> 250    modelname=get_name(MODEL_LINK, True)
    251    model=f'/workspace/sd/stable-diffusion-webui/models/Stable-diffusion/{modelname}'
    252    gdown.download(url=MODEL_LINK, output=model, quiet=False, fuzzy=True)

File /workspace/mainrunpodA1111.py:228, in mdl.<locals>.get_name(url, gdrive)
    226 headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36"}
    227 res = requests.session().get('https://drive.google.com/uc?id=xxxxxxxxxxx', headers=headers, stream=True, verify=True)
--> 228 content_disposition = six.moves.urllib_parse.unquote(res.headers["Content-Disposition"])
    229 filenm = re.search(r"filename\*=UTF-8''(.*)", content_disposition).groups()[0].replace(os.path.sep, "_")
    230 return filenm

NameError: name 'six' is not defined

**Comment by TheLastBen** [comment]
will be fixed in a few minutes
