### ISSUE TITLE
Controlnet Installation Error

### ISSUE THREAD

**Issue by icaruschan** [TheLastBen/fast-stable-diffusion#2253]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
[<ipython-input-4-88abcbc2cc9c>](https://localhost:8080/#) in <cell line: 38>()
     36 Tile='https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth'
     37 
---> 38 with capture_output() as cap:
     39   get_ipython().run_line_magic('cd', '/content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/extensions')
     40   if not os.path.exists("sd-webui-controlnet"):

NameError: name 'capture_output' is not defined

**Comment by icaruschan** [comment]
I did that, everything will run at first smoothly but when I'll try using stable diffusion, Collab would stop going red, leaving me to reconnect again

After reconnecting and starting the whole process again, I'll get the above error

**Comment by TheLastBen** [comment]
@icaruschan free colab doesn't support sd anymore, so it will disconnect you after a few minutes everytime

**Comment by kelvin-zhao** [comment]
@TheLastBen  It seems to run, but controlnet doesn't seem to process, I get a black image every time. No errors otherwise.

**Comment by TheLastBen** [comment]
@kelvin-zhao find a good tutorial on the specific controlnet model you're using

**Comment by kelvin-zhao** [comment]
@TheLastBen it's running well on my local machine so I'm not sure why on collab's version it just gives a blank tile. =(

**Comment by TheLastBen** [comment]
@kelvin-zhao Are you using chrome or brave browser

**Comment by kelvin-zhao** [comment]
@TheLastBen it is indeed a brave browser issue, worked on firefox! 🙏🏻 thank you.

**Comment by TheLastBen** [comment]
great!
