### ISSUE TITLE
Any way to use SD-CN-Animation Plugin?

### ISSUE THREAD

**Issue by pdannell** [TheLastBen/fast-stable-diffusion#2257]
When running this plugin it gives the following error:
- ValueError: Need to enable queue to use generators.

Tried what I could find online as fixes to no avail.

**Comment by TheLastBen** [comment]
comment this line in the last cell : 
```
!sed -i 's@ui.create_ui().*@ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)@' /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/webui.py
```

**Comment by pdannell** [comment]
> comment this line in the last cell :
> 
> ```
> !sed -i 's@ui.create_ui().*@ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)@' /content/gdrive/$mainpth/sd/stable-diffusion-$blasphemy/webui.py
> ```


I can find that in the Google Collab version but not in the Paperspace one specifically.

**Comment by TheLastBen** [comment]
paperspace doesn't use the queue, so you need to check with SD-CN-Animation extension maker

**Comment by pdannell** [comment]
Thank you, closing this out.
