### ISSUE TITLE
"waiting" every minute on runpod

### ISSUE THREAD

**Issue by Polilup** [TheLastBen/fast-stable-diffusion#2265]
Hi, I'm new to this, I've used the A1111 runpod a few times, but only now am I getting this kind of problem. I just want to make something using lora and control net but this always ends up "waiting" and not making what I want. I use a pretty high GPU but still get this problem. I didn't get this problem before. Is there a solution to this problem?

![Screenshot (91)](https://github.com/TheLastBen/fast-stable-diffusion/assets/121802269/028bea64-698b-499c-8833-a071804c7d73)

**Comment by TheLastBen** [comment]
do you have a good internet connection ?

**Comment by Polilup** [comment]
I have a pretty good internet, but after trying other connections, I guess the problem is the connection...

Thanks for answering!
