### ISSUE TITLE
Freezes after generations

### ISSUE THREAD

**Issue by fractaltr33** [TheLastBen/fast-stable-diffusion#23]
Constant img freezes after generations, you have to reload the page every time, generally making the colab unusable. AUTOMATIC1111 doesn't solve this problem at all, hlky has reload buttons which help a lot, but it doesn't have scripts or negative prompts. It would be nice to somehow combine it. 
By the way, in the colab from Voldemort, the local port does not help. But it works in this colab https://colab.research.google.com/drive/1KeNq05lji7p-WDS2BL-86Z8Y9SluGng4. Perhaps this will help you in some way to improve colabs. Thanks.

**Comment by TheLastBen** [comment]
I will integrate the local tunnel, to avoid freezing, which is an issue Gradio should solve
