### ISSUE TITLE
Dynamic prompts not working in new notebook

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2303]
I switched to your new notebook (https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb#scrollTo=PjzwxTkPSPHf) and when the 'start stable diffusion' cell runs I get an error that says:

Installed dynamicprompts version (0.27.0) does not match the required version (0.25.2). Please update manually by running: /usr/bin/python3 -m pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.25.2'

Something like this happened with the previous notebook and there the solution for me was adding a cell before 'start stable diffusion' with just this command:

pip install 'dynamicprompts[attentiongrabber,magicprompt]==0.25.2'

But this time when I add that and it gets to 'start stable diffusion' I now get:

Failed reading extension data from Git repository (sd-dynamic-prompts)

Automatic1111 still runs, but it ignores all the {} that have the dynamic prompts and just treats all the options inside those brackets as things separated by commas (I think).

Do you have any idea how to get dynamic prompts working again?  They are a huge part of my workflow these days.

thanks

**Comment by TheLastBen** [comment]
remove the extension then reinstall it, or simply update it

**Comment by mdlieber99** [comment]
that worked - thanks!

**Comment by TheLastBen** [comment]
great!
