### ISSUE TITLE
Query and an issue - ROOP & multi-colab with GDrive

### ISSUE THREAD

**Issue by scorpi0n81** [TheLastBen/fast-stable-diffusion#2306]
Query 1 - I have installed ROOP extension (https://github.com/s0md3v/sd-webui-roop) and post restart webUI, it all just works fine however, post closing the colab session, once you run everything again - ROOP doesnt work anymore and starts to throw errors along with controlnet errors. if I delete the notebook and start fresh and then add roop again - all works fine -- super puzzled why it installs and works just once and then stops..

Query 2 - is it possible to configure 2 notebooks simultaneously and use? so 2 notebooks connected to same G Drive but each having their own settings and configurations? only reason is because of what is happening in query above with Roop extension.. was thinking instead of deleting and going over again, might be if i can keep 2 distinct notebooks but dont know how as it creates a single SD folder in Drive as a reference point.. 

thanks!

**Comment by TheLastBen** [comment]
I just added the dependencies required by roop, it should work fine now

**Comment by scorpi0n81** [comment]
> I just added the dependencies required by roop, it should work fine now

Woah - you my man just got blessings from the depth of my heart!! Thanks man! I shall try and confirm tomorrow if things work as expected post the fix you have performed.. cheers!

**Comment by vanillasaenz** [comment]
Amazing work TheLastBen, happens the same with [sd-webui-inpaint-anything](https://github.com/Uminosachi/sd-webui-inpaint-anything), can u do the fix ? https://github.com/Uminosachi/sd-webui-inpaint-anything please. Thanks!

**Comment by TheLastBen** [comment]
> Amazing work TheLastBen, happens the same with [sd-webui-inpaint-anything](https://github.com/Uminosachi/sd-webui-inpaint-anything), can u do the fix ? https://github.com/Uminosachi/sd-webui-inpaint-anything please. Thanks!

colab or runpod ?

**Comment by vanillasaenz** [comment]
colab

**Comment by vanillasaenz** [comment]
maybe cant do it, maybe this will help u.  well anyway, thank you very much. good weekend


Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
*** Failed reading extension data from Git repository (sd-webui-inpaint-anything)
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extensions.py", line 63, in do_read_info_from_repo
        commit = repo.head.commit
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 217, in _get_commit
        obj = self._get_object()
      File "/usr/local/lib/python3.10/dist-packages/git/refs/symbolic.py", line 210, in _get_object
        return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
      File "/usr/local/lib/python3.10/dist-packages/git/objects/base.py", line 85, in new_from_sha
        oinfo = repo.odb.info(sha1)
      File "/usr/local/lib/python3.10/dist-packages/git/db.py", line 43, in info
        hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/gitpython_hack.py", line 18, in get_object_header
        ret = subprocess.check_output(
      File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/usr/lib/python3.10/subprocess.py", line 505, in run
        stdout, stderr = process.communicate(input, timeout=timeout)
      File "/usr/lib/python3.10/subprocess.py", line 1154, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/usr/lib/python3.10/subprocess.py", line 2022, in _communicate
        self._check_timeout(endtime, orig_timeout, stdout, stderr)
      File "/usr/lib/python3.10/subprocess.py", line 1198, in _check_timeout
        raise TimeoutExpired(
    subprocess.TimeoutExpired: Command '['git', 'cat-file', '--batch-check']' timed out after 2 seconds

**Comment by TheLastBen** [comment]
this is a harmless msg, everything should work fine

**Comment by MrClueless936** [comment]
> Query 1 - I have installed ROOP extension (https://github.com/s0md3v/sd-webui-roop) and post restart webUI, it all just works fine however, post closing the colab session, once you run everything again - ROOP doesnt work anymore and starts to throw errors along with controlnet errors. if I delete the notebook and start fresh and then add roop again - all works fine -- super puzzled why it installs and works just once and then stops..

I am currently having the exact same issue on Colab with AfterDetailer (https://github.com/Bing-su/adetailer). However, my issue doesn't involve Controlnet. 

I first install AfterDetailer, check for updates, then apply and close UI. I then run last cell of the Colab again and it functions fine for that runtime. However, once I disconnect and delete runtime and then start fresh, I get errors and the extension won't work at all. I need to then delete the folder in my extensions, run again and install all over again. The error it throws says that the module ultralytics.py doesn't exist, even though it's actually in the folder.

Forgive me, I'm not really versed in coding much at all. Is this a similar issue regarding dependencies as mentioned above? Can this be fixed? Thanks for the help.

**Comment by TheLastBen** [comment]
@MrClueless936 for now you'll have to run this : 
`!pip install ultralytics pydantic`
I'll add the dependencies later to the preinstalled package

**Comment by MrClueless936** [comment]
@TheLastBen Thank you very much for the temporary workaround. Worked like a charm. I really appreciate that you provide resources like your Colab for everyone to use; it really helps someone like me with minimal coding experience and without my own powerful PC to be able to enjoy Stable Diffusion. Seriously, thanks for what you do!

**Comment by TheLastBen** [comment]
Glad to hear that

**Comment by BislanAshinov** [comment]
> I just added the dependencies required by roop, it should work fine now

Hi! 
The extension stopped working after the session was restarted. There are no errors, it just generates without extension. I tried to reinstall dependencies, tried to reinstall extension, but it still doesn't work.(( 
Do you have any idea why it doesn't work? ("Enable" is clicked =) )
