### ISSUE TITLE
is there a new pod update?

### ISSUE THREAD

**Issue by N3K00OO** [TheLastBen/fast-stable-diffusion#2317]
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/96883487/4e957d38-5c5a-4979-9074-be1d6b85e89a)

when i tried to copy and paste a safetensor file that i downloaded it would not let me instead it would just download the file, also the extract archive button is missing is this a runpod problem (been getting it on every pod) 

also the copy button is now delete

i have also tested it on other browsers and still the same 🤷

**Comment by TheLastBen** [comment]
I'm aware of the issue, working on it at the moment

**Comment by N3K00OO** [comment]
do you know whats cousing it?

**Comment by TheLastBen** [comment]
an update to the docker image, you can revert back by editing the pod and changing the version back  to 2.1.0, and adding the port 3000

**Comment by N3K00OO** [comment]
thanks :D
