### ISSUE TITLE
VAE commandline args equivalent in colab to apply to all models

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#232]
Following this guide: https://www.reddit.com/r/StableDiffusion/comments/yaknek/you_can_use_the_new_vae_on_old_models_as_well_for/

Looks like --vae-path could be applied to colab if defaulted in webui.bat? Or added as a checkbox for optional use.

**Comment by TheLastBen** [comment]
for now, it is automatically merged in the "download model" cell
