### ISSUE TITLE
Conversion Error when Re-opening a Trained Model

### ISSUE THREAD

**Issue by surelymz** [TheLastBen/fast-stable-diffusion#2328]
Hi! I have been receiving a conversion error when opening the model I trained before. I was able to open it last week, but I wasn't able to reopen any of my pre-trained models this week. 

**Attempts:** 
1: I tried several times to disconnect the runtime and reconnect again. 
2: I also tried making a copy of the original Colab workbook again to run the trained model
3. I am sure that I have connected with my drive, and I have installed all dependencies, before loading the model. 
However, none of the methods work. 
4. There's only one .ckpt file in the folder with no other checkpoints. 

**Error:** 
`V2.1-512px Detected
Session found, loading the trained model ...
Converting to Diffusers ...
Traceback (most recent call last):
  File "/content/convertodiff.py", line 1137, in <module>
    convert(args)
  File "/content/convertodiff.py", line 1102, in convert
    key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
  File "/content/convertodiff.py", line 1037, in save_stable_diffusion_checkpoint
    torch.save(new_ckpt, output_file)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.
Conversion error, if the error persists, remove the CKPT file from the current session folder`

![conversion-error](https://github.com/TheLastBen/fast-stable-diffusion/assets/114205829/dc0036de-ab4c-4ad4-806a-4b5f3077db57)

Thank you for your help in advance!

**Comment by TheLastBen** [comment]
don't use numbers in the session name

**Comment by surelymz** [comment]
> don't use numbers or special characters in the session name

Hi Ben! Thank you so much for your help! It is working now!!!!!
