### ISSUE TITLE
Can't fine-tune model

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2344]
I've just switched to a new computer but given that everything is on my google drive and on google colab, that shouldn't matter, right?  Here is what happens.  When I get to the model download I put in the what I always have and get an error.  both are in the image attached.  thanks for any help!
<img width="1238" alt="Untitled" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/ee307118-6941-46c9-a085-8f68d28c7898">

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by mdlieber99** [comment]
I know this is a stupid question but how do I get to the latest notebook?

**Comment by mdlieber99** [comment]
never mind - figured it out (I think)

**Comment by mdlieber99** [comment]
used the latest notebook from your GitHub but still get the same error

**Comment by TheLastBen** [comment]
very likely there is an issue with the model, have you tried a different model ?

**Comment by mdlieber99** [comment]
hmm, its the same model and path I have used 100 times before

**Comment by TheLastBen** [comment]
probably RAM issue since the RAM fix isn't working anymore

**Comment by TheLastBen** [comment]
Make sure the cause is the RAM

**Comment by mdlieber99** [comment]
how can I do that?

**Comment by TheLastBen** [comment]
click on resources

**Comment by mdlieber99** [comment]
here's what it showed me

<img width="424" alt="Untitled 2" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/dbc33194-1574-412e-859f-562292deaa26">

**Comment by TheLastBen** [comment]
did the model work before ?

**Comment by mdlieber99** [comment]
yeah - 50+ times.  Its the level4 model.

**Comment by TheLastBen** [comment]
do you have a link for it

**Comment by mdlieber99** [comment]
its in my google drive - is that something I can give a link to?  I dl'd it from civitai months ago

**Comment by TheLastBen** [comment]
do you have the civitai link for it ?

**Comment by mdlieber99** [comment]
https://civitai.com/models/17449

**Comment by TheLastBen** [comment]
it works fine, use the latest notebook and use the link you posted above

**Comment by mdlieber99** [comment]
I put that link in the "model link" and clicked safe tensors and get "Wrong link, check that the link is valid".  Specifically, I put in https://civitai.com/models/17449 as the link.  Am I doing that wrong?

**Comment by TheLastBen** [comment]
put the link and do a screenshot of the cell

**Comment by mdlieber99** [comment]
<img width="1213" alt="Untitled 2" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/68cd8564-3e86-4232-bb28-029159d15b84">

**Comment by TheLastBen** [comment]
this is the link https://civitai.com/api/download/models/25295, you are putting the link of the page, not the model

**Comment by mdlieber99** [comment]
Good point!  Thanks, as always, for you help.
