### ISSUE TITLE
Roop stops runtime (google colab pro) 

### ISSUE THREAD

**Issue by Clicli99** [TheLastBen/fast-stable-diffusion#2354]
Hello, I’ve been encountering a lot of problems today such as roop ,everything worked smoothly till today, whenever I’m enabling it the runtime just stops.

**Comment by TheLastBen** [comment]
set your runtime shape to high-ram

**Comment by HAP0526** [comment]
src/tcmalloc.cc:283] Attempt to free invalid pointer 0x56c366fe99d0 


↑I got an error message like this. I would like to know how to solve this problem.

**Comment by TheLastBen** [comment]
use the latest notebook and it will be solved
