### ISSUE TITLE
I got an error for running training using sdxl lora

### ISSUE THREAD

**Issue by MaxTran96** [TheLastBen/fast-stable-diffusion#2370]
Traceback (most recent call last):
File "/home/ubuntu/content/diffusers/examples/dreambooth/train_dreambooth_rnpd_sdxl_lora.py", line 782, in
main()
File "/home/ubuntu/content/diffusers/examples/dreambooth/train_dreambooth_rnpd_sdxl_lora.py", line 777, in main
network.save_weights(model_path, torch.float32, None)
File "/home/ubuntu/content/diffusers/examples/dreambooth/lora_sdxl.py", line 1005, in save_weights
torch.save(state_dict, file)
File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 440, in save
with _open_zipfile_writer(f) as opened_zipfile:
File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 315, in _open_zipfile_writer
return container(name_or_buffer)
File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/serialization.py", line 288, in init
super().init(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: [enforce fail at inline_container.cc:365] . invalid file name: .safetensors

this is my command
accelerate launch /home/ubuntu/content/diffusers/examples/dreambooth/train_dreambooth_rnpd_sdxl_lora.py
--image_captions_filename
--train_text_encoder
--pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-0.9"
--instance_data_dir=/home/ubuntu/content/VenusAI/Avatar/Sessions/test/instance_images
--output_dir=/home/ubuntu/content/VenusAI/Avatar/Sessions/test/output
--captions_dir=/home/ubuntu/content/VenusAI/Avatar/Sessions/test/captain
--instance_prompt=""
--seed=123456
--resolution=1024
--mixed_precision=fp16
--train_batch_size=1
--gradient_accumulation_steps=1 --gradient_checkpointing
--use_8bit_adam
--learning_rate=2e-6
--lr_scheduler="linear"
--lr_warmup_steps=0
--max_train_steps=80

Do i need to run the convert script to diffuser format? Is the below script correct? I got my sdxl_config from https://github.com/Stability-AI/generative-models/blob/main/configs/inference/sd_xl_base.yaml

python3 /home/ubuntu/content/diffusers/scripts/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path /home/ubuntu/content/VenusAI/model_database/sd_xl_base_0.9.safetensors --dump_path /home/ubuntu/content/VenusAI/Sessions/test/model/ --original_config_file /home/ubuntu/content/sdxl_config.yaml

**Comment by MaxTran96** [comment]
Anyone know the solution to get this running?

**Comment by TheLastBen** [comment]
try to reproduce exactly the notebook's steps

**Comment by MaxTran96** [comment]
hi, i just tried using runpod 
Training_Epochs=

# Epoch = Number of steps/images.

Learning_Rate= "3e-6"

For some reason, i tried  training_epochs = 100, 200, 500, 1000, and when i put in the prompt as 'photo of nasdxl' it doesnt generate my face. My photos are in the format of nasdxl (i).png and and i'm currently using 5 photos

**Comment by TheLastBen** [comment]
did you plug in the lora node to the main model in ComfyUI ?

**Comment by MaxTran96** [comment]
how can i plug that lora node in?

**Comment by MaxTran96** [comment]
oh nevermind, i see it, thank you!
