### ISSUE TITLE
Checkpoint mergers stopped working

### ISSUE THREAD

**Issue by mdlieber99** [TheLastBen/fast-stable-diffusion#2373]
I've probably done 100 or more checkpoint mergers, but yesterday they stopped working.  I've attached relevant screenshots.  I've tried this with a number of different models, so I know it isn't specific to a particular model.  Any ideas?

<img width="1564" alt="Untitled 2" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/1a1f7c86-e119-4d34-a204-f35bc5d1f05b">
<img width="2076" alt="Untitled 3" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/105756477/9a185c7c-41d7-4618-b64a-b1919c98db66">

**Comment by TheLastBen** [comment]
it does write that checkpoint was saved, did you check the storage ?

**Comment by mdlieber99** [comment]
hmm, it seems unreliable.  sometimes it makes a file that will function and sometimes it makes a file that will never load and work.  but I guess I can work with it.  thanks!
