### ISSUE TITLE
Bad Scale: 200% Change your browser or your computer settings!  Otherwise, it will cause this page to not function properly!

### ISSUE THREAD

**Issue by noha2310** [TheLastBen/fast-stable-diffusion#2381]
The title text appears at the top of the stable diffusion window.

What should I do?

**Comment by TheLastBen** [comment]
unzoom the page

**Comment by noha2310** [comment]
When I unzoomed, the page became extremely small, so I decided to ignore it by pressing the button under the wording of the title.

Thank you for answering my question.

**Comment by bobburrage** [comment]
This is going to continue to be a problem for anyone using an Apple 'Retina display' screen which has four 'screen pixels' for each 'image pixel'. Perhaps if the check can't be changed to take that into account the message should be re-worded.

**Comment by TheLastBen** [comment]
This is an important issue, you should open one in gradio github page
