### ISSUE TITLE
Textual Inversion training error

### ISSUE THREAD

**Issue by futuranewworld** [TheLastBen/fast-stable-diffusion#2385]
After update I kept getting this error using the usual setup for my training.

Loading weights [None] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying attention optimization: xformers... done.
Weights loaded in 7.5s (load weights from disk: 5.1s, apply weights to model: 0.8s, apply half(): 0.1s, move model to device: 1.5s).
Training at rate of 0.01 until step 100
Preparing dataset...
100% 200/200 [00:05<00:00, 34.42it/s]
  0% 0/250 [00:00<?, ?it/s]*** Error training embedding
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 529, in train_embedding
        scaler.scale(loss).backward()
      File "/usr/local/lib/python3.10/dist-packages/torch/_tensor.py", line 487, in backward
        torch.autograd.backward(
      File "/usr/local/lib/python3.10/dist-packages/torch/autograd/__init__.py", line 200, in backward
        Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 77, 768]], which is output 0 of MulBackward0, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by nathannlu** [comment]
im facing the same issue. i was able to train embeddings yesterday, don't know what happened today that made it break

**Comment by futuranewworld** [comment]
> im facing the same issue. i was able to train embeddings yesterday, don't know what happened today that made it break. were you able to get it working?

No luck yet

**Comment by gusmcnair** [comment]
I am also having this issue

**Comment by gusmcnair** [comment]
Looks like the issue is with something in automatic1111 that hasn't been updated in the colab yet. If you want to fix it manually, find this file in your drive and make [the change described here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5c8f91b22975701af22d24f947af82e7d23264d5).

**Comment by futuranewworld** [comment]
> Looks like the issue is with something in automatic1111 that hasn't been updated in the colab yet. If you want to fix it manually, find this file in your drive and make [the change described here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5c8f91b22975701af22d24f947af82e7d23264d5).

I made the said changes and still didn't work for me unfortunately. Were you able to get it running?

**Comment by gusmcnair** [comment]
yes, it's running for me. you need to restart the Start Stable-Diffusion step in the colab for it to work, but otherwise idk what it could be

**Comment by futuranewworld** [comment]
I made a silly mistake a didn't delete the 2 lines as instructed. After deletion and addition it works fine now.

I do want to point out that even with the latest build, without making any changes, the problem persists. So if you want to run TI training you still have to make this manual change every time.

Thanks for the recommendation!

> yes, it's running for me. you need to restart the Start Stable-Diffusion step in the colab for it to work, but otherwise idk what it could be
