### ISSUE TITLE
Ran sd gave this error

### ISSUE THREAD

**Issue by Toshik-One** [TheLastBen/fast-stable-diffusion#2390]
![photo_5334723383545415509_y](https://github.com/TheLastBen/fast-stable-diffusion/assets/120157367/fed8641e-83d5-44ac-82e3-26d06df91778)

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by Toshik-One** [comment]
@TheLastBen Now it's on startup sd
```jupyter-notebook
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
100% 5.10M/5.10M [00:00<00:00, 71.7MB/s]
/usr/local/lib/python3.10/dist-packages/einops/einops.py:711: DeprecationWarning: invalid escape sequence '\s'
  """
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/modules/prompt_parser.py:346: DeprecationWarning: invalid escape sequence '\('
  """
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py:15: DeprecationWarning: invalid escape sequence '\('
  re_hypernet_hash = re.compile("\(([0-9a-f]+)\)$")
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/modules/models/diffusion/uni_pc/uni_pc.py:15: DeprecationWarning: invalid escape sequence '\h'
  """Create a wrapper class for the forward SDE (VP type).
/usr/local/lib/python3.10/dist-packages/basicsr/metrics/niqe.py:5: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import convolve
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
2023-07-26 07:50:59,654 - ControlNet - INFO - ControlNet v1.1.233
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body.py:5: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/hand.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
ControlNet preprocessor location: /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(version("gradio")) < LooseVersion("3.10"):
/content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(version("gradio")) < LooseVersion("3.10"):
2023-07-26 07:51:03,982 - ControlNet - INFO - ControlNet v1.1.233
/usr/local/lib/python3.10/dist-packages/onnxruntime/capi/_pybind_state.py:28: DeprecationWarning: invalid escape sequence '\S'
  "(other than %SystemRoot%\System32), "
/usr/local/lib/python3.10/dist-packages/albumentations/augmentations/functional.py:9: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
```

**Comment by Hunterclaw** [comment]
> @TheLastBen Now it's on startup sd
> 
> ```python
> Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
> 100% 5.10M/5.10M [00:00<00:00, 71.7MB/s]
> /usr/local/lib/python3.10/dist-packages/einops/einops.py:711: DeprecationWarning: invalid escape sequence '\s'
>   """
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/modules/prompt_parser.py:346: DeprecationWarning: invalid escape sequence '\('
>   """
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py:15: DeprecationWarning: invalid escape sequence '\('
>   re_hypernet_hash = re.compile("\(([0-9a-f]+)\)$")
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/modules/models/diffusion/uni_pc/uni_pc.py:15: DeprecationWarning: invalid escape sequence '\h'
>   """Create a wrapper class for the forward SDE (VP type).
> /usr/local/lib/python3.10/dist-packages/basicsr/metrics/niqe.py:5: DeprecationWarning: Please use `convolve` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
>   from scipy.ndimage.filters import convolve
> <frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
> 2023-07-26 07:50:59,654 - ControlNet - INFO - ControlNet v1.1.233
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/body.py:5: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
>   from scipy.ndimage.filters import gaussian_filter
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/openpose/hand.py:6: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
>   from scipy.ndimage.filters import gaussian_filter
> ControlNet preprocessor location: /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
>   if LooseVersion(version("gradio")) < LooseVersion("3.10"):
> /content/gdrive/Shareddrives/AI/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py:38: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
>   if LooseVersion(version("gradio")) < LooseVersion("3.10"):
> 2023-07-26 07:51:03,982 - ControlNet - INFO - ControlNet v1.1.233
> /usr/local/lib/python3.10/dist-packages/onnxruntime/capi/_pybind_state.py:28: DeprecationWarning: invalid escape sequence '\S'
>   "(other than %SystemRoot%\System32), "
> /usr/local/lib/python3.10/dist-packages/albumentations/augmentations/functional.py:9: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
>   from scipy.ndimage.filters import gaussian_filter
> ```

I got the same thing lol

**Comment by TheLastBen** [comment]
they are deprecation warnings, A1111 used to hide them, but for some reason with the last commit, they are showing, but they are harmless messages
