### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by CHJ85** [TheLastBen/fast-stable-diffusion#2393]
Hi there. I love your work.
I'm using the script on CoLab.
I have a request.
Could you please add the ability to train characters one-by-one? After I've trained and verified the first character, it'd be nice if I had the ability to start up another instance. This way I don't have to worry about keeping CoLab connected.

**Comment by TheLastBen** [comment]
everything is save on gdrive, meaning even if you disconnect, you can simply load the session and resume your training

**Comment by CHJ85** [comment]
Thanks. I'm gonna have to look into how to do that.
But it would still be a very handy feature to have though.

**Comment by TheLastBen** [comment]
adding subjects to the model is the same as resuming

**Comment by TheLastBen** [comment]
I'm talking about resuming the training in the training cell.

resuming a session will load the previous model in it's trained state, so you can continue the training by ticking the box "resume_training"

**Comment by CHJ85** [comment]
I know how to continue the current training.
But what I'm talking about is adding more subjects or characters to the model.
Currently there is no way of doing that, as far as I know. Once the model is created, you can train the current instance images, but you can't add additional subjects / people / characters or whatever the case might be.

**Comment by TheLastBen** [comment]
Yes you can, simply run the instance images cell and add-to/replace the existing instance images, the resume the training.

**Comment by CHJ85** [comment]
Really? Nice. Because I thought that option was assigned continue training and would essentially remove or destroy my current model. But that's good to know.
Can this be done with .ckpt files too or projects only?

**Comment by CHJ85** [comment]
If it's not too much to ask, do you think you could add this as an option to your next script update?
Like have the option to either continue training the model as is or add and train additional subjects to the model.
Because now it's not obvious that this is possible.

**Comment by CHJ85** [comment]
But let me see if I got this right.
If I want to continue the previous session, I do not have to paste the instance images link in, right?
But if I want to train new characters in the session I simply paste in the URL for the new images and check the box for removing the current ones?

**Comment by CHJ85** [comment]
Please disregard my complaints here, as it all turned out to be Google Colab related. Do not run this script unless you got a pro plan with lots of connections. Seriously. You're gonna run into issues. I moved on from Colab due to all the limitations, even with the pro plan. Paperspace is a whole lot better. 😀
