### ISSUE TITLE
run on v100 machine

### ISSUE THREAD

**Issue by xiaol** [TheLastBen/fast-stable-diffusion#24]
i use the colab code to install xformers, but still got 
![image](https://user-images.githubusercontent.com/1669515/193342956-12f5776f-0c1e-4bcb-a232-45bbd84d5219.png)

![image](https://user-images.githubusercontent.com/1669515/193343046-296f20b7-152b-46bb-809d-765896611ff9.png)

should i update cuda from 11.4 to 11.7?

**Comment by TheLastBen** [comment]
you installed it locally ?

**Comment by xiaol** [comment]
yes ,ubuntu 20.04 with v100.
![image](https://user-images.githubusercontent.com/1669515/193376599-8dc93070-6690-4860-aecb-4e890a4d8df8.png)

**Comment by TheLastBen** [comment]
use this : `pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers` and let it compile for 40min to 1 hour

**Comment by TheLastBen** [comment]
if you face issues compiling, I recommend the docker image by nvidia : nvcr.io/nvidia/pytorch:22.08-py3

**Comment by xiaol** [comment]
thank you, i use pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers, and successfully installed xformers , but it seems like not compiling with Cuda , and have the same result,  even i put  FORCE_CUDA=1 before pip install.

btw, i have installed nvcc since last post here.

**Comment by xiaol** [comment]
I am in production envrionments, the project was not used to have docker intergrated, can it use in conda environment?

**Comment by xiaol** [comment]
after install nvcc, i try pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers, it works, just because in the same folder i have source xformers , then import the wrong modules, thanks a lot.

**Comment by TheLastBen** [comment]
You are lucky yo get it to work outside an nvidia environment  because it's really hard to get the cuda+torch versions to work together

**Comment by TheLastBen** [comment]
but there is always a solution, for example, connect a local runtime to google colab, and install xformers, and copy the compiled files to the right folder.
