### ISSUE TITLE
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)

### ISSUE THREAD

**Issue by Ferutesu** [TheLastBen/fast-stable-diffusion#2410]
The full error codes are:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 28, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 17, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config, sd_unet, sd_models_xl
ImportError: cannot import name 'sd_unet' from 'modules' (unknown location)
------------------------------------------------------------------------------------------------------------
I used the old notebook before and work properly. This is the error of running new SDXL supported notebook. Thanks.

**Comment by TheLastBen** [comment]
Rename the SD folder to SD_old

**Comment by Ferutesu** [comment]
> Rename the SD folder to SD_old

I need to transfer the models to the new created sd folder? Is there any method to use the old models location? Thanks.

**Comment by TheLastBen** [comment]
you can move the old models folder from sd_old to sd

**Comment by Ferutesu** [comment]
> you can move the old models folder from sd_old to sd

Thanks for your reply.
