### ISSUE TITLE
NameError: name 'six' is not defined(Paperspace)

### ISSUE THREAD

**Issue by banMo88** [TheLastBen/fast-stable-diffusion#2418]
happened when downloading model from google drive

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [7], line 22
     16 Temporary_Storage = True
     18 # Download the model to a temporary storage, bigger capacity but will be removed at session shutdown.
     19 
     20 
     21 #--------------------
---> 22 model=mdls(Original_Model_Version, Path_to_MODEL, MODEL_LINK, Temporary_Storage)

File /notebooks/mainpaperspaceA1111.py:270, in mdls(Original_Model_Version, Path_to_MODEL, MODEL_LINK, Temporary_Storage)
    268       print('Model already exists')
    269 elif src=='gdrive':
--> 270    modelname=get_name(MODEL_LINK, True)
    271    if Temporary_Storage:
    272       model=f'/models/{modelname}'

File /notebooks/mainpaperspaceA1111.py:240, in mdls.<locals>.get_name(url, gdrive)
    238 res = requests.session().get(lnk, headers=headers, stream=True, verify=True)
    239 res = requests.session().get(get_url_from_gdrive_confirmation(res.text), headers=headers, stream=True, verify=True)
--> 240 content_disposition = six.moves.urllib_parse.unquote(res.headers["Content-Disposition"])
    241 filenm = re.search(r"filename\*=UTF-8''(.*)", content_disposition).groups()[0].replace(os.path.sep, "_")
    242 return filenm

NameError: name 'six' is not defined

**Comment by TheLastBen** [comment]
Will fix it shortly

**Comment by banMo88** [comment]
as aways,thanks a lot
