### ISSUE TITLE
"Session_name not defined" when using the old method

### ISSUE THREAD

**Issue by giteeeeee** [TheLastBen/fast-stable-diffusion#242]
Running the latest dreambooth with the old class image method would result in:

![13213](https://user-images.githubusercontent.com/89521447/197973850-3e2e4579-cf0b-44b0-a323-6652cf1f83b1.jpg)

Maybe move the [session name:_____] from the new method cell to the Start DreamBooth cell, so that it supports both methods in one go?

**Comment by TheLastBen** [comment]
i'll fix it shortly

**Comment by TheLastBen** [comment]
fixed, for now you simply remove the two lines if you don't want to refresh the notebook
