### ISSUE TITLE
SDXL-LoRA-PPS TypeError: upld() missing 1 required positional argument: 'ren'

### ISSUE THREAD

**Issue by RONNYKHALIL** [TheLastBen/fast-stable-diffusion#2420]
The lora encoder has been working great the last few days. Just updated it and getting this message when running the Instance_Images cell. 

File /notebooks/sdxllorapps.py:443, in uplder(Remove_existing_instance_images, Crop_images, Crop_size, IMAGES_FOLDER_OPTIONAL, INSTANCE_DIR, CAPTIONS_DIR)
    441   display(uploader, Upload, out)
    442 else:
--> 443    upld(Remove_existing_instance_images, Crop_images, Crop_size, IMAGES_FOLDER_OPTIONAL, INSTANCE_DIR, CAPTIONS_DIR, uploader)
    444    done()

TypeError: upld() missing 1 required positional argument: 'ren'

Any idea how to solve?

Cheers

**Comment by TheLastBen** [comment]
run the first cell again, it's fixed

**Comment by RONNYKHALIL** [comment]
awesome. thanks for the super quick fix
