### ISSUE TITLE
SDXL-LoRA-PPS.... ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' 

### ISSUE THREAD

**Issue by RONNYKHALIL** [TheLastBen/fast-stable-diffusion#2421]
This pops up when running the Train LoRA cell:

Traceback (most recent call last):
  File "/notebooks/diffusers/examples/dreambooth/train_dreambooth_sdxl_lora.py", line 22, in <module>
    from diffusers import AutoencoderKL, DDPMScheduler, StableDiffusionXLPipeline, UNet2DConditionModel
ImportError: cannot import name 'StableDiffusionXLPipeline' from 'diffusers' (/usr/local/lib/python3.9/dist-packages/diffusers/__init__.py)

Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.9/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', '/notebooks/diffusers/examples/dreambooth/train_dreambooth_sdxl_lora.py', '--dim=128', '--ofstnselvl=0.03', '--image_captions_filename', '--Session_dir=/notebooks/Fast-Dreambooth/Sessions/GOOODOOOZ', '--pretrained_model_name_or_path=/notebooks/stable-diffusion-XL', '--instance_data_dir=/notebooks/Fast-Dreambooth/Sessions/GOOODOOOZ/instance_images', '--output_dir=/notebooks/models/GOOODOOOZ', '--captions_dir=/notebooks/Fast-Dreambooth/Sessions/GOOODOOOZ/captions', '--seed=108140', '--resolution=1024', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=1e-6', '--lr_scheduler=cosine', '--lr_warmup_steps=0', '--num_train_epochs=44']' returned non-zero exit status 1.

**Comment by TheLastBen** [comment]
did you run the first cell ?

**Comment by RONNYKHALIL** [comment]
yea, a few times. tried without and with force reinstall.

**Comment by TheLastBen** [comment]
in a new cell, run `!pip show diffusers` see what's the version

**Comment by RONNYKHALIL** [comment]
scratch that, started a new fresh instance in paperspace and the problem is resolved. thanks!
