### ISSUE TITLE
Cannot Load Model

### ISSUE THREAD

**Issue by player-deleted** [TheLastBen/fast-stable-diffusion#2438]
After installing dependencies and updating the repo I get this error:

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [4], line 25
     19 Temporary_Storage = False
     21 # Download the model to a temporary storage, bigger capacity but will be removed at session shutdown.
     22 
     23 
     24 #--------------------
---> 25 model=mdl(Original_Model_Version, Path_to_MODEL, MODEL_LINK, safetensors, Temporary_Storage)

NameError: name 'mdl' is not defined

**Comment by Headupdef** [comment]
same error

**Comment by Skeme322** [comment]
it helped me to replace my PPS-A1111.ipynb in notepad with a file from the current version

**Comment by maciekmasiul** [comment]
same error

**Comment by TheLastBen** [comment]
Use the latest version, you'll find it inside the folder "latest_notebooks" in the main folder in paperspace

**Comment by player-deleted** [comment]
Thank you
