### ISSUE TITLE
Flip augmentation

### ISSUE THREAD

**Issue by Super-zapper** [TheLastBen/fast-stable-diffusion#2465]
Is there any way to turn on flip augmentation option for dreambooth training in colab note?

**Comment by TheLastBen** [comment]
not available option, you can just do it manually

**Comment by Super-zapper** [comment]
you mean train for example 1000 steps and than train 1000 steps of flipped images?

**Comment by TheLastBen** [comment]
you manually flip the image and add it to the dataset, flip augmentation should only be used when there is not enough images of the subject to train
