### ISSUE TITLE
TypeError: sdcmf() missing 1 required positional argument: 'Download_SDXL_Model'

### ISSUE THREAD

**Issue by RONNYKHALIL** [TheLastBen/fast-stable-diffusion#2472]
![Screenshot 2023-08-11 at 10 22 22 PM](https://github.com/TheLastBen/fast-stable-diffusion/assets/74345290/29336317-5426-4b7f-9ae1-4663d63a0eab)
Getting this error in the Paperspace Lora trainer. Can you help?

Thanks!

**Comment by TheLastBen** [comment]
use the latest notebook, you'll find it inside the folder "latest_notebooks" in the main folder

**Comment by RONNYKHALIL** [comment]
yep have been. tried fresh install and same output when I try and run Comfy UI

**Comment by TheLastBen** [comment]
fixed

**Comment by RONNYKHALIL** [comment]
thanks! works like a charm!
