### ISSUE TITLE
Missing temp model

### ISSUE THREAD

**Issue by mmehrle** [TheLastBen/fast-stable-diffusion#2474]
Just launched the new notebook and it's throwing a strange error about a missing temp model:

`FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-b979651954d8>](https://localhost:8080/#) in <cell line: 123>()
    143             model=f'/content/gdrive/{mainpth}/sd/stable-diffusion-{blasphemy}/models/Stable-diffusion/{modelname}'
    144          if not os.path.exists(model):
--> 145             dwn(MODEL_LINK, model, 'Downloading the custom model')
    146             clear_output()
    147          else:

[<ipython-input-4-b979651954d8>](https://localhost:8080/#) in dwn(url, dst, msg)
     66     with tqdm(total=file_size, disable=False, mininterval=0.5,
     67               bar_format=msg+' |{bar:20}| {percentage:3.0f}%') as pbar:
---> 68         with open(dst, "wb") as f:
     69             while True:
     70                 buffer = u.read(8192)

FileNotFoundError: [Errno 2] No such file or directory: '/content/temp_models/epicrealism_pureEvolutionV5.safetensors'`

Here's a snapshot - I was trying to load a 1.5 model:

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/8457499/70b2792d-a179-4a09-9c8f-06100c47ac12)

**Comment by mmehrle** [comment]
**Update:** Can confirm that it also happens with a copy of the Google hosted version:

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/8457499/49dbf591-8d4a-4326-8cf6-16bd6e0274c8)

**Comment by mmehrle** [comment]
Okay I just loaded a different model and now it's working. This is strange because I used the same model yesterday (134065) just yesterday, so it's not a broken model.

**Comment by mmehrle** [comment]
Same problem is back this morning. Seems intermittent. Not sure how to fix this.

**Comment by mmehrle** [comment]
Okay I think I have figured out what the problem is. When launching the notebook for the first time you need load the default 1.5 model first. Once that has succeeded other models can be loaded without issues.

Is that how it's supposed to work? I was under the impression that all models were self contained but most likely I misunderstand the architecture and respective modules involved.

**Comment by TheLastBen** [comment]
yep, there is a bug in the notebook, fixed now, thanks for the feedback

**Comment by mmehrle** [comment]
Happy to help!
