### ISSUE TITLE
UI element - VAE, noise multiplier, cond mask strength

### ISSUE THREAD

**Issue by scorpi0n81** [TheLastBen/fast-stable-diffusion#2476]
Is there a change in notebook which makes new option appear in UI? I see VAE and two new sliders for noise multiplier and conditional mask strength and somehow inpainting is worse than before. 

Any way to have the previous UI without these options?

**Comment by TheLastBen** [comment]
They were there since months ago, nothing changed in that area

**Comment by scorpi0n81** [comment]
> They were there since months ago, nothing changed in that area

Wow.. i never saw them. Guess need to delete SD folder and start afresh and select 1.5 as base. I think i selected 1.5 inpainting and this happened as i never saw them till yesterday.

**Comment by scorpi0n81** [comment]
> They were there since months ago, nothing changed in that area

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/132054081/79b52b5e-ec53-4e08-91d1-e63fe021f64c)

I always used this so far.. any tip to get back to this view? This never had those additional options

**Comment by TheLastBen** [comment]
in the webui go into settings and remove them
