### ISSUE TITLE
Running on public URL may or may not show up.

### ISSUE THREAD

**Issue by Oda1985** [TheLastBen/fast-stable-diffusion#2493]
When I tried to start it around noon, the public URL was not displayed, and when I tried to start it now, the public URL was displayed.

Is it bad that I cancelled Google Colab Pro the month before last and was running it using the number of units I purchased?

I don't want the public URL to appear or not appear, so if anyone can help me figure out why, please share your wisdom.

Below is the code that is showing up when I run the last cell.
when it doesn't start, I get this code. *I have not done anything with Colab while running the runtime

#Code.
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu .
2023-08-18 13:31:36,658 - ControlNet - INFO - ControlNet v1.1.238
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/ downloads
2023-08-18 13:31:37,201 - ControlNet - INFO - ControlNet v1.1.238
Loading weights [31e35c80fc] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/sd_xl_base_1.0.safetensors
*Deforum ControlNet support: enabled*.
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/generative-models/configs/inference/sd_xl_base.yaml
^C

Translated with www.DeepL.com/Translator (free version)

![スクリーンショット 2023-08-19 0 01 33](https://github.com/TheLastBen/fast-stable-diffusion/assets/142187274/d5114024-4a74-482d-8e0d-3cd4e1b4996d)

**Comment by TheLastBen** [comment]
use High-RAM
