### ISSUE TITLE
python3: can't open file '/content/gdrive/MyDrive/sd/stable-diffusion-wwebui/webui.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by elBlacksmith** [TheLastBen/fast-stable-diffusion#2494]
Hi, as the title says, now I am getting this error trying to execute the colab. 
I guess it´s a typo, but I don´t see it on the colab itself.

Thanks beforehand!

**Comment by HaikenEdge** [comment]
Can confirm it's an issue.

**Comment by TheLastBen** [comment]
are you using an unmodified latest notebook ?

**Comment by elBlacksmith** [comment]
> are you using an unmodified latest notebook ?

Yes, I just went to your github page and clic the picture below "Colab(pro)-AUTOMATIC1111"

**Comment by HaikenEdge** [comment]
Same as @elBlacksmith

**Comment by TheLastBen** [comment]
try again with the latest one

**Comment by HaikenEdge** [comment]
Seems fixed. Thank you kindly.

**Comment by elBlacksmith** [comment]
> try again with the latest one


Thanks for your quick response!

In the ControlNet Cell I am getting this error, that stops the Colab:

```---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-6-c8b317a0cbe1>](https://localhost:8080/#) in <cell line: 50>()
     48 
     49 mdldir='/content/gdrive/'+mainpth+'/sd/stable-diffusion-'+blasphemy+'/extensions/sd-webui-controlnet/models'
---> 50 for filename in os.listdir(mdldir):
     51   if "_sd14v1" in filename:
     52     renamed = re.sub("_sd14v1", "-fp16", filename)

FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/sd/stable-diffusion-ebui/extensions/sd-webui-controlnet/models'
```

I tried to select to update all the ControlNet models after disconnecting, deleting the Colab runtime and starting it again, but it appear the same error as above.



If I ignore the error and click the cell "Start Stable-Diffusion" I can use SD normally. So at least there is that workaround.

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
it should work fine now, make sure you use the latest notebook

**Comment by elBlacksmith** [comment]
> it should work fine now, make sure you use the latest notebook

Yep, I can confirm that now the entire Colab works perfectly.

:)

**Comment by da-art-fantasy** [comment]
Hi, as the title says, now I am getting this error trying to execute the colab.
I used a latest notebook but still getting the same error message.

Thank you in advance.

**Comment by HaikenEdge** [comment]
I can't confirm the issue; it's running fine for me (aside from the normal "The future is in a different loop" thing that gets fixed when I stop the last module and runs re-run it) from a refresh reload and start.
