### ISSUE TITLE
Runpod ControlNet 2.1 Size Problem

### ISSUE THREAD

**Issue by surelymz** [TheLastBen/fast-stable-diffusion#2499]
Hi! 

I tried to use the controlNet for the 2.1 Model. 

I downloaded my model from here: https://huggingface.co/thibaud/controlnet-sd21/tree/main
I uploaded the safetensor files manually to the controlNet model directory. 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/114205829/c4f4b1ce-4114-42b8-a7cb-bfee09f1b73d)

I have changed the setting to models/cldm_v21.yaml
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/114205829/e810e0ea-a1d8-4070-9686-56f8ee86eb05)

I have also tried reuploading the files to see if the ControlNet can be applied, but it hasn't worked. I have tested that preprocessor is working fine. 

This is the error I ran into: 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/114205829/601eab36-d794-411a-95bc-bd3ee90bc75c)

Thank you so much for any help in advance!!!

**Comment by TheLastBen** [comment]
set back controlnet settings to default, remove the extension and install it again

**Comment by surelymz** [comment]
It worked! Thank you so much!!! 

I also noticed that the preprocessor list under the x/y/z plot is not up to date. I wondered is there any way that I can change the data validation in the field to match the current preprocessor models?

An additional question is, in the Runpod template, can I access the code directly in any way like in Google Colab? Because when I open the template, I can only see the cells, but not the actual code. 

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/114205829/55a1f8fe-48af-45bb-b640-557b1b728025)

**Comment by TheLastBen** [comment]
there is a py file in the main folder, it contains the main code

**Comment by surelymz** [comment]
Thank you so much!!!
