### ISSUE TITLE
"Restore faces" disappeared.

### ISSUE THREAD

**Issue by KyotoLyon** [TheLastBen/fast-stable-diffusion#2520]
I was using the notebook until it froze during the Gladio update. When I managed to reconnect, I noticed that "Restore faces" disappeared. I apologize if this is a newbie question. But where did it go in this update? Or is it an error?
![Print Screen Gradio - 31-08-2023](https://github.com/TheLastBen/fast-stable-diffusion/assets/143690869/5ef4ec0b-9541-40b6-a51c-fe202ff1a8ab)

**Comment by TheLastBen** [comment]
it a new A1111 update, check in their repo https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by scorpi0n81** [comment]
Restore faces and Tiling generation parameters have been moved to settings out of main UI
if you want to put them back into main UI, use Options in main UI setting on the UI page.

**Comment by KyotoLyon** [comment]
Thank you!
