### ISSUE TITLE
Dreambooth error

### ISSUE THREAD

**Issue by mcqx4** [TheLastBen/fast-stable-diffusion#2521]
UPD: Fixed

Model Download Cell Error – safetensors model:
Detecting model version...
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
[<ipython-input-5-8275b455c45d>](https://localhost:8080/#) in <cell line: 149>()
    223     wget.download('https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/det.py')
    224     print('Detecting model version...')
--> 225     Custom_Model_Version=check_output('python det.py '+sftnsr+' --MODEL_PATH '+str(MODEL_PATH), shell=True).decode('utf-8').replace('\n', '')
    226     clear_output()
    227     print(''+Custom_Model_Version+' Detected')

1 frames
[/usr/lib/python3.10/subprocess.py](https://localhost:8080/#) in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    524         retcode = process.poll()
    525         if check and retcode:
--> 526             raise CalledProcessError(retcode, process.args,
    527                                      output=stdout, stderr=stderr)
    528     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command 'python det.py --from_safetensors --MODEL_PATH /content/gdrive/MyDrive/Models/protogenNovaExperimental_protogenNova (1).safetensors' returned non-zero exit status 2.

**Comment by TheLastBen** [comment]
great!
