### ISSUE TITLE
new  Samplers missing from A1111 1.6

### ISSUE THREAD

**Issue by RONNYKHALIL** [TheLastBen/fast-stable-diffusion#2526]
as per the screenshots, there are def some new ones, but quite a few of the new ones are not listed. any idea how to access them?

![Screenshot 2023-08-31 at 1 45 56 PM](https://github.com/TheLastBen/fast-stable-diffusion/assets/74345290/9f303770-fcc0-4a66-8b3c-f0484ab5f92f)
![Screenshot 2023-08-31 at 1 45 32 PM](https://github.com/TheLastBen/fast-stable-diffusion/assets/74345290/25e44a7a-d5b8-46bb-b8fc-1158e7dd77df)

**Comment by TheLastBen** [comment]
check in the A1111 repo https://github.com/AUTOMATIC1111/stable-diffusion-webui

**Comment by RONNYKHALIL** [comment]
Thanks. Sorted out

**Comment by TheLastBen** [comment]
great!
