### ISSUE TITLE
Facing this error on Runpod ! 

### ISSUE THREAD

**Issue by HelpANewbie** [TheLastBen/fast-stable-diffusion#2548]
14 # A direct link to a Model or a shared gdrive link.
     15 
     16 
     17 #--------------------
---> 18 model=mdl(Original_Model_Version, Path_to_MODEL, MODEL_LINK)

File /workspace/mainrunpodA1111.py:170, in mdl(Original_Model_Version, Path_to_MODEL, MODEL_LINK)
    168       print('Model already exists')
    169 elif src=='gdrive':
--> 170    modelname=get_name(MODEL_LINK, True)
    171    model=f'/workspace/sd/stable-diffusion-webui/models/Stable-diffusion/{modelname}'
    172    if not os.path.exists(model):

File /workspace/mainrunpodA1111.py:486, in get_name(url, gdrive)
    484 res = requests.session().get(lnk, headers=headers, stream=True, verify=True)
    485 res = requests.session().get(get_url_from_gdrive_confirmation(res.text), headers=headers, stream=True, verify=True)
--> 486 content_disposition = six.moves.urllib_parse.unquote(res.headers["Content-Disposition"])
    487 filenm = re.search(r"filename\*=UTF-8''(.*)", content_disposition).groups()[0].replace(os.path.sep, "_")
    488 return filenm

File /usr/local/lib/python3.10/dist-packages/requests/structures.py:52, in CaseInsensitiveDict.__getitem__(self, key)
     51 def __getitem__(self, key):
---> 52     return self._store[key.lower()][1]

KeyError: 'content-disposition'

**Comment by TheLastBen** [comment]
have you tried different links

**Comment by HelpANewbie** [comment]
Yes....copied the file and renamed the file without any spaces...still doesnt work

**Comment by TheLastBen** [comment]
try a different link to make sure the issue isn't in your link

**Comment by HelpANewbie** [comment]
Im going to try with different links...will update here if its working

**Comment by HelpANewbie** [comment]
The file loaded but I'm getting this error : 

RuntimeError: shape '[1280, 1280]' is invalid for input of size 1227851

**Comment by TheLastBen** [comment]
the model file looks corrupt

**Comment by HelpANewbie** [comment]
I tried with a different model and it worked....Thanks Ben :)
