### ISSUE TITLE
can't use controlnet on Colab.

### ISSUE THREAD

**Issue by maomao2020github** [TheLastBen/fast-stable-diffusion#2550]
this error occur, when I use latest notebook on Colab.
*** Error running process: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 619, in process
        script.process(p, *script_args)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 738, in process
        model_net = Script.load_control_model(p, unet, unit.model, unit.low_vram)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 311, in load_control_model
        model_net = Script.build_control_model(p, unet, model, lowvram)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py", line 321, in build_control_model
        raise RuntimeError(f"You have not selected any ControlNet Model.")
    RuntimeError: You have not selected any ControlNet Model.

**Comment by maomao2020github** [comment]
my extensions is this.

sd-webui-controlnet	https://github.com/Mikubill/sd-webui-controlnet.git	main	[876667f4](https://github.com/Mikubill/sd-webui-controlnet/commit/876667f4d6a7b450f15d2efdec9472616c679c9f)	2023-09-04 21:59:19	unknown
LDSR	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
Lora	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
ScuNET	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
SwinIR	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
canvas-zoom-and-pan	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
extra-options-section	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
mobile	[built-in](https://498f388f29a25af6ba.gradio.live/)	None			
prompt-bracket-checker	[built-in](https://498f388f29a25af6ba.gradio.live/)	None

**Comment by TheLastBen** [comment]
have you selected a controlnet model in the webui ?

**Comment by maomao2020github** [comment]
I can't select ccontrolnet model.
because no list in pulldown menu.

**Comment by maomao2020github** [comment]
sorry, problem solved. I used to wrong verdion.
I coppy latest notebook again.
I can use controlnet. thanks.
