### ISSUE TITLE
Delete A1111 1.5 installation

### ISSUE THREAD

**Issue by PaoloPgn** [TheLastBen/fast-stable-diffusion#2552]
Hi to all,
reading about problems with the 1.6 version of A1111, someone advised to remove all the files of A1111, before installing the new 1.6 and to do that it was necessary to remove the venv folder. I searched but couldn't locate the folder. Since the notebook installs the A1111 every time, is it possible to easily remove all the files of the previous version 1.5 so as to have a fresh installation only with the files of the version 1.6?
(Your notebook gives me no problems once started, the only problem is that several times I have to restart the runtime before getting to a working version, so maybe completely removing version 1.5 could be the solution).
tTank you

**Comment by TheLastBen** [comment]
yes, simply remove the folder "sd" in your gdrive or rename it to "sd_old"
