### ISSUE TITLE
DPM++ 2m SDE Karras

### ISSUE THREAD

**Issue by KuzeyVural** [TheLastBen/fast-stable-diffusion#2557]
Can't see or add this sampler in ui

**Comment by Veilosity** [comment]
I have the same issue, and there were supposedly a bunch of new samplers in V 1.6.0 that I can't see either.

**Comment by Kaka3279** [comment]
I have the same problem.
It is a dishonest response.
Please improve.

**Comment by mmehrle** [comment]
> The issue isn't related to the notebook

Can you please elaborate? Apologies for being a pain about this but if it's not the notebook then what is causing the missing resources?

**Comment by SadSAYA** [comment]
For me, the samplers may not have disappeared, they may just be moved to the top (above "Euler a")
![sampler并没有消失，只是被移到了最上面而已](https://github.com/TheLastBen/fast-stable-diffusion/assets/87817082/dbc90bae-325d-4754-9ccf-14f7ed3c52cb)

**Comment by Veilosity** [comment]
DPM++2M Karras and DPM++ SDE Karras are at the top for me as well, but the sampler we are talking about is DPM++ 2M SDE Karras which doesn't appear on the list.  There are also new 3M samplers which don't appear either.  If people with local installs are using these samplers and we can't see them, how is the issue not related to the notebook?

**Comment by dhrgusdlrns** [comment]
Yes, I think this colab is different from local a1111 web ui in anyway. I tried to change some parts but it doesn't work well.

**Comment by TheLastBen** [comment]
the notebook pulls the repo from the official A1111 link

**Comment by Veilosity** [comment]
So why can't we see or use any of the new samplers?

**Comment by TheLastBen** [comment]
fixed, use the latest notebook

**Comment by dhrgusdlrns** [comment]
Thx! It works well now.
