### ISSUE TITLE
Start Stable-Diffusion isnt working on google colab, anyone know what im doing wrong?

### ISSUE THREAD

**Issue by MelloToonz25** [TheLastBen/fast-stable-diffusion#2558]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 6, in <module>
    from modules import timer
ImportError: cannot import name 'timer' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
rename/remove the sd folder in your gdrive

**Comment by MelloToonz25** [comment]
now it just says
ERROR: ld.so: object '/content/gdrive/MyDrive/sd/libtcmalloc/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/content/gdrive/MyDrive/sd/libtcmalloc/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/content/gdrive/MyDrive/sd/libtcmalloc/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/content/gdrive/MyDrive/sd/libtcmalloc/libtcmalloc_minimal.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
python3: can't open file '/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py': [Errno 2] No such file or directory

**Comment by MelloToonz25** [comment]
nvm i just re downloaded the requirements and it worked! thanks dude!
