### ISSUE TITLE
Some new Sampling methods are missing

### ISSUE THREAD

**Issue by Toshik-One** [TheLastBen/fast-stable-diffusion#2571]
Today a friend asked me how you like the new Sampling methods dpx++ 3m sde ?  I looked and I don’t have it in the lists or settings.
![2023-9-11 13-24-3](https://github.com/TheLastBen/fast-stable-diffusion/assets/120157367/6b36f3af-5237-4768-b2a1-060507d604c0)

I have this now .
![2023-9-11 13-30-51](https://github.com/TheLastBen/fast-stable-diffusion/assets/120157367/ee6f830e-8fac-4162-baf4-fdeee2973331)

And so on a friend’s PC

@TheLastBen  Please fix this.

**Comment by Toshik-One** [comment]
@TheLastBen  Will you fix this?

**Comment by TheLastBen** [comment]
I'll investigate the issue

**Comment by Toshik-One** [comment]
> 

I invite you to please consider it, as this is one of the features of version 1.6.0.
I decided to check it on other notebooks and it’s there.

**Comment by TheLastBen** [comment]
try test running the notebook without the first cell and see if they're still missing, to make sure the issue is indeed in the notebook

**Comment by Toshik-One** [comment]
> try test running the notebook without the first cell and see if they're still missing, to make sure the issue is indeed in the notebook
I always run it this way without connecting Google Drive.

**Comment by TheLastBen** [comment]
run `pip install k-diffusion -U` 
I'll add it to the deps later

**Comment by TheLastBen** [comment]
in a new cell, run

```
!rm -r /content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion
%cd /content/gdrive/MyDrive/sd/stablediffusion/src
!git clone https://github.com/crowsonkb/k-diffusion
```

I'll add it later
