### ISSUE TITLE
A1111 Crashes when SDXL 1.0 + Refiner is used

### ISSUE THREAD

**Issue by weilintuye95** [TheLastBen/fast-stable-diffusion#2575]
Hello! Saw [this issue](https://github.com/TheLastBen/fast-stable-diffusion/issues/2394) which is very similar to mine, but it seems like the verdict in that one is that the users were using low VRAM GPUs. However I still think there still is a bug here. To test this out, I tried running A1111 with SDXL 1.0 + [refiner extension](https://github.com/wcde/sd-webui-refiner) on a Google colab notebook with the A100 option (40 VRAM) but I'm still crashing. 

This screenshot shows my generation settings:
<img width="1777" alt="image" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/12366468/54616ce3-5bd7-4aa1-99a6-ea6fd36e1883">

When i click on 'Generate', the logging below indicates that I can load the model, but the notebook cell terminates after 1-2 mins without throwing an exception and without any generation. Below is all the traceback I get. If it helps, my google colab doesn't crash completely, it's just the  `Run A1111` cell that stops running, causing the UI to timeout.

```Creating model from config: /content/gdrive/MyDrive/stable_diffusion_automatic_1111/sd/stablediffusion/generative-models/configs/inference/sd_xl_base.yaml
Applying attention optimization: xformers... done.
Model loaded in 191.4s (load weights from disk: 129.1s, load config: 3.1s, create model: 14.3s, apply weights to model: 41.1s, calculate empty prompt: 3.6s).
terminate called without an active exception```

**Comment by TheLastBen** [comment]
Use high-RAM

**Comment by weilintuye95** [comment]
ohh interesting, will try that and see! thank you!

**Comment by weilintuye95** [comment]
Closing this because it worked! Thanks again! For those who are starting out and running into the same issue as well -- if you do a 1-time purchase of credits on google colab (but don't subscribe to the google colab subscription) you don't get the option to run a 'high-ram' instance so SDXL and other large models won't run for you (or will be a pain to run) with a1111
