### ISSUE TITLE
Update on Previous Issue and New Query: LORA Files

### ISSUE THREAD

**Issue by spare122001** [TheLastBen/fast-stable-diffusion#2585]
Mr. Ben,

I hope this message finds you well. I wanted to bring to your attention an issue regarding the Runpod Jupyter notebook. It appears that the results obtained using the Runpod Jupyter notebook are of lower quality when compared to the results obtained using the Colab notebook with the stable Diffusion XL 1.0 model.

This disparity in results has raised some concerns, and I believe it is crucial for us to investigate and address this issue promptly. It could potentially impact our ongoing projects and research endeavors.

I kindly request your response to this matter. Your insights and expertise in this area will be invaluable in resolving the problem and ensuring the quality of our work.

Please share your thoughts and observations on this issue at your earliest convenience. Your prompt attention to this matter is greatly appreciated.

Thank you for your cooperation.

**Comment by TheLastBen** [comment]
Hi,
try adding `--upcast-sampling` right after `$configf`, it simulates fp32 results without using `--no-half`

**Comment by spare122001** [comment]
@TheLastBen,

I would like to extend my sincere apologies for any confusion caused by my previous message. In my earlier communication, I did not intend to refer to the resolution quality of the images generated. Instead, my concern revolves around the artistic depth and quality inherent in the images produced using the Runpod Jupyter Notebook. I have observed a disparity in the artistic merit of these images when compared to those generated through your Google Colab Notebook and the Clipdrop Stable Diffusion platform.

I kindly request that you take a moment to review the Runpod Jupyter Notebook personally. This firsthand assessment will provide you with a better understanding of the matter at hand. To aid in your evaluation, I have attached two images below, both generated from the same prompt, for demonstrative purposes.

Thank you for your attention to this matter, and I look forward to your insights.

Sincerely

![image.png](https://github.com/TheLastBen/fast-stable-diffusion/assets/145541213/7e24707f-19f9-4721-afea-08fb1c593667)

![image (1).jpg](https://github.com/TheLastBen/fast-stable-diffusion/assets/145541213/080aff3b-1308-4585-9431-264b9dee5f3f)

**Comment by TheLastBen** [comment]
What are your settings ? sampler, resolution, cfg scale, steps

**Comment by spare122001** [comment]
@TheLastBen,

I hope this message finds you well. I would like to express my gratitude for your assistance in resolving the previous issue. To provide context, I had been utilizing the DPM++ 2M Karras Sampler with 40 steps and CFG 5 at a resolution of 512x512. The issue was successfully resolved when I adjusted the CFG to 9.

However, I find myself facing a new challenge. I recently downloaded my LORA file from civit.ai, and the download process to the Stable Diffusion WebUI's LORA folder was seemingly successful. Unfortunately, these files are not appearing in the webui LORA section as expected.

I am reaching out to seek your guidance on this matter. If you could kindly advise me on the appropriate steps to rectify this situation, it would be greatly appreciated.

For illustrative purposes, I have attached two images to this message.

Once again, thank you for your continued support.

Warm regards

![Screenshot_2023-09-20-21-50-20-356.png](https://github.com/TheLastBen/fast-stable-diffusion/assets/145541213/81e11da7-2153-41ba-a365-2de23bc31f8e)

![Screenshot_2023-09-20-21-58-50-403.png](https://github.com/TheLastBen/fast-stable-diffusion/assets/145541213/1abef12f-f30b-430e-8d85-2717781ae1d2)

**Comment by TheLastBen** [comment]
SDXL native resolution is 1024x1024, anything lower could result in a loss of quality
