### ISSUE TITLE
Problem with VAE on Runpod (Error)

### ISSUE THREAD

**Issue by AresaiNSFW** [TheLastBen/fast-stable-diffusion#2606]
RuntimeError: "log_vml_cpu" not implemented for 'Half'. This error appears when I try to use inpaint with vae-ft-mse-840000-ema-prunedsafetensors activated. I tried adding --no-half to the webui-user.bat command lines, saved it and when I opened the SD it didn't seem to work. The same thing happened for the dark theme command that I tried to put in the command lines. Can you help me? I'm using fast-stable-diffusion on runpod.

![Capturar](https://github.com/TheLastBen/fast-stable-diffusion/assets/147346179/8e9c7b7e-4e7b-4649-8a54-118ed755eeb4)

**Comment by TheLastBen** [comment]
add the argument after `!python /workspace/sd/stable-diffusion-webui/webui.py $configf`
like : 
`!python /workspace/sd/stable-diffusion-webui/webui.py $configf --no-half`
