### ISSUE TITLE
Not generate class image in the old method

### ISSUE THREAD

**Issue by wilzamguerrero** [TheLastBen/fast-stable-diffusion#263]
Hi, thank you so much for this amazing tool is really nice, only 2 things first, don't work the generating of class image in the old method, i test the new method and don't work really well for me, and the old method work really well but now don't generate the class image, begin with the steps for training but don't work this part, maybe you can put this part for generate this image in other button, and the second things is more a suguerenci if is possible in the part of start dream both, can put a string for the save folder and the class image folder for customize this path. Thank you so much .

is hare some pics with this.

![image](https://user-images.githubusercontent.com/110712636/198339379-f6973bfa-50e6-499f-964d-2115d7d5fc4d.png)
![image](https://user-images.githubusercontent.com/110712636/198339503-13b146bf-bcd6-47b4-a7c0-3ba2b37fd41a.png)
![image](https://user-images.githubusercontent.com/110712636/198339571-7c0a1636-5a86-474b-8502-fd191e1906a7.png)

**Comment by kaspars-vilde** [comment]
Same here. Fast method generates for me shit model (trying on same pictures and settings i used in previous notebook with stable diff 1-4) and old method generates atrocious, unusable model(nightmare material). With previous Notebook with stable diffusion model 1-4 everything was fine. I definitely don't know how to use this notebook, not an expert, but maybe you can share the old notebook or instructions how to adapt old method with this latest notebook?

**Comment by kaspars-vilde** [comment]
You call that instructions? It's simple for you, because you made the notebook. Why even bother putting something public if you don't want to users to use it..
These are simple instructions - https://github.com/AlbertSuarez/dreambooth-stable-diffusion

**Comment by TheLastBen** [comment]
if you can't follow 2 main steps, literally 2 simple steps, then it's your problem, and it's not up tome to fix that.
