### ISSUE TITLE
Checkpoint model by default?

### ISSUE THREAD

**Issue by iaclaudioia8** [TheLastBen/fast-stable-diffusion#2639]
How can I modify the model loaded by default?

instead of Stable diffusion XL, I want to load another by default. 

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/141835147/7d835f0e-4d0b-44f3-8205-d4546b2a4b7b)

**Comment by TheLastBen** [comment]
use its link in the "model download" cell

**Comment by iaclaudioia8** [comment]
But I have the model already downloaded, I just want to set to default this model.

**Comment by TheLastBen** [comment]
It won't redownload it if it already exists

**Comment by iaclaudioia8** [comment]
I understand thank you so much for clarify, it would be very good if in a future was possible choose with model you want start. Sometime it takes a lot time to change change from one to the other
