### ISSUE TITLE
Error on the collab when trying to test the trained model: Syntax error

### ISSUE THREAD

**Issue by JimZeeKing** [TheLastBen/fast-stable-diffusion#265]
File ["<ipython-input-14-3fc9c65c7ae3>"](https://localhost:8080/#), line 29
    if Use_New_Fast_Method= "No":
                          ^
SyntaxError: invalid syntax

**Comment by TheLastBen** [comment]
i'll fix it

**Comment by TheLastBen** [comment]
if you don't want to refresh the notebook just change the line like this : 
`if Use_New_Fast_Method=="No":`

**Comment by JimZeeKing** [comment]
Thanks!

**Comment by JimZeeKing** [comment]
Great work by the way, having a blast with my friends!

**Comment by TheLastBen** [comment]
Thanks, glad to hear that
