### ISSUE TITLE
Question about instance_prompt and class_prompt (not an issue)

### ISSUE THREAD

**Issue by robertwt7** [TheLastBen/fast-stable-diffusion#2702]
couple of question about the implementation because I'm curious:

- it doesn't seem like `class_prompt` is being used in the parameter of dreambooth training, is that normal? I'm curious because in most tutorials, it is always required.

- for the `instance_prompt` as well, in the code it is set as `--instance_prompt="$PT" \` , Where $PT variable is only set once as ""? So its basically an empty string? Where does it set itself to use the image name as the identifier?

@TheLastBen , sorry if this is not the right place to ask. i will close the issue straightaway after. i'm curious and wanted to learn. thanks!

**Comment by TheLastBen** [comment]
class prompt is used for regularization, these notebook do not use regularization as it is deemed ineffective, as for the instance prompt, it is the images filenames instead of `--instance_prompt="$PT"`

**Comment by robertwt7** [comment]
thanks for clarifying @TheLastBen ,

 so the `--instance_prompt="$PT"` is redundant in this case? because it is being passed to the `train_dreambooth.py` at both `train_only_unet` and `dump_only_textenc` function

**Comment by TheLastBen** [comment]
`--instance_prompt` is being overridden with the images filenames used as captions

**Comment by robertwt7** [comment]
right, thanks for your answer. is this being overriden in the `train_dreambooth.py`? because i can still see that `$PT` (empty string) is being passed in as parameter @TheLastBen
