### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Kicher2006** [TheLastBen/fast-stable-diffusion#2732]
After running the code, the following error occurs when clicking on the link: 504 Gateway Time-out
What can I do about it? Does anyone else have the same problem?
![Screenshot_3](https://github.com/TheLastBen/fast-stable-diffusion/assets/140689532/008acdc8-064e-4547-ab3d-87c9cf5902a6)

**Comment by ranma825** [comment]
I get the same 504 error. Google colab environment.

**Comment by omar3737** [comment]
facing same issue

**Comment by Rimuru79807980** [comment]
I also have the same problem and I don't know the solution
