### ISSUE TITLE
ComfyUI Paperspace notebook; Error creating widget: could not find model

### ISSUE THREAD

**Issue by davedaverave** [TheLastBen/fast-stable-diffusion#2735]
While running this code on paperspace:
# Install the dependencies

force_reinstall= True

# Set to true only if you want to install the dependencies again.

#--------------------
with open('/dev/null', 'w') as devnull:import requests, os, importlib;open('/notebooks/mainppsComfy.py', 'wb').write(requests.get('https://huggingface.co/datasets/TheLastBen/PPS/raw/main/Scripts/mainppsComfy.py').content);os.chdir('/notebooks');import mainppsComfy;importlib.reload(mainppsComfy);from mainppsComfy import *;Deps(force_reinstall)

I get the message "Error creating widget: could not find model
"

And when i start COmfy the webpage is notfound 404 error...

**Comment by TheLastBen** [comment]
does the issue still persist ?
