### ISSUE TITLE
port 6006

### ISSUE THREAD

**Issue by ynekotann** [TheLastBen/fast-stable-diffusion#2750]
I have this problem after the 24/02 PaperSpace maintenance.

Does any one know how to solve this?

Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/notebooks/sd/stable-diffusion-webui/webui.py", line 79, in webui
    app, local_url, share_url = shared.demo.launch(
  File "/usr/local/lib/python3.9/dist-packages/gradio/blocks.py", line 1899, in launch
    ) = networking.start_server(
  File "/usr/local/lib/python3.9/dist-packages/gradio/networking.py", line 169, in start_server
    raise OSError(
OSError: Cannot find empty port in range: 6006-6006. You can specify a different port by setting the GRADIO_SERVER_PORT environment variable or passing the `server_port` parameter to `launch()`.

Even if I create a new project from scratch it still getting this problem;

**Comment by altccount** [comment]
Affirmative!

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
it seems to be back to working now

**Comment by ynekotann** [comment]
@TheLastBen I started another project from the scratch, I followed the step you provide to put the repository link in the "Workspace URL" and I still have the same error. The funny thing is that I have another paperspace and I'm not having any problems with it.

**Comment by altccount** [comment]
In paperspace:

`ConnectionResetError                      Traceback (most recent call last)
Cell In [1], line 8
      3 force_reinstall= False
      5 # Set to true only if you want to install the dependencies again.
      6 
      7 #--------------------
----> 8 with open('/dev/null', 'w') as devnull:import requests, os, time, importlib;open('/notebooks/mainpaperspaceA1111.py', 'wb').write(requests.get('https://huggingface.co/datasets/TheLastBen/PPS/raw/main/Scripts/mainpaperspaceA1111.py').content);os.chdir('/notebooks');time.sleep(3);import mainpaperspaceA1111;importlib.reload(mainpaperspaceA1111);from mainpaperspaceA1111 import *;Deps(force_reinstall)

File /notebooks/mainpaperspaceA1111.py:46, in Deps(force_reinstall)
     44 call('wget -q -i https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/Dependencies/aptdeps.txt', shell=True)
     45 call('dpkg -i *.deb', shell=True, stdout=open('/dev/null', 'w'))
---> 46 depsinst("https://huggingface.co/TheLastBen/dependencies/resolve/main/ppsdeps.tar.zst", "/deps/ppsdeps.tar.zst")
     47 call('tar -C / --zstd -xf ppsdeps.tar.zst', shell=True, stdout=open('/dev/null', 'w'))
     48 call("sed -i 's@~/.cache@/notebooks/cache@' /usr/local/lib/python3.9/dist-packages/transformers/utils/hub.py", shell=True)

File /notebooks/mainpaperspaceA1111.py:81, in depsinst(url, dst)
     79 with open(dst, "wb") as f:
     80     while True:
---> 81         buffer = u.read(8192)
     82         if len(buffer) == 0:
     83             break

File /usr/lib/python3.9/http/client.py:463, in HTTPResponse.read(self, amt)
    460 if amt is not None:
    461     # Amount is given, implement using readinto
    462     b = bytearray(amt)
--> 463     n = self.readinto(b)
    464     return memoryview(b)[:n].tobytes()
    465 else:
    466     # Amount is not given (unbounded read) so we must check self.length
    467     # and self.chunked

File /usr/lib/python3.9/http/client.py:507, in HTTPResponse.readinto(self, b)
    502         b = memoryview(b)[0:self.length]
    504 # we do not use _safe_read() here because this may be a .will_close
    505 # connection, and the user is reading more bytes than will be provided
    506 # (for example, reading in 1k chunks)
--> 507 n = self.fp.readinto(b)
    508 if not n and b:
    509     # Ideally, we would raise IncompleteRead if the content-length
    510     # wasn't satisfied, but it might break compatibility.
    511     self._close_conn()

File /usr/lib/python3.9/socket.py:704, in SocketIO.readinto(self, b)
    702 while True:
    703     try:
--> 704         return self._sock.recv_into(b)
    705     except timeout:
    706         self._timeout_occurred = True

File /usr/lib/python3.9/ssl.py:1242, in SSLSocket.recv_into(self, buffer, nbytes, flags)
   1238     if flags != 0:
   1239         raise ValueError(
   1240           "non-zero flags not allowed in calls to recv_into() on %s" %
   1241           self.__class__)
-> 1242     return self.read(nbytes, buffer)
   1243 else:
   1244     return super().recv_into(buffer, nbytes, flags)

File /usr/lib/python3.9/ssl.py:1100, in SSLSocket.read(self, len, buffer)
   1098 try:
   1099     if buffer is not None:
-> 1100         return self._sslobj.read(len, buffer)
   1101     else:
   1102         return self._sslobj.read(len)

ConnectionResetError: [Errno 104] Connection reset by peer
`
