### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by gilroff** [TheLastBen/fast-stable-diffusion#2754]
==============================================================================
You are running torch 2.1.0+cu121.
The program is tested to work with torch 2.1.2.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
=================================================================================
You are running xformers 0.0.23+3f74d96.d20231218.
The program is tested to work with xformers 0.0.23.post1.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
Civitai Helper: Get Custom Model Folder
2024-03-02 06:11:26,810  (INFO)     [Unprompted] Loading Unprompted v10.6.0 by Therefore Games
2024-03-02 06:11:26,811  (INFO)     [Unprompted] Initializing Unprompted shortcode parser...
2024-03-02 06:11:27,343  (INFO)     [Unprompted] Finished loading in 0.5319509506225586 seconds.
ControlNet preprocessor location: /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-03-02 06:11:28,538 - ControlNet - INFO - ControlNet v1.1.440
2024-03-02 06:11:29,117 - ControlNet - INFO - ControlNet v1.1.440
Loading weights [d8c8ad686a] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/pornmasterPro_proDPOV1.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
2024-03-02 06:11:36,168 - ControlNet - INFO - ControlNet UI callback registered.
Civitai Helper: Set Proxy: 
Running on public URL: https://5c0f2c603b418db0d1.gradio.live/
✔ Connected
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 109, in webui
    ui.setup_ui_api(app)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 1242, in setup_ui_api
    app.mount("/webui-assets", fastapi.staticfiles.StaticFiles(directory=launch_utils.repo_dir('stable-diffusion-webui-assets')), name="webui-assets")
  File "/usr/local/lib/python3.10/dist-packages/starlette/staticfiles.py", line 57, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory '/content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets' does not exist
Loading VAE weights specified in settings: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 30.0s (load weights from disk: 2.7s, create model: 0.9s, apply weights to model: 23.0s, load VAE: 1.0s, load textual inversion embeddings: 1.1s, calculate empty prompt: 1.1s).
Killing tunnel 127.0.0.1:7860 <> https://5c0f2c603b418db0d1.gradio.live/

**Comment by Juan-Antonio-Prieto-Hipolito** [comment]
I have the same problem, but I don't know if it is a problem with the colab or a problem with automatic1111

**Comment by Nathan2055** [comment]
I’m experiencing this as well, looks like some kind of an issue with the dependency package being downloaded not including a copy of the [stable-diffusion-webui-assets repository](https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets).

A temporary fix is to add the following to a Jupyter cell above the “Start Stable Diffusion” cell:

```
!rm -rf /tmp/sd-assets

!mkdir /tmp/sd-assets

!curl -C - -L -o /tmp/sd-assets/assets.zip https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets/archive/refs/heads/master.zip

!mkdir /workspace/sd/stable-diffusion-webui/repositories

!unzip /tmp/sd-assets/assets.zip -d /workspace/sd/stable-diffusion-webui/repositories

!mv /workspace/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets-master /workspace/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets
```

This manually downloads that repo as a ZIP and moves it to the correct location so the rest of the launch script can find it.

**Comment by Pero0407** [comment]
I'm facing the same issue where the Gradio tunnel shuts down immediately after loading the model. This problem wasn't happening yesterday, so I suspect it might be due to some updates in Colab or automatic111.

**Comment by ArtHommage** [comment]
> I’m experiencing this as well, looks like some kind of an issue with the dependency package being downloaded not including a copy of the [stable-diffusion-webui-assets repository](https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets).
> 
> A temporary fix is to add the following to a Jupyter cell above the “Start Stable Diffusion” cell:
> 
> ```
> !rm -rf /tmp/sd-assets
> 
> !mkdir /tmp/sd-assets
> 
> !curl -C - -L -o /tmp/sd-assets/assets.zip https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets/archive/refs/heads/master.zip
> 
> !mkdir /workspace/sd/stable-diffusion-webui/repositories
> 
> !unzip /tmp/sd-assets/assets.zip -d /workspace/sd/stable-diffusion-webui/repositories
> 
> !mv /workspace/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets-master /workspace/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets
> ```
> 
> This manually downloads that repo as a ZIP and moves it to the correct location so the rest of the launch script can find it.

mkdir: cannot create directory ‘/workspace/sd/stable-diffusion-webui/repositories’: No such file or directory
Archive:  /tmp/sd-assets/assets.zip
6f7db241d2f8ba7457bac5ca9753331f0c266917
checkdir:  cannot create extraction directory: /workspace/sd/stable-diffusion-webui/repositories
           No such file or directory
mv: cannot stat '/workspace/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets-master': No such file or directory

**Comment by leammurphy** [comment]
as a temp fix i added `mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets` after connecting to google drive.

**Comment by leammurphy** [comment]
> as a temp fix i added `mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets` after connecting to google drive.

https://github.com/TheLastBen/fast-stable-diffusion/issues/2755#issuecomment-1974666968

**Comment by olowwwlolololo** [comment]
Hello. Can someone just share a customized copy of the notebook? I don't understand how I can solve this problem, I'm not an IT guy

**Comment by mdlieber99** [comment]
> as a temp fix i added
> `mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets`
> then I cloned the repo into that folder
> `cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets`
> `git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git`
> after connecting to google drive.

Is this something you are adding in the automatic1111 notebook or are you adding this on your computer.  If the latter, do you know if this will work on a Mac?  thanks!

**Comment by Stylenazar** [comment]
Could you help me. 
What am I doing wrong?
<img width="753" alt="Screenshot 2024-03-02 193400" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/126091008/3c42f34e-4925-4bac-a150-2e7610e0fc7b">

Thnx

**Comment by PaoloPgn** [comment]
This is what I used and worked for me
>!mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets; cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets; git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git

**Comment by Stylenazar** [comment]
> This is what I used and worked for me
> 
> > !mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets; cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets; git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git

Yes it work for me to, thank you

**Comment by rassledassle** [comment]
I used the temp fix, and now I'm getting this error message when I try and run the model. Any recommendations?

<img width="807" alt="Screenshot 2024-03-02 at 3 36 01 PM" src="https://github.com/TheLastBen/fast-stable-diffusion/assets/161976282/2c16e241-bc55-4029-80f6-d49e72866d8d">

**Comment by Kaka32793784** [comment]
>Stylenazar

When coding with "Google Colab", you need to add a "!" mark first.

`!mkdir -p /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets`

`!cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets`
`!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui-assets.git`

Please try running it again as .
Although the error message was not resolved, I was able to launch the Stable diffusion Web-UI.
I'd like to wait this way until a full-fledged fix is worked out.

**Comment by olowwwlolololo** [comment]
> Вы могли бы помочь мне. Что я делаю не так? <img alt="Скриншот 02.03.2024 193400" width="753" src="https://private-user-images.githubusercontent.com/126091008/309490712-3c42f34e-4925-4bac-a150-2e7610e0fc7b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0MzkyMDksIm5iZiI6MTcwOTQzODkwOSwicGF0aCI6Ii8xMjYwOTEwMDgvMzA5NDkwNzEyLTNjNDJmMzRlLTQ5MjUtNGJhYy1hMTUwLTJlNzYxMGUwZmM3Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QwNDA4MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjEwZDBiM2RlMDlmOGI5NzNhNGE1MDFkNDU4NjJkY2E2Y2I1ZGEyZDQyMzc3MWZkMzNlYWMwNjZkMDY1ZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D9-aKwjRua6u_hIEsFgzbBSeedYr5Pgk9zkg5N5H2Wk">
> 
> Спасибо

I didn't understand at all what to do with the proposed code, but your screenshot helped me! Thank you very much!

**Comment by Yamacan-39** [comment]
I appreciate all your comments.

**Comment by Kaka32793784** [comment]
It seems that Mr. BEN has made changes to the program.
Although the following message is output, it seems that it can be started without entering the temporary correction command.
The error messages currently output are as follows.

"*** Error executing callback ui_tabs_callback for /content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum.py
     Traceback (most recent call last):
       File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_callbacks.py", line 180, in ui_tabs_callback
         res += c.callback() or []
       File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/ui_right.py", line 92, in on_ui_tabs
         deforum_gallery, generation_info, html_info, _ = create_output_panel("deforum", opts.outdir_img2img_samples)
     TypeError: cannot unpack non-iterable OutputPanel object

---"

**Comment by KyotoLyon** [comment]
Neither of the two codes is working. I can even connect and open the Gradio link, but then it gives a connection error
"Error
Connection errored out."

**Comment by KyotoLyon** [comment]
Sometimes when it connects, the same errors as this post appear:
https://github.com/TheLastBen/fast-stable-diffusion/issues/2773#issue-2166677399
