### ISSUE TITLE
AttributeError: module 'modules.hypernetworks.ui' has no attribute 'keys'

### ISSUE THREAD

**Issue by MasterDenis** [TheLastBen/fast-stable-diffusion#277]
Unless Mistaken thats the Error Message, Here is the Window
![image](https://user-images.githubusercontent.com/61897713/198729618-3d57e5a1-c377-42b1-87a1-4362cae86971.png)
Leading to the local link not showing.

PS: Happens in Both DreamBooth and Fast Diffusion Colab Notebooks.

**Comment by TheLastBen** [comment]
Check the box update repo and use the latest colab from the original link instead of saving it to your gdrive

**Comment by MasterDenis** [comment]
> 

Hey There! I always do both!

Thanks for the Notebook by the way, you do an amazing work!
