### ISSUE TITLE
UI loads then crashes

### ISSUE THREAD

**Issue by alexjl90210** [TheLastBen/fast-stable-diffusion#2772]
You are running torch 2.1.0+cu121.
The program is tested to work with torch 2.1.2.
UI loads then crashes.
Tunnel kills after 30 seconds
 RuntimeError: Directory '/content/gdrive/MyDrive/sd/stable-diffusion-webui/repositories/stable-diffusion-webui-assets' does not exist

Was working until Friday last week.

**Comment by mr-mitt** [comment]
I just made the folders in Drive that dont exist and it seems to be working! Now having issues with Deforum extension :-(

make this folder first: repositories
then make 'stable-diffusion-webui-assets' in that folder.

**Comment by alexjl90210** [comment]
yes that's sorted it for me too.  I can't understand why so simple fix it needed.
