### ISSUE TITLE
Unable to Launch ComfyUI in Paperspace, no tensorboard server

### ISSUE THREAD

**Issue by dreamlogic-X** [TheLastBen/fast-stable-diffusion#2786]
Hi I'm unable to launch ComfyUI at all in Paperspace, both with the most up to date repo (updated today) and with the last repo. This was working yesterday.

The most up to date repo gives me this, with no tensorboard linK:

```
Total VRAM 81229 MB, total RAM 90499 MB
xformers version: 0.0.16rc404
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A100-SXM4-80GB : 
VAE dtype: torch.float32
Using xformers cross attention
Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
Starting server

To see the GUI go to: http://0.0.0.0:6006/
```

The previous repo gives a tensorboard link, but when clicked it goes to a "404 page not found" page.

Would appreciate any help in solving this.

**Comment by pdannell** [comment]
I am seeing this also now, was just working about 2 days ago.

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
Paperspace issue fixed

**Comment by pdannell** [comment]
> issue fixed

I can confirm it's fixed for me.

**Comment by dreamlogic-X** [comment]
Thanks Ben!
