### ISSUE TITLE
Google Colab Pro - xfromers needs to be reinstalled

### ISSUE THREAD

**Issue by SDPDVADER** [TheLastBen/fast-stable-diffusion#2788]
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.0+cu121 with CUDA 1202 (you have 2.2.1+cu121)
    Python  3.10.12 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by HaikenEdge** [comment]
For reference, have this on Google Colab Pro as well.

**Comment by FackJox** [comment]
Also getting this issue, have tried some old fixes/workarounds resulting in the same error

**Comment by KyotoLyon** [comment]
same error here

**Comment by Maximb1985** [comment]
It's the same.

**Comment by Maximb1985** [comment]
Found a temporary solution in old records. Pardon my English. You need to insert this text into 
"Connect Google Drive":

!pip install lmdb
!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118

![аыв](https://github.com/TheLastBen/fast-stable-diffusion/assets/134276813/79c890d7-4d68-44b2-afef-827642aa7f60)

**Comment by HaikenEdge** [comment]
> Found a temporary solution in old records. Pardon my English. You need to insert this text into "Connect Google Drive":
> 
> !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118

Looks like a working hotfix.

**Comment by KyotoLyon** [comment]
> Found a temporary solution in old records. Pardon my English. You need to insert this text into "Connect Google Drive":
> 
> !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118

I used the code and it seems to be working

**Comment by Ptentacle1** [comment]
This didn't work for me. Everything loads fine, but as soon as the webui is launched and I try to generate anything, the gradio connection just gets killed and I get the "connection errored out." Then if I try to relaunch SD I get a miles long list of error messages.

**Comment by DjNastyMagic** [comment]
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs: query : shape=(2, 6144, 8, 40) (torch.float32) key : shape=(2, 6144, 8, 40) (torch.float32) value : shape=(2, 6144, 8, 40) (torch.float32) attn_bias : <class 'NoneType'> p : 0.0 `decoderF` is not supported because: xFormers wasn't build with CUDA support attn_bias type is <class 'NoneType'> operator wasn't built - see `python -m xformers.info` for more info `flshattF@0.0.0` is not supported because: xFormers wasn't build with CUDA support requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old) dtype=torch.float32 (supported: {torch.bfloat16, torch.float16}) operator wasn't built - see `python -m xformers.info` for more info `tritonflashattF` is not supported because: xFormers wasn't build with CUDA support requires device with capability > (8, 0) but your GPU has capability (7, 5) (too old) dtype=torch.float32 (supported: {torch.bfloat16, torch.float16}) operator wasn't built - see `python -m xformers.info` for more info triton is not available requires GPU with sm80 minimum compute capacity, e.g., A100/H100/L4 Only work on pre-MLIR triton for now `cutlassF` is not supported because: xFormers wasn't build with CUDA support operator wasn't built - see `python -m xformers.info` for more info `smallkF` is not supported because: max(query.shape[-1] != value.shape[-1]) > 32 xFormers wasn't build with CUDA support operator wasn't built - see `python -m xformers.info` for more info unsupported embed per head: 40
Time taken: 1.1 sec.

**Comment by osm14wave** [comment]
> Found a temporary solution in old records. Pardon my English. You need to insert this text into "Connect Google Drive":
> 
> !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118

Unfortunately I got an error. Maybe we need to update the text? 181→121

**Comment by momoci0704** [comment]
I got the same error.

**Comment by A3734** [comment]
me too (TT

**Comment by olowwwlolololo** [comment]
Hello. Please share screenshots of your notebook with me. I don't understand what to do with the provided code

**Comment by TooAiArt** [comment]
> Hello. Please share screenshots of your notebook with me. I don't understand what to do with the provided code

In the connect google drive cell I have put under "--#@markdown ---":

!pip install lmdb
!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download. pytorch.org/whl/cu118

and at the moment it works for me

**Comment by olowwwlolololo** [comment]
> > Hello. Please share screenshots of your notebook with me. I don't understand what to do with the provided code
> 
> In the connect google drive cell I have put under "--#@markdown ---":
> 
> !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download. pytorch.org/whl/cu118
> 
> and at the moment it works for me

I still need a screenshot. 🗿

**Comment by A3734** [comment]
I think this method is fine for now. Please insert the code before "Connect Google Drive" like in the screenshot.

!pip install lmdb
!pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118
![スクリーンショット 2024-03-14 204144](https://github.com/TheLastBen/fast-stable-diffusion/assets/155977409/837a15e7-107a-44fc-8dc5-e61fc857feed)

**Comment by momoci0704** [comment]
Installing collected packages: lmdb
Successfully installed lmdb-1.4.1
ERROR: Invalid requirement: '//download.pytorch.org/whl/cu118'
Hint: It looks like a path. File '//download.pytorch.org/whl/cu118' does not exist.

I get this error message

**Comment by BlueheIix** [comment]
> Installing collected packages: lmdb Successfully installed lmdb-1.4.1 ERROR: Invalid requirement: '//download.pytorch.org/whl/cu118' Hint: It looks like a path. File '//download.pytorch.org/whl/cu118' does not exist.
> 
> I get this error message

remove the space in the pytorch url

**Comment by olowwwlolololo** [comment]
> I think this method is fine for now. Please insert the code before "Connect Google Drive" like in the screenshot.
> 
> !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118 ![スクリーンショット 2024-03-14 204144](https://private-user-images.githubusercontent.com/155977409/312823255-837a15e7-107a-44fc-8dc5-e61fc857feed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MjY1OTcsIm5iZiI6MTcxMDQyNjI5NywicGF0aCI6Ii8xNTU5Nzc0MDkvMzEyODIzMjU1LTgzN2ExNWU3LTEwN2EtNDRmYy04ZGM1LWU2MWZjODU3ZmVlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNDI0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTg2ZGU2MjUzNjRmYTJhMjA5OGRlNmE1NDcyMjUzMjNiYjA0YzcwZDdmNzhkMjBlMDNkYWRjYjg0ZGRkNTI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6PqLgbDXr12N7Vg167HZuaHNu0aF0qcJ7usxDHI9Wlw)

Thank you so much for the screenshot! I didn't understand at all what to do with the provided code, but your screenshot helped me a lot.

**Comment by dymension** [comment]
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/1997716/14582a6f-4bc5-401c-80d0-65f710fe7af5)

**Comment by Azura-13** [comment]
Same

**Comment by aifantasyglam** [comment]
> Found a temporary solution in old records. Pardon my English. You need to insert this text into "Connect Google Drive":
> 
> !pip install lmdb !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download.pytorch.org/whl/cu118

It works, thanks a lot

**Comment by osm14wave** [comment]
> Works great, thanks Maxim



> How about this code? !pip install -q torch==2.1.2+cu121 torchvision==0.16.2+cu121 torchaudio==2.1.2+cu121 torchtext==0.16.2 torchdata==0.7.1 --extra-index-url https://download.pytorch.org/whl/cu121 -U

It works, thanks a lot!

**Comment by aifantasyglam** [comment]
> Putting the text in front of or in the "Connect Google Drive" does not change the error. Thanks a lot for your help.

put the code befor the "start stable diffusion"

![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/162564405/561c78a6-ad1f-417b-a3e8-7432bd6c42ed)

**Comment by momoci0704** [comment]
The image can now be generated.
Thank you all!

**Comment by TheLastBen** [comment]
fixed, update to the latest notebook and you won't need to install any additional package

**Comment by marsellerai** [comment]
Use rundiffusion.com. I am happy with that.

**Comment by LIQUIDMIND111** [comment]
> !pip install lmdb
> !pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0 torchtext==0.16.0+cpu torchdata==0.7.0 --index-url https://download. pytorch.org/whl/cu118

how do i update to the latest note book? i thought if you click on the collab section it will take you to the latest version of dreambooth? or where do i have to click then?

**Comment by TheLastBen** [comment]
Simply click on the thumbnail on the main page of the repo

**Comment by aifantasyglam** [comment]
Hello everyone, there is a new update that is required, what part of the code should I modify...?

Message:
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.1+cu121 with CUDA 1201 (you have 2.1.0+cu118)
    Python  3.10.13 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

**Comment by aifantasyglam** [comment]
> Hello everyone, there is a new update that is required, what part of the code should I modify...?
> 
> Message: WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 2.2.1+cu121 with CUDA 1201 (you have 2.1.0+cu118) Python 3.10.13 (you have 3.10.12) Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers) Memory-efficient attention, SwiGLU, sparse and more won't be available. Set XFORMERS_MORE_DETAILS=1 for more details

Hello again everyone, according the documentation, using only this line is enough to solve the issue:
`!pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121`

and is true, I tried and it worked

**Comment by HaikenEdge** [comment]
> > Hello everyone, there is a new update that is required, what part of the code should I modify...?
> > Message: WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 2.2.1+cu121 with CUDA 1201 (you have 2.1.0+cu118) Python 3.10.13 (you have 3.10.12) Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers) Memory-efficient attention, SwiGLU, sparse and more won't be available. Set XFORMERS_MORE_DETAILS=1 for more details
> 
> Hello again everyone, according the documentation, using only this line is enough to solve the issue: `!pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121`
> 
> and is true, I tried and it worked

Fixed for now; I imagine @TheLastBen will make an update to the notebook to resolve the issue in due time.

**Comment by aifantasyglam** [comment]
> > > Hello everyone, there is a new update that is required, what part of the code should I modify...?
> > > Message: WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 2.2.1+cu121 with CUDA 1201 (you have 2.1.0+cu118) Python 3.10.13 (you have 3.10.12) Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers) Memory-efficient attention, SwiGLU, sparse and more won't be available. Set XFORMERS_MORE_DETAILS=1 for more details
> > 
> > 
> > Hello again everyone, according the documentation, using only this line is enough to solve the issue: `!pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121`
> > and is true, I tried and it worked
> 
> Fixed for now; I imagine @TheLastBen will make an update to the notebook to resolve the issue in due time.

I guess so

**Comment by TheLastBen** [comment]
fixed

**Comment by aifantasyglam** [comment]
> fixed

Thanks a lot

**Comment by aifantasyglam** [comment]
Hello everyone, I would like to request your help, does anyone knows the reason and the solution for this....?

`Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 39, in imports
    from modules import processing, gradio_extensons, ui  # noqa: F401
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 18, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 5, in <module>
    from modules import devices, sd_hijack_optimizations, shared, script_callbacks, errors, sd_unet, patches
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_optimizations.py", line 13, in <module>
    from modules.hypernetworks import hypernetwork
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/hypernetworks/hypernetwork.py", line 8, in <module>
    import modules.textual_inversion.dataset
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/dataset.py", line 12, in <module>
    from modules import devices, shared, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/images.py", line 22, in <module>
    from modules import sd_samplers, shared, script_callbacks, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 5, in <module>
    from modules import sd_samplers_kdiffusion, sd_samplers_timesteps, sd_samplers_lcm, shared, sd_samplers_common, sd_schedulers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers_kdiffusion.py", line 3, in <module>
    import k_diffusion.sampling
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/__init__.py", line 1, in <module>
    from . import augmentation, config, evaluation, external, gns, layers, models, sampling, utils
  File "/content/gdrive/MyDrive/sd/stablediffusion/src/k-diffusion/k_diffusion/augmentation.py", line 6, in <module>
    from skimage import transform
  File "/usr/local/lib/python3.10/dist-packages/skimage/_shared/lazy.py", line 62, in __getattr__
    return importlib.import_module(f'{package_name}.{name}')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/__init__.py", line 4, in <module>
    from .radon_transform import (radon, iradon, iradon_sart,
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/radon_transform.py", line 6, in <module>
    from ._warps import warp
  File "/usr/local/lib/python3.10/dist-packages/skimage/transform/_warps.py", line 9, in <module>
    from ..measure import block_reduce
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py", line 2, in <module>
    from ._marching_cubes_lewiner import marching_cubes
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_lewiner.py", line 7, in <module>
    from ._marching_cubes_classic import _marching_cubes_classic
  File "/usr/local/lib/python3.10/dist-packages/skimage/measure/_marching_cubes_classic.py", line 3, in <module>
    from . import _marching_cubes_classic_cy
ImportError: cannot import name '_marching_cubes_classic_cy' from partially initialized module 'skimage.measure' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/skimage/measure/__init__.py)`

![image](https://github.com/user-attachments/assets/175adbad-8c44-44c0-8e03-9fa0e99a5ed9)

**Comment by Amit30swgoh** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.3.1+cu121 requires torch==2.3.1, but you have torch 2.4.0+cu121 which is incompatible.
torchvision 0.18.1+cu121 requires torch==2.3.1, but you have torch 2.4.0+cu121 which is incompatible.

**Comment by Amit30swgoh** [comment]
To resolve the dependency conflicts between CUDA, xformers, torch, and torchaudio in your Google Colab environment, you can follow these steps:

Install the Correct Versions:
Ensure that all packages (torch, torchaudio, and torchvision) are compatible with each other and with CUDA 12.1.

Force Install Specific Versions:
You can install specific versions of the packages to resolve the conflicts.

Here's how you can do it:

python
Copy code
# Uninstall conflicting packages first
!pip uninstall -y torch torchaudio torchvision xformers

# Install specific versions compatible with CUDA 12.1
!pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 torchaudio==2.3.1+cu121 --index-url https://download.pytorch.org/whl/cu121
!pip install xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121
Check Installed Versions:
After installation, verify the versions to ensure they are correctly installed:
python
Copy code
import torch
import torchvision
import torchaudio
import xformers

print(f"torch: {torch.__version__}")
print(f"torchvision: {torchvision.__version__}")
print(f"torchaudio: {torchaudio.__version__}")
print(f"xformers: {xformers.__version__}")
Restart the Runtime:
Sometimes, after resolving dependencies, it might be necessary to restart the Colab runtime.
This should resolve the version conflicts between torch, torchaudio, and xformers while ensuring compatibility with CUDA 12.1.

**Comment by aifantasyglam** [comment]
> To resolve the dependency conflicts between CUDA, xformers, torch, and torchaudio in your Google Colab environment, you can follow these steps:
> 
> Install the Correct Versions: Ensure that all packages (torch, torchaudio, and torchvision) are compatible with each other and with CUDA 12.1.
> 
> Force Install Specific Versions: You can install specific versions of the packages to resolve the conflicts.
> 
> Here's how you can do it:
> 
> python Copy code
> 
> # Uninstall conflicting packages first
> !pip uninstall -y torch torchaudio torchvision xformers
> 
> # Install specific versions compatible with CUDA 12.1
> !pip install torch==2.3.1+cu121 torchvision==0.18.1+cu121 torchaudio==2.3.1+cu121 --index-url https://download.pytorch.org/whl/cu121 !pip install xformers==0.0.27.post2 --index-url https://download.pytorch.org/whl/cu121 Check Installed Versions: After installation, verify the versions to ensure they are correctly installed: python Copy code import torch import torchvision import torchaudio import xformers
> 
> print(f"torch: {torch.**version**}") print(f"torchvision: {torchvision.**version**}") print(f"torchaudio: {torchaudio.**version**}") print(f"xformers: {xformers.**version**}") Restart the Runtime: Sometimes, after resolving dependencies, it might be necessary to restart the Colab runtime. This should resolve the version conflicts between torch, torchaudio, and xformers while ensuring compatibility with CUDA 12.1.
> 
> o resolve the conflicts and ensure everything works perfectly, you can use the following code snippet. This script will:
> 
> Upgrade PyTorch to version 2.4.0, which is compatible with CUDA 12.1. Install xFormers compatible with the upgraded PyTorch version. Handle any necessary installations and configurations. Here's the code to run in your Google Colab environment:
> 
> python Copy code
> 
> # Install the necessary dependencies
> !pip3 install torch==2.4.0+cu121 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 !pip3 install --upgrade xformers
> 
> # Verify the installation
> import torch import xformers print(f"PyTorch version: {torch.**version**}") print(f"xFormers version: {xformers.**version**}")
> 
> # Verify the GPU setup
> !nvidia-smi

Hi, I have a questio, is there any command to make an automatic verification and update....???

**Comment by LIQUIDMIND111** [comment]
I don’t know why we have to do so Many things to fix a code that is
supposed to be updated by the author

We are paying money for Google collab and now we need to fix ourselves The
code?? Please.

**Comment by dymension** [comment]
> I don’t know why we have to do so Many things to fix a code that is supposed to be updated by the author We are paying money for Google collab and now we need to fix ourselves The code?? Please.

Are you crazy man ?
You are not paying a penny to The Last ben who is developping this absolutely free for us
You want to complain about your google payment, go cry to Google !

**Comment by LIQUIDMIND111** [comment]
> > I don’t know why we have to do so Many things to fix a code that is supposed to be updated by the author We are paying money for Google collab and now we need to fix ourselves The code?? Please.
> 
> Are you crazy man ? You are not paying a penny to The Last ben who is developping this absolutely free for us You want to complain about your google payment, go cry to Google !

Do You Have Any Idea How Many Times me and many users Have Sent donations To Him? You
Don’t Even Know How Many Years I Have Been using This web Page So You Can Start
Talking Shit About Me

STFU 🖕 Who even ask you for your opinion?

For many years, this Google page has been broken and he wants people to use
runpod and other services are harder to use

If you’re not going to maintain a google collab page, then just remove the page and don’t start
criticizing, we users claiming that the code does not work

How old are you 12? Did your mom gave you your vitamins last night? anyways, who cares anymore about training on 1.5, this is old stuff...... go complain to your daddy.......

**Comment by HaikenEdge** [comment]
First, donations are just that: donations. They're not payment for services rendered or to be rendered, they're given out of the goodness of your heart.

Second, if you look at the main page, in the readme section, Colab is no longer directly linked; Ben officially only links to Paperspace, so I think Colab isn't officially supported anymore, and any merges and updates that happen are usually somebody in the comments finding a solution and Ben merging it in.

**Comment by LIQUIDMIND111** [comment]
> First, donations are just that: donations. They're not payment for services rendered or to be rendered, they're given out of the goodness of your heart.
> 
> Second, if you look at the main page, in the readme section, Colab is no longer directly linked; Ben officially only links to Paperspace, so I think Colab isn't officially supported anymore, and any merges and updates that happen are usually somebody in the comments finding a solution and Ben merging it in.

blablablabla,...... get a life......

**Comment by LIQUIDMIND111** [comment]
> First, donations are just that: donations. They're not payment for services rendered or to be rendered, they're given out of the goodness of your heart.
> 
> Second, if you look at the main page, in the readme section, Colab is no longer directly linked; Ben officially only links to Paperspace, so I think Colab isn't officially supported anymore, and any merges and updates that happen are usually somebody in the comments finding a solution and Ben merging it in.

SAME AS CODING.... did black forest asked for money or donations before releasing the FLUX MODEL? No.... so.... your comments is limited to your own reality, which is incomplete..... MANY COMPANIES and independent programmers do MANY THINGS for free and dont have as many issues as this collab page, which i can see he is NOT maintaining anymore, Bummer, i wonder why... LMAO....

**Comment by LIQUIDMIND111** [comment]
> > I don’t know why we have to do so Many things to fix a code that is supposed to be updated by the author We are paying money for Google collab and now we need to fix ourselves The code?? Please.
> 
> Are you crazy man ? You are not paying a penny to The Last ben who is developping this absolutely free for us You want to complain about your google payment, go cry to Google !

who even asked for your opinion?? the code is BROKEN, is not google's issue, is the owner of this page. so STFU and go cry to mommy.

**Comment by Kemsekov** [comment]
I have used this to update cuda drivers for kaggle T4 and it worked
```py
!echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
!apt update && apt install -y cuda-drivers
```
