### ISSUE TITLE
GOOGLE COLLAB WONT WORK!!!!

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#28]
when training, i will ALWAYS get an error!!! i set it on BOLD

To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 606, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 401, in main
    args.pretrained_model_name_or_path, subfolder="vae", use_auth_token=args.use_auth_token
  File "/usr/local/lib/python3.7/dist-packages/diffusers/modeling_utils.py", line 312, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 160, in from_config
    config_dict = cls.get_config_dict(pretrained_model_name_or_path=pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py", line 217, in get_config_dict
    **f"Error no file named {cls.config_name} found in directory {pretrained_model_name_or_path}."**
**OSError: Error no file named config.json found in directory /content/gdrive/MyDrive/stable-diffusion-v1-4.**
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/gdrive/MyDrive/stable-diffusion-v1-4', '--instance_data_dir=/content/data/eddieman', '--output_dir=/content/models/eddieman', '--instance_prompt=photo of eddieman man', '--seed=12345', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=800']' returned non-zero exit status 1

**Comment by askiiart** [comment]
Some tips for GitHub issues: First, please stop it with all caps and all those exclamation points. Second, in the future please give more descriptive titles.

Kinda unrelated, but you could put your error message in a code block like this:

Text:
\`\`\`
error message here
\`\`\`
Effect:
```
error message here
```

**Comment by 1blackbar** [comment]
It works for me right now , free colab, i have pro on other accounr that trains as well, also to save the models i use shared drives that are unlimited in space storage so when training ends i can just drag and drop the folder with trained weights into my google shared folder. Thanks a lot man!!

**Comment by TheLastBen** [comment]
You haven't accepted the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4

**Comment by TheLastBen** [comment]
@1blackbar you can now use your trained models in one click just by entering the instance name (identifier), I will work on enhancing the webui

**Comment by 1blackbar** [comment]
Thats great bu i have them all in "/content/gdrive/Shareddrives/Dysk1blackbar/AI/models" cause i have unlimited shared drive storage from here https://td.msgsuite.workers.dev/

Works great but do a backup in case they wipe it one day (happened once in 4 years)

15 gb on regular drive is just no enough for ai models to store and code on top of that with weights so id like an separate option to use different path than default mydrive/models , in the meantime ill edit cells myself

**Comment by TheLastBen** [comment]
I will custom path option, and I'll see if the euler sampler is easily implemented with diffusers

**Comment by 1blackbar** [comment]
Can You add a cell to unload gradio and model so we can train again after reviewing results ?

**Comment by TheLastBen** [comment]
when you stop the cell, it will automatically free the VRAM because the gradio is running from a python file, but i will still check if lt's really the case

**Comment by 1blackbar** [comment]
Yes it works fine, i can rerun training
