### ISSUE TITLE
Google Colab Pro | No share link in Start Stable-Diffusion Cell

### ISSUE THREAD

**Issue by HaikenEdge** [TheLastBen/fast-stable-diffusion#2817]
Was working fine last night, but ever since this morning, I'm getting this message when I run the notebook:

```
Loading weights [5dd1c2014e] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/cyberrealistic_v21.safetensors
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio
Startup time: 172.2s (launcher: 0.8s, import torch: 13.5s, import gradio: 1.4s, setup paths: 27.3s, import ldm: 0.8s, initialize shared: 8.6s, other imports: 39.3s, setup codeformer: 0.7s, setup gfpgan: 0.4s, list SD models: 0.8s, load scripts: 20.7s, load upscalers: 1.4s, reload hypernetworks: 1.7s, initialize extra networks: 16.5s, create ui: 36.9s, gradio launch: 0.5s, add APIs: 0.7s).
```

Tried downloading the file, but my anti-virus considers it a threat, then I realized I wouldn't know where to put it anyways since I searched the sd directory and no folder titled "usr" came up.

**Comment by mr-mitt** [comment]
I have this issue as well. using google colab. cant find the folder on Drive.

**Comment by momoci0704** [comment]
I have this problem too.

**Comment by dymension** [comment]
Same here
but the flder is not linked to the Drive, but to the virtual server we are launching

**Comment by HaikenEdge** [comment]
> but the flder is not linked to the Drive, but to the virtual server we are launching

So, presumably, the virtual server's antivirus is flagging it and that's why the link's not spawning?

**Comment by dymension** [comment]
This pb occured last year here, and it was a problem from Gradio
[](https://github.com/gradio-app/gradio/issues/3498)

**Comment by HaikenEdge** [comment]
That sounds like a problem on Gradio's end and not something A1111 can fix?

**Comment by yasu5555** [comment]
I have the same problem, I use colab and I don't know where to place it.

**Comment by Meiteisho** [comment]
Gradio API is down : https://status.gradio.app/793595965

**Comment by yasu5555** [comment]
![Gradio-Status](https://github.com/TheLastBen/fast-stable-diffusion/assets/156520743/eab78540-973f-4762-9541-236aebde3cef)
It may be that gradio is down.

**Comment by HaikenEdge** [comment]
Gradio is back up, as is the shared link.
