### ISSUE TITLE
Local gtx3090 card training dreambooth is supported?

### ISSUE THREAD

**Issue by Luffffffy** [TheLastBen/fast-stable-diffusion#282]
![image](https://user-images.githubusercontent.com/49063302/198818656-e603ff13-a06f-4245-aa06-9acf7f973146.png)

**Comment by TheLastBen** [comment]
Today I will a local Dreambooth version (windows) that will be compatible with all GPUs

**Comment by Luffffffy** [comment]
> Today I will a local Dreambooth version (windows) compatible with all GPUs

Oh, that would be great, thank you so much!!!

**Comment by ProgramItUp** [comment]
@TheLastBen,
That sounds great.  We're looking forward to the local Windows version that is compatible with all NVIDIA GPUs.  
Thanks
