### ISSUE TITLE
Unable to launch ComfyUI in Paperspace, tensorboard link "Service Unavailable"

### ISSUE THREAD

**Issue by dreamlogic-X** [TheLastBen/fast-stable-diffusion#2820]
Hi Ben, the script is loading as normal but the tensor board link appears broken. 

I had a similar error here:
https://github.com/TheLastBen/fast-stable-diffusion/issues/2786

Thanks for your help

**Comment by dreamlogic-X** [comment]
I updated the repo now and have the exact error as above. At the bottom it says:

"Starting server

To see the GUI go to: http://0.0.0.0:6006/"

**Comment by jayceftg** [comment]
It seems a logging problem between sd() and server.py

**Comment by doggs696** [comment]
It is temporary solution
Run it.
Url will display.

click the url
after To see the GUI go to: http://0.0.0.0:6006/" displayed.

`localurl="https://tensorboard-"+os.environ.get('PAPERSPACE_FQDN')
print(localurl)

Args="--listen --port 6006 --preview-method auto"

#--------------------
sd()
!python /notebooks/ComfyUI/main.py $Args`

**Comment by TheLastBen** [comment]
will check it out

**Comment by TheLastBen** [comment]
fixed

**Comment by dreamlogic-X** [comment]
Thanks for the fix! Can confirm it's working. And thanks @doggs696 for that fix if it happens again.
