### ISSUE TITLE
gradio link not showing up

### ISSUE THREAD

**Issue by shirasaginuma** [TheLastBen/fast-stable-diffusion#2823]
I got the following error and the gradio link is no longer showing up. What is the cause?

Could not create share link. Missing file: /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2. 

Please check your internet connection. This can happen if your antivirus software blocks the download of this file. You can install manually by following these steps: 

1. Download this file: https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64
2. Rename the downloaded file to: frpc_linux_amd64_v0.2
3. Move the file to this location: /usr/local/lib/python3.10/dist-packages/gradio

**Comment by lemyqross** [comment]
It was an error inside the paperspace, not an error inside this project. ^^
