### ISSUE TITLE
The 7th execution item "Start Stable-Diffusion" does not output any execution message and the URL to start "Stable Diffusion Web UI" is not output.

### ISSUE THREAD

**Issue by Kaka32793784** [TheLastBen/fast-stable-diffusion#2871]
When "fast-stable-diffusion" is executed in "Google Colab", the 7th execution item "Start Stable-Diffusion" does not output any execution message, it ends after a few minutes, and the URL to start "Stable Diffusion Web UI" is The URL to start "Stable Diffusion Web UI" is not output. Please let me know what I should do.

Perhaps it is related to the fact that I forgot to "Connect and Delete Runtime" the last time I closed "Start Stable-Diffusion".

Please let us know how to deal with this.

**Comment by TheLastBen** [comment]
are you on free colab ?

**Comment by Kaka32793784** [comment]
No, we participate in the "Google Colab" for a fee.

**Comment by TheLastBen** [comment]
rename the folder sd in your google drive to sd_old and try again, make sure you run all the cells before the 7th cell

**Comment by Kaka32793784** [comment]
I tried today and was able to successfully start the "sd" folder without setting it to "sd_old".

It may have been a temporary error.

We apologize for the inconvenience.
