### ISSUE TITLE
Since last update I can't get it running.

### ISSUE THREAD

**Issue by zakpurp** [TheLastBen/fast-stable-diffusion#289]
Getting error when i try to run either dreambooth or Stable diffusion..

**Comment by enriqwe** [comment]
Same here, I had it working before but I tried yesterday and since then it keeps throwing this error
ImportError: cannot import name 'image_from_url_text' from 'modules.generation_parameters_copypaste' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/generation_parameters_copypaste.py)

![image](https://user-images.githubusercontent.com/117003689/198869079-bc913ed0-94dd-4773-80a3-f6cd39f2990c.png)
The model is in the same folder and it is correctly spelled

**Comment by zakpurp** [comment]
![Screenshot_20221030_043451_com android chrome_edit_185999544482554](https://user-images.githubusercontent.com/90535722/198869714-9ab835ce-99d6-40d3-baf3-0fe768b9a50f.jpg)

**Comment by TheLastBen** [comment]
check the box "update_repo" andmake sure you use the latest colab. In case you save it in your gdrive, use the link from the repo

**Comment by C27U** [comment]
Same
![Screenshot_20221030-175056_Bromite](https://user-images.githubusercontent.com/79103915/198872668-b660276d-be76-41a6-bd3c-19e56acf9c1e.png)

**Comment by TheLastBen** [comment]
check your instance images, one of them is either not an image file or a corrupt image file

**Comment by C27U** [comment]
> 

I removed the images and uploaded new ones still got these:

Steps:   0% 0/1500 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 694, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 590, in main
    for step, batch in enumerate(train_dataloader):
  File "/usr/local/lib/python3.7/dist-packages/accelerate/data_loader.py", line 348, in __iter__
    current_batch = next(dataloader_iter)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 292, in __getitem__
    instance_image = Image.open(path)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2843, in open
    fp = builtins.open(filename, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ncrm/instance_images/.ipynb_checkpoints'
Steps:   0% 0/1500 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--save_starting_step=500', '--save_n_steps=0', '--train_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-5', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/ncrm/instance_images', '--output_dir=/content/models/ncrm', '--instance_prompt=', '--seed=96576', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--center_crop', '--lr_warmup_steps=0', '--max_train_steps=1500']' returned non-zero exit status 1.
Something went wrong

**Comment by C27U** [comment]
Oh i had to delete the whole Fast-dreambooth folder

**Comment by TheLastBen** [comment]
there is of folder ".ipynb_checkpoints'" inside your instance images folder
are you using the latest notebook ?

**Comment by zakpurp** [comment]
Using the latest collab notebook and I dont see any "ipynb_checkpoints"
file.

**Comment by TheLastBen** [comment]
@zakpurp 
copy the error log instead of a screenshot, so I can see the full text

**Comment by enriqwe** [comment]
> check the box "update_repo" and use the latest colab. In case you saved it in your gdrive, use the link from the repo

this was my problem. thanks!

**Comment by R2Pitou** [comment]
/bin/bash: accelerate: command not found
Something went wrong

**Comment by TheLastBen** [comment]
you skipped the dependencies cell and probably also the first cell

**Comment by R2Pitou** [comment]
The nested ones, yes. 
Thank you <3

First 3000 rounds done.

**Comment by zakpurp** [comment]
Got it working for training now.. Thanks guys!

**Comment by zakpurp** [comment]
Thanks for the help
