### ISSUE TITLE
Version for a local runtime

### ISSUE THREAD

**Issue by askiiart** [TheLastBen/fast-stable-diffusion#29]
Right now it's only possible to run these notebooks through Google Colab, but I'm sure many people, myself included, want the ability to run this is a local runtime. 

Similarly, I found [an issue requesting kaggle support](https://github.com/TheLastBen/fast-stable-diffusion/issues/20). However, that would still only allow for Colab or Kaggle.

One option would be to create multiple notebooks for the different platforms. Another would be to detect the platform in the notebook, like [Disco Diffusion](https://colab.research.google.com/github/alembics/disco-diffusion/blob/main/Disco_Diffusion.ipynb) does.

[Here](https://colab.research.google.com/drive/1B_LRFVP1BMVrPoI9DT8icOtkwPYgyElY?usp=sharing) I've tried to start porting the hlky notebook to be compatible with a local (and theoretically any platform) notebook, but it doesn't work, and my methods are pretty crude.

Edit: [Here](https://github.com/askiiart/universal-fast-stable-diffusion) has *working* notebooks, AUTOMATIC1111 and hlky so far.

**Comment by 1blackbar** [comment]
xformers dont work on windows so this is not possible on win, works on linux https://www.youtube.com/watch?v=VgKDZqAii1I

**Comment by askiiart** [comment]
> xformers( speedup code) dont work on windows so this is not possible on win, works on linux https://www.youtube.com/watch?v=VgKDZqAii1I
Well, linux would be an improvement at least

**Comment by TheLastBen** [comment]
I'll give it a try

**Comment by jujpenabe** [comment]
@askiiart Have you tested the AUTOMATIC1111 in Kaggle?

**Comment by askiiart** [comment]
@jujpenabe No, I will test it when I can, or you can test it if you'd like. The repo is askiiart/universal-fast-stable-diffusion.

**Comment by jujpenabe** [comment]
@askiiart I'm testing it right now.
I could at least point out some changes for the kaggle version.

**Comment by askiiart** [comment]
If this needs to be discussed further, the discussion can be part of the pull request (once I get around to it). As for now, I'm closing this.
