### ISSUE TITLE
Error Automatic 1111

### ISSUE THREAD

**Issue by Ohanaedits23** [TheLastBen/fast-stable-diffusion#2908]
Hello! Since this morning, Automatic 1111 has been giving me this error on Colab Pro. Can anyone help me? Thanks!

IndexError                                Traceback (most recent call last)
[<ipython-input-10-09b31cc1a357>](https://0swyrfcbixx-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240814-060115_RC00_662843208#) in <cell line: 45>()
     65     time.sleep(4)
     66     with open('/content/srv.txt', "r") as file: text = file.read()
---> 67     srv= re.findall(r"https?://(?:\S+?\.)?trycloudflare\.com\S*", text)[0]
     68 
     69     for line in fileinput.input('/usr/local/lib/python3.10/dist-packages/gradio/blocks.py', inplace=True):

IndexError: list index out of range

**Comment by aionrevenge** [comment]
no problem on me, don't use cloudflare tunnel

**Comment by Ohanaedits23** [comment]
Thanks for answering, I'll try it later to see if there's no problem.

**Comment by Ohanaedits23** [comment]
It worked for me, thanks
