### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by goburinking** [TheLastBen/fast-stable-diffusion#2918]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-17-31e191356cea> in <cell line: 45>()
     65     time.sleep(4)
     66     with open('/content/srv.txt', "r") as file: text = file.read()
---> 67     srv= re.findall(r"https?://(?:\S+?\.)?trycloudflare\.com\S*", text)[0]
     68 
     69     for line in fileinput.input('/usr/local/lib/python3.10/dist-packages/gradio/blocks.py', inplace=True):

IndexError: list index out of range

**Comment by goburinking** [comment]
I need to solve the problem, can someone please help me.
IndexError: list index out of range

**Comment by goburinking** [comment]
![Uploading Stable Diffusion.jpg…]()

**Comment by goburinking** [comment]
![Uploading Stable Diffusion.jpg…]()

**Comment by goburinking** [comment]
![Stable Diffusion](https://github.com/user-attachments/assets/b19af197-5164-4f6f-8e4f-fbdc39d20015)

**Comment by Ineman** [comment]
i had same error and i changed code time.sleep(4) to time.sleep(6)
no error now
