### ISSUE TITLE
Error Colab Automatic 1111

### ISSUE THREAD

**Issue by Ohanaedits23** [TheLastBen/fast-stable-diffusion#2920]
Hi!!Since this morning, I’ve been having issues with Automatic 1111. It tells me that I need to install xformers, but when I try to install them, I get an error. Is anyone else experiencing the same issue?

**Comment by BlessedDuelOP** [comment]
you have to run this command:
!pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121
before turning on SD
I hope it helped you :)

**Comment by MajorGruberth** [comment]
@BlessedDuelOP: at what point should I insert the "install former" line?

I have the same issue - I didn't use Colab for some month and I started straight away with an error. 

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.4.0+cu121)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 162, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 52, in webui
    initialize.initialize()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 74, in initialize
    initialize_rest(reload_script_modules=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 102, in initialize_rest
    sd_models.list_models()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 165, in list_models
    model_list = modelloader.load_models(model_path=model_path, model_url=model_url, command_path=shared.cmd_opts.ckpt_dir, ext_filter=[".ckpt", ".safetensors"], download_name="v1-5-pruned-emaonly.safetensors", ext_blacklist=[".vae.ckpt", ".vae.safetensors"], hash_prefix=expected_sha256)
TypeError: load_models() got an unexpected keyword argument 'hash_prefix'

**Comment by TheLastBen** [comment]
xformer issue fixed

**Comment by MajorGruberth** [comment]
thank you!

**Comment by Ohanaedits23** [comment]
Thank you
