### ISSUE TITLE
Can't run this on Colab anymore

### ISSUE THREAD

**Issue by ShizukaKitakami55** [TheLastBen/fast-stable-diffusion#2921]
It was running perfectly fine sometime ago.
I connect my drive, install/update the AUTOMATIC1111 repo, the requirements (I already downloaded what I needed so I didn't download anything) but when I try to run it, it will give out this error message

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.3.0+cu121 with CUDA 1201 (you have 2.4.0+cu121)
    Python  3.10.14 (you have 3.10.12)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details

Anything I'm doing wrong?
![image](https://github.com/user-attachments/assets/82b466d3-780a-4c27-96cf-48c43af0af7c)
Thanks for your help.

**Comment by TheLastBen** [comment]
fixed
