### ISSUE TITLE
Error when downloading LoRA

### ISSUE THREAD

**Issue by justahumanb** [TheLastBen/fast-stable-diffusion#2944]
NameError                                 Traceback (most recent call last)
[<ipython-input-6-7e4ad16c4d53>](https://localhost:8080/#) in <cell line: 5>()
      8   os.makedirs('/content/gdrive/'+mainpth+'/sd/stable-diffusion-w'+blsaphemy+'/models/Lora', exist_ok=True)
      9 
---> 10   src=getsrc(LoRA_LINK)
     11 
     12   if src=='civitai':

NameError: name 'getsrc' is not defined

Happens with LoRas from all the sources

**Comment by BlessedDuelOP** [comment]
Check the folders to see if the Lora has downloaded correctly; sometimes the file downloads but ends up with 0 mg. You can also use a code cell to download the Lora of your choice: !wget LINK -O /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/yourlora.safetensors

**Comment by justahumanb** [comment]
> Check the folders to see if the Lora has downloaded correctly; sometimes the file downloads but ends up with 0 mg. You can also use a code cell to download the Lora of your choice: !wget LINK -O /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Lora/yourlora.safetensors
That worked, thank you!
