### ISSUE TITLE
Conversion Error on DreamBooth

### ISSUE THREAD

**Issue by Kamizaki-Risa** [TheLastBen/fast-stable-diffusion#303]
I'm using a translator.

The wd-v1-3-full.ckpt conversion attempt of hakurei/waifu-diffusion-v1-3 fails repeatedly.
I checked Compatibility_Mode, but it's no use at all.

--2022-10-31 03:47:19--  https://raw.githubusercontent.com/CompVis/stable-diffusion/main/configs/stable-diffusion/v1-inference.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1873 (1.8K) [text/plain]
Saving to: ‘v1-inference.yaml’

v1-inference.yaml   100%[===================>]   1.83K  --.-KB/s    in 0s      

2022-10-31 03:47:19 (30.3 MB/s) - ‘v1-inference.yaml’ saved [1873/1873]

Downloading: 100% 4.52k/4.52k [00:00<00:00, 5.12MB/s]
Downloading: 100% 1.71G/1.71G [00:26<00:00, 64.7MB/s]
^C
Conversion error, check your CKPT and try again
Conversion error, check your CKPT and try again
Conversion error, check your CKPT and try again
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-4-d6828d0f14a4>](https://localhost:8080/#) in <module>
     85       while not os.path.exists('/content/stable-diffusion-v1-5/unet/diffusion_pytorch_model.bin'):
     86         print('Conversion error, check your CKPT and try again')
---> 87         time.sleep(5)
     88   else:
     89     while not os.path.exists(str(CKPT_Path)):

KeyboardInterrupt:

**Comment by TheLastBen** [comment]
Check the box "compatibility_mode" in the "download model" cell

**Comment by Kamizaki-Risa** [comment]
![sdad](https://user-images.githubusercontent.com/76465138/198976675-59cba962-a03c-49a2-9c62-552afda346f6.png)

I checked "Compatibility_mode", but it still doesn't work.

**Comment by TheLastBen** [comment]
to you have a link to the CKPT ? so I can try it

**Comment by TheLastBen** [comment]
ah yes, the RAM is insufficient, use this one : https://huggingface.co/hakurei/waifu-diffusion-v1-3/blob/main/wd-v1-3-float32.ckpt  
and paste it in the CKPT_Link

**Comment by Kamizaki-Risa** [comment]
Oh, I thought I had to do a dream booth study with full ver. Thanks very much for your help.
