### ISSUE TITLE
No module named 'xformers'

### ISSUE THREAD

**Issue by Luffffffy** [TheLastBen/fast-stable-diffusion#307]
I runing on my vscode jupyter

![image](https://user-images.githubusercontent.com/49063302/198947358-31ffcefe-55b5-409c-8b10-336889ecc2cd.png)

`!xcopy /E /Q /H /Y "$MAIN_DIR/usr/local/lib/python3.7/dist-packages" "$s"`
In fact, i confused about that, i used Anaconda env, need change this packages path?
eg: `!xcopy /E /Q /H /Y "D:/Anaconda3/envs/fast-dreambooth/Lib/site-packages" "$s"`

**Comment by TheLastBen** [comment]
You don't need to change that, just install xformers in anaconda

**Comment by Luffffffy** [comment]
> You don't need to change that, just install xformers in anaconda

I see, thanks.
