### ISSUE TITLE
On COLAB: Testing the trained model error: "did you forget to build xformers with `python setup.py develop"

### ISSUE THREAD

**Issue by Foolevil** [TheLastBen/fast-stable-diffusion#312]
Before this I had some problems with building a CKPT model (with text_encoder). Now:

WARNING:root:WARNING: 
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop
----
RuntimeError: No such operator xformers::efficient_attention_forward_generic - did you forget to build xformers with `python setup.py develop`?

**Comment by Foolevil** [comment]
I run "Setting up the environment" with no errrs
GPU 0: Tesla T4

**Comment by TheLastBen** [comment]
try again "Setting up the environment" and make sure you're using the latest notebook

**Comment by Foolevil** [comment]
OK

**Comment by shreks7** [comment]
I am still getting this issue - 

`/usr/local/lib/python3.7/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
WARNING:root:WARNING: /usr/local/lib/python3.7/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE
Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop` 

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

And it fails  `File "/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 46, in no_such_operator
    f"No such operator xformers::{name} - did you forget to build xformers with python setup.py develop?`

**Comment by TheLastBen** [comment]
do 
`!pip uninstall xformers` and then rerun the cell xformers in the dependencies section

**Comment by shreks7** [comment]
I modified the xformer block to this - 

```
%pip cache purge
%pip uninstall -y xformers
%pip install https://github.com/TheLastBen/fast-stable-diffusion/raw/main/precompiled/T4/xformers-0.0.13.dev0-py3-none-any.whl```

**Comment by TheLastBen** [comment]
it might be related to the version of linux or pytorch, since you're using a different kind of VM
