### ISSUE TITLE
problem on colab 

### ISSUE THREAD

**Issue by rewixx** [TheLastBen/fast-stable-diffusion#315]
i updated and this error is here

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 10, in <module>
    from modules.paths import script_path
ModuleNotFoundError: No module named 'modules.paths'

**Comment by TheLastBen** [comment]
you need to run the cell before the last one

**Comment by RomerEnr** [comment]
@TheLastBen what cell ? I have the same error

**Comment by TheLastBen** [comment]
the requirements cell

**Comment by RomerEnr** [comment]
I run the first one, installing the second step "Installing AUTOMATIC111 repo", then in the step 3 I load the model, and in the step 4 I have installed the requirements

**Comment by TheLastBen** [comment]
Your using a very old version of the colab, always use the latest one from the link : 
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by RomerEnr** [comment]
I am using the same colab, i get the same error

**Comment by TheLastBen** [comment]
do a clean run, remove the folder sd from your gdrive and run the colab

**Comment by RomerEnr** [comment]
okey, I will try

**Comment by RomerEnr** [comment]
@TheLastBen fixed, thanks you ;)

**Comment by TheLastBen** [comment]
great !
