### ISSUE TITLE
The model doesn't exist on you Gdrive, use the file explorer to get the path

### ISSUE THREAD

**Issue by loranger** [TheLastBen/fast-stable-diffusion#318]
Hi,

Last week, I was able to use this awesome colab and made beautiful portraits, but I can't anymore.
As soon I try to start to test the trained models, I got the following error:

`The model doesn't exist on you Gdrive, use the file explorer to get the path : `

I mounted gdrive again, download the model again, re-upload the images instance again, removed everything including on gdrive and started all over again, but always fails on this very last error.

What did I miss ?

**Comment by TheLastBen** [comment]
Hi,
did you input the hugging face token in the right place ? in the "model download" cell ?

**Comment by loranger** [comment]
Yes sir !
And I did accept the SD 1.5 terms. I did train my photos and played a lot few days ago.
Since then, I open the (grdive-ly) saved colab notebook, get my values back, reconnect, but always get this error when I try to test my trained values, even if I start again with new instances images

**Comment by TheLastBen** [comment]
Make a screenshot of the cell + error

**Comment by loranger** [comment]
I tried for few days to launch the notebook from scratch and to interrupt it again, for resuming later, and it worked flawlessy, so I may have forgot something, but I can't really figure out what…

Anyway, thank you so much for your support and your awesome notebook!
