### ISSUE TITLE
cant use extension properly

### ISSUE THREAD

**Issue by demosch** [TheLastBen/fast-stable-diffusion#324]
first: thanks for adding the extension downlaoder! ive installed the image brwoser with it and got it into the UI but: i cant specify image directory (see screenshot)
![Uploading Bildschirmfoto 2022-11-01 um 13.16.01.png…]()

**Comment by demosch** [comment]
what do i have to change-so it can get access to my images?

**Comment by TheLastBen** [comment]
I didn't add the feature, AUTOMATIC1111 did.
The link to the image you gave is broken

**Comment by demosch** [comment]
<img width="1440" alt="Bildschirmfoto 2022-11-01 um 13 16 01" src="https://user-images.githubusercontent.com/92346072/199231169-e5601f35-0693-4bff-980b-37e71652b0b7.png">

**Comment by demosch** [comment]
where to input ''--administrator'' so i can use it?

**Comment by TheLastBen** [comment]
in the last cell like this : 

```
  if os.path.isfile(model):
    !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --ckpt "$model" --administrator
  else:
    !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --ckpt-dir "$model" --administrator
except:
   !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share --disable-safe-unpickle --administrator
```

**Comment by demosch** [comment]
into: images_history.py ?

**Comment by demosch** [comment]
File ["<ipython-input-7-576781885763>"](https://localhost:8080/#), line 72
    if os.path.isfile(model):
    ^
IndentationError: unexpected indent


@TheLastBen

**Comment by demosch** [comment]
<img width="1440" alt="Bildschirmfoto 2022-11-01 um 13 29 46" src="https://user-images.githubusercontent.com/92346072/199232548-f4b4d547-bb4d-4e77-aa11-c9d5fc9df84c.png">

**Comment by TheLastBen** [comment]
don't copy all the lines, just copy --administrator, to avoid indentation errors

**Comment by demosch** [comment]
fixed. thanks alot
