### ISSUE TITLE
On colab I am getting: /bin/bash: accelerate: command not found Something went wrong

### ISSUE THREAD

**Issue by SingingTurnip** [TheLastBen/fast-stable-diffusion#325]
I follow the steps of the new method and once I get to the training I put in 5500 as the amount of traing steps because I have uploaded 55 images.

At the bottom it then says its executing, stops and says

`/bin/bash: accelerate: command not found
Something went `wrong``

**Comment by TheLastBen** [comment]
you missed the first cells

**Comment by SingingTurnip** [comment]
I had clicked play on all except the old method.

**Comment by TheLastBen** [comment]
`accelerate: command not found Something went wrong``

this means that the accelerate dependency isn't correctly installed, rerun the dependencies cell

**Comment by SingingTurnip** [comment]
Ok I will go through it again thanks :)

Also, is `Enable_text_encoder_training` needed and what does it actually
do/mean?

**Comment by TheLastBen** [comment]
It replaces the instance prompt, it makes the training more efficient and allows the retraining of the model without destroying it.

**Comment by SingingTurnip** [comment]
Ok got it working but I am confused over something.

I put the same seed as settings that I used on a previously trained model which is 1.4 I think it was and the results are different.

What could be the reason?
Same images used btw. Only MAJOR differenceis that I used a different colab for 1.4 and it wasnt a fast one and I didnt use fp16 or whatever its called.

Also I noticed when I tried to use LMS that the image was all pixelated in different colours almost like when you interrupt the rendering.

1.4 
![00093-2835123704](https://user-images.githubusercontent.com/19948596/199497141-ba1538bc-efc0-493d-b145-89f198b60de2.png)

1.5
![00000-2835123704-realistic clo___](https://user-images.githubusercontent.com/19948596/199497301-ee96232c-32c1-4bef-9784-a07221b6a13c.png)

**Comment by SingingTurnip** [comment]
Both my beautiful 40 year old face that only a mother could love but there is a huge difference.

**Comment by TheLastBen** [comment]
how much did you put in the text_encoder % ? if you left it at 40%, lower it to 10%

**Comment by SingingTurnip** [comment]
Yeah it was 40, I thought default would be ok.

I'll see if I can restore the previous session and lower it.

Cheers.

**Comment by TheLastBen** [comment]
you need to restart the training (not resume) and keep the strength of the text_encoder to 10%, also don't forget to lower the num of input pics to 25
