### ISSUE TITLE
Undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE

### ISSUE THREAD

**Issue by shreks7** [TheLastBen/fast-stable-diffusion#326]
In relation to #312 (Closed). I am opening it again, if there is any fix, would appreciate it. 

I am still getting this issue (using the latest colab fast-dreambooth on T4) -

`/usr/local/lib/python3.7/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE WARNING:root:WARNING: /usr/local/lib/python3.7/dist-packages/xformers/_C.so: undefined symbol: _ZNK3c104impl13OperatorEntry20reportSignatureErrorENS0_12CppSignatureE Need to compile C++ extensions to get sparse attention suport. Please run python setup.py build develop`

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
And it fails File `"/usr/local/lib/python3.7/dist-packages/xformers/ops.py", line 46, in no_such_operator f"No such operator xformers::{name} - did you forget to build xformers with python setup.py develop?`

**Comment by shreks7** [comment]
Closed here https://github.com/TheLastBen/fast-stable-diffusion/issues/312#issuecomment-1298873097

**Comment by khansharkhamnida** [comment]
Hi I am getting this error as well but I am not sure on how to solve it

Package                Version
---------------------- -----------------------------
accelerate             0.26.1
addict                 2.4.0
aliyun-python-sdk-core 2.14.0
aliyun-python-sdk-kms  2.16.2
antlr4-python3-runtime 4.9.3
asttokens              2.4.1
attrs                  23.2.0
av                     11.0.0
backcall               0.2.0
Brotli                 1.0.9
certifi                2023.11.17
cffi                   1.16.0
charset-normalizer     2.0.4
click                  8.1.7
colorama               0.4.6
crcmod                 1.7
cryptography           41.0.7
decorator              5.1.1
decord                 0.6.0
diffusers              0.11.1
einops                 0.7.0
executing              2.0.1
filelock               3.13.1
fsspec                 2023.12.2
huggingface-hub        0.20.3
idna                   3.4
imageio                2.33.1
importlib-metadata     7.0.1
ipython                8.12.3
jedi                   0.19.1
jmespath               0.10.0
joblib                 1.3.2
jsonlines              4.0.0
matplotlib-inline      0.1.6
mdurl                  0.1.2
mkl-fft                1.3.8
mkl-random             1.2.4
mkl-service            2.4.0
model-index            0.1.11
mypy-extensions        1.0.0
numpy                  1.24.3
omegaconf              2.3.0
opencv-python          4.9.0.80
opendatalab            0.0.10
openxlab               0.0.34
ordered-set            4.1.0
oss2                   2.17.0
packaging              23.2
pandas                 2.0.3
parso                  0.8.3
pexpect                4.9.0
pickleshare            0.7.5
Pillow                 10.0.1
pip                    23.3.2
platformdirs           4.1.0
prompt-toolkit         3.0.43
psutil                 5.9.8
ptyprocess             0.7.0
pure-eval              0.2.2
pycparser              2.21
pycryptodome           3.20.0
Pygments               2.17.2
pyOpenSSL              23.2.0
pyre-extensions        0.0.23
PySocks                1.7.1
python-dateutil        2.8.2
pytz                   2023.4
PyYAML                 6.0
regex                  2023.12.25
requests               2.31.0
rich                   13.4.2
sacremoses             0.1.1
safetensors            0.4.2
setuptools             69.0.3
six                    1.16.0
stack-data             0.6.3
tabulate               0.9.0
termcolor              2.4.0
tokenizers             0.13.3
tomli                  2.0.1
torch                  1.13.1
torchaudio             0.13.1
torchvision            0.14.1
tqdm                   4.66.1
traitlets              5.14.1
transformers           4.28.0
typing_extensions      4.9.0
typing-inspect         0.9.0
tzdata                 2023.4
urllib3                1.26.18
wcwidth                0.2.13
wheel                  0.41.2
xformers               0.0.15.dev0+4c06c79.d20221201
yapf                   0.40.2
zipp                   3.17.0


(fyp) nsazielle@DESKTOP-AS65KE6:~/Synthda/fyp$ nvidia-smi
Mon Jan 29 22:54:49 2024
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 512.98       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   56C    P8    23W /  N/A |   1306MiB /  8192MiB |     19%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       551      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+
