### ISSUE TITLE
Hanging in AUTOMATIC1111 notebook on "Start stable-diffusion" step.

### ISSUE THREAD

**Issue by nerdvegas** [TheLastBen/fast-stable-diffusion#329]
I've successfully used this notebook before, but now it's hanging after "Connected" is printed. I'm using reserved GPU remote host. I've given it 15 minutes but it won't get any further.

**Comment by TheLastBen** [comment]
Saying connected means that the operation was successful and you should click on the given link to open the interface

**Comment by nerdvegas** [comment]
Ah right - I actually got mixed up and had run the Dreambooth notepad previously. User error, closing
