### ISSUE TITLE
Can not run without trainning

### ISSUE THREAD

**Issue by liangwei191** [TheLastBen/fast-stable-diffusion#34]
sorry for open a new post.
But After finished the train.I dont know which cells to choose to run again that could make the last cell working by skipping the trainning part.
And I dont find how to assign model path for which model to use.

**Comment by TheLastBen** [comment]
when you launch the gradio interface after the training, it will automatically use the trained model, but do not disconnect from the runtime after the training.
I'm working on making it easier to use and reuse the trained models

**Comment by liangwei191** [comment]
OK.Waiting for that then.Thank you for the work.

**Comment by liangwei191** [comment]
OK.Waiting for that then.Thank you for the work.

**Comment by TheLastBen** [comment]
Now you can test your trained at anytime using just the identifier used for it's training, as long as the model is in your Gdrive, all in one click without going through the other cells
