### ISSUE TITLE
fast_stable_diffusion_AUTOMATIC1111 doesn't starts

### ISSUE THREAD

**Issue by Nayjest** [TheLastBen/fast-stable-diffusion#348]
Today fast_stable_diffusion_AUTOMATIC1111 doesn't starts,

https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

When trying to start stable-diffusion:

File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 24, in <module>
    import modules.sd_vae
ModuleNotFoundError: No module named 'modules.sd_vae'

(Yesterday everything worked fine)

**Comment by Nayjest** [comment]
I also used "update repo" checkbox,
It failed because can't rewrite local changes, so I replaced "git pull" to
!git fetch
!git reset --hard
And my repo after that was updated to this commit:
HEAD is now at 61af311 Merge pull request #4112 from Harvester62/Italian

**Comment by manueljerez7** [comment]
didn't work for me

**Comment by FLICKERTRICK** [comment]
![IMG_20221102_224452](https://user-images.githubusercontent.com/56978314/199589561-d90cf3bf-c3e6-436b-ac44-9d8bdc73dddd.jpg)
![IMG_20221102_224023](https://user-images.githubusercontent.com/56978314/199589586-8da6392c-b832-40de-b6bf-038f1f56a022.jpg)
Umm I'm not codder. What's need to do?

**Comment by FLICKERTRICK** [comment]
![IMG_20221102_222526](https://user-images.githubusercontent.com/56978314/199590052-d19e591b-ae5b-4c40-ae32-2daa73946c0e.jpg)
![IMG_20221102_224023](https://user-images.githubusercontent.com/56978314/199590079-bd37718d-8d07-4492-ae07-6072880c9779.jpg)

I'm not coder. What i should do?

**Comment by ItsOlegDm** [comment]
![image](https://user-images.githubusercontent.com/55553104/199612221-aa788d25-1627-47ae-ba5f-b847839addd7.png)

**Comment by AndreUrzua** [comment]
I went to Google drive, deleted the sd folder and run all, it seems like that fixes the issue

**Comment by TheLastBen** [comment]
Run this, then check the box "update_repo"

```
%cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/
!wget -O processing.py https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/modules/processing.py
```

**Comment by maartenwijntjes** [comment]
> I went to Google drive, deleted the sd folder and run all, it seems like that fixes the issue

This worked for me. 

> Run this, then check the box "update_repo"
> 
> ```
> %cd /content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/
> !wget -O processing.py https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/modules/processing.py
> ```

I did not understand this, I put the lines of code in various locations, reran the notebook but error stayed. Anyway deleting the sd folder helped so I'm happy to continue with this marvellous notebook!

**Comment by TheShankar** [comment]
it seems to be failing to download the file sd_vae.py on the module folders, from this commit:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/675b51ebd3a0afbe097e0dc1384fd9ab8f5f1b38#diff-07c0fede266d0a64bfda4b3fe2581203dcb8f9ff59755ea20b760e45d5ab2c6d
