### ISSUE TITLE
How do I precompile Xformer for my GPU

### ISSUE THREAD

**Issue by Shawn-Shan** [TheLastBen/fast-stable-diffusion#353]
I have Titan RTX on my machines. Any instructions on how I can precompile the xformer to support my GPU?

**Comment by askiiart** [comment]
Check out [this](https://github.com/TheLastBen/fast-stable-diffusion/issues/95) and [this](https://github.com/TheLastBen/fast-stable-diffusion/issues/26).

**Comment by Shawn-Shan** [comment]
Thanks for the quick response. And apologies for asking a dup question.

**Comment by askiiart** [comment]
By the way, you can't do this with conda's pip env. You have to do it with the normal system pip, with conda deactivated.
