### ISSUE TITLE
NameError: name 's' is not defined

### ISSUE THREAD

**Issue by alexisargyris** [TheLastBen/fast-stable-diffusion#355]
Hello,

I am trying to test a previously trained model. I get `NameError: name 's' is not defined`. What should I do?

![screen](https://user-images.githubusercontent.com/1640855/199668332-3174fab5-585c-4df9-9626-92eda9c74e68.jpg)

**Comment by TheLastBen** [comment]
You need to run the dependencies cell first

**Comment by alexisargyris** [comment]
Very true! Thanks a lot
