### ISSUE TITLE
CUDA error on AUTOMATIC1111 Colab

### ISSUE THREAD

**Issue by timheigames** [TheLastBen/fast-stable-diffusion#36]
It was working fine earlier today, but now when I try to use the AUTOMATIC1111 WEBUI Colab with the Tesla T4 GPU, I get the following error:
```
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

It might be related to the changes made to '_C.so' in commit e4bb78c.

**Comment by TheLastBen** [comment]
I didn't implement the files yet, it might be the xformers official repo changing, I'll fix that in a moment

**Comment by TheLastBen** [comment]
scratch that, you are right ! I replaced the T4 _C.so by mistake

**Comment by TheLastBen** [comment]
fix now, thanks

**Comment by mauzus** [comment]
Awesome, thank you very much!

**Comment by timheigames** [comment]
Thanks for the quick fix! I can confirm it's working again on my end, so I will close the issue.
