### ISSUE TITLE
Help ... how to enable --api

### ISSUE THREAD

**Issue by a7medee** [TheLastBen/fast-stable-diffusion#360]
trying to run the krita extension [ auto-sd-paint-ext ](https://github.com/Interpause/auto-sd-paint-ext) on the [automatic111 colab](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb)
I managed to install the extension but I'm struggling with enabling  api ... any tips
thanks for the work

**Comment by Alexandre-Touzet** [comment]
I have the same issue, can't make the --api to work.

Thank you for the help!

**Comment by TheLastBen** [comment]
the --api is related to the localhost if I'm not wrong, and with colab you can't connect directly to the localhost

**Comment by a7medee** [comment]
> the --api is linked to the localhost if I'm not wrong, and with colab you can't connect directly to the localhost

true. I'm planning to use ngrok after i figure the api part

**Comment by TheLastBen** [comment]
you don't need ngrok, it's already running on a similar tunnel "localtunnel"

**Comment by a7medee** [comment]
I'm trying replicate this [colab](https://github.com/danilw/Krita-StableDiffusion-WebUI-Colab) 
it uses ngrok for remote connection 
it was working two days ago

**Comment by TheLastBen** [comment]
try doing the same thing with the current "localtunnel", maybe it'll work

**Comment by Alexandre-Touzet** [comment]
I used this with success https://github.com/TheLastBen/fast-stable-diffusion/discussions/317

**Comment by a7medee** [comment]
> I used this with success #317

can you explain how to do the second step

**Comment by Alexandre-Touzet** [comment]
Simply edit your model.py in sd/stable-diffusion-webui/modules/api/

**Comment by a7medee** [comment]
thanks a lot it worked
