### ISSUE TITLE
Automatic1111 Error

### ISSUE THREAD

**Issue by CJohnDesign** [TheLastBen/fast-stable-diffusion#369]
I'm getting the following error on the very last step: 
```Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 12, in <module>
    from modules import devices, sd_samplers, upscaler, extensions
ImportError: cannot import name 'extensions' from 'modules' (unknown location)
```

I did have to change `!git pull` to `!git fetch !git reset --hard` on step 2

**Comment by pedroimp2** [comment]
I have the same error, I made the change you indicated and it keeps coming up

**Comment by TheLastBen** [comment]
I'll change the update repo code too !git fetch and !git reset --hard

**Comment by TheLastBen** [comment]
should work now https://github.com/TheLastBen/fast-stable-diffusion/commit/7d70393f539b139fc2a245203082cc11cfc1fc7d

**Comment by CJohnDesign** [comment]
I'm still getting the same error
