### ISSUE TITLE
Automatic1111 doesn't start after loading model.

### ISSUE THREAD

**Issue by Neverdusk** [TheLastBen/fast-stable-diffusion#370]
I seem to keep getting this output log after running every step. I don't receive any link or server after running the Colab.
![Capture](https://user-images.githubusercontent.com/79533944/199845196-e0f1c2c3-6268-46e8-9f40-c8f3b35c362e.PNG)

For reference, I inserted a drive folder path into the Model Load step, using a folder that contains multiple models.
![Capture1](https://user-images.githubusercontent.com/79533944/199845341-65c47b78-87b9-4a21-a7d9-040c905601a5.PNG)

After this failed a few times, I tried using the shared link method, but that also produced the same result. Every step previously succeeded, and the repo was confirmed to be up to date in the previous step. This is my first time using this Colab, so I'm not quite sure if I'm doing anything wrong, but any help is appreciated.

**Comment by askiiart** [comment]
You do not have any problems. You are not given a link, it is downloaded and put in the right spot automatically.

P.S. Remember to close this, please!

**Comment by askiiart** [comment]
Do you have a token? If not, you'll need that.

**Comment by Neverdusk** [comment]
I thought the token was only for downloading from Huggingface? I've been trying to use the path_to_trained_model or link_to_trained_model methods.

**Comment by askiiart** [comment]
You need it every time, sorry. I honestly don't know why, but you do.

**Comment by Neverdusk** [comment]
I input a token but received the same error. Does the Colab only work with Stable Diffusion 1.4/1.5 and not other models?

**Comment by zakpurp** [comment]
I think so. Use stable diffusion 1.5 for me it works well

**Comment by zakpurp** [comment]
Go on hugging face and make sure you accept term to use stable-diffusion-v1. 5

**Comment by Neverdusk** [comment]
I've already accepted the terms, but I'm trying to use Waifu Diffusion 1.2, since it has an interesting hybrid style. 

Is the Colab unable to use the alternate models I already have in Google Drive? Or any custom models?

**Comment by askiiart** [comment]
Only dreambooth can use different models

**Comment by Neverdusk** [comment]
Got it. Thanks for the help.

**Comment by TheLastBen** [comment]
The error is because you're out of RAM (not VRAM), use the 4.7GB CKPT version and it'll work

**Comment by Neverdusk** [comment]
Thank you, I'll try with a smaller model then.
