### ISSUE TITLE
train Hypernetwork error 

### ISSUE THREAD

**Issue by robbebluecp** [TheLastBen/fast-stable-diffusion#375]
<img width="841" alt="" src="https://user-images.githubusercontent.com/19666597/199888322-21662396-0464-45d0-ba73-685db7b516be.png">

with this setting, when i click train Hypernetwork, cmd comes with error as below:

<img width="789" alt="截屏2022-11-04 12 36 18" src="https://user-images.githubusercontent.com/19666597/199888467-24f6b72c-8a4e-4cbe-90cd-2273aeeec7b5.png">

please help

**Comment by TheLastBen** [comment]
did you check the "hypernetwork training compatibility" box ?

**Comment by robbebluecp** [comment]
thanks for reply, and i sovle the problem by choosing my hypernetwork in
setting-stable diffusion-hypernetwork
Stable Diffusio

Ben ***@***.***> 于2022年11月4日周五 12:40写道：

**Comment by TheLastBen** [comment]
Great !
