### ISSUE TITLE
Hello ben, i see things have change a lot.

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#377]
i am getting this error

NameError                                 Traceback (most recent call last)
[<ipython-input-14-901947b9542f>](https://localhost:8080/#) in <module>
     68 try:
---> 69    Contain_f
     70    pass

NameError: name 'Contain_f' is not defined

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
[<ipython-input-14-901947b9542f>](https://localhost:8080/#) in <module>
     70    pass
     71 except:
---> 72    Contain_f=Contains_faces
     73 
     74 Enable_text_encoder_training= False #@param{type: 'boolean'}

NameError: name 'Contains_faces' is not defined

**Comment by LIQUIDMIND111** [comment]
actually, i DID defined faces ..... even if NOT using NEW method

**Comment by TheLastBen** [comment]
hi, I fixed that an hour ago, try the latest colab https://github.com/TheLastBen/fast-stable-diffusion/commit/4a090f510625f22ba312dffe5c3bd869c6f0c4e8

**Comment by LIQUIDMIND111** [comment]
> hi, I fixed that an hour ago [4a090f5](https://github.com/TheLastBen/fast-stable-diffusion/commit/4a090f510625f22ba312dffe5c3bd869c6f0c4e8), try the latest colab

ok i will ADD THAT to the code? also, i DID tried the fast method with 2 characters, a man alone and a female alone, SHOULD I CHOOSE the BOTH option on FACES? and on subject, do i use PERSON or "male, female" if i am training 2 characters at the same time? Please help me here, i DID rename 20 pictures of myself and a lady friend BOTH we have 20 files with a TOKEN already also added to the file, AND a class name like this: 4ZJENNIFER_woman_01.jpg etc. and me 4ZZEDDIE_man_01.jpg etc....... Anyway, the results are an amazing HD model of people I DONT KNOW, LOLOLOL...... it came out amazing, but NOT either one of us...... so, what am i doing wrong? how do i really train 2 characters at the same time in which they are a man and woman...... how to i choose the CLASS OPTION.... man, woman OR person?

**Comment by LIQUIDMIND111** [comment]
![Screenshot 2022-11-04 071424](https://user-images.githubusercontent.com/112510084/199959822-370ff7f9-ecd0-42e6-8cb7-ac5501a1d60d.jpg)
IF i use HER token alone on iteration, i do this 4ZJJJennifer woman, and its GORGEOUS quality, BUT NOT HER, and i have done many models of her ALONE, but NEVER 2 models IN ONE

**Comment by LIQUIDMIND111** [comment]
![Screenshot 2022-11-04 071829](https://user-images.githubusercontent.com/112510084/199960536-70458132-8207-46b9-9f08-7928e5e24933.jpg)
HOW do i do this part for 2 characters?

**Comment by LIQUIDMIND111** [comment]
![Screenshot 2022-11-04 072025](https://user-images.githubusercontent.com/112510084/199960874-99f58393-5e85-4d07-a2d6-6d84f2b9dbc1.jpg)


if i use my instance ONLY 4ZEEEddie man, it shows this.... NICE, bbut NOT ME, what happened? this training has NEVER change someone so much!!! before....

**Comment by TheLastBen** [comment]
You're using the old method, use the new method

**Comment by LIQUIDMIND111** [comment]
> 
![Screenshot 2022-11-04 071829](https://user-images.githubusercontent.com/112510084/199962508-90d4d7b6-c6ff-4e4a-8906-2a0d5b5f7474.jpg)
 how do i do this for 2 characters?

**Comment by TheLastBen** [comment]
you need to rename the pictures to the instances, but work very well with the old method

**Comment by LIQUIDMIND111** [comment]
> and on "subject/class", do i use PERSON or "male, female" if i am training 2 characters at the same time? Please help me here, i DID rename 20 pictures of myself and a lady friend BOTH we have 20 files with a TOKEN/INSTANCE already added to the INSTANCE files, AND like this: 4ZJENNIFER_woman_01.jpg etc. and me 4ZZEDDIE_man_01.jpg etc.......
> 
> Anyway, the results are an amazing HD model of people I DONT KNOW, LOLOLOL...... it came out amazing, but NOT either one of us...... so, what am i doing wrong? how do i really train 2 characters at the same time in which they are a man and woman...... how to i choose the CLASS OPTION.... man, woman OR person? i thought the CLASS had to be ONE WORD ONLY. and instance IF its two: "4ZJJJennifer, 4ZEDDIE" or "4ZJJJennifer woman, 4ZEDDIE man"

YES I MENTIONED ON TOP I DID THAT ALREADY,

**Comment by LIQUIDMIND111** [comment]
> you need to rename the pictures to the instances, but work very well with the old method

hello ben, i did that already yesterday, so today im gonna try again, please, let me know WHAT DO I WRITE on the section that says SUBJECT TYPE if i am doing 2 characters? Do i separate them by commas? ALSO the instance, do i write the instances separated by commas?

**Comment by LIQUIDMIND111** [comment]
Ok i DID IT finally with the OLD version!!!!, IF YOU HAVE 2 CHARACTERS, then SUBJECT should be PERSON, not MAN, WOMAN.... but i do look ugly.... only did a 1000 steps test.... maybe do it FULL RUN now.. Thanks ben,, take care.. i will send tips for coffee soon!

**Comment by kelvinz** [comment]
What if I'm training for a dog?
