### ISSUE TITLE
Where to copy the trained model in AUTOMATIC1111?

### ISSUE THREAD

**Issue by dskmusic** [TheLastBen/fast-stable-diffusion#38]
Where i have to put the files? And how to use? Thanks

**Comment by TheLastBen** [comment]
the model works only with diffusers, I'm working on a way to be able to use the trained model anytime you want.

**Comment by dskmusic** [comment]
Thanks, i dont understand very well, but many thanks for your efforts!

**Comment by TheLastBen** [comment]
Happy to help
