### ISSUE TITLE
Suggestion: dump interval ckpt to Sessions/instance

### ISSUE THREAD

**Issue by giteeeeee** [TheLastBen/fast-stable-diffusion#380]
Now ckpt_N_step is dumped to "Fast-Dreambooth/Sessions/".

Instead, how about dump it to "Fast-Dreambooth/Sessions/instance name"?

**Comment by TheLastBen** [comment]
That what I intended to do, since I didn't get the time to test it, it appears that it stops at Sessions instead of going inside the specific session folder, I'll fix that

**Comment by TheLastBen** [comment]
hopefully this will fix it : https://github.com/TheLastBen/fast-stable-diffusion/commit/fbb7dfc34e6ae6e815715122d1e76e70738201a0

**Comment by giteeeeee** [comment]
> hopefully this will fix it : [fbb7dfc](https://github.com/TheLastBen/fast-stable-diffusion/commit/fbb7dfc34e6ae6e815715122d1e76e70738201a0)

I'll test it now, waiting for the diffusers...

speaking of which, could you maybe add a diffuser_path to the gdrive? So that the notebook can directly use the bin file instead of going through "CKPT_Path:___" then convert everytime.

**Comment by giteeeeee** [comment]
no luck

console says dumping ckpt to /Sessions/instance, but still ends up in /Sessions/

**Comment by TheLastBen** [comment]
I'll change it to Model_Path, if it's a ckpt it'll convert it, if it's diffusers, it'll use it directly

**Comment by giteeeeee** [comment]
> I'll change it to Model_Path, if it's a ckpt it'll convert it, if it's diffusers, it'll use it directly

that'd be awesome

**Comment by giteeeeee** [comment]
now it dumps correctly. thanks
