### ISSUE TITLE
Two new errors: 'Namespace' object has no attribute 'server_name" & hypernetwork.py invalid syntax 

### ISSUE THREAD

**Issue by animeking527** [TheLastBen/fast-stable-diffusion#395]
<img width="853" alt="Screen Shot 2022-11-05 at 9 44 34 AM" src="https://user-images.githubusercontent.com/73794570/200123536-b3ebaa08-0378-4cc3-a861-45331a57f2e5.png">
<img width="589" alt="Screen Shot 2022-11-05 at 9 46 20 AM" src="https://user-images.githubusercontent.com/73794570/200123537-3b2f300a-ec79-4eb3-a81f-07be978b8341.png">

**Comment by riclimcoo** [comment]
I am also getting this issue.

**Comment by TheLastBen** [comment]
A1111 probably made a syntax error, they will fix it quickly
