### ISSUE TITLE
Local Host Refuses to connect.

### ISSUE THREAD

**Issue by IsItArt** [TheLastBen/fast-stable-diffusion#40]
Hello, I'm getting this error regularly when trying to launch the local connection.  When I went to the public gradio I was taken to something that I'm pretty sure isn't Stable Diffusion.  The translated text says "Convert Kurdish speech to writing".

![image](https://user-images.githubusercontent.com/114830354/193424426-395a8459-d6b0-4559-b9b6-50a76797b2a3.png)

**Comment by TheLastBen** [comment]
Gradio sometimes sends you a link to a different server, just restart the gradio cell and it'll fix

**Comment by IsItArt** [comment]
Any suggestions on the local host error?  I'd like to be able to do it that way instead of using the public if possible.

**Comment by TheLastBen** [comment]
Impossible with google colab, but you can set a password for you server, I'll add that option later

**Comment by IsItArt** [comment]
Ahh okay, thanks!

**Comment by TheLastBen** [comment]
no problem
