### ISSUE TITLE
Error message when trying to inpaint

### ISSUE THREAD

**Issue by norfuer** [TheLastBen/fast-stable-diffusion#404]
Hello!

For almost two weeks now, I've been using this Colab. Great piece of work, I gotta say! 

Unfortunately, for most of that time, I've been unable to use inpainting, because of some error or another. Attached are just a few that I've gotten. 

Yesterday, I was finally able to start using inpaint. Probably because I just kept updating it as it went along. After using it for a brief couple of hours, I went on with the rest of my day. 

Next time I started it up, inpaint stopped working for me. 

Which is truly unfortunate. Inpaint, I can see, has the potential to be a powerful feature to really increase the precision of image control. 

And I'm hoping to be able to use it again!

Thank you for all your hard work keeping this Colab updated!

![Screenshot_70](https://user-images.githubusercontent.com/65845435/200144776-8348b7b9-62de-48e7-9679-7903c7f6f1fe.png)
![Screenshot_67](https://user-images.githubusercontent.com/65845435/200145601-8cd498c8-d2e6-4e56-8157-d655c02c4fb7.png)
![Screenshot_68](https://user-images.githubusercontent.com/65845435/200145609-6d5e33d2-6674-4cd0-a970-4ac357cb93ad.png)

**Comment by TheLastBen** [comment]
how to reproduce the error ?

**Comment by norfuer** [comment]
I usually just send a freshly generated image to inpaint, turn on inpaint
full resolution, draw a mask, type in the prompts, adjust settings to match
my txt2img settings, then hit generate.

Also happens whenever I drag an image into inpaint.

I don't know if it's because I'm doing something wrong.

**Comment by norfuer** [comment]
Figured it out. It's my privacy suite. Turning it off lets me use inpaint. I apologise for the inconvenience.
