### ISSUE TITLE
local_fast_dreambooth_win issue with model

### ISSUE THREAD

**Issue by vgaggia** [TheLastBen/fast-stable-diffusion#421]
I just keep getting this:

No model found, make sure you put the diffusers model in the right folder

i tried making a folder called models in root(with a model in it) but it seems to have not made any difference, does the ckpt have to be named something in specific?

I've also put a model in literally all the folders and i still get the error, it doesn't really say which folder its looking in either, this feels like it's probably a bug.

Running the Jupyter notebook with VSCode + miniconda

**Comment by TheLastBen** [comment]
The diffusers model should be in a folder called "stable-diffusion-v1-5"

**Comment by vgaggia** [comment]
I created the folder and put the model in there, but still nothing, does it have to be inside another directory in the repo?

**Comment by TheLastBen** [comment]
do a screenshot of the model's folder structure

**Comment by vgaggia** [comment]
![image](https://user-images.githubusercontent.com/1644490/200267954-2f63565c-60fc-4337-9bb5-547567b41dc6.png)
![image](https://user-images.githubusercontent.com/1644490/200268063-c8b89580-3c27-4850-8a3b-414dcea1e525.png)

**Comment by TheLastBen** [comment]
nope, you shouldn't use the ckpt, it should be like this : https://huggingface.co/runwayml/stable-diffusion-v1-5/tree/main (without the ckpt files)

**Comment by vgaggia** [comment]
Ohhh i see, i'm so sorry about that, thank you very much.

**Comment by CptGabok** [comment]
@vgaggia Did you get this to work? And...how did you even get to this step, if I might ask?

**Comment by vgaggia** [comment]
@CptGabok Well where are you stuck?
