### ISSUE TITLE
Dreambooth colab : the folder /cont/models/ is not created

### ISSUE THREAD

**Issue by remybonnav** [TheLastBen/fast-stable-diffusion#44]
Hi, when running the  "Start dreambooth cell " we get an error that the folder /content/models/ is not there.
I manually add it and it works but maybe would be smoother to create the folder in the last cells or at the beginning of this cell.
;)

**Comment by TheLastBen** [comment]
it should create it automatically, unless there is another error, are you sure you're not getting an error ?

**Comment by remybonnav** [comment]
In the code I only see this 
`INSTANCE_DIR="/content/data/"+INSTANCE_NAME
!mkdir -p $INSTANCE_DIR
CLASS_DIR="/content/data/"+ SUBJECT_NAME
OUTPUT_DIR="/content/models/"+ INSTANCE_NAME`

So it seems it only creates the directory to put the instances images 

I'll check tomorrow (now training in progress and go to bed)

**Comment by 1blackbar** [comment]
I also dont like the fact it doesnt even ask me if i want to copy models folder to drive and does it automaticaly, id prefere a cell to do that only if i want to and i decide about the path.
Another thing is the path which webui is using to load the model from, i would like to specifty path by myself
I know it was made one click for people who are afraid of many cells on colab but this is not the way to treat all other users who want total freedom about where things should be stored and loaded from.
These things weight quite a bit and default paths should be editable.
Now i have to tinker with the code and paths everytime i open notebook to change defaults.
