### ISSUE TITLE
auto1111 doesn't run

### ISSUE THREAD

**Issue by giteeeeee** [TheLastBen/fast-stable-diffusion#449]
Notebook is up to date
Have tried deleting the sd folder
Have tried using both the local and gradio server

Error log:
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [fc713e21] from /content/gdrive/MyDrive/Lh/zxn6-30z-2e6-3000poly/zxn6-30z-2e6-3000poly.ckpt
Applying cross attention optimization (Doggettx).
Model loaded.
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 203, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 149, in webui
    demo = modules.ui.create_ui(wrap_gradio_gpu_call=wrap_gradio_gpu_call) 
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 676, in create_ui
    txt_promid="txt2img_prompt_image", file_count="single", type="bytes", visible=False)
  File "/usr/local/lib/python3.7/dist-packages/gradio/components.py", line 2103, in __init__
    f"Invalid value for parameter `type`: {type}. Please choose from one of: {valid_types}"
ValueError: Invalid value for parameter `type`: bytes. Please choose from one of: ['file', 'binary']

**Comment by pietrocosta81** [comment]
I am also experiencing this issue

**Comment by TheLastBen** [comment]
I'm on it

**Comment by TheLastBen** [comment]
fixed, apparently A1111 not yet compatible with gradio 3.9.1, setting it to 3.9 fixed the issue.

use the updated notebook : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by giteeeeee** [comment]
now works thanks a lot

**Comment by jcplus** [comment]
> fixed, apparently A1111 not yet compatible with gradio 3.9.1, setting it to 3.9 fixed the issue.
> 
> use the updated notebook : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

It works for me.
Before I know this, actually re-run from the *Installing Requirements* also fixes. :D
