### ISSUE TITLE
Resuming training from a previous session gives error and create a new ckpt file in seconds

### ISSUE THREAD

**Issue by JimZeeKing** [TheLastBen/fast-stable-diffusion#452]
Just tried to resume a training started yesterday and it fails with error (disapearing too fast for me to event read) but still create a ckpt file.

**Comment by JimZeeKing** [comment]
![image](https://user-images.githubusercontent.com/19315887/201108097-9bbac9ab-40cc-4732-b83d-b556db90c54f.png)
Manage to grab a screen

**Comment by JimZeeKing** [comment]
@TheLastBen Yes

**Comment by TheLastBen** [comment]
there should be a folder named "models" that contains the model in the file explorer tab

**Comment by JimZeeKing** [comment]
@TheLastBen You mean in my drive?

**Comment by TheLastBen** [comment]
in the colab file explorer, in colab storage, not in gdrive

**Comment by JimZeeKing** [comment]
@TheLastBen you are right there is none, weird since i resumed a session. I guess i should run the "download the model"

**Comment by TheLastBen** [comment]
yep you should start again with the orignal model

**Comment by JimZeeKing** [comment]
@TheLastBen Ok tx a lot. Weird that before (yesterday) it asked me to download the model when strating training, but now it does not

**Comment by TheLastBen** [comment]
I noticed that, I'll check it out
