### ISSUE TITLE
Missing DPM++ 2S a Karras sampler

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#455]
I heard this new sampler should be available thru Auto's. I updated the repo yesterday in colab with a ton of changes. Today it says it is up to date. I have not blown away my SD folder hoping it was part of Auto and not base SD.
![image](https://user-images.githubusercontent.com/4285187/201275454-63f765bc-46a9-43e2-84aa-3a9f36dafb63.png)
Do you have to enable something before we get access?

**Comment by TheLastBen** [comment]
rename/remove the folder "sd" from your gdrive and do a clean run

**Comment by GuruVirus** [comment]
Awww man. Thanks!
