### ISSUE TITLE
Sometimes gradio webui wont display result even tho it was synthesized cause i see it in notebook

### ISSUE THREAD

**Issue by 1blackbar** [TheLastBen/fast-stable-diffusion#46]
Im not sure wht causes it maybe big sizes and memory leak of some sort ?
I prompt like 20 times with batch 2 and 576x704 on t4 and after awhile images wont display anymore i have to refresh F5 the page to make the thing work again.
Is it fixable?
Also can you let us specify a path to googledrive for all images prompted with web ui ? that would be neat, now im saving by hand and im out of names :D

**Comment by TheLastBen** [comment]
That's a problem with gradio that they should fix, as for saving the pics in gdrive, I'll work on it

**Comment by 1blackbar** [comment]
So can you add a cell thats generating images without gradio ?

**Comment by mauzus** [comment]
Yeah, an optional cell like in the previous DreamBooth notebook would be great. Gradio can be very buggy, at least on free Colab.

Saving automatically in GD would be amazing, too!

**Comment by TheLastBen** [comment]
I'll add a cell for that

**Comment by 1blackbar** [comment]
yeh saving images from prompts on drive will be useful

**Comment by TheLastBen** [comment]
fixed

**Comment by AbyszOne** [comment]
> Yeah, an optional cell like in the previous DreamBooth notebook would be great. Gradio can be very buggy, at least on free Colab.
> 
> Saving automatically in GD would be amazing, too!

Fuck you.
