### ISSUE TITLE
xformers not working?

### ISSUE THREAD

**Issue by ShinCoreSys** [TheLastBen/fast-stable-diffusion#463]
i am running the auto1111 colab and when i use --xformers arg for launch, it gives me this:

![image](https://user-images.githubusercontent.com/86867253/201463039-028ed45b-8843-4efe-ae01-890701a22672.png)

am i doing something wrong?

**Comment by TheLastBen** [comment]
don't use --xfomers, it is automatically implemented in the colab since the release of the xformers optimization

**Comment by ShinCoreSys** [comment]
ah, i didnt know that. you have my thanks, and appreciation for your hard work @TheLastBen !
