### ISSUE TITLE
Running on local URL:  https://:443

### ISSUE THREAD

**Issue by hashborgir** [TheLastBen/fast-stable-diffusion#465]
Running on local URL:  https://:443

Server won't launch on the localtunnel, but like this, and no way to access it. Latest update.

**Comment by bananasss00** [comment]
Problem with local tunnel server. You can use gradio for now

https://github.com/TheLastBen/fast-stable-diffusion/issues/225

**Comment by wilzamguerrero** [comment]
the same 
![image](https://user-images.githubusercontent.com/110712636/201474893-daeeef77-3a45-4de6-98a5-1766d0e0d4ce.png)

**Comment by hashborgir** [comment]
Localtunnel is down right now. I'm sure when it comes up again it'll work. Until then Gradio server works.
