### ISSUE TITLE
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'  Time taken: 36.32sTorch active/reserved: 2069/2082 MiB, Sys VRAM: 2716/15110 MiB (17.97%)

### ISSUE THREAD

**Issue by wilzamguerrero** [TheLastBen/fast-stable-diffusion#467]
AttributeError: 'UNet2DConditionModel' object has no attribute 'enable_gradient_checkpointing'
Time taken: 36.32sTorch active/reserved: 2069/2082 MiB, Sys VRAM: 2716/15110 MiB (17.97%)

I have this error but checkpoint gradient is enable
![image](https://user-images.githubusercontent.com/110712636/201475109-1c3152f6-8ee2-4bdf-9179-801bb08db087.png)
![image](https://user-images.githubusercontent.com/110712636/201475124-14bb4946-43a2-4244-996b-bf7c5572ae8e.png)

**Comment by bananasss00** [comment]
execute in your colab `!pip install diffusers==0.7.2`

**Comment by wilzamguerrero** [comment]
Say  Incorrect diffusers version for Dreambooth, running installer.: 0.7.2 later to this work but.
![image](https://user-images.githubusercontent.com/110712636/201475793-e420e5f1-e43d-473e-bb75-24043bfa6366.png)

**Comment by bananasss00** [comment]
> Say Incorrect diffusers version for Dreambooth, running installer.: 0.7.2 later to this work but. ![image](https://user-images.githubusercontent.com/110712636/201475793-e420e5f1-e43d-473e-bb75-24043bfa6366.png)
yesterday it worked without installing diffiserrs, but today I have the same. I don't know what's the matter

**Comment by wilzamguerrero** [comment]
> > Say Incorrect diffusers version for Dreambooth, running installer.: 0.7.2 later to this work but. ![image](https://user-images.githubusercontent.com/110712636/201475793-e420e5f1-e43d-473e-bb75-24043bfa6366.png)
> > yesterday it worked without installing diffiserrs, but today I have the same. I don't know what's the matter

Maybe is gradio because yesterday with the local server work really good.

**Comment by wilzamguerrero** [comment]
!pip install GitPython==3.1.27
!pip install Pillow==9.2.0
!pip install accelerate==0.14.0
!pip install albumentations==1.3.0
!pip install basicsr==1.4.2
!pip install bitsandbytes==0.35.0
!pip install bitsandbytes
!pip install clean-fid==0.1.29
!pip install diffusers==0.7.2
!pip install einops==0.4.1
!pip install fairscale==0.4.9
!pip install font-roboto
!pip install fonts
!pip install ftfy==6.1.1
!pip install gfpgan==1.3.8
!pip install gradio==3.9
!pip install inflection==0.5.1
!pip install jsonmerge==1.8.0
!pip install kornia==0.6.7
!pip install lark==1.1.2
!pip install modelcards==0.1.6
!pip install numpy==1.23.3
!pip install omegaconf==2.2.3
!pip install piexif==1.1.3
!pip install pytorch_lightning==1.7.6
!pip install realesrgan==0.3.0
!pip install resize-right==0.0.2
!pip install scikit-image==0.19.2
!pip install tensorboard==2.11.0
!pip install timm==0.6.7
!pip install torch
!pip install torchdiffeq==0.2.3
!pip install tqdm==4.64.1
!pip install transformers==4.21.0

work with this
