### ISSUE TITLE
Batchprocessing in img2img only works once, img2img then becomes unresponsive

### ISSUE THREAD

**Issue by fabwa** [TheLastBen/fast-stable-diffusion#47]
Batchprocessing in img2img only works once, img2img then becomes unresponsive

**Comment by TheLastBen** [comment]
That's a gradio issue, check the official repo of automatic1111 for any solution

**Comment by TheLastBen** [comment]
Also try opening an issue on the gradio official github

**Comment by Gitterman69** [comment]
got the same problem with txt2img as well... after 1 run I gotta restart the colab

**Comment by fabwa** [comment]
Workaround:
Replace last. cell with this:


!pip install pyngrok

from pyngrok import ngrok

ngrok.kill()
# Get your authtoken from https://dashboard.ngrok.com/auth (make a free account and activate email)

NGROK_AUTH_TOKEN = "..."
ngrok.set_auth_token(NGROK_AUTH_TOKEN)


%cd /content/gdrive/MyDrive/sd/stable-diffusion/

public_url = ngrok.connect(7860, proto="http", options={"bind_tls": True})
!echo "----------------------------------------"
!echo "use once web server has initiated"
!echo "----------------------------------------"
print("Tracking URL:", public_url)
!echo "----------------------------------------"
!python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py --autolaunch --precision autocast --gradio-auth ash:ash


Log in with ash:ash
