### ISSUE TITLE
Having alot of black squares when doing SD upscaling

### ISSUE THREAD

**Issue by papom123** [TheLastBen/fast-stable-diffusion#473]
When I'm doing SD upscaling there's alot of back squares in the same place. no matter how much i changed the settings. I'n locals i would do --no-half-vae in the webui-user.bat file to fix this issue. how can I activate this with your automatic colab?

**Comment by papom123** [comment]
![SD upscale](https://user-images.githubusercontent.com/118077415/201522422-922b3fb3-2b4a-45ab-bfb5-62112725fc3f.JPG)
Its all like this. Please help.

**Comment by TheLastBen** [comment]
I'll see what I can do

**Comment by TheLastBen** [comment]
in the A111 Colab, check the boxes "Redownload_the_original_model" AND "Hypernetwork_Training_Compatibility", then try the SD upscaling.

**Comment by papom123** [comment]
Works perfectly! Thankyou so much! <3

**Comment by TheLastBen** [comment]
great !

**Comment by papom123** [comment]
However, when i turn use vae it happens again. :(

**Comment by TheLastBen** [comment]
check the box "Redownload_the_original_model" without checking the box "Hypernetwork_Training_Compatibility",

**Comment by papom123** [comment]
Nope. Still doesnt work. :(

**Comment by TheLastBen** [comment]
I misunderstood, you know that  --no-half-vae disables the vae right ? so that means the SD upscaling is not compatible with the new vae

**Comment by papom123** [comment]
Oh. I didnt know that. Since i can do it locally but my computer is too slow so i thought i'd be able to do it here too. Thankyou so much for trying to help! <3
