### ISSUE TITLE
RESULTS ON THE NEW PAGE are amazing but i have ONE issue now!

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#474]
BRO!!! The results using text encoder at 100, are amazing!!!

If i use only ONE instance like **"a photo bvuwyfjennxiffer in the park"** i will get a picture exactly as she is, and if i use the instance **"a photo of uvtbehrtangxie in the couch"**, i will get exactly as she is.

BUT NOW I HAVE AN ISSUE. IF I USE BOTH INSTANCES, as i have done before with PERFECT RESULTS, like **"a photo of uvtbehrtangxie, and bvuwyfjennxiffer in the park"** - instead of having 2 people with its own faces, i will have 2 girls with a BLEND of each of their faces... this has not happened before on the OLD model when i prompt 2 instances at once..... a man and a woman, they will come together VERY WELL....

i did this before and got great results.... what do you think is happening now??? i can send screenshots of results if you want...... please let me know whats happening,,,,,

**Comment by LIQUIDMIND111** [comment]
LOOK RESUTLS HERE BEN:


PHOTO ONE - a photo bvuwyfjennxiffer in the park

PERFECT RESULT, LOOKS LIKE HER 99%
![instance b](https://user-images.githubusercontent.com/112510084/201492416-01689d20-5a0a-460e-a00b-ea9fa15a4ee9.jpg)

PHOTO 2 a photo of uvtbehrtangxie in the couch

LOOKS LIKE HER 98%
![instance a](https://user-images.githubusercontent.com/112510084/201492430-4a2db0c1-928c-46a0-ab40-7a01d33ee64b.jpg)

PHOTO 3 - a photo of uvtbehrtangxie, and bvuwyfjennxiffer in the park

THEY BLENDED.... 
YOU CAN SEE THEY MORPH TOGETHER, and this has not happened to me before,,, whats the matter?
![instances a and b](https://user-images.githubusercontent.com/112510084/201492442-10221d88-793f-4d6e-8c73-5939b4cb2d7b.jpg)

**Comment by TheLastBen** [comment]
training on two people or more from the same gender will result in merging, this has nothing to do with the training, it's just the way diffusion works (for now)

**Comment by LIQUIDMIND111** [comment]
ah got it, but when i used MYSELF with one of THEM, it came out all good when we are together, so you mean its OK because of the gender difference?

**Comment by christopher-altman** [comment]
The best way to fix it for now is by using _Inpainting_ after the fact to fill in the facial details as deemed fit …
