### ISSUE TITLE
Text encoder at 100% supposed to train unet at same time? 

### ISSUE THREAD

**Issue by animeking527** [TheLastBen/fast-stable-diffusion#475]
I just tried a model with current colab with text encoder checked and set to 100 however it trained the text enc & unet separately. I read in another issue that they're supposed to train simultaneously when set to 100? If this is correct, was there something else to do to trigger them to train together?

**Comment by TheLastBen** [comment]
if you set contain_faces to other thant "No" the text encoder will train first with class images, then followed the UNet without class images

**Comment by animeking527** [comment]
Ah, I see. Thanks!
