### ISSUE TITLE
Dreambooth in automatic 111 but when i press train with the model  v1-5-pruned-emaonly

### ISSUE THREAD

**Issue by wilzamguerrero** [TheLastBen/fast-stable-diffusion#478]
Hi i try to use Dreambooth in automatic 111 but when i press create with the model  v1-5-pruned-emaonly.ckpt i have error and don't continue generating the creation.

when this happend only stop all in colab

![image](https://user-images.githubusercontent.com/110712636/201498051-58704977-17b7-4fa6-b963-475d1b6ec3d9.png)

**Comment by TheLastBen** [comment]
probably not enough RAM, use a 4GB CKPT

**Comment by wilzamguerrero** [comment]
> probably not enough RAM, use a 4GB CKPT

Im only used 4 ckpt, i dont use the big.

**Comment by TheLastBen** [comment]
check the error log

**Comment by wilzamguerrero** [comment]
> check the error log

i only have this message 
![image](https://user-images.githubusercontent.com/110712636/201539314-9012fe52-c4af-4649-9bb3-e70962fdd253.png)

**Comment by TheLastBen** [comment]
^C means the program stopped because the RAM is full

**Comment by bananasss00** [comment]
> > check the error log
> 
> i only have this message ![image](https://user-images.githubusercontent.com/110712636/201539314-9012fe52-c4af-4649-9bb3-e70962fdd253.png)
There is not enough memory for webui-dreambooth extension on colab(free) with 12gb ram and 2gb ckpt. I blocked the loading of the main model with a webui code patch, after which the training was successful

**Comment by bananasss00** [comment]
> **TheLastBen** ^C means the program stopped because the RAM is full

I also tried unloading the model at runtime, but that doesn't help, the size of the process doesn't decrease. Do you know how to do it right?
`from modules import shared, sd_hijack
import gc, torch, psutil

print(psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024)

shared.sd_model.to('cpu') # without this not help too
sd_hijack.model_hijack.undo_hijack(shared.sd_model)
del shared.sd_model.cond_stage_model
del shared.sd_model.first_stage_model
del shared.sd_model.model.diffusion_model.input_blocks
del shared.sd_model.model.diffusion_model.middle_block
del shared.sd_model.model.diffusion_model.output_blocks
del shared.sd_model.model.diffusion_model
del shared.sd_model.model
del shared.sd_model
shared.sd_model = None

gc.collect()
torch.cuda.empty_cache()
torch.cuda.ipc_collect()

print(psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024)`

**Comment by wilzamguerrero** [comment]
i used the model thtat creacte in automatic111 
and later i used this

!pip install -q git+https://github.com/huggingface/diffusers
pip install bitsandbytes
pip install --upgrade pip

and if dont work i used this to

pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116
or
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117

now is working dreambooth with some issues um working on this 
![image](https://user-images.githubusercontent.com/110712636/201770505-8a43e7a1-9513-4dc0-913f-b0e6b6191437.png)

**Comment by bananasss00** [comment]
> now is working dreambooth with some issues um working on this ![image](https://user-images.githubusercontent.com/110712636/201770505-8a43e7a1-9513-4dc0-913f-b0e6b6191437.png)
Convert to ckpt not crashing?

And how many RAM u have?

**Comment by wilzamguerrero** [comment]
15
