### ISSUE TITLE
Dreambooth Train_text_encoder_for: Sensible Defaults

### ISSUE THREAD

**Issue by niklas2810** [TheLastBen/fast-stable-diffusion#482]
Hey there! 

I'm quite new to Stable Diffusion, so I'm sorry if I got something wrong. Anyways, I'm currently trying to train a model on my face, and wondered why Train_text_encoder_for is set to 100% by default. 

If I understand the caption correctly, doesn't this mean that the output from the model is super hard to stylize and basically reproduces the input images? That's how I understood it and lowered it a bit (50% I think). My output model is not very good at styles now (30 input images, 3000 steps) should I set the value to something way lower (like 10/15%) to get better styling or do I simply have to train it longer? I noticed that the recommended step count is now 20x images, not 10x images anymore.

Thanks for creating this awesome project! I hope you can help me out :)

**Comment by TheLastBen** [comment]
initially I set it to 35% for easier style training/transfer, but then I got complaints about the method not being good at faces, so I set it back to 100% and if someone wants to train a style or transfer a style, they will have to set the texnt_encoder to 15% or less and set the training steps to higher than 7000

**Comment by niklas2810** [comment]
Okay cool, thanks for the info! Just making sure I got this right:

For faces and styles use a low Train_text_encoder_for value (15% or less) and increase step to something like 7000? And for which kind of images does a high Train_text_encoder_for value make sense?

**Comment by TheLastBen** [comment]
For faces you set it to 100%, for style, set it to 10-20%

if you want to stylize the faces, reduce it to 50-60%

the maximum total steps of the text_encoder should be 4000
