### ISSUE TITLE
Gradio issue is so annoying 

### ISSUE THREAD

**Issue by MrAshbury20** [TheLastBen/fast-stable-diffusion#49]
**I should rerun the gradio interface every single time I generate something, although it's seems to be done in colab but no results shown in the Gradio, the previous version of the colab was much more amazing in working well , I was able to generate many prompts , and free to use much steps too , I reached 500 steps and it was outstanding, now with this version i can just generate from time to time with less steps less dimensions, and also less number of images, what a worst downgrade, I don't have the perfect pc or components to enjoy  SD in general like everbody does, but at least I hope people  improve the colabs versions to the best not the worst, not everybody has monsters PC. Thanks TheLastBen for your efforts.**

**Comment by TheLastBen** [comment]
For the in-Gradio features you need to open an issue here :  https://github.com/AUTOMATIC1111/stable-diffusion-webui
the colabs are just a way to run the repos from automatic1111 and hlky

**Comment by fabwa** [comment]
Workaround:
Replace last. cell with this:

!pip install pyngrok

from pyngrok import ngrok

ngrok.kill()
Get your authtoken from https://dashboard.ngrok.com/auth (make a free account and activate email)

NGROK_AUTH_TOKEN = "..."
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

%cd /content/gdrive/MyDrive/sd/stable-diffusion/

public_url = ngrok.connect(7860, proto="http", options={"bind_tls": True})
!echo "----------------------------------------"
!echo "use once web server has initiated"
!echo "----------------------------------------"
print("Tracking URL:", public_url)
!echo "----------------------------------------"
!python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py --autolaunch --precision autocast --gradio-auth ash:ash

Log in with ash:ash
