### ISSUE TITLE
How can we add a password to the gradio web ui?

### ISSUE THREAD

**Issue by gregrobison** [TheLastBen/fast-stable-diffusion#50]
Since it's a public address, I'd like to put a password on it, but can't figure out where to add the flags. Thanks.

**Comment by TheLastBen** [comment]
try this flag : --gradio-auth user:password

**Comment by gregrobison** [comment]
If I'm using the Colab version, would I add it to !python /content/interface.py?

**Comment by TheLastBen** [comment]
I see that you are using dreambooth, try it and le me know if it works

**Comment by gregrobison** [comment]
Dreambooth works well on my dogs, running out of colab compute credits now... But I'd like to create more images in the gradio ui with a password (like AUTOMATIC1111's version).

**Comment by TheLastBen** [comment]
You can still use Dreambooth with the free version of colab

**Comment by TheLastBen** [comment]
same thing for the AUTOMATIC1111 fork, just add **--gradio-auth user:password** in the last cell
