### ISSUE TITLE
black blank images instead of results in webui

### ISSUE THREAD

**Issue by 1blackbar** [TheLastBen/fast-stable-diffusion#51]
I really would prefere to inference inside colab and not in webui

**Comment by TheLastBen** [comment]
I updated the colab to save images in Gdrive, you must use the latest colab from the repo

**Comment by 1blackbar** [comment]
yup, worked now, also i edited the path to model in interface.py

StableDiffusionPipeline.from_pretrained("/content/gdrive/Shareddrives/Dysk1blackbar/AI/models/krs",torch_dtype=torch.float16

Can you open up that path so we can paste the location of the model ourselves it in the cell  without having to open py file ? and if its empty just use default one ?

**Comment by TheLastBen** [comment]
I'm working on that at the moment

**Comment by TheLastBen** [comment]
Added a custom path, give it a try

**Comment by 1blackbar** [comment]
works great

**Comment by TheLastBen** [comment]
Now the produced CKPTs are 2Gb (half precision)
