### ISSUE TITLE
Training with fp16 produces 4gb checkpoint

### ISSUE THREAD

**Issue by JimZeeKing** [TheLastBen/fast-stable-diffusion#513]
As the title say, before when i trained a model with fp16 on it would be 2gb in size.
Trained a new model this morning with fp16 and got a 4gb checkpoint, is this normal?

**Comment by TheLastBen** [comment]
Yes, fp16 is half precision, so the ckpt is produced in half-precision

**Comment by JimZeeKing** [comment]
@TheLastBen Just to be sure a fp16 checkpoint would be 2gb right? Because mine is 4gb even though is use fp16. Sorry if my issue was not clear.

**Comment by TheLastBen** [comment]
You should get a 2gb ckpt if the fp16 is checked.

**Comment by JimZeeKing** [comment]
@TheLastBen Well something is off beacuse i kept the default values (fp16 cheked) and got a 4gb ckpt. Is there a way to go back in time on collab to see the settings of my last run?

**Comment by TheLastBen** [comment]
if you uncheck the fp16 you will notice the training time doubling, that should be a sign.

**Comment by JimZeeKing** [comment]
@TheLastBen Well for the last run i paid for collab credits and used the premium gpu so the time for 6000 steps was about 1h:10min . Ill close this and report if i manage to recreate the problem.

Thanks

**Comment by TheLastBen** [comment]
if you're using the A1000, use 1024 pictures, upload large pictures and set the "autocrop" to 1024 and the resolution in the training cell to 1024, you will be surprised by the quality

**Comment by JimZeeKing** [comment]
@TheLastBen Humm i did activate the premium GPU but did not see the name if it...is it in the little ressource box top right?

**Comment by TheLastBen** [comment]
in a new cell, run `!nvidia-smi` it will show the GPU's name
