### ISSUE TITLE
FIRST ATTEMPT DOING A STYLE MODEL

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#514]
The only question I have for now is, DO I NEED TO UPLOAD CLASS images for styles also??? IF SO, then can i use the same images as my instances? or maybe related images that are NOT the same as subject images/??

**Comment by JimZeeKing** [comment]
I didnt not upload class image for my style training and it worked really well so that is possibly not relevant to upload them, maybe i am wrong though

**Comment by LIQUIDMIND111** [comment]
> I didnt not upload class image for my style training and it worked really well so that is possibly not relevant to upload them, maybe i am wrong though

thanks sir

**Comment by LIQUIDMIND111** [comment]
> > I didnt not upload class image for my style training and it worked really well so that is possibly not relevant to upload them, maybe i am wrong though
> 
> thanks sir

so in STYLE you use only the instance or INSTANCE STYLE ?

**Comment by TheLastBen** [comment]
No need for class images if the style images do not contain repetitive faces.

**Comment by Barry-Bot1** [comment]
> 

What if the style had both faces and landscapes/Objects ect..?

**Comment by TheLastBen** [comment]
It shouldn't be an issue, train it without class images, just make sure you name the images correctly, using a unique identifier that doesn't contain existing words or abbreviations.
