### ISSUE TITLE
EOL error on Gradio cell in Dreambooth colab

### ISSUE THREAD

**Issue by TheOn3WhoKn0cks** [TheLastBen/fast-stable-diffusion#52]
This is probably something very easy to fix if I knew anything about Python, but whenever I try to run the last cell I get the following error message: 

  File "/content/interface.py", line 204
    path='/content/gdrive/MyDrive/models/modelx",torch_dtype=torch.float16).to("cuda")
                                                                                    ^
SyntaxError: EOL while scanning string literal 

I tried to play a little with the syntax to see if I could get it to work but I couldn't figure it out

**Comment by TheLastBen** [comment]
I'll check it out, will be fixed in a few

**Comment by TheLastBen** [comment]
I think you didn't update the colab to the latest commit, try and load the latest colab from the repo
