### ISSUE TITLE
About the tag autocomplete extension

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#520]
I modified my code with reference to this problem to make the extension works.
https://github.com/TheLastBen/fast-stable-diffusion/issues/409
![}TO{@2}0S% `(IO_5M}8)M4](https://user-images.githubusercontent.com/112967097/202092605-4c63a41e-5ac3-41ac-98e4-a27241ac9c07.png)
It works correctly until today.
The change of the cell cause start up problem while nothing wrong was reported.
![1D@M~L XT78G01RIAS$U5 4](https://user-images.githubusercontent.com/112967097/202092432-aa6010b2-1a7f-4e6f-b891-052341b66d54.png)
After change back the cell, it return to normal.
Seems we have to find a new way to make this extension work.

**Comment by TheLastBen** [comment]
keep the change and use the gradio server to see if it works

**Comment by tsound97** [comment]
No, it doesn't.
And I just realized that my operation was the opposite of what was in your commit.
I change **stable-diffusion** to **stable-diffusion-webui**
![GEH8N 2AU`AF4_0L@VXX3D7](https://user-images.githubusercontent.com/112967097/202096006-0a3e57a8-f3b3-4dcf-bc95-36dcefee665a.png)
![image](https://user-images.githubusercontent.com/112967097/202095817-37622400-1e86-46f9-8274-c726f806251a.png)
Did I misunderstand something？

**Comment by TheLastBen** [comment]
did you figure out why it suddenly won't work ?

**Comment by tsound97** [comment]
No, I try a lot include the API option and finally find the problem is caused by change **stable-diffusion** to **stable-diffusion-webui**

**Comment by tsound97** [comment]
I do a clean run, and it works. Thanks for help!
