### ISSUE TITLE
Xformers for supported GPU in Colab

### ISSUE THREAD

**Issue by mediocreatmybest** [TheLastBen/fast-stable-diffusion#526]
Hi!

It doesn't look like xformers is being installed and used when running with a supported Colab GPU. 
Looking at the output it is just loading the usual

 "Applying cross attention optimization (Doggettx)." 

This is within the AUTOMATIC1111 Fast Stable Diffusion Colab, that is also with the Hypernetwork compatibility unselected.

Thanks!

**Comment by TheLastBen** [comment]
Hi, if you get more than 4.8 it/s with the T4 for 512x512 images, then xformers works

**Comment by mediocreatmybest** [comment]
Thanks. 
When generating at 512x512? 
I'll give this a shot today and update the post.

**Comment by mediocreatmybest** [comment]
Not sure why I didn't see this before, maybe because I tried to install the dreambooth extension to see if it worked? 

`Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import xattention
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 8, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import xattention
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 8, in <module>
    from diffusers.models.attention import xformers
ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)`

It does continue to load, I'm getting between 1 to 4 it/s but seems to settle on larger steps at 3.6 it/s

**Comment by TheLastBen** [comment]
disable the API box

**Comment by mediocreatmybest** [comment]
Thanks, I did disable it, I'm guessing the extension still is trying to call it? 
Doesn't matter if Hypernetwork compatibility or API is enabled or disabled, if that extension is installed it kicks out the xformers error, that was one of the reasons I wasn't sure it was being activated at all? 

Thanks :)

**Comment by TheLastBen** [comment]
Hypernetwork compatibility will uninstall xformers, but the API I'm no sure what it does to the xfomers

**Comment by mediocreatmybest** [comment]
No worries, I'm suspecting at this point the dreambooth extension isn't compatible with the colab version since it spits out xformers errors no matter the option checked. Might be something I need to manually install line by line till I see what causes it.

**Comment by wilzamguerrero** [comment]
> Not sure why I didn't see this before, maybe because I tried to install the dreambooth extension to see if it worked?
> 
> ```
> Error loading script: api.py
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
>     module = script_loading.load_module(scriptfile.path)
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
>     exec(compiled, module.__dict__)
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 9, in <module>
>     from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
>     from extensions.sd_dreambooth_extension.dreambooth import xattention
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 8, in <module>
>     from diffusers.models.attention import xformers
> ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)
> ```
> 
> ```
> Error loading script: main.py
> Traceback (most recent call last):
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 164, in load_scripts
>     module = script_loading.load_module(scriptfile.path)
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
>     exec(compiled, module.__dict__)
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 3, in <module>
>     from extensions.sd_dreambooth_extension.dreambooth import conversion, dreambooth
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/conversion.py", line 30, in <module>
>     from extensions.sd_dreambooth_extension.dreambooth import xattention
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/xattention.py", line 8, in <module>
>     from diffusers.models.attention import xformers
> ImportError: cannot import name 'xformers' from 'diffusers.models.attention' (/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py)
> ```
> 
> It does continue to load, I'm getting between 1 to 4 it/s but seems to settle on larger steps at 3.6 it/s


Use this 

!pip install diffusers==0.7.2

**Comment by wilzamguerrero** [comment]
or use all of this for fix the start of dreambooth

!pip install GitPython==3.1.27
!pip install Pillow==9.2.0
!pip install accelerate==0.14.0
!pip install albumentations==1.3.0
!pip install basicsr==1.4.2
!pip install bitsandbytes==0.35.0
!pip install bitsandbytes
!pip install clean-fid==0.1.29
!pip install diffusers==0.7.2
!pip install einops==0.4.1
!pip install fairscale==0.4.9
!pip install font-roboto
!pip install fonts
!pip install ftfy==6.1.1
!pip install gfpgan==1.3.8
!pip install gradio==3.9
!pip install inflection==0.5.1
!pip install jsonmerge==1.8.0
!pip install kornia==0.6.7
!pip install lark==1.1.2
!pip install modelcards==0.1.6
!pip install numpy==1.23.3
!pip install omegaconf==2.2.3
!pip install piexif==1.1.3
!pip install pytorch_lightning==1.7.6
!pip install realesrgan==0.3.0
!pip install resize-right==0.0.2
!pip install scikit-image==0.19.2
!pip install tensorboard==2.11.0
!pip install timm==0.6.7
!pip install torch
!pip install torchdiffeq==0.2.3
!pip install tqdm==4.64.1
!pip install transformers==4.21.0

and check and unckeck this option

![image](https://user-images.githubusercontent.com/110712636/202563326-df7c6f8b-084c-4cee-8572-b7b1fa6cafa4.png)

**Comment by mediocreatmybest** [comment]
> or use all of this for fix the start of dreambooth
> 
> !pip install GitPython==3.1.27 !pip install Pillow==9.2.0 !pip install accelerate==0.14.0 !pip install albumentations==1.3.0 !pip install basicsr==1.4.2 !pip install bitsandbytes==0.35.0 !pip install bitsandbytes !pip install clean-fid==0.1.29 !pip install diffusers==0.7.2 !pip install einops==0.4.1 !pip install fairscale==0.4.9 !pip install font-roboto !pip install fonts !pip install ftfy==6.1.1 !pip install gfpgan==1.3.8 !pip install gradio==3.9 !pip install inflection==0.5.1 !pip install jsonmerge==1.8.0 !pip install kornia==0.6.7 !pip install lark==1.1.2 !pip install modelcards==0.1.6 !pip install numpy==1.23.3 !pip install omegaconf==2.2.3 !pip install piexif==1.1.3 !pip install pytorch_lightning==1.7.6 !pip install realesrgan==0.3.0 !pip install resize-right==0.0.2 !pip install scikit-image==0.19.2 !pip install tensorboard==2.11.0 !pip install timm==0.6.7 !pip install torch !pip install torchdiffeq==0.2.3 !pip install tqdm==4.64.1 !pip install transformers==4.21.0
> 
> and check and unckeck this option
> 
> ![image](https://user-images.githubusercontent.com/110712636/202563326-df7c6f8b-084c-4cee-8572-b7b1fa6cafa4.png)
> 
> now is working for me
> 
> ![image](https://user-images.githubusercontent.com/110712636/202563419-da40e9d9-f61b-4b4b-b0e3-060c05d54982.png)

Awesome, thanks. 
I'll try this tonight when I'm back home and report back.

**Comment by mediocreatmybest** [comment]
looks all good now with the updates. closing.
