### ISSUE TITLE
After training all image are solid black

### ISSUE THREAD

**Issue by JimZeeKing** [TheLastBen/fast-stable-diffusion#535]
As the title says, i just did a training yeasterday and now when i test it all output is black, regardless of the prompt. What could be the cause?

**Comment by TheLastBen** [comment]
if the settings or not changed much, it must've been the instance images

**Comment by JimZeeKing** [comment]
@TheLastBen I did not change anything, use all black and white images, do you know what in the image could cause this? The image format? the image itself?

**Comment by TheLastBen** [comment]
try the same images with a small amount of steps (200), if the problem persists, try again but with different images, if the results aren't black, then the problem resides in the first images

**Comment by JimZeeKing** [comment]
i got a nan as a lost value so i guess its overtrained maybe?
will try what you said

**Comment by TheLastBen** [comment]
check the learning rate if it hasn't changed, it should be 2e-6

**Comment by JimZeeKing** [comment]
@TheLastBen Yep too many steps for the number of images i had. Thanks!
