### ISSUE TITLE
DreamBooth Error when training the text encoder

### ISSUE THREAD

**Issue by voidxd** [TheLastBen/fast-stable-diffusion#536]
It seems that today I'm getting a flickering error when training the text encoder and then it disappears and goes on to train the unet.

I'm using an A100, have tried with 90 images, 60 images, and 30 images. 18000 steps, 12000 steps, and 6000 steps, respectively. Kept text encoder under 4000. Tried this about 10 times and every time I'm getting the error. It appears after a few steps when training the text encoder.

I didn't know how to catch it other than recording it. It seems there are two different errors. 

Could you help, please? Thank you.

**Error 1**
![error_1](https://user-images.githubusercontent.com/58847957/202763600-d008544d-8123-41d7-b898-8af3220a9da0.png)

**Error 2**
![error_2](https://user-images.githubusercontent.com/58847957/202763607-a6d6dc25-6dbe-4a1f-9a14-3b4177504880.png)

**Comment by voidxd** [comment]
Seems to work with fp16 unchecked. Thank you.

Isn't it at all possible to train with fp16 enabled with A100, since I assume it's considerably faster? 

I have also tried it out with P100 and it seems to work.

**Comment by TheLastBen** [comment]
I personally use the A100 with fp16 and it works, I'll try to find the cause for that issue
