### ISSUE TITLE
What does With_Prior_Reservation do?

### ISSUE THREAD

**Issue by mcpejs** [TheLastBen/fast-stable-diffusion#54]
First of all, thank you so much for making this program, and I think it's a miracle that I can use dreambooth so easily

Question is:
I thought When `With_Prior_Reservation` is true, it would automatically generate a regularization image and use it for training
But even if I set `With_Prior_Reservation` to False, `Generating class images:` message is appear and it generate data/SUBJECT_NAME images
I can't understand why it generate class images because I thought class images were not used for training when `With_Prior_Reservation` is false

I know you have a lot of work, but I would really appreciate it if you could tell me what happens if `With_Prior_Reservation` is false
Thank you!!

**Comment by TheLastBen** [comment]
When With_Prior_Reservation is false, it shouldn't generate class images, I'll check that out

**Comment by TheLastBen** [comment]
remember when you set it to "No", you have to run that cell before starting dreambooth

**Comment by mcpejs** [comment]
I'm very sorry There was no problem running it again, I think i didn't run the cell before start the training As you say
Thank you so much for answering even though it was my mistake

**Comment by TheLastBen** [comment]
happy to help
