### ISSUE TITLE
Dreambooth: Every face looks like the face I trained it on, even without the keyword

### ISSUE THREAD

**Issue by voidxd** [TheLastBen/fast-stable-diffusion#559]
I had been using your notebook for ~1+ months and I believe it didn't used to behave like this.

I just trained a model on a male face with:
- 22 images
- 4000 steps
- 35 text encoder

Now if I give Stable Diffusion a prompt like _**portrait male fantasy art heartstone Video game icon, 2d game art gta cover , official fanart behance hd artstation by Jesper Ejsing, by RHADS, Makoto Shinkai and Lois van baarle, ilya kuvshinov, rossdraws**_, it will look very much like the person I trained Stable Diffusion on, but more artsy.

If I use the keyword in the ~first half of the prompt it will generate almost the exact face of the person I trained without much styling. If I add the keyword toward the end, or at the end of the prompt, sometimes I get stylized results and sometimes I get the exact face without style.

Is this expected behavior?

Thank you.

**Comment by TheLastBen** [comment]
try reducing the text_encoder % (set it to 15%) and increase the total steps to 6000
