### ISSUE TITLE
Commandline args in colab

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#560]
There are custom parameters that local users can set. Is there any way to set similar in colab? e.g. --no-half-vae or any of the other tons of options?

**Comment by TheLastBen** [comment]
you can add those in the last cell

**Comment by TheLastBen** [comment]
Have you tested --no-half-vae ? how do see the difference ?

**Comment by GuruVirus** [comment]
Are you suggesting adding additional commands after "--ckpt" below?

```
if os.path.isfile(model):
    !python /content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py $share $api --disable-safe-unpickle --ckpt "$model"
```
