### ISSUE TITLE
Downloading local models stopped working about an hour ago with compatibility_mode is not defined message (with or without the setting clicked)

### ISSUE THREAD

**Issue by dreamofmt** [TheLastBen/fast-stable-diffusion#566]
I was training a model and got disconnected, so I reconnected and tried to start my session back. It never saved my CKPT file (due to being disconnected), so I went to redownload the model using path and link (on my own drive, as well as other various ckpt files). 

I received an error about compatibility mode, I checked the box for compatibility mode and I receive the same error. I tried a different google drive account, and another browser, and then I rebooted. It is still happening.

This is the error if I click compatibility mode, or if I don't click it - it is always the same. I tried to run the cell about 50+ times at this point and always errors out.

NameError                                 Traceback (most recent call last)
[<ipython-input-5-809fafeef6e1>](https://localhost:8080/#) in <module>
    119     get_ipython().system('mkdir /content/stable-diffusion-v1-5')
    120     with capture.capture_output() as cap:
--> 121       if Compatiblity_Mode:
    122         get_ipython().system('wget https://raw.githubusercontent.com/huggingface/diffusers/039958eae55ff0700cfb42a7e72739575ab341f1/scripts/convert_original_stable_diffusion_to_diffusers.py')
    123         get_ipython().system('python /content/convert_original_stable_diffusion_to_diffusers.py --checkpoint_path "$CKPT_Path" --dump_path /content/stable-diffusion-v1-5')

NameError: name 'Compatiblity_Mode' is not defined

![Screenshot (8338)_cr](https://user-images.githubusercontent.com/116125222/202926675-8b2e2936-5bb3-4db4-ae36-9e5edc1bd65f.png)
![Screenshot (8339)_cr](https://user-images.githubusercontent.com/116125222/202926679-725fba14-af3b-4b18-85c4-f5274809015f.png)

Thank you for your time.

**Comment by TheLastBen** [comment]
fixed, caused by an incomplete merged pull request

**Comment by dreamofmt** [comment]
Thank you very much for fixing this, and everything else you do. Works excellently now.
