### ISSUE TITLE
A colab notebook I recently found.

### ISSUE THREAD

**Issue by tsound97** [TheLastBen/fast-stable-diffusion#588]
It has more features, please consider this as a reference for future updates.
Hope everything goes better!
https://colab.research.google.com/github/NoCrypt/sd-webui-colab/blob/main/sd-webui-colab.ipynb#scrollTo=gfKvWAVnz8OB

**Comment by TheLastBen** [comment]
That's just a bunch of checkboxes making the colab unnecessarily complicated and long, they are not features, instead of laying out dozens of extensions in the colab, the webui has integrated an easy library for that.

**Comment by nawnie** [comment]
most of these are not necessary if you have command line access or just add a line. im referring to the.. goodies most of which you can install via the ui.

it would be nice to have an easier way to change learning rate (found cartoon styles benefit from a higher start) or changing the LR scheduler, and the batch size / gradient steps. maybe also a spot to add urls to download directly to drive, again this is super easy for anyone willing to learn, so i think ill attempt to do that and post it on here if anyone wants them. id look for it around 3 am tommorrow :D

**Comment by nawnie** [comment]
got bored, here it is, its a previous version of the notebook but it still working 11/16 I believe I will update to latest tonight 

https://github.com/nawnie/fast-stable-diffusion/commit/1e6212bdc51581ea13a02620bf7ae56572198db3

Excuse typos they'll be fixed later.

**Comment by tsound97** [comment]
> 



> That's just a bunch of checkboxes making the colab unnecessarily complicated and long, they are not features, instead of laying out dozens of extensions in the colab, the webui has integrated an easy library for that.

Indeed, I just think there are a few things that are convenient, such as you can add argument directly to the options instead of the code. Maybe it's better for the new guys. 
By the way, I have recommended your notebook to all my friends in China, especially the fastdb, it works really well!
Really appreciate what you've done for this community.
![IMG_3520(20221105-215506)](https://user-images.githubusercontent.com/112967097/203456098-c13654d0-b9cd-4cce-beb6-cfc3480c9a56.JPG)
![IMG_3539](https://user-images.githubusercontent.com/112967097/203456101-6330714d-a62b-4fc8-bc94-f4da0c5dc12d.JPG)
![IMG_3600(20221113-173211)](https://user-images.githubusercontent.com/112967097/203456104-334dab3f-d294-4e69-9301-9f2be917b3ed.PNG)
![IMG_3605(20221113-173211)](https://user-images.githubusercontent.com/112967097/203456108-f2b9b98e-98fe-4dc1-b098-9d23f2b73974.PNG)

**Comment by TheLastBen** [comment]
> By the way, I have recommended your notebook to all my friends in China, especially the fastdb, it works really well!

Thank you, I appreciate it.
