### ISSUE TITLE
Can't get "Test the model in one click" to run with "With_Prior_Preservation" ckpt

### ISSUE THREAD

**Issue by samf1986** [TheLastBen/fast-stable-diffusion#59]
I was able to run this colab before, but when I tried "With_Prior_Preservation" training (43 instance images, 217 Optional class images) I generated a ckpt with "Start DreamBooth", but cannot seem to get it to run. 
Trying to run it from the drive location 
![image](https://user-images.githubusercontent.com/46737294/193583566-a5da2747-f356-41ca-b23e-db2e3ce26d6b.png)
I get the following error:
![image](https://user-images.githubusercontent.com/46737294/193583412-29db030c-dda2-47f4-9130-163bcc03ae5a.png)
Copying the ckpt into colab, I instead get:
![image](https://user-images.githubusercontent.com/46737294/193583699-1518b6be-5572-44d1-adf1-b1926a1da742.png)

What am I doing wrong? Note: I did put in the Huggingface token and have accepted the conditions.

**Comment by TheLastBen** [comment]
You can't test the CKPT in the dreambooth colab, if you want to test the ckpt, open the AUTOMATIC1111 colab and paste the path to the model in "download model" cell

**Comment by samf1986** [comment]
Thank you!

**Comment by TheLastBen** [comment]
happy, to help, I will add a simpler way to use the ckpt shortly
