### ISSUE TITLE
contains faces option re enable

### ISSUE THREAD

**Issue by maxixa** [TheLastBen/fast-stable-diffusion#593]
please re enable contains faces option for prior preservation 
it is good for faces on my trainings

**Comment by WisePanda007** [comment]
you can change code by youself
<img width="486" alt="image" src="https://user-images.githubusercontent.com/30204756/203467386-31556e9b-3643-4b6e-a2bd-bcbf94fdbef2.png">

**Comment by maxixa** [comment]
ok

**Comment by TheLastBen** [comment]
it doesn't improve faces, it reduces overfitting, but if you set the text_encoder at a low value, there won't be overfitting
