### ISSUE TITLE
[DreamBooth] Optional cell not optional

### ISSUE THREAD

**Issue by Pfaeff** [TheLastBen/fast-stable-diffusion#61]
It says to skip the cell if one doesn't want to upload class images, but skipping causes the "Start DreamBooth" cell to throw errors. 
Running the cell and then canceling the upload seems to work fine, though.

**Comment by TheLastBen** [comment]
fixed, update the colab and let me know if it's fine

**Comment by Pfaeff** [comment]
Seems to work now, thank you!

**Comment by TheLastBen** [comment]
Great !
