### ISSUE TITLE
After 12 successful CKPT file creations, NOW its not showing on GDRIVE

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#62]
I have made 12 successful conversions to CKPT FILES, but all of a sudden, at the end it says CKPT FILE ON GDRIVE, BUT it never shows, sometimes it takes a while, but now NEVER shows..... any hints ?
![adasda](https://user-images.githubusercontent.com/112510084/193612028-58fc9cdb-3a23-4da9-bafa-80497dd29849.PNG)

**Comment by TheLastBen** [comment]
Clique on the refresh button on top of the file explorer or simply navigate to your Gdrive with your browser to check the files

**Comment by LIQUIDMIND111** [comment]
yes sir, i have done that MANY times, and files are not showing now, i eve change the TOKENS from hugging face and DELETED MY BROWSER HISTORY etc.....  not sure what's happening, i have tried on 3 different emails accounts, and nothing is showing n ow..... so sad!!!!!

**Comment by 1blackbar** [comment]
it does work fine for me tho, no issues so far and it takes like minute or two to show up soemtimes

**Comment by TheLastBen** [comment]
I fixed it, now you can see the ckpt files in your drive without any issue

**Comment by LIQUIDMIND111** [comment]
> it does work fine for me tho, no issues so far and it takes like minute or two to show up soemtimes

yes i have done MANY, but NOW the last 2 hours, are not showing... thats rare if the code was not changed.

**Comment by LIQUIDMIND111** [comment]
im gonna do another one now

**Comment by TheLastBen** [comment]
@LIQUIDMIND111  wait a minute or two until the colab is refreshed, make sure you use the colab from the repo

**Comment by TheLastBen** [comment]
wait 5 mintes

**Comment by TheLastBen** [comment]
I meant if you have downloaded the colab in your gdrive, redownload it

**Comment by LIQUIDMIND111** [comment]
> I meant if you have downloaded the colab in your gdrive, redownload it

i have tried to find the folder but i don't see anything, seems the repo deletes everything except the MODELS, i have deleted many older folders to make sure i  have also plenty of space..... lets see what happens because last run also did not showed a file..... and did not received an error message...... either of memory issues or path issues...

**Comment by TheLastBen** [comment]
I fixed all the path issues in the colab, try and do a clean test run with only 10 steps to check

**Comment by LIQUIDMIND111** [comment]
> I fixed all the path issues in the colab, try and do a clean test run with only 10 steps to check

ok sir

**Comment by LIQUIDMIND111** [comment]
> I fixed all the path issues in the colab, try and do a clean test run with only 10 steps to check

i tried with 50 steps, and now it worked, let me try with 1000 steps, but i noticed, when it was NOT saving the file, i did not see this code that I DO SEE NOW: """

Reshaping encoder.mid.attn_1.q.weight for SD format
Reshaping encoder.mid.attn_1.k.weight for SD format
Reshaping encoder.mid.attn_1.v.weight for SD format
Reshaping encoder.mid.attn_1.proj_out.weight for SD format
Reshaping decoder.mid.attn_1.q.weight for SD format
Reshaping decoder.mid.attn_1.k.weight for SD format
Reshaping decoder.mid.attn_1.v.weight for SD format
Reshaping decoder.mid.attn_1.proj_out.weight for SD format

NOT SURE if it was running it or not, but NOW i see this code as this morning, then the files were saving correctly... FINALLY NOW IT WORKS., let me try with a full run of 1000

**Comment by LIQUIDMIND111** [comment]
> 

hello Sir, the model I just downloaded has issues, i noticed that ALL PAST MODELS are 4GB in size, but this LAST model is only 2GB even using the same amount of steps and input images as before.... 

PLUS, the result speaks for itself, ALL ARTWORKS come out in grayscale, NO EVEN adding COLOR PHOTO on the prompt, SEE ATTACHMENTS, the model came out with VERY NICE SHARPNESS but only black and white, even with ALL COLOR PHOTOS used as input... plese verify.....

![ewrewe](https://user-images.githubusercontent.com/112510084/193642427-6ef570e6-a4b3-461e-8347-f9ef563fceee.PNG)

**Comment by LIQUIDMIND111** [comment]
i am trying again now sir, another question, if I DO NOT CHOOSE this option "With the prior reservation method", how many subject photos MAX is allowed to upload,? Compared to THIS METHOD in which you ask for 200 photos

**Comment by TheLastBen** [comment]
the model (2GB) is in half precision which is what is used by the WEBUI anyway, the greyscale us strictly related to your class images

**Comment by LIQUIDMIND111** [comment]
> the model (2GB) is in half precision which is what is used by the WEBUI anyway, the greyscale is strictly related to your class images

but why all other models are 3.97GB and i just made them using the SAME codes as this 2GB one... i have been using your collab since 6am with the same codes, and dont get it why the model changed also if i did not chose half-precision on your collab? did you change the code? can i change it to full precision as before?

**Comment by TheLastBen** [comment]
the author of the conversion script added the option of half-precision.
even if you use the 3.97 model, the WEBUI will still use the half-precision, the results are exactly the same.

**Comment by LIQUIDMIND111** [comment]
> the author of the conversion script added the option of half-precision. even if you use the 3.97 model, the WEBUI will still use the half-precision, the results are exactly the same.

ok got you, so you are sure the model coming out in grayscale has nothing to so with the change of half precision?

**Comment by TheLastBen** [comment]
Yes

**Comment by LIQUIDMIND111** [comment]
> Yes

thanks sir.
