### ISSUE TITLE
No sapace left on colab VM

### ISSUE THREAD

**Issue by ANTONIOPSD** [TheLastBen/fast-stable-diffusion#623]
It happens when I save too many steps, there should be an option to delete old checkpoints from the colab disk once they are uploaded to gdrive otherwise the colab disk gets filled and the process fails.

This time happened at the end of the training because I set the backup checkpoints specifically to fill the disk and it failed at generating the tokenizer:

![imagen](https://user-images.githubusercontent.com/1978099/204025301-7f13f642-4a24-434a-8116-3d91f5866c33.png)

My gdrive has more than 60GB left

The final ckpt is created in gdrive and the tokenizer folder is empty

**Comment by TheLastBen** [comment]
well there is the last cell that will let you delete unused sessions from your gdrive but not specific ckpts.
as for the tokenizer, it's not a problem, even if it's not saved it will be pulled automatically from OpenAI's repo

**Comment by ANTONIOPSD** [comment]
mmm that last cell removes ckpts from gdrive but that's not the problem, because it's the colab virtual machine what is getting filled, I think it's /content/models what should be cleared after the ckpts are uploaded to gdrive

**Comment by ANTONIOPSD** [comment]
> well, there is the last cell that will let you delete unused sessions from your gdrive but not specific ckpts. as for the tokenizer, it's not a problem, even if it's not saved it will be pulled automatically from OpenAI's repo

mmm that's not the problem, that cell is for deleting models from gdrive, right?, the real problem is the colab virtual machine disk getting filled with models that are keeped even after they are uploaded to gdrive. I think  /content/models should be cleared after each step ckpt is uploaded to gdrive.

**Comment by TheLastBen** [comment]
intermediary checkpoints aren't saved in the colab storage, the tokenizer failed saving in gdrive, not VM storage

**Comment by ANTONIOPSD** [comment]
> intermediary checkpoints aren't saved in the colab storage, the tokenizer failed saving in gdrive, not VM storage

no, it failed because it thinks that there's no space because the main vm disk is full

**Comment by ANTONIOPSD** [comment]
![imagen](https://user-images.githubusercontent.com/1978099/204049204-a0aaae22-7e0e-4ed1-8a7c-dcfeb0549d93.png)

**Comment by TheLastBen** [comment]
I  must've forgotten, I didn't use that feature since a long time, I'll add a delete command right after dumping to gdrive

**Comment by TheLastBen** [comment]
fixed https://github.com/TheLastBen/diffusers/commit/c367152698f5374477b690dd0428ed3a047ff3d0, use the latest colab

**Comment by ANTONIOPSD** [comment]
> fixed [TheLastBen/diffusers@c367152](https://github.com/TheLastBen/diffusers/commit/c367152698f5374477b690dd0428ed3a047ff3d0), use the latest colab

thanks
