### ISSUE TITLE
Static path to model

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#63]
Can you please add a field to reference a model's path locally in GoogleDrive instead of re-downloading thru HuggingFace every time (such a time waste and network waste)? I have like 3 copies of the same model because everyone's colab requires theirs to be in a different folder. I have no understanding of how multiple models are loaded so maybe add multiple paths or just a whole folder to be read now that there's custom models, waifu & robo diffusion out there.

This applies to all colabs (e.g. I've used your fast Automatic webUI and Dreambooth colabs).

**Comment by TheLastBen** [comment]
the dreambooth colab exports the ckpt to the main gdrive folder, then you can use the path of that ckpt and input it in AUTOMATIC1111 colab cell "download model".

**Comment by TheLastBen** [comment]
yes, anything existing on your Gdrive won't be redownloaded
