### ISSUE TITLE
Way to train dreambooth with an existing model

### ISSUE THREAD

**Issue by ID4niis** [TheLastBen/fast-stable-diffusion#64]
Is there any way I can train a model with Dreambooth using a model that already exists? Like training a specific character with the yiffy model, wd, stuff like that.
I know there is like in other ways, but not in colab. And having that would definitely help with the results.
(sorry if this has already been answered btw, still new to these training stuff)

**Comment by TheLastBen** [comment]
You will need to convert the CKPT to diffusers to be able to train it with this version of Dreambooth

**Comment by ID4niis** [comment]
> You will need to convert the CKPT to diffusers to be able to train it with this version of Dreambooth

I see. I'll try to do that. Thanks.
