### ISSUE TITLE
Error under "Requirements" after update of Automatic Web UI

### ISSUE THREAD

**Issue by herbertwestern** [TheLastBen/fast-stable-diffusion#641]
I was using it earlier without issue, but had to log back in due to a timeout. Updated the Automatic Webui via the Colab, then got this when I ran "Requirements,"

  File "<ipython-input-5-e946482980a3>", line 39
    get_ipython().system('wget -O paths.py https://raw.githubusercontent.com/TheLastBen/fast-stable-diffusion/main/AUTOMATIC1111_files/paths.py')
    ^
IndentationError: unexpected indent

**Comment by TheLastBen** [comment]
fixed now use the link : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by herbertwestern** [comment]
Solved, thanks!
