### ISSUE TITLE
No output folder in gdrive

### ISSUE THREAD

**Issue by bitmanid** [TheLastBen/fast-stable-diffusion#643]
i'm using latest colab https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb and there is no output folder.

**Comment by eliasprompt** [comment]
same here

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/d39a5ab9d69727247a121b7c5a845c14adfdb6a0

**Comment by bitmanid** [comment]
@TheLastBen thanks!
