### ISSUE TITLE
AssertionError: Couldn't find Stable Diffusion (universal fork)

### ISSUE THREAD

**Issue by askiiart** [TheLastBen/fast-stable-diffusion#644]
I'm running SD 1.5 with a universal fork of this repo, but I keep getting this error:
```
AssertionError: Couldn't find Stable Diffusion in any of: ['/home/ben/big-stuff/ai-and-notebooks/stable-diffusion/testing']
```
`testing` is the folder the AUTOMATIC1111 notebook file is in.

**I've modified `paths.py`** to be:
```python
possible_sd_paths = [os.getcwd()]
```
os.getcwd() gets the directory the file in *running* in (not that it is *placed* in)

---

For reference, this is what the `testing` folder looks like:
![image](https://user-images.githubusercontent.com/90910526/204101693-6652de9d-d335-4faf-8015-39f6dd90de54.png)

Any suggestions on how to fix this?

**Comment by TheLastBen** [comment]
instead of `[os.getcwd()]` use the direct path to the "stable-diffusion" folder

**Comment by askiiart** [comment]
> instead of `[os.getcwd()]` use the direct path to the "stable-diffusion" folder (which is inside sd)

Thanks, that worked.

**Comment by askiiart** [comment]
BTW, @TheLastBen just a suggestion: Have a dev branch and a stable branch. It would probably cut down on the number of issues, and it's also kinda annoying constantly pulling fixes from you lol

Or you could have a section in the README showing verified working commits.

**Comment by TheLastBen** [comment]
When A1111 pushes a commit, sometimes I have to update the Colab accordingly otherwise it breaks, so it's a race against time, no time for a dev branch.

**Comment by CJohnDesign** [comment]
@TheLastBen I think A1111 pushed another commit - getting: 
`AssertionError: Couldn't find Stable Diffusion in any of: ['/content/gdrive/MyDrive/sd/stablediffusion', '.', '/content/gdrive/MyDrive/sd']`

**Comment by TheLastBen** [comment]
remove the folder sd and try again

**Comment by CJohnDesign** [comment]
I tried that. I could get it to work again but had to switch back to 1.5

**Comment by TheLastBen** [comment]
make sure you're using the latest colab
