### ISSUE TITLE
Error name 'NM' is not defined" when exporting to HF

### ISSUE THREAD

**Issue by Hugo-Dz** [TheLastBen/fast-stable-diffusion#647]
![CleanShot 2022-11-26 at 20 19 49@2x](https://user-images.githubusercontent.com/30731578/204105655-02df6647-70ab-4002-a895-9b67d116cb33.png)

**Comment by TheLastBen** [comment]
You need to run the testing cell first, even if for 1 second

**Comment by Hugo-Dz** [comment]
Thanks for your reply!! Btw, have you a good learning resource to deploy the model in production?

**Comment by TheLastBen** [comment]
I'm not exactly sure of what you mean by "deploy the model in production"

**Comment by Hugo-Dz** [comment]
Deploying like an inference API to let the model available on the web :)

Found a kind of doc on HF with a custom handler to create inference endpoints!

**Comment by Lukas1h** [comment]
> Deploying like an inference API to let the model available on the web :)
> 
> Found a kind of doc on HF with a custom handler to create inference endpoints!

[https://replicate.com/replicate/dreambooth](https://replicate.com/replicate/dreambooth) might be a better solution for what you're looking for.

**Comment by Hugo-Dz** [comment]
@Lukas1h Make sens yep!
