### ISSUE TITLE
unable to start Stable-Diffusion with V 2.0 (Automatic1111)

### ISSUE THREAD

**Issue by elBlacksmith** [TheLastBen/fast-stable-diffusion#652]
Hi, 

I have tried several times to start the normal Automatic1111 UI but I am getting this error in the last cell "Start stable-diffusion":

```
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Downloading: 100% 3.94G/3.94G [01:35<00:00, 41.4MB/s]
^C
```

I deleted the "sd" folder, I even checked the "update repo" flied on the Automatic1111 instalation cell, and I also check the V2 field on the "Start stable-diffusion". 
I did those steps on my main Colab account, and in a Collab backup account, and I got the same message.

**Comment by Raprogue** [comment]
Me too, my guess is not enough RAM to execute. If you look RAM goes up until it closes the aplication

**Comment by caoboyeehaw** [comment]
yup, having this same issue from the Automatic1111 update as well

**Comment by TheLastBen** [comment]
it requires (for now) more RAM than what free colab offers

**Comment by lolxdmainkaisemaanlu** [comment]
same issue here and now even 1.5 model is not working.

**Comment by TheLastBen** [comment]
> same issue here and now even 1.5 model is not working.

don't save the colab in your gdrive, always use the link : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by elBlacksmith** [comment]
Closed, as there is an oficial temporary fix
