### ISSUE TITLE
Keyword arguments {'requires_safety_checker': False} not recognized.

### ISSUE THREAD

**Issue by ANTONIOPSD** [TheLastBen/fast-stable-diffusion#656]
Tried on commit 8b5dd9cdb29e408d4312f02afa140dc56946d8d0

**Model**: V2-768px
**Contains_faces:** Female

![imagen](https://user-images.githubusercontent.com/1978099/204116195-380a181f-23f8-4d12-a673-91600f17b91d.png)

**Comment by TheLastBen** [comment]
It's just an info, not an issue

**Comment by ANTONIOPSD** [comment]
Oh, ok.
Another thing is that I get all brown images on Automatic's repo when using the generated model, probably Automatic needs to uodate something?

**Comment by TheLastBen** [comment]
I'm aware of that issue, the solution will come from the diffusers repo
