### ISSUE TITLE
The config attributes {'clip_sample': False} were passed to PNDMScheduler, but are not expected and will be ignored

### ISSUE THREAD

**Issue by SAC020** [TheLastBen/fast-stable-diffusion#661]
Hi,

Using the old method with captioned images as it seems to be working a lot better for training specific poses (not faces) vs the new one. 

Set text encoding at 30%, getting the message in the subject. It does not break the training, but I am afraid it is not stopping the text encoder and it eventually encodes to 100% and "overcooks" the trained model

Can you please check?

Thanks

```

Progress:|████████                 | 30% 4139/13800 [9:02:01<20:31:36,  7.65s/it, loss=0.0145, lr=1.43e-6] SAVING CHECKPOINT: /content/gdrive/MyDrive/cydohc_step_4140.ckpt
**The config attributes {'clip_sample': False} were passed to PNDMScheduler, but are not expected and will be ignored. Please verify your scheduler_config.json configuration file.**
Converting to CKPT ...
Done, resuming training ...
Progress:|███████████              | 45% 6185/13800 [13:24:19<16:09:55,  7.64s/it, loss=0.0151, lr=1.15e-6]
```

**Comment by TheLastBen** [comment]
Don't worry about that message, it's just an info, it doesn't break anything.

**Comment by SAC020** [comment]
Ok, thank you
