### ISSUE TITLE
cannot import name 'ui_tempdir' from 'modules' ERROR

### ISSUE THREAD

**Issue by tamal777** [TheLastBen/fast-stable-diffusion#666]
I'm, getting this error. how to fix?

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
ImportError: cannot import name 'ui_tempdir' from 'modules' (unknown location)

**Comment by TheLastBen** [comment]
Remove the folder sd from your drive and do a clean run

**Comment by nytromen** [comment]
> Remove the folder sd from your drive and do a clean run

I should do it every start?

**Comment by TheLastBen** [comment]
> I should do it every start?

Only when there is a major update like the V2

**Comment by Dreason8** [comment]
I'm getting this error now too, after a clean run.

**Comment by TheLastBen** [comment]
use the latest colab and a clean run

**Comment by tamal777** [comment]
> use the latest colab and a clean run

I'm already using the latest colab with fresh install after automatic 111 update. it was working but after few minus I have to restart SD and got this error.

**Comment by nytromen** [comment]
> > I should do it every start?
> 
> Only when there is a major update like the V2

Anyway we love your job. Good job. We understand that you are doing the best you can. That's why we are all so offended that the service does not work

**Comment by tamal777** [comment]
it's working now. I have reinstalled it.
