### ISSUE TITLE
no module named 'safetensors'

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [TheLastBen/fast-stable-diffusion#669]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 11, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 8, in <module>
    import safetensors.torch
ModuleNotFoundError: No module named 'safetensors'

Please help guys

**Comment by joanorsky** [comment]
Yep…  had that too…

**Comment by Katsu2098** [comment]
I am having this exact error as well from 2 hours ago.

**Comment by norfuer** [comment]
Same. So sad...

**Comment by TheLastBen** [comment]
fixed

**Comment by TheLastBen** [comment]
do this  : `!pip install safetensors`

**Comment by norfuer** [comment]
> do this : `!pip install safetensors`

Where do I type it?

**Comment by joanorsky** [comment]
> > do this : `!pip install safetensors`
> 
> Where do I type it?

On a new code form.. before the start of v2

**Comment by norfuer** [comment]
> > > do this : `!pip install safetensors`
> > 
> > 
> > Where do I type it?
> 
> On a new code form.. before the start of Stable Diffusion

Thanks!

**Comment by norfuer** [comment]
I've got this now... :(

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [61135deb] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/AniPlus/AniPlus.ckpt
Using VAE found similar to selected model: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/AniPlus/AniPlus.vae.pt
Loading VAE weights from: /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/AniPlus/AniPlus.vae.pt
Applying cross attention optimization (Doggettx).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings: 
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 212, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 159, in webui
    demo.queue(concurrency_count=111500)
NameError: name 'demo' is not defined

**Comment by RaymondDuke** [comment]
Had this problem, but it 's fixed now. 

Now the "Start stable-diffusion" completes but nothing happens. It doesn't spit out a link for a local server.

**Comment by RaymondDuke** [comment]
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
^C

New to collab. I noticed the RAM was getting higher and higher. Did it cap out?

**Comment by PatricioFernandezF** [comment]
Same here @RaymondDuke

**Comment by TheLastBen** [comment]
if you're using pro, do this : Runtime-> Change runtime type -> Runtime shape -> High-RAM

**Comment by RaymondDuke** [comment]
Thanks. I'm not using pro. I never had to before, but seems like it's now necessary?

**Comment by TheLastBen** [comment]
it is necessary only with the V2, set the GPU Class to standard to avoid wasting compute units

**Comment by lolxdmainkaisemaanlu** [comment]
this issue is now fixed by Ben... had to just install safe tensors lol

**Comment by patriciouca** [comment]
I have the same issue...
