### ISSUE TITLE
^C and termination on 'Start stable-diffusion' block

### ISSUE THREAD

**Issue by EntityinArray** [TheLastBen/fast-stable-diffusion#675]
I decided to try Stable-Diffusion V2, but when I run the last 'Start stable-diffusion' block, it loads something for a while and then prints '^C' and exits without error
![Screenshot from 2022-11-27 20-06-58](https://user-images.githubusercontent.com/18554021/204150035-3070ede7-7691-4773-988f-b3f239800f73.png)

I tried clearing the sd folder, placing 'Update repo' checkbox and 'Redownload_the_original_model' checkbox, but none of that helped

fast-stable-diffusion commit 185e67f
stable-diffusion-webui commit 9e78d2c
stablediffusion commit 47b6b60

**Comment by Klaushayan** [comment]
That's because V2 uses a lot of RAM and you are running out of RAM. I don't know if paid colab users also suffer from this since I'm on a free plan, but this is a RAM issue instead of VRAM, so they probably have the same issue.

**Comment by TheLastBen** [comment]
@Klaushayan pro colab has the "high-ram" feature when using standard gpu, and when using premium gpu, they won't face this issue at all

**Comment by EntityinArray** [comment]
Hmmm, I see, I use the free plan of colab. Thanks for help!

**Comment by EntityinArray** [comment]
Maybe somebody knows where one can try Stable-Diffusion V2 for free?

**Comment by Klaushayan** [comment]
@TheLastBen Yeah I just realized looking at other issues.
I wonder if it's the webui or the model itself being too big or something

**Comment by TheLastBen** [comment]
> @TheLastBen Yeah I just realized looking at other issues. I wonder if it's the webui or the model itself being too big or something

I'm working on a temporary fix, should be available soon

**Comment by jcplus** [comment]
Tested on my pro and it has no ^C issue but happens on my free colab

**Comment by TheLastBen** [comment]
@jcplus when using free, in the A1111 colab, check the box V_2_RAM_FIX
