### ISSUE TITLE
SD Colab not working

### ISSUE THREAD

**Issue by GuruVirus** [TheLastBen/fast-stable-diffusion#676]
I have deleted all my SD folders and started fresh. I use free colab so I can't run 2.0 models so I'm only interested in 1.5 features etc. Is there any way you can put the old colab version back that you don't need to update, and start a new one for 2.0 compatible? Merging them sounds unnecessarily complicated.

Final cell output:
![image](https://user-images.githubusercontent.com/4285187/204151850-79cad1a5-b8b8-445f-9bbe-f93e4b7b528a.png)

**Comment by TheLastBen** [comment]
you are using an outdated colab, safetensors dependency was added a few hours ago

**Comment by GuruVirus** [comment]
Refresh got me the new version.
Generated an error when running with update repo.
Deleted all again, disconnected runtime. Now working.
