### ISSUE TITLE
Conversion error on dreambooth colab

### ISSUE THREAD

**Issue by luci9t** [TheLastBen/fast-stable-diffusion#697]
I've been getting the conversion error "use a 4gb model insteadof a 7gb one". I am using a 4gb model and the same model worked fine till 4-5 days ago I think, any idea how to fix this? I am running the latest repo, and checked the compatibility mode option.

**Comment by StripedPuppy** [comment]
I think it might be an issue with the device you're assigned. Maybe it's not powerful enough to mount the model.

**Comment by luci9t** [comment]
> I think it might be an issue with the device you were assigned for the session. Maybe it's not powerful enough to mount the model.

I doubt that, this model I can run it on my 1650 laptop, it's slow but I can run it, I don't think Google has that low performance GPUs, besides as I said I had no problem running this same model a week ago. Could be wrong but it seems unlikely to me it's a hardware issue.

**Comment by TheLastBen** [comment]
IF you can share the model, send me the link so I can test it

**Comment by luci9t** [comment]
Sure, [here](https://drive.google.com/file/d/1e0tgjyeuxgNIZxV4g7U_onBJR1KHaF4n/view?usp=sharing)

**Comment by luci9t** [comment]
It also shows this: rm: cannot remove '/content/convert_original_stable_diffusion_to_diffusers.py': No such file or directory

**Comment by TheLastBen** [comment]
the error is caused by gdown argument -O which breaks the whole process, should work now, unless colab plays game with the RAM.

**Comment by TheLastBen** [comment]
that means not enough RAM, check if there is another version of the same model, I'm sure there is.

**Comment by luci9t** [comment]
Huh ok so it was actually a ram problem, ok thanks for your support, I'll look for other versions of the model or might just upgrade to colab pro ig.
