### ISSUE TITLE
Can't generate images anymore with automatic1111

### ISSUE THREAD

**Issue by Stoi84** [TheLastBen/fast-stable-diffusion#711]
As the title says. Everything was working just fine 12 hours ago and haven't changed anything since then but update the repo when starting the colab again. I'm using the 1.5 model (no v2) and some custom models. I restarted the colab multiple times, the repo is up to date, no luck fixing the issue.

What's happening is, when I generate an image and reach 100%, the image is never displayed. The generate button does nothing after this. However, I can still edit settings, change the model or the VAE, that'll be shown in the colab output. There's no error message at all.

If I look at the output on the colab, I can see it's generating 2 things from 0 to 100% despite me asking for a single image (not sure if it's normal or not).

I have to admit that I'm at loss now.

**Comment by TheLastBen** [comment]
check the box "use_gradio_server" and try again

**Comment by Stoi84** [comment]
Thanks, it helped.

While trying to solve the issue I noticed it would only happen when rendering larger images. 512x512 would not cause the issue, for example, but 896x1024 would.

Not sure if it's a temporary issue or not, but in any case, thanks for the help, it works just fine now using the gradio sever.
