### ISSUE TITLE
When use the AUTOMATIC1111-V2

### ISSUE THREAD

**Issue by clovelee** [TheLastBen/fast-stable-diffusion#712]
webui auto load model.cpkt, the output images are all bad. How to use the 768-v-ema.ckpt in webui?

**Comment by TheLastBen** [comment]
The V2 isn't a good model, that is just a fact

**Comment by tsound97** [comment]
You may try adding some negative prompt. https://www.reddit.com/r/StableDiffusion/comments/z6ao2j/please_use_negative_prompts_with_stable_diffusion/

> webui auto load model.cpkt, the output images are all bad. How to use the 768-v-ema.ckpt in webui?
