### ISSUE TITLE
Colab Issues AUTOMATIC1111

### ISSUE THREAD

**Issue by MrAshbury20** [TheLastBen/fast-stable-diffusion#714]
Xfomers not found, Dreambooth can't load up, eventhough I installed its extension, Inpaint gives error, some generation errors, results don't show up

**Comment by nytromen** [comment]
Results dont show up

**Comment by retropunk** [comment]
I ran the last cell "Start stable-diffusion" and this is the message, what am I suppose to do next? Thank you

No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
^C

**Comment by TheLastBen** [comment]
Check the box V2_RAM_FIX
