### ISSUE TITLE
Dreambooth Colab error loading images 

### ISSUE THREAD

**Issue by tuwonga** [TheLastBen/fast-stable-diffusion#717]
`AttributeError                            Traceback (most recent call last)
[<ipython-input-6-1458a7a7e267>](https://localhost:8080/#) in <module>
     73       identifier=filename.split(".")[0]
     74       new_path_with_file = os.path.join(INSTANCE_DIR, filename)
---> 75       file = Image.open(new_path_with_file)
     76       width, height = file.size
     77       if file.size !=(Crop_size, Crop_size):

4 frames
[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode)
   2852     return ImageQt.fromqpixmap(im)
   2853 
-> 2854 
   2855 _fromarray_typemap = {
   2856     # (shape, typestr) => mode, rawmode

[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in preinit()
    364     """
    365 
--> 366     global _initialized
    367     if _initialized >= 2:
    368         return 0

[/usr/local/lib/python3.7/dist-packages/PIL/JpegImagePlugin.py](https://localhost:8080/#) in <module>
     42 import warnings
     43 
---> 44 from . import Image, ImageFile, TiffImagePlugin
     45 from ._binary import i16be as i16
     46 from ._binary import i32be as i32

[/usr/local/lib/python3.7/dist-packages/PIL/TiffImagePlugin.py](https://localhost:8080/#) in <module>
    419 
    420 
--> 421 class ImageFileDirectory_v2(MutableMapping):
    422     """This class represents a TIFF tag directory.  To speed things up, we
    423     don't decode tags unless they're asked for.

[/usr/local/lib/python3.7/dist-packages/PIL/TiffImagePlugin.py](https://localhost:8080/#) in ImageFileDirectory_v2()
    696                 (TiffTags.FLOAT, "f", "float"),
    697                 (TiffTags.DOUBLE, "d", "double"),
--> 698                 (TiffTags.IFD, "L", "long"),
    699             ],
    700         )

AttributeError: module 'PIL.TiffTags' has no attribute 'IFD'`

**Comment by TheLastBen** [comment]
try this in a new cell `!pip install pillow==9.0` and restart the runtime

**Comment by tuwonga** [comment]
> try this in a new cell `!pip install pillow==9.0` and restart the runtime

I already did

**Comment by TheLastBen** [comment]
try the version 8.4

**Comment by tuwonga** [comment]
on kaggle the 9 is working. but the image loading is different, there's no loading but dataset path.
Ok, I will try with 8.4. Thank you !

**Comment by tuwonga** [comment]
it doesn't work, neither with 8.4

**Comment by TheLastBen** [comment]
do you restart the runtime after the installation ? (not disconnecting, only restart)

**Comment by tuwonga** [comment]
> do you restart the runtime after the installation ? (not disconnecting, only restart)

yes yes, I did .

**Comment by tuwonga** [comment]
ok, I did and finally it works but now I have a new issue ^_^

**Comment by TheLastBen** [comment]
what issue ?

**Comment by tuwonga** [comment]
I had a problem with the folder diffusers so I ran again the first cell for dependencies than I go to train again and finally now it's training ! ^___^
