### ISSUE TITLE
Invalid Syntax error while running automatic111 Web UI

### ISSUE THREAD

**Issue by ayushk58** [TheLastBen/fast-stable-diffusion#718]
The following error is being show, while running the WebUI collab.

File ["<ipython-input-7-f28451b310f1>"](https://localhost:8080/#), line 85
    if Model_Version = "V2-768":
                     ^
SyntaxError: invalid syntax

**Comment by KGUY1** [comment]
same

**Comment by konqiDAM** [comment]
I just open a PR to fix it
You have to change if `Model_Version = "V2-768"`: to if `Model_Version == "V2-768":`
and ` elif Model_Version = "V2-512":` to `elif Model_Version == "V2-512":`
or use https://colab.research.google.com/github/konqiDAM/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb that already has the fix

**Comment by TheLastBen** [comment]
fixed on the three notebooks

**Comment by KGUY1** [comment]
That fixed it thanks.

**Comment by ayushk58** [comment]
Fixed
