### ISSUE TITLE
Training from own ckpt?

### ISSUE THREAD

**Issue by xiaol** [TheLastBen/fast-stable-diffusion#72]
How can i trainning on ckpt file? based on finetune,  weight merge or dream booth checkpoint to continue training.

**Comment by TheLastBen** [comment]
This version of dreambooth trains diffusers models, you will need to convert your CKPT to diffusers, I think there are tutorials for that.

**Comment by xiaol** [comment]
thank you, firgure it out!

**Comment by jujpenabe** [comment]
Training from own ckpt preserve the custom instance names used in prompts? 
I'm not sure if merging checkpoints with AUTOMATIC preserve their own prompts.

**Comment by TheLastBen** [comment]
retraining a Dreambooth model can be tricky, try textual inversion for multiple trainings
