### ISSUE TITLE
The instance_prompt environment variable never gets set

### ISSUE THREAD

**Issue by ricky-sb** [TheLastBen/fast-stable-diffusion#724]
It appears as though the `$PT` variable never gets set, so the `--instance_prompt` flag is completely empty. 

https://github.com/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

```python
try:
  MODEL_NAME
  pass
except:
  MODEL_NAME=""
  
PT=""
```

I do see that the old version had some logic around setting the instance prompt and class prompt - although the new version doesn't have any such logic. Does this affect anything?

What prompt should I be using when I have a completed Dreambooth model?

**Comment by TheLastBen** [comment]
Inside the training script : the instance prompt = Input instance prompt+ image caption
Since Input instance prompt ="", that would leave the images filenames as the instance prompt/name
