### ISSUE TITLE
Sampling * Images can not exceeds 200 (roughly). Otherwise GUI lost response.

### ISSUE THREAD

**Issue by longlivebigcat** [TheLastBen/fast-stable-diffusion#728]
I have tried the dreambooth and automatic1111 released 14hours ago. Both of them worked for SD 1.5. However, what I have found is : sampling * Images can not exceeds 200 (roughly). Otherwise the automatic1111 GUI lost response. The back end calculation seemed to complete successfully, Show info like:Total progress100% 63/63 [01:01<00:00,  1.03it/s]. However, the images did not appear. Then I click any buttons on the GUI, none responded. 

I have to refresh the browser to reload. The GUI then work again.

I have tried it with 1,2,3,4 images (batch count* batch size), found it is strong linked to the sampling number. The upper limit seems to be around 200 (not exactly 200)

**Comment by longlivebigcat** [comment]
I have tried the latest model, the problem is still there.

P.S. I have been using dreambooth for two months. The problem appears after the release of SD2.0 related version

**Comment by TheLastBen** [comment]
that is probably an issue with the webui not the colab itself

**Comment by askiiart** [comment]
Please close this and open an issue on the [AUTOMATIC1111 repo](https://github.com/AUTOMATIC1111/stable-diffusion-webui)

**Comment by longlivebigcat** [comment]
OK
