### ISSUE TITLE
Couldn't using META's new inference engine increase Fast Stable's speed even more?

### ISSUE THREAD

**Issue by jvkap** [TheLastBen/fast-stable-diffusion#73]
https://github.com/facebookincubator/AITemplate/tree/main/examples/05_stable_diffusion

https://ai.facebook.com/blog/gpu-inference-engine-nvidia-amd-open-source/?utm_source=twitter&utm_medium=organic_social&utm_campaign=blog

**Comment by TheLastBen** [comment]
I was trying to get it to work, but I'm getting some errors about syntax, any feedback would be great

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/facebookincubator/AITemplate/issues/102
- https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1625
- https://github.com/ShivamShrirao/diffusers/issues/32

---

> AITemplate is for inference. I don't think it would provide any speedup during training.
> **EDIT:** nevermind. You can still accelerate the frozen parts of the model.
> 
> _Originally posted by @matteoserva in https://github.com/ShivamShrirao/diffusers/issues/32#issuecomment-1275067312_

> It is just for inference so won't be helpful in training. I also tested it, it's good for inference but also takes a really long time to compile.
> 
> _Originally posted by @ShivamShrirao in https://github.com/ShivamShrirao/diffusers/issues/32#issuecomment-1279625711_

**Comment by 0xdevalias** [comment]
> > It is just for inference so won't be helpful in training. I also tested it, it's good for inference but also takes a really long time to compile.
> 
> Just FYI - The compilation time with the latest open-source version has been improved a lot from our first release. In our experiences, it can be 4X faster for the models where computation-intensive ops are mostly GEMM-family ops. We've made similar improvement for Conv ops in our internal version, which will be sync-ed to the open-source repo later. Stay tuned. Thanks.
> 
> _Originally posted by @chenyang78 in https://github.com/facebookincubator/AITemplate/issues/102#issuecomment-1326014540_
