### ISSUE TITLE
Failed to load Dreambooth on Colab (A1111), Deforum too!!!

### ISSUE THREAD

**Issue by MrAshbury20** [TheLastBen/fast-stable-diffusion#745]
AssertionError: extension access disabed because of commandline flags

**Comment by cerarslan** [comment]
Use the local server to install extension sir! 

https://github.com/TheLastBen/fast-stable-diffusion/issues/725

**Comment by MrAshbury20** [comment]
> Use the local server to install extension sir!
> 
> #725

Thank You sir! but I encounter troubles while using the Local sever, I tried to install dreambooth and deforum extentions, deforum was installed, and I can see it on the panel above , however Dreambooth still can't find it , I appreciate if you could help me with that too, and thank you in advance

**Comment by MrAshbury20** [comment]
again found issue with Deforum: ModuleNotFoundError: No module named 'py3d_tools'

**Comment by cerarslan** [comment]
> again found issue with Deforum: ModuleNotFoundError: No module named 'py3d_tools'

👇 I believe we r same person rn sir. 🤭🤭

https://github.com/TheLastBen/fast-stable-diffusion/issues/745

**Comment by MrAshbury20** [comment]
waiting for the legendary TheLastBen to fix our mesery lol!

**Comment by TheLastBen** [comment]
I'll work on it soon

**Comment by CJohnDesign** [comment]
I'm still having these two problems. 

1. When I try and install Deforum via extensions tabs, I get: `AssertionError: extension access disabled because of command line flags`
2. When I upload the extensions folder, I get this when I generate: `ModuleNotFoundError: No module named 'py3d_tools'`

**Comment by TheLastBen** [comment]
you can't install it because you're using the gradio server

**Comment by CJohnDesign** [comment]
Yup, Just found it on another issue. Thanks! https://github.com/TheLastBen/fast-stable-diffusion/issues/685
