### ISSUE TITLE
Conversion error when resuming v2 training

### ISSUE THREAD

**Issue by dalmackay** [TheLastBen/fast-stable-diffusion#758]
If i skip the model download cell and put in a session link, it tries to load the model but gives size mismatch conversion error. If i put in a direct link or path to the trained ckpt in the model download cell, i get "conversion error, insufficient ram or corrupt". tried with and without compatibility mode

**Comment by TheLastBen** [comment]
There is no conversion script for the V2 right now, but I fixed the issue by saving the diffusers to the gdrive, from now on, using the latest colab, you will be able to resume trainings of the V2 model.
