### ISSUE TITLE
Missing font in hlky webui collab

### ISSUE THREAD

**Issue by TheOn3WhoKn0cks** [TheLastBen/fast-stable-diffusion#77]
When using the hlky webui, when I click "View Batch Progress", I get the error: No usable font found (tried arial.ttf, DejaVuSans.ttf). I never used it from the original repo so I don't know if the problem is from there.

**Comment by TheLastBen** [comment]
I'll check if they updated their dependencies list

**Comment by TheLastBen** [comment]
fixed 👍
