### ISSUE TITLE
auto1111 repo throwing gradio errors

### ISSUE THREAD

**Issue by ShinCoreSys** [TheLastBen/fast-stable-diffusion#770]
--------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-5-cb1fd0d4ffb7>](https://localhost:8080/#) in <module>
     60   srv= getoutput('cat /content/srvr.txt')
     61 
---> 62   for line in fileinput.input('/usr/local/lib/python3.7/dist-packages/gradio/blocks.py', inplace=True):
     63     if line.strip().startswith('self.server_name ='):
     64         line = f'            self.server_name = "{srv[8:]}"\n'

1 frames
[/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
    340                     pass
    341                 # The next few lines may raise OSError
--> 342                 os.rename(self._filename, self._backupfilename)
    343                 self._file = open(self._backupfilename, self._mode)
    344                 try:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py.bak'

this is on premium colab, running 2.0 settings

**Comment by sketchius** [comment]
Probably related to this issue, which he's working on now:
https://github.com/TheLastBen/fast-stable-diffusion/issues/769#issuecomment-1332732879
