### ISSUE TITLE
'time' is not defined.

### ISSUE THREAD

**Issue by fragloser** [TheLastBen/fast-stable-diffusion#780]
NameError                                 Traceback (most recent call last)

[<ipython-input-2-6e90308b5c49>](https://localhost:8080/#) in <module>
     10 get_ipython().system('mv Dependencies_AUT.3 Dependencies_AUT.7z.003  ')
     11 get_ipython().system('7z x Dependencies_AUT.7z.001')
---> 12 time.sleep(3)
     13 get_ipython().system('cp -r /content/usr/local/lib/python3.8/dist-packages /usr/local/lib/python3.8/')
     14 get_ipython().system('rm -r /content/usr')

NameError: name 'time' is not defined

**Comment by TheLastBen** [comment]
the colab will be ready in less than an hour, it's not stable at the moment

**Comment by fragloser** [comment]
Ty for the update!
