### ISSUE TITLE
Resuming V2 training cancels instantly

### ISSUE THREAD

**Issue by dalmackay** [TheLastBen/fast-stable-diffusion#784]
Loaded a previous session, checked resume training, pushed start... training instantly ends (doesnt train) and ckpt/diffusers saves to gdrive. tried with different step counts. shows no errors afterwards

**Comment by articulite** [comment]
I think it's because the dependencies are 404ing rn. They were deleted from the repo.

**Comment by articulite** [comment]
I wonder if we should just be using fallback runtimes to avoid all this bugness for now.

**Comment by TheLastBen** [comment]
it's fixed now
