### ISSUE TITLE
Webui link does not appear (^C)

### ISSUE THREAD

**Issue by KuzeyVural** [TheLastBen/fast-stable-diffusion#794]
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [6569e224] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/kuvuvu.ckpt
^C

It looks like this and I have tried with other models too, haven't given any links.

**Comment by cerarslan** [comment]
I have same issue and looking around I saw legendary ben says google colab upgrading v3.8 python sir..

**Comment by redsparrowgit** [comment]
What about upgrading it ? Is it impossible to use in the previous version ?

**Comment by alelordelo** [comment]
@cerarslan and @redsparrowgit so not possible to test it for now?

**Comment by cerarslan** [comment]
Low ram modification doesn't work for now.

**Comment by CJohnDesign** [comment]
I'm having the same problem. Looks like we wait...

**Comment by acjbizar** [comment]
Setting Runtime shape to High-RAM in Notebook settings fixed this for me.

**Comment by acjbizar** [comment]
> Did you do anything else?

No, that did the trick for me. *However*, since then a new issue has arisen and the fix for **that** problem is to check `Use_Gradio_Server`. This space moves fast, and so you might be looking at a different problem than before. :)

**Comment by alelordelo** [comment]
> > Did you do anything else?
> 
> No, that did the trick for me. _However_, since then a new issue has arisen and the fix for **that** problem is to check `Use_Gradio_Server`. This space moves fast, and so you might be looking at a different problem than before. :)

thanks! I tried again and now somehow worked!
