### ISSUE TITLE
"ModuleNotFoundError: No module named 'fastapi'"

### ISSUE THREAD

**Issue by hbenthow** [TheLastBen/fast-stable-diffusion#805]
Starting last night, whenever I try to run your Colab version of Automatic1111, I get the following error:

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
```

I tried deleting all of the files from my Google Drive and trying again, but it doesn't help.

**Comment by dravid-cmyk** [comment]
Even gradio server is very slow now

**Comment by adiellarac** [comment]
I too am experiencing this problem. I get the same error message.

**Comment by TheLastBen** [comment]
are you using the latest colab ?

**Comment by hbenthow** [comment]
> are you using the latest colab ?

Yes.

**Comment by TheLastBen** [comment]
run this in a new cell : `!pip install -U fastapi`

**Comment by hbenthow** [comment]
It gave me the message:

`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: fastapi in /usr/local/lib/python3.8/dist-packages (0.88.0)
Requirement already satisfied: starlette==0.22.0 in /usr/local/lib/python3.8/dist-packages (from fastapi) (0.22.0)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /usr/local/lib/python3.8/dist-packages (from fastapi) (1.10.2)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.8/dist-packages (from starlette==0.22.0->fastapi) (3.6.2)
Requirement already satisfied: typing-extensions>=3.10.0 in /usr/local/lib/python3.8/dist-packages (from starlette==0.22.0->fastapi) (4.1.1)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.8/dist-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi) (1.3.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.8/dist-packages (from anyio<5,>=3.4.0->starlette==0.22.0->fastapi) (2.10)`

Then, when I ran the "Start stable-diffusion" cell, it worked this time.

**Comment by TheLastBen** [comment]
fastapi should be installed by default, I don't know what caused it to break

**Comment by adiellarac** [comment]
> are you using the latest colab ?

I have switched to the latest version of the colab and have deleted the SD folder created on my GDrive. Now it works, thanks.

Although sometimes the images don't generate, and the generate images button stops working until I close it and reopen it. This happens a lot when I increase the size of the images, activate the resize fix and increase the number of steps. And I don't remember this happening before.

**Comment by TheLastBen** [comment]
I'm aware of the freezing issue and I'm working on it.

**Comment by hbenthow** [comment]
> I'm aware of the freezing issue and I'm working on it.

I just ran into a new problem. I tried using LDSR upscaling in the Extras tab, and it didn't work. The Colab page gave this error:

`100% 1.86k/1.86k [00:00<00:00, 612kB/s]
Loading model from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/LDSR/model.ckpt
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 113.62 M params.
Keeping EMAs of 308.
Error completing request
Arguments: (0, 1, <PIL.Image.Image image mode=RGB size=1024x1024 at 0x7FF334372400>, None, '', '', True, 0, 0, 0, 4, 4267, 4267, False, 3, 0, 1, False) {}
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 189, in run_extras
    image, info = op(image, info)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 150, in run_upscalers_blend
    res = upscale(image, *upscale_args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/extras.py", line 118, in upscale
    res = upscaler.scaler.upscale(image, resize, upscaler.data_path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/upscaler.py", line 64, in upscale
    img = self.do_upscale(img, selected_model)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ldsr_model.py", line 54, in do_upscale
    return ldsr.super_resolution(img, ddim_steps, self.scale)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ldsr_model_arch.py", line 87, in super_resolution
    model = self.load_model_from_config(half_attention)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ldsr_model_arch.py", line 25, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 562, in __init__
    self.instantiate_first_stage(first_stage_config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/models/diffusion/ddpm.py", line 614, in instantiate_first_stage
    model = instantiate_from_config(config)
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/content/gdrive/MyDrive/sd/stablediffusion/ldm/util.py", line 87, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
AttributeError: module 'ldm.models.autoencoder' has no attribute 'VQModelInterface'`

**Comment by TheLastBen** [comment]
`module 'ldm.models.autoencoder' has no attribute 'VQModelInterface'`
This means the LDSR upscaling script isn't compatible with the sd v2 repo

**Comment by hbenthow** [comment]
> `module 'ldm.models.autoencoder' has no attribute 'VQModelInterface'` This means the current LDSR upscaling script isn't compatible with the sd v2 repo

But I'm using the 1.5 model.

**Comment by TheLastBen** [comment]
Yes but the SD repo is the new stability one, not the old one from Compvis

**Comment by hbenthow** [comment]
Is there a way to fix that?
    On Saturday, December 3, 2022 at 01:44:50 AM CST, Ben ***@***.***> wrote:  
 
 


Yes but the SD repo is the new stability one, not the old one from Compvis

**Comment by hbenthow** [comment]
> Yes but the SD repo is the new stability one, not the old one from Compvis

Is there a way to fix that?

**Comment by TheLastBen** [comment]
Check with the A1111 team, I'm sure they will find a fix

**Comment by MarcKast** [comment]
Hello. Same problem.

Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'


pasted into a new cell: !pip install -U fastapi

but another message came out:


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: fastapi in /usr/local/lib/python3.9/dist-packages (0.93.0)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in /usr/local/lib/python3.9/dist-packages (from fastapi) (1.10.5)
Requirement already satisfied: starlette<0.26.0,>=0.25.0 in /usr/local/lib/python3.9/dist-packages (from fastapi) (0.25.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.9/dist-packages (from pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2->fastapi) (4.5.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /usr/local/lib/python3.9/dist-packages (from starlette<0.26.0,>=0.25.0->fastapi) (3.6.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.9/dist-packages (from anyio<5,>=3.4.0->starlette<0.26.0,>=0.25.0->fastapi) (2.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.9/dist-packages (from anyio<5,>=3.4.0->starlette<0.26.0,>=0.25.0->fastapi) (1.3.0)
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/shared.py", line 9, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

![2023-03-09_03-04-56](https://user-images.githubusercontent.com/127359756/223881051-278deccd-2452-496e-ace7-576ec7af8814.png)


what to do?

**Comment by DobrySkazochnik** [comment]
> what to do?
create two code blocks after "Requirements"
1st: 
`%%writefile requirements.txt
blendmodes
accelerate
basicsr
fonts
font-roboto
gfpgan
gradio==3.16.2
invisible-watermark
numpy
omegaconf
opencv-contrib-python
requests
piexif
Pillow
pytorch_lightning==1.7.7
realesrgan
scikit-image>=0.19
timm==0.4.12
transformers==4.25.1
torch
einops
jsonmerge
clean-fid
resize-right
torchdiffeq
kornia
lark
inflection
GitPython
torchsde
safetensors
psutil
albumentations==0.4.3
opencv-python
pudb==2019.2
imageio==2.9.0
omegaconf==2.1.1
test-tube>=0.7.5
webdataset==0.2.5
open-clip-torch==2.7.0
kornia==0.6
invisible-watermark>=0.1.5
streamlit-drawable-canvas==0.8.0
xformers
fastapi`
2nd:
`!pip install -r requirements.txt
!pip install git+https://github.com/openai/CLIP.git
!pip install --upgrade fastapi==0.90.1`

![2023-03-09_06-10-51](https://user-images.githubusercontent.com/32751843/223907440-eae0ace2-05ad-4d55-9868-972607025490.png)

**Comment by Maximus71ru** [comment]
Hello, when trying to run AUTOMATIC 1111.ipynb, at the last stage, loading Star Stable-Diffusion I get an error:
"
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 7, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'"

In my case, what can be done to correct the error?

**Comment by Maximus71ru** [comment]
I have now received a notification that I have exhausted my limit in the Collab.

**Comment by ZhuominLi** [comment]
> > what to do?
> > create two code blocks after "Requirements"
> > 1st:
> > `%%writefile requirements.txt blendmodes accelerate basicsr fonts font-roboto gfpgan gradio==3.16.2 invisible-watermark numpy omegaconf opencv-contrib-python requests piexif Pillow pytorch_lightning==1.7.7 realesrgan scikit-image>=0.19 timm==0.4.12 transformers==4.25.1 torch einops jsonmerge clean-fid resize-right torchdiffeq kornia lark inflection GitPython torchsde safetensors psutil albumentations==0.4.3 opencv-python pudb==2019.2 imageio==2.9.0 omegaconf==2.1.1 test-tube>=0.7.5 webdataset==0.2.5 open-clip-torch==2.7.0 kornia==0.6 invisible-watermark>=0.1.5 streamlit-drawable-canvas==0.8.0 xformers fastapi`
> > 2nd:
> > `!pip install -r requirements.txt !pip install git+https://github.com/openai/CLIP.git !pip install --upgrade fastapi==0.90.1`
> 
> ![2023-03-09_06-10-51](https://user-images.githubusercontent.com/32751843/223907440-eae0ace2-05ad-4d55-9868-972607025490.png)

It works!!!!
