### ISSUE TITLE
[FAST-DreamBooth] Error sending image

### ISSUE THREAD

**Issue by GabrielMirandaOliveira** [TheLastBen/fast-stable-diffusion#807]
error sending image in google colab - error both in the folder and directly from the computer

![image](https://user-images.githubusercontent.com/30904933/205177998-e9b13869-23b2-40fe-8e0e-dc8910044933.png)

**Comment by voidxd** [comment]
It works for me if I uncheck `Crop_images`, and I crop them myself.

**Comment by GabrielMirandaOliveira** [comment]
I will try right now

**Comment by GabrielMirandaOliveira** [comment]
> Funciona para mim se eu desmarcar `Crop_images`, e eu mesmo os corto.


it worked, thank you, you are top
