### ISSUE TITLE
[Dreambooth] Resumed generation stops halfway through as completed

### ISSUE THREAD

**Issue by younyokel** [TheLastBen/fast-stable-diffusion#808]
I don't know if it's related to latest updates to the colab but for the last day I can't resume training my model. I train it for 12,000 steps and it always took me three and a half hours, but now it's always exactly one hour when it ends, and the progress bar doesn't even reach half of it (I can't say for sure, I haven't watched it).

**Comment by TheLastBen** [comment]
do a screenshot

**Comment by younyokel** [comment]
Seems to be fixed now.
