### ISSUE TITLE
Is V2 ready to be used?

### ISSUE THREAD

**Issue by TejasQ** [TheLastBen/fast-stable-diffusion#813]
Hi, I'm a YouTuber who highlights great work like this and I've been using it and _loving it_! Thank you for your great work! I'd like to use V2 but I saw [here](https://github.com/TheLastBen/fast-stable-diffusion/issues/633#issuecomment-1328266285) that it doesn't work/isn't ready yet.

Where can I follow progress on this?

**Comment by TheLastBen** [comment]
Hi and thanks, the V2 does work, it only requires a bit more RAM, so if you have colab pro subscription, you can use it without an issue.

Runtime-> Change runtime type -> Runtime shape -> High-RAM
keep the GPU to standard to not waste compute units

**Comment by TejasQ** [comment]
Thanks a lot!
