### ISSUE TITLE
Dreambooth V2 768 size mismatch at Create/Load a Session

### ISSUE THREAD

**Issue by ANTONIOPSD** [TheLastBen/fast-stable-diffusion#814]
It happens when I try to resume training using a previous model, I even tried to use the yaml file, but I get the same error, there should be a code to detect the model version and auto download the matching yaml from the official repo so we don't have to have 37 million yaml files.

![imagen](https://user-images.githubusercontent.com/1978099/205217714-19db5ed3-9b70-420a-a7ba-0f12241f399f.png)

Using 9ae2bd02e81ed4425f73f1ca5146fc07a50fc45a

**Comment by TheLastBen** [comment]
You trained this model before the recent update where the model is also saved in diffusers format in your gdrive. Because the conversion script doesn't work for V2

**Comment by ANTONIOPSD** [comment]
I trained a V2 model from scracth like 5 hours ago then I tried to resume the training using the generated checkpoint from that training. Everything V2.

**Comment by TheLastBen** [comment]
Can you check the session folder if there is a folder inside that contains the diffusers model ?

**Comment by ANTONIOPSD** [comment]
Nop, only the instance_images and the CKPTs.
Training was stopped, so I selected the latest step_xxxx.ckpt

**Comment by TheLastBen** [comment]
that's why, it only saves the diffusers when the training is done

**Comment by TheLastBen** [comment]
I could make it saves the diffusers model intermediately, but that would consume so much space, I'll look into it

**Comment by ANTONIOPSD** [comment]
That would be nice, because you never know when google is going to disconnect the session when using the free version and many times it will produce an unfinished model.

**Comment by TheLastBen** [comment]
I'll add it

**Comment by ANTONIOPSD** [comment]
thanks
