### ISSUE TITLE
Fine-tuned V2-768 model no longer recognizes tokens

### ISSUE THREAD

**Issue by samf1986** [TheLastBen/fast-stable-diffusion#838]
I successfully trained a V2-768 model with good results on 11/29. Yesterday I tried training with an expanded dataset and the resulting ckpt does not recognize the token at all. Has the training method changed?

The changes I made to the training were: 
1) Increasing the dataset from 16 images and 16 * 200 steps to 37 images and 37 * 200 steps.
2) Increasing text encoder training from 50% to 100%
3) Disabling face training, and
4) Changing the naming convention from "token (n).png" to "token, space separated multi word string, word (n).png"--that is, including captions with spaces separating words in strings and commas separating strings.

**Comment by TheLastBen** [comment]
The V2 behaves in a weird way, also the ckpt conversion script isn't working, but someone has just published a working conversion script, I'll add it in s few hours.
