### ISSUE TITLE
InPaint broken (ui.py, line 800)

### ISSUE THREAD

**Issue by ClemensLode** [TheLastBen/fast-stable-diffusion#847]
When running InPaint with the default setting "Inpaint masked", I get the following error:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 273, in run_predict
    output = await app.blocks.process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 742, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 653, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 800, in update_orig
    same_size = state is not None and state.size == image.size
AttributeError: 'dict' object has no attribute 'size'

**Comment by ClemensLode** [comment]
A picture is generated, but it's independent of the given image, meaning the mask is ignored.

**Comment by dravid-cmyk** [comment]
@TheLastBen same issue

**Comment by TheLastBen** [comment]
I'm aware of it

**Comment by ThanapatSornsrivichai** [comment]
Same. when will this become stable? It seems to break every minor update or something.

**Comment by ThanapatSornsrivichai** [comment]
The picture also duplicate to the left. Don't know if it's related.
![image](https://user-images.githubusercontent.com/36567807/205450498-29f4c6e4-0b3a-4749-8f7b-717e5b4b52a8.png)

**Comment by TheLastBen** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5360

**Comment by dravid-cmyk** [comment]
> [AUTOMATIC1111/stable-diffusion-webui#5360](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5360) it's not the colab

have you fixed the collab?

**Comment by dravid-cmyk** [comment]
@TheLastBen

**Comment by TheLastBen** [comment]
this issue is to be fixed by A1111 team, I don't maintain that repo

**Comment by dravid-cmyk** [comment]
> this issue is to be fixed by A1111 team, I don't maintain that repo

but some user said they fixed by  git checkout a2feaa95fc0c4c94131eb75b5b1bc0eaa1696551 .\modules\img2img.py .\modules\ui.py this where to copy this??

**Comment by inck86** [comment]
> > this issue is to be fixed by A1111 team, I don't maintain that repo
> 
> but some user said they fixed by git checkout a2feaa95fc0c4c94131eb75b5b1bc0eaa1696551 .\modules\img2img.py .\modules\ui.py this where to copy this??

join the question. how to implement this please tell me

**Comment by ClemensLode** [comment]
The issue is fixed with https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/8504db51704d238cc7616f6bf59eb049d3eb101d
