### ISSUE TITLE
NameError: name 'V2' is not defined ( while unsing the 1.5 model)

### ISSUE THREAD

**Issue by metzo007** [TheLastBen/fast-stable-diffusion#851]
Hi, I get this error in ther training part. I do not use the v2 model

[<ipython-input-6-d2b747e8a89d>](https://localhost:8080/#) in <module>
    170   unet_train(SESSION_DIR, stpsv, stp, MODELT_NAME, INSTANCE_DIR, OUTPUT_DIR, PT, Seed, Res, precision, GC, Training_Steps)
    171 
--> 172 elif V2 and Resolution!="512" and not("A100" in s):
    173     if Enable_text_encoder_training :
    174       train_only_textenc(MODELT_NAME, INSTANCE_DIR, OUTPUT_DIR, PT, Seed, Res, precision, Training_Steps=stptxt)

NameError: name 'V2' is not defined

Best, Metzo

**Comment by TheLastBen** [comment]
https://github.com/TheLastBen/fast-stable-diffusion/commit/a009fc75e22c7800a4574028f2c1426dbfe4df49
if you don't want to refresh the colab, just add this commit manually

**Comment by metzo007** [comment]
I always run the latest version :-). Is the problem fixed?

**Comment by TheLastBen** [comment]
yes

**Comment by metzo007** [comment]
works now :-) . Thanks again

**Comment by emmajane1313** [comment]
just ran the latest version and am getting the same error

**Comment by TheLastBen** [comment]
https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb
