### ISSUE TITLE
FileNotFoundError - No such file or directory: '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py

### ISSUE THREAD

**Issue by metzo007** [TheLastBen/fast-stable-diffusion#854]
Hi, I get this error starting stable-diffusion

FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-14-55b102f3c5f0>](https://localhost:8080/#) in <module>
     44 if Use_Gradio_Server:
     45   share='--share'
---> 46   for line in fileinput.input('/usr/local/lib/python3.7/dist-packages/gradio/blocks.py', inplace=True):
     47     if line.strip().startswith('self.server_name ='):
     48         line = '            self.server_name = server_name\n'

1 frames
[/usr/lib/python3.8/fileinput.py](https://localhost:8080/#) in _readline(self)
    340                     pass
    341                 # The next few lines may raise OSError
--> 342                 os.rename(self._filename, self._backupfilename)
    343                 self._file = open(self._backupfilename, self._mode)
    344                 try:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py' -> '/usr/local/lib/python3.7/dist-packages/gradio/blocks.py.bak'

**Comment by TheLastBen** [comment]
remove the folder sd and do a clean run with the latest colab

**Comment by dravid-cmyk** [comment]
> remove the folder sd and do a clean run with the latest colab

can you pleasee tell how to fix inpaint issue on collab iam kinda new

**Comment by metzo007** [comment]
I did this but get the same error. I try again

**Comment by metzo007** [comment]
works again. thanks for you help :-)
