### ISSUE TITLE
NameError: name 'V2' is not defined

### ISSUE THREAD

**Issue by Ai-Artsca** [TheLastBen/fast-stable-diffusion#857]
NameError                                 Traceback (most recent call last)
[<ipython-input-6-10f074cfc136>](https://localhost:8080/#) in <module>
    183   prc="--fp16" if precision=="fp16" else ""
    184   get_ipython().run_line_magic('cd', '/content')
--> 185   if V2:
    186     get_ipython().system('wget -O convertosdv2.py https://github.com/TheLastBen/fast-stable-diffusion/raw/main/Dreambooth/convertosdv2.py')
    187     clear_output()

NameError: name 'V2' is not defined

**Comment by TheLastBen** [comment]
fixed in the latest commit
