### ISSUE TITLE
Previous version of this notebook

### ISSUE THREAD

**Issue by ivanislart** [TheLastBen/fast-stable-diffusion#86]
Hi, first of all thank you for your work. I was trying your Google Colab notebook and it worked perfectly. But since you updated it a few days ago, it doesn't work anymore. Could I have the previous version of this notebook? Thank you!

**Comment by ivanislart** [comment]
Yes, but it doesn't work for me. It worked until 2 October

**Comment by TheLastBen** [comment]
What notebook are you using exactly and what kind of error ?

**Comment by ivanislart** [comment]
I am using this https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

The error is in the "Start Dreambooth" cell. 
The error is as follows: 

The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Generating class images:   6% 3/50 [01:41<26:14, 33.51s/it]

**Comment by TheLastBen** [comment]
There is no error here, the script is running, those above are just harmless warnings

**Comment by ivanislart** [comment]
oh ok, you're right and I'm such an idiot. Thank you so much for your time and help, and sorry for wasting your time.

**Comment by ivanislart** [comment]
Wow! Now the interface is amazing, thanks so much you are the best!

**Comment by TheLastBen** [comment]
happy to help
