### ISSUE TITLE
When resuming training, text encoder is always re-trained from scratch...

### ISSUE THREAD

**Issue by jfjensen** [TheLastBen/fast-stable-diffusion#867]
Everytime I want to resume training my UNet model from a given checkpoint, the text encoder is always retrained from scratch.
Is it possible to save a trained text encoder and then re-use it when resuming the training of the UNet?

**Comment by TheLastBen** [comment]
you simply un check the box "Enable_text_encoder_training" and it will train only the UNet

**Comment by jfjensen** [comment]
ok... but will it re-use the existing text encodings then?

**Comment by TheLastBen** [comment]
Yes if you check the box "resume training" it will use the existing (trained) text encoder

**Comment by jfjensen** [comment]
ok thank you very much for the clarification!!
