### ISSUE TITLE
Updated accelerate package seems to break Dreambooth launch

### ISSUE THREAD

**Issue by algestam** [TheLastBen/fast-stable-diffusion#87]
Accelerate 0.13.0 was just released and it seems to break the dreambooth launch step.

Workaround: change the setup step from:

    %pip install accelerate

to:

    %pip install accelerate==0.12.0

**Comment by TheLastBen** [comment]
Thanks I'll fix it

**Comment by algestam** [comment]
Thanks, great 👍
