### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by wackywacko4** [TheLastBen/fast-stable-diffusion#875]
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 14, in <module>
    from modules import shared, devices, sd_samplers, upscaler, extensions, localization, ui_tempdir
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_samplers.py", line 12, in <module>
    from modules import prompt_parser, devices, processing, images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/processing.py", line 15, in <module>
    import modules.sd_hijack
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack.py", line 10, in <module>
    import modules.textual_inversion.textual_inversion
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/textual_inversion/textual_inversion.py", line 13, in <module>
    from modules import shared, devices, sd_hijack, processing, sd_models, images, sd_samplers
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_models.py", line 15, in <module>
    from modules.sd_hijack_inpainting import do_inpainting_hijack, should_hijack_inpainting
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/sd_hijack_inpainting.py", line 6, in <module>
    import ldm.models.diffusion.ddpm
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/diffusion/ddpm.py", line 24, in <module>
    from ldm.models.autoencoder import VQModelInterface, IdentityFirstStage, AutoencoderKL
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/models/autoencoder.py", line 8, in <module>
    from ldm.modules.diffusionmodules.model import Encoder, Decoder
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/diffusionmodules/model.py", line 9, in <module>
    from ldm.modules.attention import LinearAttention
ImportError: cannot import name 'LinearAttention' from 'ldm.modules.attention' (/content/gdrive/MyDrive/sd/stable-diffusion-webui/ldm/modules/attention.py)

**Comment by TheLastBen** [comment]
remove the folder sd from your gdrive and do a clean run with the latest colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by wackywacko4** [comment]
> remove the folder sd from your gdrive and do a clean run with the latest colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

It worked, thank you! But now I am having issues connecting to a local server and have to use the gradio server option, which does not seem to work as well. Is that an issue with the colab, or on googles end, and do you have any advice? Thank you for your time and quick response!!

**Comment by akilmaf** [comment]
I also had the same problem and removing SD folder just worked well. Gradio server option works well. The default method does not work and the local webpage does not load

**Comment by wackywacko4** [comment]
> I also had the same problem and removing SD folder just worked well. Gradio server option works well. The default method does not work and the local webpage does not load
> 
> Edit: Gradio server "looks" normal but does not produce images. Or produces only once and the rest is not visible. You click on the generate button and nothing appears after it is completed.
> 
> Edit 2: Although the gradio server seems like it is not producing anything, you can still find the generated results on your G drive in recent files. So it is about the interface only and it is working in the background it seems.

I have noticed exactly the same. It is still working and generating, but the interface does not seem to be updating correctly when using the gradio server, which is exactly why I was hoping there was a decent quick fix to not have to use it. But at least it still generates

**Comment by akilmaf** [comment]
Can you try using it in a private tab or clean the cookies?

**Comment by akilmaf** [comment]
> remove the folder sd from your gdrive and do a clean run with the latest colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

Now it totally stopped generating images. It doesn't even start loading after clicking on the generate button.

Am I missing something here?
