### ISSUE TITLE
python3: can't open file '/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py': [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by Plecko** [TheLastBen/fast-stable-diffusion#889]
Getting this error on the final cell. Can't seem to generate a link.

python3: can't open file '/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py': [Errno 107] Transport endpoint is not connected

Used to work fine. So I tried deleting the SD folder, but after disconnecting and running all cells again it seems that it hasn't redownloaded an SD folder to my drive...

**Comment by TheLastBen** [comment]
disconnect from the runtime and start over

**Comment by Plecko** [comment]
I tried that but it didn't help.

I've tried doing that a few times now and I still seem to be missing the SD folder that I deleted.

Stumped!

**Comment by TheLastBen** [comment]
when you connect your gdrive in colab, run the "Install AUTOMATIC1111 repo" cell

**Comment by Plecko** [comment]
God I hate colab sometimes...

I did that at least five times. I closed the page, reopened the notebook, tried again and it worked!

Thanks for your help mate!
