### ISSUE TITLE
Render progress and step preview is broken

### ISSUE THREAD

**Issue by xone4** [TheLastBen/fast-stable-diffusion#89]
Render progress stck at 0% i tested it in txt2img plus the step preview doesn't show any images but after completion the grid show normally

**Comment by TheLastBen** [comment]
it is the result of fixing the freezing when generating a big batch or high res images, I'll see if I can bring back the progress visualization.

**Comment by xone4** [comment]
and the interrupt button is stuck too
sorry

**Comment by TheLastBen** [comment]
Update your colab, I implemented a temporary fix

**Comment by xone4** [comment]
thank you very much for your hard work

**Comment by TheLastBen** [comment]
fixed
