### ISSUE TITLE
CONVERTING CKPT FILES KILLED? WTH?

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#894]
Bro, what a waste of time..... why i
![Screenshot 2022-12-06 062831](https://user-images.githubusercontent.com/112510084/205887124-76c4506d-edcd-4263-b86b-1c81c190507d.jpg)
s this happening????

**Comment by LIQUIDMIND111** [comment]
> not enough RAM, it happens with the V2

lol, so what does  it means? i cannot get a file until it reaches the final step?

**Comment by LIQUIDMIND111** [comment]
> not enough RAM, it happens with the V2


rare, it also happened yesterday making a 1.5 model, but at 768x768 
![Screenshot 2022-12-06 063629](https://user-images.githubusercontent.com/112510084/205888592-84808926-1efa-407c-803e-7775d7cbbf05.jpg)

**Comment by TheLastBen** [comment]
> lol, so what does it means? i cannot get a file until it reaches the final step?

Yes
