### ISSUE TITLE
Issues with Dreambooth for SD v2.1

### ISSUE THREAD

**Issue by Alx-AI** [TheLastBen/fast-stable-diffusion#906]
Running into a couple issues:

1. Doesn't seem to be anywhere to put our token that will house the object
2. Running into `File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 11, in <module>
    from modules.call_queue import wrap_queued_call, queue_lock, wrap_gradio_gpu_call
ModuleNotFoundError: No module named 'modules.call_queue' can you help me solve it` when trying to test the inference

**Comment by TheLastBen** [comment]
remove the folder sd and use the latest colab  : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by Alx-AI** [comment]
Seems to address #2, am I just missing where I can input the name for the <token> to include in my prompts? Seems nowhere to be found in most recent fast DB notebook  [https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb](https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb)

**Comment by Alx-AI** [comment]
Tested this and did not work, running into the following ^C quitting when trying to run the client 
![image](https://user-images.githubusercontent.com/4674698/206314701-139296b2-b845-43a5-8d0f-fa61d492d63b.png)

**Comment by OEvgeny** [comment]
This is likely an out of memory error due to free colab limitations

**Comment by voidxd** [comment]
@OEvgeny asking you since you've been very active here lately and seem quite knowledgeable. So to conclude, right now, we can't use Colab Free to test trained 2.0 and 2.1 models?

**Comment by TheLastBen** [comment]
you can use free colab or standard gpu to test 2.0 and 2.1

**Comment by voidxd** [comment]
> you can use free colab or standard gpu to test 2.0 and 2.1

I just tried it out and it works. Thank you. The previous week I kept having the ^C issue.

**Comment by mediocreatmybest** [comment]
> > you can use free colab or standard gpu to test 2.0 and 2.1
> 
> I just tried it out and it works. Thank you. The previous week I kept having the ^C issue.

I've found I've needed to flag the colab with additional RAM with SDv2 otherwise I get the out of RAM error with ^C
Can't say I get this issue with SD1.5. I do have the Pro subscription so it isn't an issue but still pops up from time to time.

**Comment by Alx-AI** [comment]
Confirmed with new updates dreambooth and running it works!
