### ISSUE TITLE
RESUME TRAINING WONT WORK AFTER RUNTIME IS CLOSED.

### ISSUE THREAD

**Issue by LIQUIDMIND111** [TheLastBen/fast-stable-diffusion#919]
PLEASE FIX CODE, i wanted to make a model for a Xmas poster and seems is not happening..... i need to train at LEAST 15000 steps and i cant resume because of CODE ERROR, not because of Google issues, please..... do you have a PAID COLLAB PAGE? i would prefer to PAY SOMETHING and have flawless runtimes... but this error im getting have been active for MANY days already and people are mentioning the same error......

**Comment by TheLastBen** [comment]
Copy the error log here

**Comment by LIQUIDMIND111** [comment]
> Copy the error log here

Session found, loading the trained model ...
Converting to Diffusers ...
Traceback (most recent call last):
File "/content/convertodiff.py", line 1107, in
convert(args)
File "/content/convertodiff.py", line 1076, in convert
key_count = save_stable_diffusion_checkpoint(v2_model, args.model_to_save, text_encoder, unet,
File "/content/convertodiff.py", line 1013, in save_stable_diffusion_checkpoint
torch.save(new_ckpt, output_file)
File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 422, in save
with _open_zipfile_writer(f) as opened_zipfile:
File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 309, in _open_zipfile_writer
return container(name_or_buffer)
File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 287, in init
super(_open_zipfile_writer_file, self).init(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory /content/models does not exist.
Conversion error, if the error persists, remove the CKPT file from the current session folder
[ ]

**Comment by TheLastBen** [comment]
will be fixed in a few minutes

**Comment by LIQUIDMIND111** [comment]
> will be fixed in a few minutes

Sorry @TheLastBen, ill wait... I was mad because i just activated yesterday google pro, and I'm new with this computational units things, 

i am just mad i used 20 units out of 100, and this is my first time doing this and if i get errors, then i don't know what to do. Resuming from 9000 to get to 15000 was not possible, and i was angry because i waited 8 hours and fell asleep and got disconnected SOMEHOW even with google pro.... 

BUT HEY, ill be glad to help out you guys also. i will be glad to donate or give some $$ credit to yourself because you deserve it. Just let me know one thing:

on Google pro, i get discounted 1.97 computational units per hour of STANDARD GPU use. and if i choose the PREMIUM GPU, it gets depleted 15.1 units PER hour!!! Imagine that difference someone chooses that much GPU and not needing it... 

so my question is, do you believe that for a long steps training, if i choose premium GPU, i will get faster training? or not really?

**Comment by LIQUIDMIND111** [comment]
@TheLastBen hey mate, here i bought some coffee for you, i mean, i have been using your repo for 2 months now, so i had to send something. 
![Screenshot 2022-12-08 073715](https://user-images.githubusercontent.com/112510084/206437604-4d760201-b13c-48cd-8765-f8ee174cbf74.jpg)

**Comment by LIQUIDMIND111** [comment]
@TheLastBen i read you fixed something, but i reloaded the collab page, and tried to resume again and get this error i believe is the same:
![Screenshot 2022-12-08 075237](https://user-images.githubusercontent.com/112510084/206439996-bbe9ab64-bce4-4635-a761-15c008a95159.jpg)

**Comment by TheLastBen** [comment]
the model you created was converted with a broken script, so the model itself is broken, resuming its training is a waste of time

**Comment by LIQUIDMIND111** [comment]
> the model you created was converted with a broken script, so the model itself is broken, resuming its training is a waste of time

never mind then, i also decided to reduce EVEN MORE the amount of images, TOO MUCH IMAGES is NOT better if they are blurry, so i CLEANED images and got way less time to train now,, lets try again from 0, thanks... please let me kn ow if you recieve the tip since i did not used paypal.....

**Comment by LIQUIDMIND111** [comment]
> so my question is, do you believe that for a long steps training, if i choose premium GPU, i will get faster training? or not really?

do you believe that for a long steps training, if i choose premium GPU, i will get faster training? or not really?

**Comment by TheLastBen** [comment]
keep the GPU to standard, you don't need the A100 for dreambooth, it's a waste of units

**Comment by LIQUIDMIND111** [comment]
> keep the GPU to standard, you don't need the A100 for dreambooth, it's a waste of units



> keep the GPU to standard, you don't need the A100 for dreambooth, it's a waste of units

ah, very much thanks.... ill try again...
