### ISSUE TITLE
Malicious file error on trained v2.0

### ISSUE THREAD

**Issue by dalmackay** [TheLastBen/fast-stable-diffusion#935]
I was resuming training on a trained v2.0 model and it trained normally but fails to load into Auto1111 with this error:

Error verifying pickled file from E:\automaticSD\auto fresh\stable-diffusion-webui-master\models\Stable-diffusion\rndyvrgs.ckpt:
Traceback (most recent call last):
  File "E:\automaticSD\auto fresh\stable-diffusion-webui-master\modules\safe.py", line 131, in load_with_extra
    check_pt(filename, extra_handler)
  File "E:\automaticSD\auto fresh\stable-diffusion-webui-master\modules\safe.py", line 84, in check_pt
    check_zip_filenames(filename, z.namelist())
  File "E:\automaticSD\auto fresh\stable-diffusion-webui-master\modules\safe.py", line 76, in check_zip_filenames
    raise Exception(f"bad file inside {filename}: {name}")
Exception: bad file inside E:\automaticSD\auto fresh\stable-diffusion-webui-master\models\Stable-diffusion\rndyvrgs.ckpt: rndyvrgs/data.pkl

The file may be malicious, so the program is not going to read it.
You can skip this check with --disable-safe-unpickle commandline argument.

This model worked normally the first 2 times I trained it.

**Comment by TheLastBen** [comment]
Use this argument --disable-safe-unpickle

**Comment by sampanes** [comment]
What changed that caused this to come up in 1.5? it's recent

**Comment by TheLastBen** [comment]
it's an old commit by A1111

**Comment by sampanes** [comment]
ok, thank you for everything you do
