### ISSUE TITLE
Automatic1111 colab not launching

### ISSUE THREAD

**Issue by ponderer89** [TheLastBen/fast-stable-diffusion#94]
when executing the last cell an error comes up:
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 31, in <module>
    modules.sd_models.setup_model()
TypeError: setup_model() missing 1 required positional argument: 'dirname'

**Comment by TheLastBen** [comment]
Are you using the latest colab from the repo ?
