### ISSUE TITLE
Script stops saving after 1000 , Killed

### ISSUE THREAD

**Issue by siraxe** [TheLastBen/fast-stable-diffusion#961]
![chrome_WYGSLhng9v](https://user-images.githubusercontent.com/27487254/206880605-198b8784-8a93-4104-8d3b-ba5e4f8a31a0.png)
![chrome_GtQpXLIBYP](https://user-images.githubusercontent.com/27487254/206880613-56337e98-0c48-4c8b-be6b-d5bd695777d2.png)
Tried multiple times , first 1000 steps are fine then it stops converting to ckpt

**Comment by TheLastBen** [comment]
not enough RAM when training the V2, but the final model will be saved without issue.

**Comment by siraxe** [comment]
> 

ah okay , thank you)
