### ISSUE TITLE
issues with black images after model was trained, with 2.0 / 2.1

### ISSUE THREAD

**Issue by tomthedude** [TheLastBen/fast-stable-diffusion#973]
hello,
thank you for the great work
i have some issue i can not identify it source
atm when i am training v2 or v2.1 via this colab repo,
and then use automatic1111, i get black images, all the time no matter what the prompt is
to be honest, i did manage to train one model on v2 a couple of days ago, but he doesnt know that person i trained it for.
so far i could not get v2 or 2.1 to work after training
i am using 20 images, uncropped, with 768px setting
had no similar issues with 1.5 or any other models i got (openjoruney ex.), all working fine
scratching my head really, cheers

**Comment by TheLastBen** [comment]
you're probably running an old version of the colab
AUT : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

DREMBOOTH : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by tomthedude** [comment]
> you're probably running an old version of the colab AUT : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> 
> DREMBOOTH : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

i did it like 3-4 hours ago on the latest version there was at the time, did it update since then with fixes?

**Comment by tomthedude** [comment]
> what settings did you use for training ?
lets see
Model_Version 2.1 768px (also tried with 2.0 768px when it was still available)
20 instance images, uncropped
unet 3000
text encoder 350
Resolution: 768px

those are the settings i used, pretty basic
it makes a ckpt file as if all was done ok, but can not produce images from it, all black images
also, it is the same set of images i used to train 1.5 etc, so unlikely it is images issue

**Comment by TheLastBen** [comment]
do not save the colab to your gdrive, always use this link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb, you're getting black images because you're running an old colab

**Comment by tomthedude** [comment]
> do not save the colab to your gdrive, always use this link https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb, you're getting black images because you're running an old colab

not sure what you mean not to save colab to my gdrive, i do not save anything to my gdrive except what is coming in there from the integration of the script

**Comment by TheLastBen** [comment]
google colab always asks the user to save the notebook to their gdrive, so you might've done that

**Comment by tomthedude** [comment]
> google colab always asks the user to save the notebook to their gdrive, so you might've done that

ok, thanks, will try again later.. not more compute units hehe
cheers
