### ISSUE TITLE
AUTOMATIC1111 Consistently erroring

### ISSUE THREAD

**Issue by TheClownVamp** [TheLastBen/fast-stable-diffusion#98]
Thanks for all your work on this! Definitely the fastest implementation I've seen. Today, I'm find that AUTOMATIC1111 is consistently giving run time errors when you try to do a task. Not sure if known issue so just wanted to flag

**Comment by TheLastBen** [comment]
You're using the latest colab ?

**Comment by TheClownVamp** [comment]
If that just means grabbing the link from the github, then yes! Is it no replicating for you?

**Comment by TheLastBen** [comment]
remove the "sd" folder from your gdrive and do a clean run then try reproducing the error +screenshot

**Comment by TheClownVamp** [comment]
That seems to work, thank you! Is there a way to "freeze" a version of Collab if it's working/stable for us. Doing a hard refresh of the folder is a bit painful since we lose any custom models we upload :)

**Comment by TheLastBen** [comment]
The errors you experienced was due to a major path redefinition by AUTOMATIC1111, so I had to adapt the notebook to it, also implementing a fix to the webui freezing when doing large batches conflicted with some of the functionalities, but it's done now.

**Comment by TheClownVamp** [comment]
Roger that! Thank you so much!
